<!DOCTYPE html>
<html lang="zh-cmn-Hans">
<head>
    <!-- Make 2018-04-19 16:49:58 -->
<!-- Make 1524127798 -->
<meta charset="UTF-8">
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
<meta name="renderer" content="webkit"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
<meta name=applicable-device content="pc">
<meta http-equiv="Cache-Control" content="no-transform"/>
<meta http-equiv="Cache-Control" content="no-siteapp"/>
<meta name="baidu-site-verification" content="99J7V1k1Vz" />
<meta name="google-site-verification" content="Odmo8X4zeUG1WPcCrCAueZz-dyBPFBs4Zqlb9FBT5z4" />
<meta http-equiv="Access-Control-Allow-Origin" content="*" />
<!-- Global site tag (gtag.js) - Google Analytics -->
<!-- <script async src="https://www.googletagmanager.com/gtag/js?id=UA-114904919-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-114904919-2');
</script> -->

    <title>红妆翘睫双眼皮_眼部_海南红妆时尚双美整形美容连锁</title>
    <meta property="og:type" content="article"/>
    <meta property="article:author" content="红妆双美"/>
    <meta property="article:published_time" content="2018-03-14T19:37:30+08:00" />
    <meta name="keywords" content="红妆双美,翘睫双眼皮，单眼皮，内双眼，大小眼"/>
    <meta name="description" content="红妆双美翘睫双眼皮精细无痕，翘睫美眸，改变的不止是眼睛，更是眼神。红妆双美翘睫双眼皮术后效果自然无痕，加速消肿，七天速现美眼，一次成型，持久保持。"/>
    <meta property="article:tag" content="红妆双美,翘睫双眼皮，单眼皮，内双眼，大小眼">
    <link rel="canonical" href="https://www.hzshuangmei.com/projects/eye/qjsyp.html" />
    <link rel="alternate" media="only screen and(max-width: 640px)" href="https://m.hzshuangmei.com/projects/eye/qjsyp.html" >
    <!-- Pre for optimization -->
<link rel="dns-prefetch" href="https://cdn.bootcss.com">
<link rel="dns-prefetch" href="https://uploads.hzshuangmei.com">
<link rel="dns-prefetch" href="https://img.hzshuangmei.com">
<link rel="dns-prefetch" href="https://css.hzshuangmei.com">
<link rel="dns-prefetch" href="https://js.hzshuangmei.com">
<link rel="dns-prefetch" href="https://pv.kuaishang.cn">
<link rel="dns-prefetch" href="https://z8.cnzz.com">
<link rel="dns-prefetch" href="https://s19.cnzz.com">
<link rel="dns-prefetch" href="https://tag.baidu.com">
<link rel="dns-prefetch" href="https://sp0.baidu.com">
<link rel="preload" href="https://css.hzshuangmei.com/pc/common.css" as="style" crossorigin />
<link rel="preload" href="https://img.hzshuangmei.com/pc/favicon.ico" as="image" type="image/x-icon" crossorigin />
<!-- Style for the page-->
<link rel="stylesheet" href="https://cdn.bootcss.com/Swiper/3.4.2/css/swiper.min.css"/>
<link rel="stylesheet" href="https://css.hzshuangmei.com/pc/common.css"/>
<link rel="stylesheet" href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" >
<!-- favicon.ico -->
<link rel="icon" href="https://img.hzshuangmei.com/pc/favicon.ico" type="image/x-icon"/>
<link rel="shortcut icon" href="https://img.hzshuangmei.com/pc/favicon.ico" type="image/x-icon"/>
<!-- humanstxt -->
<link rel="author" href="https://www.hzshuangmei.com/humans.txt" />
<link rel="preload" as=image  href="https://img.hzshuangmei.com/pc/kst/default.png">
<link rel="prefetch" src="https://img.hzshuangmei.com/pc/kst/default.png">
<link rel="prerender" src="https://img.hzshuangmei.com/pc/kst/default.png">
<link rel="prefetch" src="https://img.hzshuangmei.com/pc/kst/qjsyp.png">
<link rel="prerender" src="https://img.hzshuangmei.com/pc/kst/qjsyp.png">
<link rel="preload" as=image  href="https://img.hzshuangmei.com/pc/kst/qjsyp.png">

     <link rel="preload" href="https://css.hzshuangmei.com/pc/tjb.css" as="style" crossorigin />
    <link rel="stylesheet" href="https://css.hzshuangmei.com/pc/tjb.css"/>
    <meta content="设计观彩恒，前端陈晓珍，文案暂无/" name="author" />
<link href="//css.hzshuangmei.com/pc/qjsyp/theme.css" rel="stylesheet" />

<body>
<header>
    <div class="top">
        <div class="shuang_m1 clearFix">
            <div class="top_l">
                <!--<span>香港红瑞集团 旗下品牌 海南红妆双美连锁</span>-->
                <img src="https://img.hzshuangmei.com/pc/tl_logo.png" alt="logo" />|<span>美丽时间：周一周日9点--21点</span>
            </div>
            <!-- 增加百度站内搜索 -->
            <div class="top_c">
                <div class="search_box">
                    <form action="https://www.hzshuangmei.com/search/" target="_blank" autocomplete="off" id="bdcs-search-form" class="site-search-form">
                        <input type="hidden" name="s" value="5257607230163915007">
                         <input type="hidden" name="entry" value="1">
                        <input type="text" placeholder="请输入您要搜索的内容..." id="bdcsMain" name="q">
                        <button type="submit" id="bdcs-search-form-submit"></button>
                    </form>
                </div>
            </div>
                        <!-- 增加百度站内搜索 -->
            <div class="top_r">
                <a href="" class="pad_r"><i class="tel"></i><span>0898-66156043</span></a>
                <span>关注我们：</span>
                <a href="" class="pad_l"><i class="wbo"></i></a>
                <a href=""><i class="wxin"></i></a>
                <a href=""><i class="qq"></i></a>
            </div>
        </div>
    </div>
    <div class="sm_logo">
        <a href="/"><img src="https://img.hzshuangmei.com/pc/h_logo.png" alt=""/></a>
    </div>
</header>
<nav id="nav">
    <ul class="shuang_m1 nav_ul">
        <li class="nav_list">
            <a href="/" class="nav_link" target="_blank" rel="noopener">
                <span>首 页</span><br/>
                <span>Home</span>
            </a>
        </li>
        <li class="nav_list">
            <a href="/brand" class="nav_link bor_r" target="_blank" rel="noopener">
                <span>品 牌</span><br/>
                <span>brands</span>
            </a>
        </li>
        <li class="nav_list">
            <a href="/projects" class="nav_link bor_l bor_r" target="_blank" rel="noopener">
                <span>项 目</span><br/>
                <span>projects</span>
            </a>
            <div class="clearFix" id="project">
                <ul>
                    <li>
                        <h5><a href="/projects/tattoo/" target="_blank" rel="noopener">医学纹绣</a></h5>
                    </li>
                    <!--              <li>
                        <a href="/projects/tattoo/yanxian.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P4041610355P.jpg" alt="红妆艺术美瞳线"/>
                            <p><i></i><span>红妆艺术美瞳线</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/tattoo/hsbyjwm.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404160923556.jpg" alt="韩式半永久纹眉"/>
                            <p><i></i><span>韩式半永久纹眉</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/tattoo/xwx.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/img/180331/1-1P3311106490-L.jpg" alt="洗纹绣"/>
                            <p><i></i><span>洗纹绣</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/tattoo/xwx.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/img/180331/1-1P3311106490-L.jpg" alt="洗纹绣"/>
                            <p><i></i><span>洗纹绣</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/tattoo/wash.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180222/1-1P222110205243.jpg" alt="激光洗纹绣"/>
                            <p><i></i><span>激光洗纹绣</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/tattoo/hsbyjwm.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404160923556.jpg" alt="韩式半永久纹眉"/>
                            <p><i></i><span>韩式半永久纹眉</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button">-->
                    <!--<a href="/projects" target="_blank" rel="noopener">查看更多</a>-->
                    <!--</li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/eye/" target="_blank" rel="noopener">眼部整形</a></h5>
                    </li>
                    <!--   <li>
                        <a href="/projects/eye/qmtm.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404161354458.jpg" alt=""/>
                            <p><i></i><span>切眉提眉术</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/eye/slxc.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180222/1-1P22216455E61.jpg" alt=""/>
                            <p><i></i><span>上睑下垂</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/eye/yandai.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404160Q03S.jpg" alt=""/>
                            <p><i></i><span>无痕祛眼袋</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/eye/yandai.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404160Q03S.jpg" alt="无痕祛眼袋"/>
                            <p><i></i><span>无痕祛眼袋</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/eye/slxc.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180222/1-1P22216455E61.jpg" alt="上睑下垂"/>
                            <p><i></i><span>上睑下垂</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/eye/hzyj.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180206/1-1P206100342338.jpg" alt="红妆孕睫术"/>
                            <p><i></i><span>红妆孕睫术</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/nose/" target="_blank" rel="noopener">鼻部整形</a></h5>
                    </li>
                    <!--              <li>
                        <a href="/projects/nose/lineeaglenose.html" target="_blank" rel="noopener">
                        <img src="https://uploads.hzshuangmei.com/180109/1-1P10916214I29.jpg" alt=""/>
                            <p><i></i><span>线雕隆鼻</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/nose/heben.html" target="_blank" rel="noopener">
                        <img src="https://uploads.hzshuangmei.com/180109/1-1P109162114246.jpg" alt=""/>
                            <p><i></i><span>红妆赫本软骨鼻</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/nose/longbijiage.html" target="_blank" rel="noopener">
                        <img src="https://uploads.hzshuangmei.com/180209/1-1P2091524433K.jpg" alt=""/>
                            <p><i></i><span>隆鼻价格</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/nose/longbijiage.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180209/1-1P2091524433K.jpg" alt="隆鼻价格"/>
                            <p><i></i><span>隆鼻价格</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/nose/hzbbqb.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180208/1-1P20QZ14O61.jpg" alt="红妆芭比翘鼻"/>
                            <p><i></i><span>红妆芭比翘鼻</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/nose/nose.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180109/1-1P109161Fc42.jpg" alt="全立体鼻缩窄术"/>
                            <p><i></i><span>全立体鼻缩窄术</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/face/" target="_blank" rel="noopener">面部整形</a></h5>
                    </li>
                    <!--                <li class="star">
                        <a href="/projects/zhifang/ztzfmd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180109/1-1P109162329454.jpg" alt=""/>
                            <p><i></i><span>自体脂肪面雕</span></p>
                        </a>
                    </li><li class="star">
                        <a href="/projects/xiaba/vlmxd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P40416062R04.jpg" alt=""/>
                            <p><i></i><span>v立美线雕</span></p>
                        </a>
                    </li><li class="star">
                        <a href="/projects/face/zitizhifang.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180208/1-1P20Q54P4G4.jpg" alt=""/>
                            <p><i></i><span>自体脂肪面部填充</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/face/zitizhifang.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180208/1-1P20Q54P4G4.jpg" alt="自体脂肪面部填充"/>
                            <p><i></i><span>自体脂肪面部填充</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/xiaba/vlmxd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P40416062R04.jpg" alt="v立美线雕"/>
                            <p><i></i><span>v立美线雕</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/zhifang/ztzfmd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180109/1-1P109162329454.jpg" alt="自体脂肪面雕"/>
                            <p><i></i><span>自体脂肪面雕</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/skin/" target="_blank" rel="noopener">皮肤美容</a></h5>
                    </li>
                    <!--                 <li>
                        <a href="/projects/qudou/duoweiqd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180222/1-1P222143953U0.jpg" alt=""/>
                            <p><i></i><span>红妆多维祛痘</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/quban/xpmqb.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180328/1-1P32Q356202V.jpg" alt=""/>
                            <p><i></i><span>红妆皮秒祛斑</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/skin/sgz.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180406/1-1P4061A303F6.jpg" alt=""/>
                            <p><i></i><span>水光针</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/quban/xpmqb.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180328/1-1P32Q356202V.jpg" alt="红妆皮秒祛斑"/>
                            <p><i></i><span>红妆皮秒祛斑</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/chuzhou/quzhou.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180212/1-1P212102446403.jpg" alt="除皱抗衰"/>
                            <p><i></i><span>除皱抗衰</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/quban/quban.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180312/1-1P3121601494G.jpg" alt="红妆祛斑"/>
                            <p><i></i><span>红妆祛斑</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/ha/" target="_blank" rel="noopener">玻尿酸</a></h5>
                    </li>
                    <!--                     <li>
                        <a href="/projects/ha/qydbns.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180208/1-1P20Q0501X26.jpg" alt=""/>
                            <p><i></i><span>乔雅登玻尿酸</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/ha/zhbns.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180109/1-1P109161SV57.jpg" alt=""/>
                            <p><i></i><span>综合玻尿酸</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/ha/restylane.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180413/1-1P413100FcV.jpg" alt=""/>
                            <p><i></i><span>瑞蓝玻尿酸</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/ha/restylane.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180413/1-1P413100FcV.jpg" alt="瑞蓝玻尿酸"/>
                            <p><i></i><span>瑞蓝玻尿酸</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/ha/bnsqflw.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180411/1-1P411140P9134.jpg" alt="玻尿酸祛除法令纹"/>
                            <p><i></i><span>玻尿酸祛除法令纹</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/ha/xbnsfet.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180322/1-1P322092GMV.jpg" alt="玻尿酸丰额头"/>
                            <p><i></i><span>玻尿酸丰额头</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/body/" target="_blank" rel="noopener">形体雕塑</a></h5>
                    </li>
                    <!-- <li>
                        <a href="/projects/body/sdlxz.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404161320X4.jpg" alt=""/>
                            <p><i></i><span>水动力吸脂</span></p>
                       </a>
                    </li> -->
                    <li>
                        <a href="/projects/body/sdlxz.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404161320X4.jpg" alt="水动力吸脂"/>
                            <p><i></i><span>水动力吸脂</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
            </div>
        </li>
        <li class="nav_list">
            <a href="/doctors" class="nav_link bor_l bor_r" target="_blank" rel="noopener">
                <span>专 家</span><br/>
                <span>experts</span>
            </a>
            <div id="expert">
                <ul>
                    <li>
                        <h5><a href="/doctors/surgery" target="_blank" rel="noopener">整形美容专家</a></h5>
                    </li>
                    <!--                     <li>
                        <a href="/plugin/view.php?aid=227" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180414/1-1P4140929454T.jpg" alt="薛开兴"/>
                            <p><span class="n_f">薛开兴</span><span class="n_b">整形外科院长</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=153" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180131/1-1P131093205432.jpg" alt="余志亮"/>
                            <p><span class="n_f">余志亮</span><span class="n_b">整形专家</span></p>
                            <i></i>
                        </a>
                    </li> -->
                    <li>
                        <a href="/doctors/surgery/guanhaitao.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180227/1-1P22G44625M2.jpg" alt="关海涛 "/>
                            <p><span class="n_f">关海涛 </span><span class="n_b">整形外科院长</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=176" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180131/1-1P1310U92D41.jpg" alt="朱红振"/>
                            <p><span class="n_f">朱红振</span><span class="n_b">整形外科院长</span></p>
                            <i></i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <h5><a href="/doctors/laser" target="_blank" rel="noopener">激光美容专家</a></h5>
                    </li>
                    <!--             <li>
                        <a href="/doctors/laser/lijie.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/171206/1-1G20611435D10.jpg" alt="李杰"/>
                            <p><span class="n_f">李杰</span><span class="n_b">光学美肤中心院长</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/doctors/laser/yzw.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180131/1-1P131104604521.jpg" alt="姚志文"/>
                            <p><span class="n_f">姚志文</span><span class="n_b">非手术面部年轻化专家</span></p>
                            <i></i>
                        </a>
                    </li> -->
                    <li>
                        <a href="/doctors/laser/lijie.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/171206/1-1G20611435D10.jpg" alt="李杰"/>
                            <p><span class="n_f">李杰</span><span class="n_b">光学美肤中心院长</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/doctors/laser/yzw.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180131/1-1P131104604521.jpg" alt="姚志文"/>
                            <p><span class="n_f">姚志文</span><span class="n_b">非手术面部年轻化专家</span></p>
                            <i></i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <h5><a href="/doctors/tattoo" target="_blank" rel="noopener">医学纹绣</a></h5>
                    </li>
                    <!--                    <li>
                        <a href="/plugin/view.php?aid=139" target="_blank" rel="noopener">
                    <img src="https://uploads.hzshuangmei.com/180117/1-1P11GF5391A.jpg" alt="杨小丽"/>
                            <p><span class="n_f">杨小丽</span><span class="n_b">纹饰指导师</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=136" target="_blank" rel="noopener">
                    <img src="https://uploads.hzshuangmei.com/180125/1-1P125154A1105.jpg" alt="高方云"/>
                            <p><span class="n_f">高方云</span><span class="n_b">纹饰指导师</span></p>
                            <i></i>
                        </a>
                    </li> -->
                    <li>
                        <a href="/plugin/view.php?aid=164" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180125/1-1P12515435J45.jpg" alt="冯晓琳"/>
                            <p><span class="n_f">冯晓琳</span><span class="n_b">纹饰技术总指导师</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=137" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180117/1-1P11GA95JV.jpg" alt="孟超"/>
                            <p><span class="n_f">孟超</span><span class="n_b">纹饰指导师</span></p>
                            <i></i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <h5><a href="/doctors" target="_blank" rel="noopener">特邀专家</a></h5>
                    </li>
                    <li>
                        <a href="/doctors/surgery/ljb.html" target="_blank" rel="noopener">
                             <img src="https://uploads.hzshuangmei.com/180131/1-1P131092S24W.jpg" alt="雷建波(客座)"/>
                            <p><span class="n_f">雷建波(客座)</span><span class="n_b">整形美容专家</span></p>
                            <i></i>
                        </a>
                    </li>
<li>
                        <a href="/doctors/surgery/liudalie.html" target="_blank" rel="noopener">
                             <img src="https://uploads.hzshuangmei.com/171223/1-1G223091J5950.jpg" alt="柳大烈(客座)"/>
                            <p><span class="n_f">柳大烈(客座)</span><span class="n_b">教授</span></p>
                            <i></i>
                        </a>
                    </li>

                </ul>
                <ul>
                    <li>
                        <h5 class="moon"><a href="/doctors" target="_blank" rel="noopener">每月专家</a></h5>
                    </li>
                    <li class="last-one">
                        <!--<a class="last-one" href="https://www.hzshuangmei.com/doctors/surgery/liudalie.html " target="_blank" rel="noopener">-->
                            <!--<img src="https://img.hzshuangmei.com/pc/nav_zhuanjial.jpg" alt=""/>-->
                        <!--</a>-->
                        <a class="last-one j-consult" href="javascript:void(0)"  target="_blank" rel="noopener nofollow">
                            <img src="https://img.hzshuangmei.com/pc/myzzj.jpg" alt=""/>
                        </a>
                    </li>
                </ul>
            </div>
        </li>
        <li class="nav_list">
            <a href="/cases" class="nav_link bor_l bor_r" target="_blank" rel="noopener">
                <span>真人秀</span><br/>
                <span>Show</span>
            </a>
        </li>
        <li class="nav_list">
            <a href="/news" class="nav_link bor_l" target="_blank" rel="noopener">
            <span>活 动</span><br/>
                <span>News</span>
            </a>
        </li>
    </ul>
</nav>

<div class="container banner">
	<div class="row">
		<h1 class="sr-only">
			红妆翘睫双眼皮</h1>
		<p class="sr-only">
			精细无痕 翘睫美眸</p>
		<p class="sr-only">
			大眼 深邃 水汪汪 媚眼 炯炯有神</p>
		<p class="sr-only">
			改变的不止是眼睛 更是眼神</p>
	</div>
</div>
<div class="container m1">
	<div class="row">
		<h2>
			<span class="sr-only">没大眼睛 如何萌</span></h2>
	</div>
	<div class="row row1">
		<div>
			<img alt="单眼皮女生" src="//img.hzshuangmei.com/pc/qjsyp/img1_1.jpg" />
			<div>
				<h3>
					单眼皮</h3>
				<p>
					上眼皮较薄的单眼皮，看上去总是那么无神，缺少灵动的感觉......</p>
				<a class="consult j-consult " href="javascript:void(0);" rel="nofollow">咨询解决方法</a></div>
		</div>
		<div>
			<img alt="内双眼女生" src="//img.hzshuangmei.com/pc/qjsyp/img1_2.jpg" />
			<div>
				<h3>
					内双眼</h3>
				<p>
					皮是双眼皮，但有时很不明显，或者完全消失，心里总是有些遗憾......</p>
				<a class="consult j-consult " href="javascript:void(0);" rel="nofollow">咨询解决方法</a></div>
		</div>
	</div>
	<div class="row row2">
		<div>
			<img alt="大小眼女生" src="//img.hzshuangmei.com/pc/qjsyp/img1_3.jpg" />
			<div>
				<h3>
					大小眼</h3>
				<p>
					一只眼单，一只眼双，或者两侧双眼皮宽窄不一，给人一种不和谐感.....</p>
				<a class="consult j-consult " href="javascript:void(0);" rel="nofollow">咨询解决方法</a></div>
		</div>
		<div>
			<img alt="咪咪眼女生" src="//img.hzshuangmei.com/pc/qjsyp/img1_4.jpg" />
			<div>
				<h3>
					咪咪眼</h3>
				<p>
					生来就是一条缝，明明很用力的睁着，却仿佛永远睡不醒.......</p>
				<a class="consult j-consult " href="javascript:void(0);" rel="nofollow">咨询解决方法</a></div>
		</div>
	</div>
</div>
<div class="container m2">
	<div class="row">
		<h2>
			<span class="sr-only">会放电的三种眼睛类型</span></h2>
	</div>
	<div class="row">
		<div class="col1">
			<img alt="广尾型眼型" src="//img.hzshuangmei.com/pc/qjsyp/img2_1.jpg" />
			<div>
				<h3>
					广尾型</h3>
				<p>
					内窄外宽，适合眉毛眼角间距中，眼角微扬的女孩子</p>
				<a class="consult j-consult " href="javascript:void(0);" rel="nofollow">我要做广尾型 &nbsp;&nbsp; 》</a></div>
		</div>
		<div class="col2">
			<img alt="平行型眼型" src="//img.hzshuangmei.com/pc/qjsyp/img2_2.jpg" />
			<div>
				<h3>
					平行型</h3>
				<p>
					双眼皮与上睑睑缘基本平行，重睑先外的不超过外眼角，适合大眼睛，眉弓较高，眉毛跟眼角较远的人</p>
				<a class="consult j-consult " href="javascript:void(0);" rel="nofollow">我要做平行型&nbsp;&nbsp; 》</a></div>
		</div>
		<div class="col3">
			<img alt="新月形眼型" src="//img.hzshuangmei.com/pc/qjsyp/img2_3.jpg" />
			<div>
				<h3>
					新月形</h3>
				<p>
					新月形的特点是重睑在内，外眼角眼缘较近，睑中部稍宽，比较天然可爱</p>
				<a class="consult j-consult " href="javascript:void(0);" rel="nofollow">我要做新月形&nbsp;&nbsp; 》</a></div>
		</div>
	</div>
</div>
<div class="container m3">
	<div class="row">
		<h2>
			<span class="sr-only">红妆翘睫双眼皮三大优势</span></h2>
		<div class="row1">
			<h3>
				精细操作</h3>
			<p>
				眼部显微镜下手术，配合眼科专用器械，操作更精准</p>
		</div>
		<div class="row2">
			<h3>
				恢复管理</h3>
			<p>
				超微创，术后效果自然无痕，加速消肿，七天速现美眼</p>
			<p class="fr">
				自然<br />
				无痕<br />
				微创</p>
		</div>
		<div class="row3">
			<h3>
				一次成型</h3>
			<p>
				精益求精的手术完美呈现，一次成型，持久保持</p>
		</div>
	</div>
</div>
<div class="container m41">
	<h2>
		<span class="sr-only">红妆双眼皮成形术四大方法</span></h2>
	<div class="row">
		<h3>
			<span class="sr-only">灵动翘睫双眼皮</span></h3>
		<p class="twoline">
			<span>原理</span>面部黄金比例，精算眼睛各个弧度，是一种修整眼皮长宽、眼角高低、内眦外眦大小、全面改善眼部形态、提升眼睛神韵的综合眼部整形手术</p>
		<p>
			<span>优势</span>可以使得眼睫毛略微上翘，眼部轮廓变大，达到双目有神，风情万种的效 果，双眼皮非常自然</p>
		<p>
			<span class="last">适合人群</span>内窄外宽，适合眉毛眼角间距中，眼角微扬的女孩子</p>
		<div class="step">
			<img alt="眼睛说明图" src="//img.hzshuangmei.com/pc/qjsyp/img41_1.jpg" />
			<p>
				<span>术前：</span>综合求美者脸型、面部五官、个人气质等因素，按照三庭五眼的美学标准，定制适合求美者的双眼皮</p>
			<p>
				<span>术中：</span>修整眼皮长宽、眼角高低、内眦外眦大小、全面改善眼部形态、提升眼睛神韵</p>
			<p>
				<span>术后：</span>术后双眼精致美丽、明亮有神，也被誉为&ldquo;会说话的眼睛成形术&rdquo;</p>
		</div>
		<div class="duibi">
			<img alt="翘睫双眼皮手术前后对比图" class="fl" href="javascript:void(0);" rel="nofollow" src="//img.hzshuangmei.com/pc/qjsyp/img41_2.jpg" /> <img alt="翘睫双眼皮手术前后对比图" class="fr" href="javascript:void(0);" rel="nofollow" src="//img.hzshuangmei.com/pc/qjsyp/img41_3.jpg" /></div>
		<a class="consult j-consult " href="javascript:void(0);" rel="nofollow">立即咨询</a></div>
</div>
<div class="container m42">
	<div class="row">
		<h3>
			<span class="sr-only">红妆隐形切开法</span></h3>
		<p>
			<span>原理</span>在眼皮特定部位切开皮肤，去除多余脂肪、皮肤，再将皮肤与上睑肌腱膜缝合，形成双眼皮</p>
		<p>
			<span>优势</span>塑造的双眼皮自然优美，生动。</p>
		<p>
			<span class="last">适合人群</span>上睑皮肤松弛或脂肪过多者，外眼角松弛导致三角眼</p>
		<div class="step">
			<img alt="手术过程说明图" src="//img.hzshuangmei.com/pc/qjsyp/img42_1.jpg" />
			<p>
				<span>术前：</span>综合求美者脸型、面部五官、个人气质等因素，按照三庭五眼的美学标准，定制适合求美者的双眼皮</p>
			<p>
				<span>术中：</span>为确保无痕，红妆专家将切口精确到1毫米，采用高清度数字控制下进行手术，过程安全</p>
			<p>
				<span>术后：</span>在成功实现了微创目标的同时，恢复速度快，效果可长久保持</p>
		</div>
		<div class="duibi">
			<img alt="翘睫双眼皮隐形切开法手术前后对比图" class="fl" href="javascript:void(0);" rel="nofollow" src="//img.hzshuangmei.com/pc/qjsyp/img42_2.jpg" /> <img alt="翘睫双眼皮隐形切开法手术前后对比图" class="fr" href="javascript:void(0);" rel="nofollow" src="//img.hzshuangmei.com/pc/qjsyp/img42_3.jpg" /></div>
		<a class="consult j-consult " href="javascript:void(0);" rel="nofollow">立即咨询</a></div>
</div>
<div class="container m43">
	<div class="row">
		<h3>
			<span class="sr-only">红妆埋线双眼皮</span></h3>
		<p class="twoline">
			<span>原理</span>埋线双眼皮手术是指通过缝合的方式，是直接把缝线（或高分子缝合线）埋藏于皮肤及睑板之间，使上睑皮肤同睑板发生粘连，形成重睑的一种</p>
		<p>
			<span>优势</span>手术简便，缩短治疗及恢复时间，效果自然</p>
		<p>
			<span class="last">适合人群</span>适用于睑裂大、眼睑薄、无臃肿、眼睑皮肤无松弛而张力正常、无内眦赘皮的求美者</p>
		<div class="step">
			<img alt="手术过程说明图" src="//img.hzshuangmei.com/pc/qjsyp/img43_1.jpg" />
			<p>
				<span>术前：</span>综合求美者脸型、面部五官、个人气质等因素，按照三庭五眼的美学标准，定制适合求美者的双眼皮</p>
			<p>
				<span>术中：</span>将上睑分内、中、外三等份，在规划好的位置进行精确埋线</p>
			<p>
				<span>术后：</span>术后睁眼，完美重睑线可呈现，创伤小，消肿快，不留疤</p>
		</div>
		<div class="duibi">
			<img alt="翘睫双眼皮红妆埋线双眼皮手术前后对比图" class="fl" href="javascript:void(0);" rel="nofollow" src="//img.hzshuangmei.com/pc/qjsyp/img43_2.jpg" /> <img alt="翘睫双眼皮红妆埋线双眼皮手术前后对比图" class="fr" href="javascript:void(0);" rel="nofollow" src="//img.hzshuangmei.com/pc/qjsyp/img43_3.jpg" /></div>
		<a class="consult j-consult " href="javascript:void(0);" rel="nofollow">立即咨询</a></div>
</div>
<div class="container m44">
	<div class="row">
		<h3>
			<span class="sr-only">红妆三点定位双眼皮</span></h3>
		<p class="twoline">
			<span>原理</span>三点定位双眼皮手术过程就是在上眼睑皮肤准备形成重睑皱襞的部位内、中、外三个小口切开皮肤，使上眼睑皮肤与睑板粘连，呈现出完美的双眼皮。</p>
		<p>
			<span>优势</span>切口小，瘢痕不明显，效果自然</p>
		<p>
			<span class="last">适合人群</span>眼睑皮肤薄，眼裂长，鼻梁高的求美者</p>
		<div class="step">
			<img alt="手术过程说明图" src="//img.hzshuangmei.com/pc/qjsyp/img44_1.jpg" />
			<p>
				<span>术前：</span>针对个人眼形、面部五官比例及整体气质，数字化精细测量和设计，精准设计双眼皮的宽度和弧度，量身设计</p>
			<p>
				<span>术中：</span>突破性运用精细的皮肤纹路对接缝合技术，采用与皮肤纹理一致的切口方向，减少切口的张力，有效避免疤痕的产生</p>
			<p>
				<span>术后：</span>睑缘充分舒展，睫毛自然上翘，形成完美的重睑线</p>
		</div>
		<div class="duibi">
			<img alt="翘睫双眼皮三点定位双眼皮手术前后对比图" class="fl" href="javascript:void(0);" rel="nofollow" src="//img.hzshuangmei.com/pc/qjsyp/img44_2.jpg" /> <img alt="翘睫双眼皮三点定位双眼皮手术前后对比图" class="fr" href="javascript:void(0);" rel="nofollow" src="//img.hzshuangmei.com/pc/qjsyp/img44_3.jpg" /></div>
		<a class="consult j-consult " href="javascript:void(0);" rel="nofollow">立即咨询</a></div>
</div>
<div class="container m5">
	<div class="row">
		<h2>
			&nbsp;</h2>
		<img alt="李科" src="//img.hzshuangmei.com/pc/qjsyp/img5.png" />
		<div class="name">
			<p class="name" style="font-size:50px;">
				刘志坤</p>
			<p>
				DOCTOR</p>
		</div>
		<div class="discript">
			<ul>
				<li>
					红妆尚整形外科院长</li>
				<li>
					中国整形美容协会海峡两岸分会委员</li>
				<li>
					中西医结合医学美容专业委员会脂肪整形分会委员</li>
				<li>
					中国整形美容协会眼整形美容理事会青年理事</li>
				<li>
					湖南省医疗美容协会鼻整形专业委员会委员</li>
				<!--  <li>逸美透明质酸系列产品认证医师</li>
                    <li>大连医科大学特聘讲师</li>
                    <li>吸脂塑形领域资深专家</li> -->
			</ul>
			<h3>
				金牌项目：</h3>
			<p>
				眼部综合整形，鼻综合整形，乳房综合整形，纳米活细胞脂肪面雕，面部微创整形</p>
			<a class="consult j-consult " href="javascript:void(0);" rel="nofollow">立即咨询</a></div>
	</div>
</div>


<div  class="tjb">
    <div class="m_rj">
        <!--<div class="tjb_title1">-->
            <!--<img src="https://img.hzshuangmei.com/pc/tjb_title1.png" alt=""/>-->
        <!--</div>-->
               <div class="tjb_title1">
            <img src="https://img.hzshuangmei.com/pc/tjb_title1.png" alt="相关日记"/>
        </div><ul class="tjb_rj clearFix"> <li>
              <a href="/cases/eye/41.html" class="tbj_t" target="_blank">
                  <img src="https://uploads.hzshuangmei.com/171206/2-1G206154H4562.jpg" alt="术后"/>
              </a>
              <div class="tbj_b">
                  <a href="/cases/eye/41.html" class="tbj_b_img" target="_blank"><img src="https://uploads.hzshuangmei.com/171206/2-1G206154F5911.jpg" alt="术前"/></a>
                     <p class="p1 tbj_b_p1">【 速美项目 】</p>
                  <p class="p2"><a href="https://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;fi=68948">灵动翘睫双眼皮</a></p>
                  <a href="/cases/eye/41.html" class="tjb_video" target="_blank"><img src="//img.hzshuangmei.com/pc/tjb_video.png" alt="整形案例视频"/></a>
              </div>
              </li><li>
              <a href="/cases/eye/117.html" class="tbj_t" target="_blank">
                  <img src="https://uploads.hzshuangmei.com/180108/2-1P10QFG55P.jpg" alt="术后"/>
              </a>
              <div class="tbj_b">
                  <a href="/cases/eye/117.html" class="tbj_b_img" target="_blank"><img src="https://uploads.hzshuangmei.com/180108/2-1P10QFF0540.jpg" alt="术前"/></a>
                     <p class="p1 tbj_b_p1">【 速美项目 】</p>
                  <p class="p2"><a href="https://www.hzshuangmei.com/projects/eye/qjsyp.html">双眼皮手术</a>、<a href="https://www.hzshuangmei.com/projects/eye/kyj.html">开内眼角手术</a></p>
                  <a href="/cases/eye/117.html" class="tjb_video" target="_blank"><img src="//img.hzshuangmei.com/pc/tjb_video.png" alt="整形案例视频"/></a>
              </div>
              </li><li>
              <a href="/cases/eye/119.html" class="tbj_t" target="_blank">
                  <img src="https://uploads.hzshuangmei.com/180109/2-1P109110Z4a8.jpg" alt="术后"/>
              </a>
              <div class="tbj_b">
                  <a href="/cases/eye/119.html" class="tbj_b_img" target="_blank"><img src="https://uploads.hzshuangmei.com/180109/2-1P109110T14M.JPG" alt="术前"/></a>
                     <p class="p1 tbj_b_p1">【 速美项目 】</p>
                  <p class="p2"><a href="https://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;fi=68948">芭比大眼术</a>&nbsp;<a href="https://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;fi=68948">芭比翘鼻术</a></p>
                  <a href="/cases/eye/119.html" class="tjb_video" target="_blank"><img src="//img.hzshuangmei.com/pc/tjb_video.png" alt="整形案例视频"/></a>
              </div>
              </li></ul>
    </div>
    <div class="m_zj">
        <!--<div class="tjb_title2">-->
            <!--<img src="https://img.hzshuangmei.com/pc/tjb_title2.png" alt=""/>-->
        <!--</div>-->
             <div class="tjb_title2">
            <img src="https://img.hzshuangmei.com/pc/tjb_title2.png" alt="推荐专家"/>
        </div><ul class="tjb_zj clearFix"> <li class="clearFix">
                <a href="/plugin/view.php?aid=227" class="tjb_l" target="_blank"><img src="https://uploads.hzshuangmei.com/180414/1-1P4140929454T.jpg" alt="薛开兴"/></a>
                <div class="tjb_r">
                    <p class="p3"><a href="/plugin/view.php?aid=227" class="tjb_name" target="_blank">薛开兴</a></p>
                    <p class="p4"><a href="/plugin/view.php?aid=227" target="_blank">整形外科院长</a></p>
                    <div class="tjb_sc clearFix">
                        <p>擅长项目：</p>
                        <p>鼻部综合整形 眼部综合整形 玻尿酸注射 面部年轻化整形  </p>
                    </div>
                    <div class="tjb_button">
                        <a class="j-consult" href="javascript:void(0);" rel="nofollow" target="_blank"><img src="//img.hzshuangmei.com/pc/tjb_button.png" alt="点击咨询"/></a>
                    </div>
                </div></li><li class="clearFix">
                <a href="/doctors/surgery/guanhaitao.html" class="tjb_l" target="_blank"><img src="https://uploads.hzshuangmei.com/180227/1-1P22G44625M2.jpg" alt="关海涛 "/></a>
                <div class="tjb_r">
                    <p class="p3"><a href="/doctors/surgery/guanhaitao.html" class="tjb_name" target="_blank">关海涛 </a></p>
                    <p class="p4"><a href="/doctors/surgery/guanhaitao.html" target="_blank">整形外科院长</a></p>
                    <div class="tjb_sc clearFix">
                        <p>擅长项目：</p>
                        <p><a href="http://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;fi=68948">V立美线雕</a> <a href="http://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;fi=68948">鼻部整形</a>&nbsp; <a href="http://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;fi=68948">眼部综合整形</a>  </p>
                    </div>
                    <div class="tjb_button">
                        <a class="j-consult" href="javascript:void(0);" rel="nofollow" target="_blank"><img src="//img.hzshuangmei.com/pc/tjb_button.png" alt="点击咨询"/></a>
                    </div>
                </div></li></ul>
    </div>
    <div class="m_xm">
        <!--<div class="tjb_title3">-->
            <!--<img src="https://img.hzshuangmei.com/pc/tjb_title3.png" alt=""/>-->
        <!--</div>-->
        <!--<div class="tjb_xm">-->
               <div class="tjb_title3">
            <img src="https://img.hzshuangmei.com/pc/tjb_title3.png" alt="相关项目"/>
        </div><div class="tjb_xm"><div class="tjb_img clearFix">
  <a href="/projects/eye/yandai.html" target="_blank"><img src="https://uploads.hzshuangmei.com/180404/1-1P404160Q03S.jpg" alt="无痕祛眼袋"></a><a href="/projects/eye/hzyj.html" target="_blank"><img src="https://uploads.hzshuangmei.com/180206/1-1P206100342338.jpg" alt="红妆孕睫术"></a><a href="/projects/eye/sypjgjm.html" target="_blank"><img src="https://uploads.hzshuangmei.com/180126/1-1P1261A955N2.jpg" alt="双眼皮价格解密"></a>
</div>         </div>

        <!--</div>-->
    </div>
</div>
<div class="index_items" id="index_items">
    <div class="shuang_m1">
        <div class="clearFix border-r">
            <div class="icon">
                <span>双美概况</span>
                <i></i>
            </div>
            <ul class="mar_t">
                <li><a href="/" target="_blank" rel="noopener" >>返回首页</a></li>
                <li><a class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener">>来院路线</a></li>
                <li><a class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener">>联系我们</a></li>
                <li><a href="/brand" target="_blank" rel="noopener">>品牌起源</a></li>
                <!--<li><a href="">>企业文化</a></li>-->
            </ul>
        </div>
        <div class="clearFix border-l border-r">
            <div class="icon">
                <span>整形美容</span>
                <i></i>
            </div>
            <ul class="mar_t">
                <li><a href="/projects/chest/#project_nav" target="_blank" rel="noopener">>胸部整形</a></li>
                <li><a href="/projects/eye/#project_nav" target="_blank" rel="noopener">>眼部整形</a></li>
                <li><a href="/projects/nose/#project_nav" target="_blank" rel="noopener">>鼻部整形</a></li>
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>唇部整形</a></li>
                <li><a href="/projects/body/#project_nav" target="_blank" rel="noopener">>塑形体雕</a></li>
                <li><a href="/projects/zhifang/ztzfmd.html" target="_blank" rel="noopener">>自体脂肪填充</a></li>
                <li><a href="/projects/#project_nav" target="_blank" rel="noopener">>其他系列</a></li>
                <li><a href="/projects/ha/bnsxb.html" target="_blank" rel="noopener">>下巴整形</a></li>
                <li><a href="/projects/private/#project_nav" target="_blank" rel="noopener">>私密整形</a></li>
            </ul>
        </div>
        <div class="clearFix border-l border-r">
            <div class="icon">
                <span>光学美肤</span>
                <i></i>
            </div>
            <ul class="mar_t">
                <li><a href="/projects/quban/quban.html" target="_blank" rel="noopener">>美白祛斑</a></li>
                <li><a href="/projects/tuomao/tuomao2.html" target="_blank" rel="noopener">>专业脱毛</a></li>
                <li><a href="/projects/qudou/hzqdk.html" target="_blank" rel="noopener">>祛痘祛疤印</a></li>
                <li><a href="/projects/chuzhou/quzhou.html" target="_blank" rel="noopener">>紧肤抗衰</a></li>
            </ul>
        </div>
        <div class="clearFix border-l">
            <div class="icon">
                <span>微创美容</span>
                <i></i>
            </div>
            <ul class="mar_t">
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>玻尿酸塑形</a></li>
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>玻尿酸祛皱</a></li>
                <li><a href="/projects/botox/#project_nav" target="_blank" rel="noopener">>BOTOX注射</a></li>
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>疤痕针</a></li>
                <li><a href="/projects/tattoo/#project_nav" target="_blank" rel="noopener">>纹绣</a></li>
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>水光注射</a></li>
                <li><a href="/projects/#project_nav" target="_blank" rel="noopener">>其他</a></li>
            </ul>
        </div>
    </div>
</div>
<footer id="footer">
    <div class="shuang_m1 clearFix">
        <div class="left">
            <h2><a href=""><img src="https://img.hzshuangmei.com/pc/f_logo.png" alt="红妆双美"/></a></h2>
            <p class="addr"><i></i>红妆双美地址：海口市海府路4号海口宾馆附楼2层</p>
            <p>本站信息仅供参考建 版权所有:红妆双美 https://www.hzshuangmei.com<br/>
                <a href="http://www.miitbeian.gov.cn/" rel="nofollow" target="_blank">琼ICP备17004048号-1</a> (海)医广[2017]第085号 <a href="//www.hzshuangmei.com/humans.txt" rel="nofollow" target="_blank"><img src="//img.hzshuangmei.com/pc/humanstxt-transparent-color.png" class="humanstxt"></a><br/>
                网站部分图文来源于网络，如有侵权，请联系我们 联系电话：0898-66156043</p>
        </div>
        <div class="middle"></div>
        <div class="right right1">
            <div class="right_t clearFix">
                <div class="clearFix">
                    <div class="ewm"></div>
                    <div>
                        <p class="fon1">微信扫一扫</p>

                        <p>1）获得最新优惠</p>

                        <p>2）在线实时咨询</p>

                        <p>3）专属服务通道</p>
                    </div>
                </div>

                <div class="clearFix">
                    <div class="f_phone"></div>
                    <div>
                        <p class="fon1">全国免费咨询热线</p>

                        <p class="fon2">0898-66156043</p>

                        <p class="fon3">咨询时间：8:00—20:00</p>
                    </div>
                </div>
            </div>
             <!--<div class="right_b">-->
                <!--<i></i><span>友情链接:</span>-->
                <!---->
                <!--<a href='https://www.honorreal.com/' target='_blank'>红瑞集团</a> /-->
                <!---->
                <!--<a href='https://www.hoozonspa.com' rel='nofollow' target='_blank'>红妆美容</a> /-->
                <!---->
                <!--<a href='http://www.yueyimei.com' target='_blank'>悦伊美</a> /-->
                <!---->
            <!--</div>-->
            <p class="copyright">Copyright © 2017 红妆双美 版权所有 违者必究 | <a href="/statement/copyright.html" rel="nofollow" target="_blank" rel="noopener">版权及隐私声明</a><br>
              设计,文案,技术等求职请投递至网络部root#hzwlb.org(#替换成@)</p>
        </div>
    </div>
</footer>
<!-- 右侧悬浮 开始 -->
<div class="yb_conct">
    <div class="yb_bar">
        <ul>
            <li class="yb_QQ"><a target="_blank" rel="noopener" href="javascript:void(0)" class="j-site-consult" title="立即咨询" rel="nofollow">立即咨询</a></li>
            <li class="yb_phone"><a target="_blank" rel="noopener" href="javascript:void(0)" class="j-site-consult" title="门店查询" rel="nofollow">门店查询</a></li>
            <li class="yb_top">返回顶部</li>
            <li class="yb_ercode" >微信扫一扫<br>
                <img class="hd_qr" src="https://img.hzshuangmei.com/pc/WeChatApplet.jpg" width="125" alt="关注微信小程序">
            </li>
        </ul>
    </div>
</div>
<!-- 结束 -->

</body>
<link rel="preload" href="https://js.hzshuangmei.com/pc/common.js" as="script" crossorigin>
<link rel="preload" href="https://js.hzshuangmei.com/pc/layer/layer.js" as="script" crossorigin>
<link rel="preload" href="https://js.hzshuangmei.com/pc/kst_popup.js" as="script" crossorigin>
<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/Swiper/3.4.2/js/swiper.min.js"></script>
<script src="https://js.hzshuangmei.com/pc/common.js" ></script>
<script src="https://js.hzshuangmei.com/pc/layer/layer.js"></script>
<script src="https://js.hzshuangmei.com/pc/kst_popup.js"></script>
 <!-- html5标签兼容ie低版本浏览器 -->
<!-- [if lt IE 9]>     -->
<script src="https://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<!-- <![endif] -->
<!-- 百度站内搜索 -->
<!-- <script type="text/javascript">(function(){document.write(unescape('%3Cdiv id="bdcs"%3E%3C/div%3E'));var bdcs = document.createElement('script');bdcs.type = 'text/javascript';bdcs.async = true;bdcs.src = '//znsv.baidu.com/customer_search/api/js?sid=5257607230163915007' + '&plate_url=' + encodeURIComponent(window.location.href) + '&t=' + Math.ceil(new Date()/3600000);var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(bdcs, s);})();</script> -->



</html>
