<!DOCTYPE html>
<html lang="zh-cmn-Hans">
<head>
    <!-- Make 2018-04-21 18:05:40 -->
<!-- Make 1524305140 -->
<meta charset="UTF-8">
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
<meta name="renderer" content="webkit"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
<meta name=applicable-device content="pc">
<meta http-equiv="Cache-Control" content="no-transform"/>
<meta http-equiv="Cache-Control" content="no-siteapp"/>
<meta name="baidu-site-verification" content="99J7V1k1Vz" />
<meta name="google-site-verification" content="Odmo8X4zeUG1WPcCrCAueZz-dyBPFBs4Zqlb9FBT5z4" />
<meta http-equiv="Access-Control-Allow-Origin" content="*" />
<!-- Global site tag (gtag.js) - Google Analytics -->
<!-- <script async src="https://www.googletagmanager.com/gtag/js?id=UA-114904919-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-114904919-2');
</script> -->

    <meta name="keywords" content="红妆,红妆双美,红妆生活美容,红妆医学美容"/>
    <meta name="description" content="红妆双美，秉承“医美+生美＝完美”“一站双享美丽+”的理念，专为女性的美丽智能服务。致力于为更多的爱美者提供“智能美颜、科技瘦身、光电抗衰、艺术纹绣、微创整形、激光美肤”等核心品项，使更多的女性悦享『医学美容』快速变美和『生活美容』持续养护的双重惊喜，实现更合理更有效的恒久美丽。"/>
    <meta name="author" content="设计：于涛，前端：王苗"/>
    <title>海南红妆时尚双美整形美容连锁</title>
    <!-- Pre for optimization -->
<link rel="dns-prefetch" href="https://cdn.bootcss.com">
<link rel="dns-prefetch" href="https://uploads.hzshuangmei.com">
<link rel="dns-prefetch" href="https://img.hzshuangmei.com">
<link rel="dns-prefetch" href="https://css.hzshuangmei.com">
<link rel="dns-prefetch" href="https://js.hzshuangmei.com">
<link rel="dns-prefetch" href="https://pv.kuaishang.cn">
<link rel="dns-prefetch" href="https://z8.cnzz.com">
<link rel="dns-prefetch" href="https://s19.cnzz.com">
<link rel="dns-prefetch" href="https://tag.baidu.com">
<link rel="dns-prefetch" href="https://sp0.baidu.com">
<link rel="preload" href="https://css.hzshuangmei.com/pc/common.css" as="style" crossorigin />
<link rel="preload" href="https://img.hzshuangmei.com/pc/favicon.ico" as="image" type="image/x-icon" crossorigin />
<!-- Style for the page-->
<link rel="stylesheet" href="https://cdn.bootcss.com/Swiper/3.4.2/css/swiper.min.css"/>
<link rel="stylesheet" href="https://css.hzshuangmei.com/pc/common.css"/>
<link rel="stylesheet" href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" >
<!-- favicon.ico -->
<link rel="icon" href="https://img.hzshuangmei.com/pc/favicon.ico" type="image/x-icon"/>
<link rel="shortcut icon" href="https://img.hzshuangmei.com/pc/favicon.ico" type="image/x-icon"/>
<!-- humanstxt -->
<link rel="author" href="https://www.hzshuangmei.com/humans.txt" />
<link rel="preload" as=image  href="https://img.hzshuangmei.com/pc/kst/default.png">
<link rel="prefetch" src="https://img.hzshuangmei.com/pc/kst/default.png">
<link rel="prerender" src="https://img.hzshuangmei.com/pc/kst/default.png">
<link rel="prefetch" src="https://img.hzshuangmei.com/pc/kst/.png">
<link rel="prerender" src="https://img.hzshuangmei.com/pc/kst/.png">
<link rel="preload" as=image  href="https://img.hzshuangmei.com/pc/kst/.png">

    <link rel="preload" href="https://css.hzshuangmei.com/pc/index.css" as="style" crossorigin />
    <link rel="preload" href="https://js.hzshuangmei.com/pc/index.js" as="script" crossorigin />
    <link rel="preload" href="https://img.hzshuangmei.com/pc/brand2.webm" as="video"  type="video/webm" crossorigin />
    <link rel="stylesheet" href="https://css.hzshuangmei.com/pc/index.css"/>
    <link rel="canonical" href="https://www.hzshuangmei.com/">
    <link rel="alternate" media="only screen and(max-width: 640px)"     href="https://m.hzshuangmei.com/" >
</head>
<body>
<header>
    <div class="top">
        <div class="shuang_m1 clearFix">
            <div class="top_l">
                <!--<span>香港红瑞集团 旗下品牌 海南红妆双美连锁</span>-->
                <img src="https://img.hzshuangmei.com/pc/tl_logo.png" alt="logo" />|<span>美丽时间：周一周日9点--21点</span>
            </div>
            <!-- 增加百度站内搜索 -->
            <div class="top_c">
                <div class="search_box">
                    <form action="https://www.hzshuangmei.com/search/" target="_blank" autocomplete="off" id="bdcs-search-form" class="site-search-form">
                        <input type="hidden" name="s" value="5257607230163915007">
                         <input type="hidden" name="entry" value="1">
                        <input type="text" placeholder="请输入您要搜索的内容..." id="bdcsMain" name="q">
                        <button type="submit" id="bdcs-search-form-submit"></button>
                    </form>
                </div>
            </div>
                        <!-- 增加百度站内搜索 -->
            <div class="top_r">
                <a href="" class="pad_r"><i class="tel"></i><span>0898-66156043</span></a>
                <span>关注我们：</span>
                <a href="" class="pad_l"><i class="wbo"></i></a>
                <a href=""><i class="wxin"></i></a>
                <a href=""><i class="qq"></i></a>
            </div>
        </div>
    </div>
    <div class="sm_logo">
        <a href="/"><img src="https://img.hzshuangmei.com/pc/h_logo.png" alt=""/></a>
    </div>
</header>
<nav id="nav">
    <ul class="shuang_m1 nav_ul">
        <li class="nav_list">
            <a href="/" class="nav_link" target="_blank" rel="noopener">
                <span>首 页</span><br/>
                <span>Home</span>
            </a>
        </li>
        <li class="nav_list">
            <a href="/brand" class="nav_link bor_r" target="_blank" rel="noopener">
                <span>品 牌</span><br/>
                <span>brands</span>
            </a>
        </li>
        <li class="nav_list">
            <a href="/projects" class="nav_link bor_l bor_r" target="_blank" rel="noopener">
                <span>项 目</span><br/>
                <span>projects</span>
            </a>
            <div class="clearFix" id="project">
                <ul>
                    <li>
                        <h5><a href="/projects/tattoo/" target="_blank" rel="noopener">医学纹绣</a></h5>
                    </li>
                    <!--              <li>
                        <a href="/projects/tattoo/yanxian.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P4041610355P.jpg" alt="红妆艺术美瞳线"/>
                            <p><i></i><span>红妆艺术美瞳线</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/tattoo/hsbyjwm.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404160923556.jpg" alt="韩式半永久纹眉"/>
                            <p><i></i><span>韩式半永久纹眉</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/tattoo/xwx.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/img/180331/1-1P3311106490-L.jpg" alt="洗纹绣"/>
                            <p><i></i><span>洗纹绣</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/tattoo/xwx.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/img/180331/1-1P3311106490-L.jpg" alt="洗纹绣"/>
                            <p><i></i><span>洗纹绣</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/tattoo/wash.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180222/1-1P222110205243.jpg" alt="激光洗纹绣"/>
                            <p><i></i><span>激光洗纹绣</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/tattoo/hsbyjwm.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404160923556.jpg" alt="韩式半永久纹眉"/>
                            <p><i></i><span>韩式半永久纹眉</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button">-->
                    <!--<a href="/projects" target="_blank" rel="noopener">查看更多</a>-->
                    <!--</li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/eye/" target="_blank" rel="noopener">眼部整形</a></h5>
                    </li>
                    <!--   <li>
                        <a href="/projects/eye/qmtm.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404161354458.jpg" alt=""/>
                            <p><i></i><span>切眉提眉术</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/eye/slxc.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180222/1-1P22216455E61.jpg" alt=""/>
                            <p><i></i><span>上睑下垂</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/eye/yandai.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404160Q03S.jpg" alt=""/>
                            <p><i></i><span>无痕祛眼袋</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/eye/yandai.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404160Q03S.jpg" alt="无痕祛眼袋"/>
                            <p><i></i><span>无痕祛眼袋</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/eye/slxc.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180222/1-1P22216455E61.jpg" alt="上睑下垂"/>
                            <p><i></i><span>上睑下垂</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/eye/hzyj.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180206/1-1P206100342338.jpg" alt="红妆孕睫术"/>
                            <p><i></i><span>红妆孕睫术</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/nose/" target="_blank" rel="noopener">鼻部整形</a></h5>
                    </li>
                    <!--              <li>
                        <a href="/projects/nose/lineeaglenose.html" target="_blank" rel="noopener">
                        <img src="https://uploads.hzshuangmei.com/180109/1-1P10916214I29.jpg" alt=""/>
                            <p><i></i><span>线雕隆鼻</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/nose/heben.html" target="_blank" rel="noopener">
                        <img src="https://uploads.hzshuangmei.com/180109/1-1P109162114246.jpg" alt=""/>
                            <p><i></i><span>红妆赫本软骨鼻</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/nose/longbijiage.html" target="_blank" rel="noopener">
                        <img src="https://uploads.hzshuangmei.com/180209/1-1P2091524433K.jpg" alt=""/>
                            <p><i></i><span>隆鼻价格</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/nose/longbijiage.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180209/1-1P2091524433K.jpg" alt="隆鼻价格"/>
                            <p><i></i><span>隆鼻价格</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/nose/hzbbqb.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180208/1-1P20QZ14O61.jpg" alt="红妆芭比翘鼻"/>
                            <p><i></i><span>红妆芭比翘鼻</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/nose/nose.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180109/1-1P109161Fc42.jpg" alt="全立体鼻缩窄术"/>
                            <p><i></i><span>全立体鼻缩窄术</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/face/" target="_blank" rel="noopener">面部整形</a></h5>
                    </li>
                    <!--                <li class="star">
                        <a href="/projects/zhifang/ztzfmd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180109/1-1P109162329454.jpg" alt=""/>
                            <p><i></i><span>自体脂肪面雕</span></p>
                        </a>
                    </li><li class="star">
                        <a href="/projects/xiaba/vlmxd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P40416062R04.jpg" alt=""/>
                            <p><i></i><span>v立美线雕</span></p>
                        </a>
                    </li><li class="star">
                        <a href="/projects/face/zitizhifang.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180208/1-1P20Q54P4G4.jpg" alt=""/>
                            <p><i></i><span>自体脂肪面部填充</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/face/zitizhifang.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180208/1-1P20Q54P4G4.jpg" alt="自体脂肪面部填充"/>
                            <p><i></i><span>自体脂肪面部填充</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/xiaba/vlmxd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P40416062R04.jpg" alt="v立美线雕"/>
                            <p><i></i><span>v立美线雕</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/zhifang/ztzfmd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180109/1-1P109162329454.jpg" alt="自体脂肪面雕"/>
                            <p><i></i><span>自体脂肪面雕</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/skin/" target="_blank" rel="noopener">皮肤美容</a></h5>
                    </li>
                    <!--                 <li>
                        <a href="/projects/qudou/duoweiqd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180222/1-1P222143953U0.jpg" alt=""/>
                            <p><i></i><span>红妆多维祛痘</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/quban/xpmqb.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180328/1-1P32Q356202V.jpg" alt=""/>
                            <p><i></i><span>红妆皮秒祛斑</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/skin/sgz.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180406/1-1P4061A303F6.jpg" alt=""/>
                            <p><i></i><span>水光针</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/quban/xpmqb.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180328/1-1P32Q356202V.jpg" alt="红妆皮秒祛斑"/>
                            <p><i></i><span>红妆皮秒祛斑</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/chuzhou/quzhou.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180212/1-1P212102446403.jpg" alt="除皱抗衰"/>
                            <p><i></i><span>除皱抗衰</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/quban/quban.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180312/1-1P3121601494G.jpg" alt="红妆祛斑"/>
                            <p><i></i><span>红妆祛斑</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/ha/" target="_blank" rel="noopener">玻尿酸</a></h5>
                    </li>
                    <!--                     <li>
                        <a href="/projects/ha/qydbns.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180208/1-1P20Q0501X26.jpg" alt=""/>
                            <p><i></i><span>乔雅登玻尿酸</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/ha/zhbns.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180109/1-1P109161SV57.jpg" alt=""/>
                            <p><i></i><span>综合玻尿酸</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/ha/restylane.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180413/1-1P413100FcV.jpg" alt=""/>
                            <p><i></i><span>瑞蓝玻尿酸</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/ha/restylane.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180413/1-1P413100FcV.jpg" alt="瑞蓝玻尿酸"/>
                            <p><i></i><span>瑞蓝玻尿酸</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/ha/bnsqflw.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180411/1-1P411140P9134.jpg" alt="玻尿酸祛除法令纹"/>
                            <p><i></i><span>玻尿酸祛除法令纹</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/ha/xbnsfet.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180322/1-1P322092GMV.jpg" alt="玻尿酸丰额头"/>
                            <p><i></i><span>玻尿酸丰额头</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/body/" target="_blank" rel="noopener">形体雕塑</a></h5>
                    </li>
                    <!-- <li>
                        <a href="/projects/body/sdlxz.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404161320X4.jpg" alt=""/>
                            <p><i></i><span>水动力吸脂</span></p>
                       </a>
                    </li> -->
                    <li>
                        <a href="/projects/body/sdlxz.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404161320X4.jpg" alt="水动力吸脂"/>
                            <p><i></i><span>水动力吸脂</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
            </div>
        </li>
        <li class="nav_list">
            <a href="/doctors" class="nav_link bor_l bor_r" target="_blank" rel="noopener">
                <span>专 家</span><br/>
                <span>experts</span>
            </a>
            <div id="expert">
                <ul>
                    <li>
                        <h5><a href="/doctors/surgery" target="_blank" rel="noopener">整形美容专家</a></h5>
                    </li>
                    <!--                     <li>
                        <a href="/plugin/view.php?aid=227" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180414/1-1P4140929454T.jpg" alt="薛开兴"/>
                            <p><span class="n_f">薛开兴</span><span class="n_b">整形外科院长</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=153" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180131/1-1P131093205432.jpg" alt="余志亮"/>
                            <p><span class="n_f">余志亮</span><span class="n_b">整形专家</span></p>
                            <i></i>
                        </a>
                    </li> -->
                    <li>
                        <a href="/doctors/surgery/guanhaitao.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180227/1-1P22G44625M2.jpg" alt="关海涛 "/>
                            <p><span class="n_f">关海涛 </span><span class="n_b">整形外科院长</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=176" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180131/1-1P1310U92D41.jpg" alt="朱红振"/>
                            <p><span class="n_f">朱红振</span><span class="n_b">整形外科院长</span></p>
                            <i></i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <h5><a href="/doctors/laser" target="_blank" rel="noopener">激光美容专家</a></h5>
                    </li>
                    <!--             <li>
                        <a href="/doctors/laser/lijie.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/171206/1-1G20611435D10.jpg" alt="李杰"/>
                            <p><span class="n_f">李杰</span><span class="n_b">光学美肤中心院长</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/doctors/laser/yzw.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180131/1-1P131104604521.jpg" alt="姚志文"/>
                            <p><span class="n_f">姚志文</span><span class="n_b">非手术面部年轻化专家</span></p>
                            <i></i>
                        </a>
                    </li> -->
                    <li>
                        <a href="/doctors/laser/lijie.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/171206/1-1G20611435D10.jpg" alt="李杰"/>
                            <p><span class="n_f">李杰</span><span class="n_b">光学美肤中心院长</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/doctors/laser/yzw.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180131/1-1P131104604521.jpg" alt="姚志文"/>
                            <p><span class="n_f">姚志文</span><span class="n_b">非手术面部年轻化专家</span></p>
                            <i></i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <h5><a href="/doctors/tattoo" target="_blank" rel="noopener">医学纹绣</a></h5>
                    </li>
                    <!--                    <li>
                        <a href="/plugin/view.php?aid=139" target="_blank" rel="noopener">
                    <img src="https://uploads.hzshuangmei.com/180117/1-1P11GF5391A.jpg" alt="杨小丽"/>
                            <p><span class="n_f">杨小丽</span><span class="n_b">纹饰指导师</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=136" target="_blank" rel="noopener">
                    <img src="https://uploads.hzshuangmei.com/180125/1-1P125154A1105.jpg" alt="高方云"/>
                            <p><span class="n_f">高方云</span><span class="n_b">纹饰指导师</span></p>
                            <i></i>
                        </a>
                    </li> -->
                    <li>
                        <a href="/plugin/view.php?aid=164" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180125/1-1P12515435J45.jpg" alt="冯晓琳"/>
                            <p><span class="n_f">冯晓琳</span><span class="n_b">纹饰技术总指导师</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=137" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180117/1-1P11GA95JV.jpg" alt="孟超"/>
                            <p><span class="n_f">孟超</span><span class="n_b">纹饰指导师</span></p>
                            <i></i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <h5><a href="/doctors" target="_blank" rel="noopener">特邀专家</a></h5>
                    </li>
                    <li>
                        <a href="/doctors/surgery/ljb.html" target="_blank" rel="noopener">
                             <img src="https://uploads.hzshuangmei.com/180131/1-1P131092S24W.jpg" alt="雷建波(客座)"/>
                            <p><span class="n_f">雷建波(客座)</span><span class="n_b">整形美容专家</span></p>
                            <i></i>
                        </a>
                    </li>
<li>
                        <a href="/doctors/surgery/liudalie.html" target="_blank" rel="noopener">
                             <img src="https://uploads.hzshuangmei.com/171223/1-1G223091J5950.jpg" alt="柳大烈(客座)"/>
                            <p><span class="n_f">柳大烈(客座)</span><span class="n_b">教授</span></p>
                            <i></i>
                        </a>
                    </li>

                </ul>
                <ul>
                    <li>
                        <h5 class="moon"><a href="/doctors" target="_blank" rel="noopener">每月专家</a></h5>
                    </li>
                    <li class="last-one">
                        <!--<a class="last-one" href="https://www.hzshuangmei.com/doctors/surgery/liudalie.html " target="_blank" rel="noopener">-->
                            <!--<img src="https://img.hzshuangmei.com/pc/nav_zhuanjial.jpg" alt=""/>-->
                        <!--</a>-->
                        <a class="last-one j-consult" href="javascript:void(0)"  target="_blank" rel="noopener nofollow">
                            <img src="https://img.hzshuangmei.com/pc/myzzj.jpg" alt=""/>
                        </a>
                    </li>
                </ul>
            </div>
        </li>
        <li class="nav_list">
            <a href="/cases" class="nav_link bor_l bor_r" target="_blank" rel="noopener">
                <span>真人秀</span><br/>
                <span>Show</span>
            </a>
        </li>
        <li class="nav_list">
            <a href="/news" class="nav_link bor_l" target="_blank" rel="noopener">
            <span>活 动</span><br/>
                <span>News</span>
            </a>
        </li>
    </ul>
</nav>

<h1><span class="sr-only">海南红妆时尚双美整形美容连锁</span></h1>
<div class="banner">
    <div class="swiper-container banner_swiper">
    <div class="swiper-wrapper">
        <!--<a href="javascript:void(0)" target="_blank" class="swiper-slide j-site-consult">-->
        <!--<img src="//img.hzshuangmei.com/pc/banner/xnxymm.jpg" alt="新年新颜"/>-->
        <!--</a>-->
        <!--<a href="javascript:void(0)" target="_blank" class="swiper-slide j-site-consult">-->
        <!--<img src="//img.hzshuangmei.com/pc/banner/banner0.jpg" alt="新年耀美"/>-->
        <!--</a>-->
        <!--<a class="j-consult swiper-slide" href="javascript:void(0)"  rel="nofollow">-->
        <!--<img src="//img.hzshuangmei.com/pc/banner/pczzj.jpg" alt="张子杰专家"/>-->
        <!--</a>-->
        <a class="j-consult swiper-slide" href="javascript:void(0)"  rel="nofollow">
            <img src="//img.hzshuangmei.com/pc/banner/wxsg.jpg" alt="纹绣水光"/>
        </a>
        <a class="j-consult swiper-slide" href="javascript:void(0)"  rel="nofollow">
            <img src="//img.hzshuangmei.com/pc/banner/banner6.jpg" alt="樱花唇"/>
        </a>
        <!--<a href="//www.hzshuangmei.com/brand/"  class="swiper-slide">-->
            <!--<img src="//img.hzshuangmei.com/pc/banner/banner1.jpg" alt="红妆22年"/>-->
        <!--</a>-->
        <!--<a href="//www.hzshuangmei.com/projects/tattoo/byjwm.html" class="swiper-slide">-->
        <!--<img src="//img.hzshuangmei.com/pc/banner/banner2.jpg " alt="半永久纹眉"/>-->
        <!--</a>-->
        <a href="//www.hzshuangmei.com/projects/eye/qjsyp.html " class="swiper-slide">
            <img src="//img.hzshuangmei.com/pc/banner/banner3.jpg" alt="翘睫双眼皮"/>
        </a>
        <a href="//www.hzshuangmei.com/projects/nose/dlslb.html" class="swiper-slide">
            <img src="//img.hzshuangmei.com/pc/banner/banner5.jpg" alt="达拉斯隆鼻"/>
        </a>
        <a class="j-consult swiper-slide" href="javascript:void(0)"  rel="nofollow">
            <img src="//img.hzshuangmei.com/pc/banner/hzjm.jpg" alt="红妆脊美"/>
        </a>
    </div>
    <div class="swiper-pagination banner-pagination"></div>
</div>
</div>
<div class="index_news">
    <div class="m1 clearFix">
        <div class="video">
            <h2>
                <a href="/video/" target="_blank" rel="noopener">
                    <span>视频中心</span><br/>
                    <img src="https://img.hzshuangmei.com/pc/n_video_center.png"   alt="video center"/>
                </a>
            </h2>
            <div class="swiper-button-next video-button-next"></div>
            <div class="swiper-button-prev video-button-prev"></div>
            <div class="swiper-container video_swiper">
    <div class="swiper-wrapper">
        <div class="swiper-slide">
            <video width="369" height="282" controls="true"  name="media" poster="https://img.hzshuangmei.com/pc/brand.jpg" preload="meta">
   <source src="https://img.hzshuangmei.com/pc/brand2.webm" type="video/webm" >
      <!--      <source src="https://img.hzshuangmei.com/pc/brand.mp4" type="video/mp4" > -->
            </video>
            <p>红妆双美品牌介绍</p>
        </div>
        <div class="swiper-slide">
            <video width="369" height="282" controls="true"" name="media" poster="https://img.hzshuangmei.com/pc/brand.jpg"  preload="meta">
  <source src="https://img.hzshuangmei.com/pc/brand2.webm" type="video/webm" >
          <!--      <source src="https://img.hzshuangmei.com/pc/brand.mp4" type="video/mp4" > -->
            </video>
            <p>红妆双美品牌介绍</p>
        </div>
        <div class="swiper-slide">
            <video width="369" height="282" controls="true"  name="media" poster="https://img.hzshuangmei.com/pc/brand.jpg" preload="meta">
  <source src="https://img.hzshuangmei.com/pc/brand2.webm" type="video/webm" >
  <!-- <source src="https://img.hzshuangmei.com/pc/brand.mp4" type="video/mp4"> -->
            </video>
            <p>红妆双美品牌介绍</p>
        </div>
    </div>
</div>
        </div>
        <div class="news">
            <h2 class="news_h">
                <a href="/news/" target="_blank" rel="noopener">
                    <span>新闻中心</span><br/>
                    <img src="https://img.hzshuangmei.com/pc/latest_activity.png"  alt="latest activity"/>
                </a>
            </h2>

            <div class="news_content">
                <div class="swiper-button-next news-button-next"></div>
                <div class="swiper-button-prev news-button-prev"></div>
                <div class="swiper-container news_swiper">
                    <div class="swiper-wrapper">
                        <a href="/news/210.html" class="swiper-slide" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180321/2-1P32110514M48.jpg"  alt="女神节|心悦女神，乐享三">

                            <div class="timu">女神节|心悦女神，乐享三八暨红妆&颜值青春健康行活动圆满举办！</div>
                            <div class="date">
                                <span>21</span>
                                <span>2018-03</span>
                            </div>
                        </a>
<a href="/news/204.html" class="swiper-slide" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180226/2-1P22611141U45.jpg"  alt="红瑞资讯|红瑞集团举行开">

                            <div class="timu">红瑞资讯|红瑞集团举行开年拜师仪式，学习分享红瑞企业文化！ </div>
                            <div class="date">
                                <span>26</span>
                                <span>2018-02</span>
                            </div>
                        </a>
<a href="/news/201.html" class="swiper-slide" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180221/2-1P221140J9A1.jpg"  alt="青春芳华 美好生活 | 热烈">

                            <div class="timu">青春芳华 美好生活 | 热烈祝贺2018红瑞嘉年华盛典圆满举办 </div>
                            <div class="date">
                                <span>21</span>
                                <span>2018-02</span>
                            </div>
                        </a>

                    </div>
                    <div class="swiper-pagination news-pagination"></div>
                </div>
            </div>
            <div class="inform">
                <span class="tj_tit">最新推荐：</span>

                <div class="swiper-container news_tuijian">
                    <div class="swiper-wrapper">
                        <div class="swiper-slide">
                            <p class="recommend">
                                <i></i>
                                <a href="/news/219.html" class="conment_a">美唇季 | 她从乌唇蜕变樱花女神，奇迹就在你身边！</a>
                            </p>

                            <p class="clock">
                                <i></i><span>2018-03-27</span>
                            </p>
                        </div>
<div class="swiper-slide">
                            <p class="recommend">
                                <i></i>
                                <a href="/news/218.html" class="conment_a">【真人案例】40分钟改写眉毛命运，支付宝账单“颜值正义”第一人！</a>
                            </p>

                            <p class="clock">
                                <i></i><span>2018-03-27</span>
                            </p>
                        </div>
<div class="swiper-slide">
                            <p class="recommend">
                                <i></i>
                                <a href="/news/217.html" class="conment_a">【真人案例】 长着一对高低眉，改变之后竟如此美！！</a>
                            </p>

                            <p class="clock">
                                <i></i><span>2018-03-27</span>
                            </p>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="index_project">
    <div class="m1">
        <h3><img  src="https://img.hzshuangmei.com/pc/title1.png"  alt="主打项目 缔造完美"/></h3>

        <div id="tab2">
            <ul>
                <li class="fli2">整形美容</li>
                <li>皮肤激光</li>
                <li>注射微整</li>
                <li>艺术纹绣</li>
                <li>美容SPA护理</li>
            </ul>
        </div>
        <ul id="tabCon2">
            <li class="fdiv2">
                <div class="clearFix">
                    <div class="left">
                        <a class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener">
                        <img  src="https://img.hzshuangmei.com/pc/p1_01.jpg"  alt="红妆芭比大眼"/>
                        </a>
                    </div>
                    <div class="right clearFix">
                        <a href="/projects/eye/yandai.html" target="_blank" rel="noopener"><img src="https://img.hzshuangmei.com/pc/tjxm/tjxm1.jpg" alt="红妆无痕祛眼袋"/></a>
                        <a class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener"><img src="https://img.hzshuangmei.com/pc/tjxm/tjxm2.jpg" alt="韩式隆鼻"/></a>
                        <a href="/projects/nose/hzbbqb.html" target="_blank" rel="noopener"><img src="https://img.hzshuangmei.com/pc/tjxm/tjxm3.jpg" alt="红妆芭比翘鼻"/></a>
                        <a href="/projects/nose/heben.html" target="_blank" rel="noopener"><img src="https://img.hzshuangmei.com/pc/tjxm/tjxm4.jpg" alt="赫本软骨鼻"/></a>
                        <a href="/projects/face/zitizhifang.html" target="_blank" rel="noopener"><img src="https://img.hzshuangmei.com/pc/tjxm/tjxm5.jpg" alt="自体脂肪填充"/></a>
                        <a href="/projects/chest/hzwhfx.html" target="_blank" rel="noopener"><img src="https://img.hzshuangmei.com/pc/tjxm/tjxm6.jpg" alt="无痕丰胸"/></a>
                    </div>
                </div>
            </li>
            <li>
                <div class="clearFix">
                    <div class="left">
                        <a href="/projects/quban/wuchuang.html " target="_blank" rel="noopener"><img src="https://img.hzshuangmei.com/pc/p1_08.jpg"  alt="无创量子祛斑"/></a>
                    </div>
                    <div class="right clearFix">
                        <!--<a class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener"><img src="https://img.hzshuangmei.com/pc/p1_09.jpg" alt="超声刀"/></a>-->
                        <a href="/projects/quban/pimiao.html" target="_blank" rel="noopener"><img  src="https://img.hzshuangmei.com/pc/p1_11.jpg"  alt="皮秒祛斑"/></a>
                        <a href="/projects/quban/queban.html" target="_blank" rel="noopener"><img  src="https://img.hzshuangmei.com/pc/p1_10.jpg"  alt="祛雀斑"/></a>
                        <a class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener"><img  src="https://img.hzshuangmei.com/pc/p1_09_1.jpg"  alt="光子嫩肤"/></a>
                        <a href="/projects/tuomao/tuomao2.html" target="_blank" rel="noopener"><img src="https://img.hzshuangmei.com/pc/p1_12.jpg"  alt="清凉脱毛"/></a>
                        <a href="/projects/skin/ssmk.html"  target="_blank" rel="noopener"><img  src="https://img.hzshuangmei.com/pc/p1_13.jpg"  alt="毛孔收缩"/></a>
                        <a class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener"><img  src="https://img.hzshuangmei.com/pc/p1_14.jpg"  alt="激光除皱"/></a>
                    </div>
                </div>
            </li>
            <li>
                <div class="clearFix">
                    <div class="left"><a class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener"><img  src="https://img.hzshuangmei.com/pc/p1_15.jpg"  alt="微针回春术"/></a>
                    </div>
                    <div class="right clearFix">
                        <a href="/projects/ha/facille.html" target="_blank" rel="noopener"><img  src="https://img.hzshuangmei.com/pc/p1_16.jpg"   alt="法思丽玻尿酸"/></a>
                        <a href="/projects/ha/hzrlbns.html" target="_blank" rel="noopener"><img  src="https://img.hzshuangmei.com/pc/p1_17.jpg"   alt="瑞蓝玻尿酸"/></a>
                        <a href="/projects/ha/ymbns.html" target="_blank" rel="noopener"><img  src="https://img.hzshuangmei.com/pc/p1_18.jpg"   alt="逸美玻尿酸"/></a>
                        <a href="/projects/ha/ifresh.html" target="_blank" rel="noopener"><img src="https://img.hzshuangmei.com/pc/p1_19.jpg" alt="爱芙莱玻尿酸"/></a>
                        <a href="/projects/botox/shoulianzhen2.html" target="_blank" rel="noopener"><img  src="https://img.hzshuangmei.com/pc/p1_20.jpg"   alt="瘦脸针"/></a>
                        <a class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener"><img  src="https://img.hzshuangmei.com/pc/p1_21.jpg"   alt="BOTOX"/></a>
                    </div>
                </div>
            </li>
            <li>
                <div class="clearFix">
                    <div class="left"><a href="/projects/tattoo/hzyswx.html" target="_blank" rel="noopener"><img  src="https://img.hzshuangmei.com/pc/p1_22.jpg" alt="艺术纹绣"/></a>
                    </div>
                    <div class="right clearFix">
                        <a href="/projects/tattoo/byjwm.html" target="_blank" rel="noopener"><img  src="https://img.hzshuangmei.com/pc/p1_23.jpg"   alt="韩式半永久纹眉"/></a>
                        <a class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener"><img  src="https://img.hzshuangmei.com/pc/p1_24.jpg"   alt="韩式粉雾眉"/></a>
                        <a href="/projects/tattoo/yanxian.html" target="_blank" rel="noopener"><img  src="https://img.hzshuangmei.com/pc/p1_25.jpg"   alt="美瞳线"/></a>
                        <a  class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener"><img  src="https://img.hzshuangmei.com/pc/p1_26.jpg"   alt="韩式丝雾眉"/></a>
                        <a class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener"><img  src="https://img.hzshuangmei.com/pc/p1_27.jpg"   alt="艺术晶唇"/></a>
                        <a class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener"><img  src="https://img.hzshuangmei.com/pc/p1_28.jpg"   alt="五度空间仿真眉"/></a>
                    </div>
                </div>
            </li>
            <li>
                <div class="clearFix">
                    <div class="left">  <a  class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener"><img  src="https://img.hzshuangmei.com/pc/xmk/spa.jpg" alt="红妆暖SPA"/></a>
                    </div>
                    <div class="right clearFix">
                        <a  class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener"><img  src="https://img.hzshuangmei.com/pc/xmk/spa1.jpg"   alt="面部护理"/></a>
                        <a class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener"><img  src="https://img.hzshuangmei.com/pc/xmk/spa2.jpg"  alt="面部抗衰"/></a>
                        <a  class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener"><img  src="https://img.hzshuangmei.com/pc/xmk/spa3.jpg"   alt="红妆脊美"/></a>
                        <a  class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener"><img  src="https://img.hzshuangmei.com/pc/xmk/spa4.jpg"  alt="石尚岩盘浴"/></a>
                        <a class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener"><img  src="https://img.hzshuangmei.com/pc/xmk/spa5.jpg"   alt="瘦身塑形"/></a>
                        <a class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener"><img  src="https://img.hzshuangmei.com/pc/xmk/spa6.jpg"   alt="胸部护理"/></a>
                    </div>
                </div>
            </li>
        </ul>
        <a href="/projects" class="ask" target="_blank" rel="noopener" rel="nofollow">MORE+</a>
    </div>
</div>
<div class="index_expert">
    <div class="m1">
        <h3><img src="https://img.hzshuangmei.com/pc/title2.png" alt="仁医仁术 匠心手品"/></h3>

        <div id="tab3">
            <ul class="clearFix">
                <li class="fli3">整形美容专家</li>
                <li>皮肤整容专家</li>
                <li>医学纹绣师</li>
                <li>专业护理团队</li>
            </ul>
        </div>
        <ul id="tabCon3">
            <li class="fdiv3">
                <!-- Swiper -->
                <div class="swiper-container swiper-container4">
                    <div class="swiper-wrapper">
                        <!--            <div class="swiper-slide">
                                       <a href="/doctors/surgery/guanhaitao.html" target="_blank" rel="noopener">
                                           <img src="https://uploads.hzshuangmei.com/180227/1-1P22G35AT18.jpg" alt="关海涛 "/>
                                           <p>[整形外科院长] 关海涛 </p>
                                       </a>
                                   </div><div class="swiper-slide">
                                       <a href="/plugin/view.php?aid=176" target="_blank" rel="noopener">
                                           <img src="https://uploads.hzshuangmei.com/180131/1-1P1310UZc23.jpg" alt="朱红振"/>
                                           <p>[整形外科院长] 朱红振</p>
                                       </a>
                                   </div><div class="swiper-slide">
                                       <a href="/doctors/surgery/liuzhikun.html" target="_blank" rel="noopener">
                                           <img src="https://uploads.hzshuangmei.com/180124/1-1P1241Q332955.jpg" alt="刘志坤"/>
                                           <p>[整形外科院长] 刘志坤</p>
                                       </a>
                                   </div><div class="swiper-slide">
                                       <a href="/plugin/view.php?aid=227" target="_blank" rel="noopener">
                                           <img src="https://uploads.hzshuangmei.com/180414/1-1P4140930032H.jpg" alt="薛开兴"/>
                                           <p>[整形外科院长] 薛开兴</p>
                                       </a>
                                   </div><div class="swiper-slide">
                                       <a href="/doctors/surgery/guozongke.html" target="_blank" rel="noopener">
                                           <img src="https://uploads.hzshuangmei.com/180112/1-1P112160P4351.jpg" alt="郭宗科(客座)"/>
                                           <p>[教授] 郭宗科(客座)</p>
                                       </a>
                                   </div><div class="swiper-slide">
                                       <a href="/doctors/surgery/liudalie.html" target="_blank" rel="noopener">
                                           <img src="https://uploads.hzshuangmei.com/171223/1-1G223091PH64.jpg" alt="柳大烈(客座)"/>
                                           <p>[教授] 柳大烈(客座)</p>
                                       </a>
                                   </div><div class="swiper-slide">
                                       <a href="/plugin/view.php?aid=211" target="_blank" rel="noopener">
                                           <img src="https://uploads.hzshuangmei.com/180321/2-1P321140955X1.jpg" alt="张子杰（客座）"/>
                                           <p>[教授] 张子杰（客座）</p>
                                       </a>
                                   </div><div class="swiper-slide">
                                       <a href="/doctors/surgery/ljb.html" target="_blank" rel="noopener">
                                           <img src="https://uploads.hzshuangmei.com/180111/1-1P1111RPc29.jpg" alt="雷建波(客座)"/>
                                           <p>[整形美容专家] 雷建波(客座)</p>
                                       </a>
                                   </div><div class="swiper-slide">
                                       <a href="/doctors/surgery/luoyong.html" target="_blank" rel="noopener">
                                           <img src="https://uploads.hzshuangmei.com/180124/1-1P1241Q255407.jpg" alt="罗勇"/>
                                           <p>[整形外科主任] 罗勇</p>
                                       </a>
                                   </div><div class="swiper-slide">
                                       <a href="/plugin/view.php?aid=206" target="_blank" rel="noopener">
                                           <img src="https://uploads.hzshuangmei.com/180226/1-1P2261A53G39.jpg" alt="邓少波"/>
                                           <p>[整形外科院长] 邓少波</p>
                                       </a>
                                   </div><div class="swiper-slide">
                                       <a href="/plugin/view.php?aid=152" target="_blank" rel="noopener">
                                           <img src="https://uploads.hzshuangmei.com/180124/1-1P1241Q43D25.jpg" alt="王保生(客座)"/>
                                           <p>[教授] 王保生(客座)</p>
                                       </a>
                                   </div><div class="swiper-slide">
                                       <a href="/plugin/view.php?aid=153" target="_blank" rel="noopener">
                                           <img src="https://uploads.hzshuangmei.com/180124/1-1P1241Q615556.jpg" alt="余志亮"/>
                                           <p>[整形专家] 余志亮</p>
                                       </a>
                                   </div> -->
                        <div class="swiper-slide">
                            <a href="/doctors/surgery/guanhaitao.html" target="_blank" rel="noopener">
                                <img  src="https://uploads.hzshuangmei.com/180227/1-1P22G35AT18.jpg"  alt="关海涛 "/>
                                <p>[整形外科院长] 关海涛 </p>
                            </a>
                        </div><div class="swiper-slide">
                            <a href="/plugin/view.php?aid=176" target="_blank" rel="noopener">
                                <img  src="https://uploads.hzshuangmei.com/180131/1-1P1310UZc23.jpg"  alt="朱红振"/>
                                <p>[整形外科院长] 朱红振</p>
                            </a>
                        </div><div class="swiper-slide">
                            <a href="/doctors/surgery/liuzhikun.html" target="_blank" rel="noopener">
                                <img  src="https://uploads.hzshuangmei.com/180124/1-1P1241Q332955.jpg"  alt="刘志坤"/>
                                <p>[整形外科院长] 刘志坤</p>
                            </a>
                        </div><div class="swiper-slide">
                            <a href="/plugin/view.php?aid=227" target="_blank" rel="noopener">
                                <img  src="https://uploads.hzshuangmei.com/180414/1-1P4140930032H.jpg"  alt="薛开兴"/>
                                <p>[整形外科院长] 薛开兴</p>
                            </a>
                        </div><div class="swiper-slide">
                            <a href="/doctors/surgery/guozongke.html" target="_blank" rel="noopener">
                                <img  src="https://uploads.hzshuangmei.com/180112/1-1P112160P4351.jpg"  alt="郭宗科(客座)"/>
                                <p>[教授] 郭宗科(客座)</p>
                            </a>
                        </div><div class="swiper-slide">
                            <a href="/doctors/surgery/liudalie.html" target="_blank" rel="noopener">
                                <img  src="https://uploads.hzshuangmei.com/171223/1-1G223091PH64.jpg"  alt="柳大烈(客座)"/>
                                <p>[教授] 柳大烈(客座)</p>
                            </a>
                        </div><div class="swiper-slide">
                            <a href="/plugin/view.php?aid=211" target="_blank" rel="noopener">
                                <img  src="https://uploads.hzshuangmei.com/180321/2-1P321140955X1.jpg"  alt="张子杰（客座）"/>
                                <p>[教授] 张子杰（客座）</p>
                            </a>
                        </div><div class="swiper-slide">
                            <a href="/doctors/surgery/ljb.html" target="_blank" rel="noopener">
                                <img  src="https://uploads.hzshuangmei.com/180111/1-1P1111RPc29.jpg"  alt="雷建波(客座)"/>
                                <p>[整形美容专家] 雷建波(客座)</p>
                            </a>
                        </div><div class="swiper-slide">
                            <a href="/doctors/surgery/luoyong.html" target="_blank" rel="noopener">
                                <img  src="https://uploads.hzshuangmei.com/180124/1-1P1241Q255407.jpg"  alt="罗勇"/>
                                <p>[整形外科主任] 罗勇</p>
                            </a>
                        </div><div class="swiper-slide">
                            <a href="/plugin/view.php?aid=152" target="_blank" rel="noopener">
                                <img  src="https://uploads.hzshuangmei.com/180124/1-1P1241Q43D25.jpg"  alt="王保生(客座)"/>
                                <p>[教授] 王保生(客座)</p>
                            </a>
                        </div><div class="swiper-slide">
                            <a href="/plugin/view.php?aid=206" target="_blank" rel="noopener">
                                <img  src="https://uploads.hzshuangmei.com/180226/1-1P2261A53G39.jpg"  alt="邓少波"/>
                                <p>[整形外科院长] 邓少波</p>
                            </a>
                        </div><div class="swiper-slide">
                            <a href="/plugin/view.php?aid=153" target="_blank" rel="noopener">
                                <img  src="https://uploads.hzshuangmei.com/180124/1-1P1241Q615556.jpg"  alt="余志亮"/>
                                <p>[整形专家] 余志亮</p>
                            </a>
                        </div><div class="swiper-slide">
                            <a href="/plugin/view.php?aid=155" target="_blank" rel="noopener">
                                <img  src="https://uploads.hzshuangmei.com/180124/1-1P1241Q21S17.jpg"  alt="刘宇飞"/>
                                <p>[助理医生] 刘宇飞</p>
                            </a>
                        </div><div class="swiper-slide">
                            <a href="/plugin/view.php?aid=159" target="_blank" rel="noopener">
                                <img  src="https://uploads.hzshuangmei.com/180124/1-1P1241R11H92.jpg"  alt="周春金"/>
                                <p>[助理医生] 周春金</p>
                            </a>
                        </div><div class="swiper-slide">
                            <a href="/plugin/view.php?aid=158" target="_blank" rel="noopener">
                                <img  src="https://uploads.hzshuangmei.com/180124/1-1P1241Q54MB.jpg"  alt="围闯"/>
                                <p>[助理医生] 围闯</p>
                            </a>
                        </div><div class="swiper-slide">
                            <a href="/plugin/view.php?aid=157" target="_blank" rel="noopener">
                                <img  src="https://uploads.hzshuangmei.com/180124/1-1P1241Q4094F.jpg"  alt="隋浩"/>
                                <p>[助理医生] 隋浩</p>
                            </a>
                        </div><div class="swiper-slide">
                            <a href="/plugin/view.php?aid=156" target="_blank" rel="noopener">
                                <img  src="https://uploads.hzshuangmei.com/180124/1-1P1241QT24H.jpg"  alt="胡杨"/>
                                <p>[助理医生] 胡杨</p>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="swiper-button-next swiper-button-next4"></div>
                <div class="swiper-button-prev swiper-button-prev4"></div>

            </li>
            <li>
                <div class="swiper-container swiper-container4">
                    <div class="swiper-wrapper">
                        <!--                 <div class="swiper-slide">
                                            <a href="/doctors/laser/lijie.html" target="_blank" rel="noopener">
                                                <img src="https://uploads.hzshuangmei.com/171206/1-1G206114336330.jpg" alt="李杰"/>
                                                <p>[光学美肤中心院长] 李杰</p>
                                            </a>
                                        </div><div class="swiper-slide">
                                            <a href="/doctors/laser/yzw.html" target="_blank" rel="noopener">
                                                <img src="https://uploads.hzshuangmei.com/180327/1-1P32F94AT36.jpg" alt="姚志文"/>
                                                <p>[非手术面部年轻化专家] 姚志文</p>
                                            </a>
                                        </div><div class="swiper-slide">
                                            <a href="/plugin/view.php?aid=147" target="_blank" rel="noopener">
                                                <img src="https://uploads.hzshuangmei.com/180124/1-1P1241PQa04.jpg" alt="林粤鑫"/>
                                                <p>[色素祛除美容专家] 林粤鑫</p>
                                            </a>
                                        </div><div class="swiper-slide">
                                            <a href="/plugin/view.php?aid=146" target="_blank" rel="noopener">
                                                <img src="https://uploads.hzshuangmei.com/180124/1-1P1241Q03E36.jpg" alt="袁兆周"/>
                                                <p>[紧肤除皱抗衰专家] 袁兆周</p>
                                            </a>
                                        </div><div class="swiper-slide">
                                            <a href="/plugin/view.php?aid=145" target="_blank" rel="noopener">
                                                <img src="https://uploads.hzshuangmei.com/180124/1-1P1241Q10H53.jpg" alt="赵丽萍"/>
                                                <p>[射频嫩肤美容专家] 赵丽萍</p>
                                            </a>
                                        </div> -->
                        <div class="swiper-slide">
                            <a href="/doctors/laser/lijie.html" target="_blank" rel="noopener">
                                <img src="https://uploads.hzshuangmei.com/171206/1-1G206114336330.jpg"   alt="李杰"/>
                                <p>[光学美肤中心院长] 李杰</p>
                            </a>
                        </div><div class="swiper-slide">
                            <a href="/doctors/laser/yzw.html" target="_blank" rel="noopener">
                                <img src="https://uploads.hzshuangmei.com/180327/1-1P32F94AT36.jpg"   alt="姚志文"/>
                                <p>[非手术面部年轻化专家] 姚志文</p>
                            </a>
                        </div><div class="swiper-slide">
                            <a href="/plugin/view.php?aid=149" target="_blank" rel="noopener">
                                <img src="https://uploads.hzshuangmei.com/180124/1-1P1241PUS03.jpg"   alt="王平藏"/>
                                <p>[祛斑美肤专家] 王平藏</p>
                            </a>
                        </div><div class="swiper-slide">
                            <a href="/plugin/view.php?aid=148" target="_blank" rel="noopener">
                                <img src="https://uploads.hzshuangmei.com/180124/1-1P1241PIS15.jpg"   alt="李华"/>
                                <p>[水光嫩肤祛斑专家] 李华</p>
                            </a>
                        </div><div class="swiper-slide">
                            <a href="/plugin/view.php?aid=147" target="_blank" rel="noopener">
                                <img src="https://uploads.hzshuangmei.com/180124/1-1P1241PQa04.jpg"   alt="林粤鑫"/>
                                <p>[色素祛除美容专家] 林粤鑫</p>
                            </a>
                        </div><div class="swiper-slide">
                            <a href="/plugin/view.php?aid=146" target="_blank" rel="noopener">
                                <img src="https://uploads.hzshuangmei.com/180124/1-1P1241Q03E36.jpg"   alt="袁兆周"/>
                                <p>[紧肤除皱抗衰专家] 袁兆周</p>
                            </a>
                        </div><div class="swiper-slide">
                            <a href="/plugin/view.php?aid=145" target="_blank" rel="noopener">
                                <img src="https://uploads.hzshuangmei.com/180124/1-1P1241Q10H53.jpg"   alt="赵丽萍"/>
                                <p>[射频嫩肤美容专家] 赵丽萍</p>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="swiper-button-next swiper-button-next4"></div>
                <div class="swiper-button-prev swiper-button-prev4"></div>
            </li>
            <li>
                <div class="swiper-container swiper-container4">
                    <div class="swiper-wrapper">
                        <!--        <div class="swiper-slide">
                                   <a class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener">
                                       <img src="https://uploads.hzshuangmei.com/180125/1-1P125154412c5.jpg" alt="冯晓琳"/>
                                       <p>[纹饰技术总指导师] 冯晓琳</p>
                                   </a>
                               </div><div class="swiper-slide">
                                   <a class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener">
                                       <img src="https://uploads.hzshuangmei.com/180117/1-1P11GA914A3.jpg" alt="孟超"/>
                                       <p>[纹饰指导师] 孟超</p>
                                   </a>
                               </div><div class="swiper-slide">
                                   <a class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener">
                                       <img src="https://uploads.hzshuangmei.com/180117/1-1P11GF5042G.jpg" alt="杨小丽"/>
                                       <p>[纹饰指导师] 杨小丽</p>
                                   </a>
                               </div><div class="swiper-slide">
                                   <a class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener">
                                       <img src="https://uploads.hzshuangmei.com/180125/1-1P125154F55X.jpg" alt="高方云"/>
                                       <p>[纹饰指导师] 高方云</p>
                                   </a>
                               </div><div class="swiper-slide">
                                   <a class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener">
                                       <img src="https://uploads.hzshuangmei.com/180117/1-1P11GAJ03X.jpg" alt="黎秀带"/>
                                       <p>[纹饰指导师] 黎秀带</p>
                                   </a>
                               </div><div class="swiper-slide">
                                   <a class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener">
                                       <img src="https://uploads.hzshuangmei.com/180117/1-1P11GF201N9.jpg" alt="邱小雪"/>
                                       <p>[纹饰指导师] 邱小雪</p>
                                   </a>
                               </div><div class="swiper-slide">
                                   <a class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener">
                                       <img src="https://uploads.hzshuangmei.com/180117/1-1P11GA430950.jpg" alt="黄文燕"/>
                                       <p>[纹饰指导师] 黄文燕</p>
                                   </a>
                               </div> -->
                        <div class="swiper-slide">
                            <a href="/plugin/view.php?aid=164" target="_blank" rel="noopener">
                                <img src="https://uploads.hzshuangmei.com/180125/1-1P125154412c5.jpg"  alt="冯晓琳"/>
                                <p>[纹饰技术总指导师] 冯晓琳</p>
                            </a>
                        </div><div class="swiper-slide">
                            <a href="/plugin/view.php?aid=137" target="_blank" rel="noopener">
                                <img src="https://uploads.hzshuangmei.com/180117/1-1P11GA914A3.jpg"  alt="孟超"/>
                                <p>[纹饰指导师] 孟超</p>
                            </a>
                        </div><div class="swiper-slide">
                            <a href="/plugin/view.php?aid=139" target="_blank" rel="noopener">
                                <img src="https://uploads.hzshuangmei.com/180117/1-1P11GF5042G.jpg"  alt="杨小丽"/>
                                <p>[纹饰指导师] 杨小丽</p>
                            </a>
                        </div><div class="swiper-slide">
                            <a href="/plugin/view.php?aid=136" target="_blank" rel="noopener">
                                <img src="https://uploads.hzshuangmei.com/180125/1-1P125154F55X.jpg"  alt="高方云"/>
                                <p>[纹饰指导师] 高方云</p>
                            </a>
                        </div><div class="swiper-slide">
                            <a href="/plugin/view.php?aid=138" target="_blank" rel="noopener">
                                <img src="https://uploads.hzshuangmei.com/180117/1-1P11GAJ03X.jpg"  alt="黎秀带"/>
                                <p>[纹饰指导师] 黎秀带</p>
                            </a>
                        </div><div class="swiper-slide">
                            <a href="/plugin/view.php?aid=140" target="_blank" rel="noopener">
                                <img src="https://uploads.hzshuangmei.com/180117/1-1P11GF201N9.jpg"  alt="邱小雪"/>
                                <p>[纹饰指导师] 邱小雪</p>
                            </a>
                        </div><div class="swiper-slide">
                            <a href="/plugin/view.php?aid=141" target="_blank" rel="noopener">
                                <img src="https://uploads.hzshuangmei.com/180117/1-1P11GA430950.jpg"  alt="黄文燕"/>
                                <p>[纹饰指导师] 黄文燕</p>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="swiper-button-next swiper-button-next4"></div>
                <div class="swiper-button-prev swiper-button-prev4"></div>
            </li>
            <li id="hltd"><div class="hltd" >
                <a  class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener">
                    <img  src="https://img.hzshuangmei.com/pc/xmk/zyhl.jpg"   alt="护理团队"/>
                </a>
            </div>
            </li>
        </ul>
        <a href="/doctors" class="ask" target="_blank" rel="noopener" rel="nofollow">MORE+</a>
    </div>
</div>
<div class="index_clients">
    <div class="m1">
        <h3><img  src="https://img.hzshuangmei.com/pc/title3.png"  alt="真人代言 现身说法"/></h3>
        <div id="tab4">
            <ul class="clearFix">
                <li class="fli4">整形美容案例</li>
                <li>皮肤激光案例</li>
                <li>注射微整案例</li>
                <li>医学纹绣案例</li>
            </ul>
        </div>
        <div id="tabCon4">
            <ul class="fdiv4 clearFix">
                <li>
                    <div class="clients_t">
                        <a href="/cases/nose/232.html" target="_blank" rel="noopener">
                            <img  src="https://uploads.hzshuangmei.com/180420/2-1P420161053O2.jpg"  alt="周孔秋"/>
                            <span>术前</span>

                            <p>[美丽蜕变] 周孔秋</p>
                        </a>
                        <a href="/cases/nose/232.html" class="qiehuan">
                            <img  src="https://uploads.hzshuangmei.com/180420/2-1P420161142936.jpg"   alt="周孔秋"/>
                            <span>术后</span>

                            <p>[美丽蜕变] 周孔秋</p>
                        </a>
                    </div>
                    <div class="clients_b">
                        <p>塑美方案：<a href="https://www.hzshuangmei.com/projects/nose/heben.html">耳软骨隆鼻</a></p>

                        <p>塑美专家：<a href="https://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;fi=68948">薛开兴</a></p>
                        <a href="/cases/nose/232.html" class="xiangqing" target="_blank" rel="noopener">案例详情</a>
                    </div>
                </li>
<li>
                    <div class="clients_t">
                        <a href="/cases/eye/231.html" target="_blank" rel="noopener">
                            <img  src="https://uploads.hzshuangmei.com/180420/2-1P42015352S35.jpg"  alt="黄金杏"/>
                            <span>术前</span>

                            <p>[美丽蜕变] 黄金杏</p>
                        </a>
                        <a href="/cases/eye/231.html" class="qiehuan">
                            <img  src="https://uploads.hzshuangmei.com/180420/2-1P420153553D6.jpg"   alt="黄金杏"/>
                            <span>术后</span>

                            <p>[美丽蜕变] 黄金杏</p>
                        </a>
                    </div>
                    <div class="clients_b">
                        <p>塑美方案：<a href="https://www.hzshuangmei.com/projects/eye/qjsyp.html">红妆翘睫双眼皮</a></p>

                        <p>塑美专家：<a href="https://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;fi=68948">薛开兴</a></p>
                        <a href="/cases/eye/231.html" class="xiangqing" target="_blank" rel="noopener">案例详情</a>
                    </div>
                </li>
<li>
                    <div class="clients_t">
                        <a href="/cases/zhifang/225.html" target="_blank" rel="noopener">
                            <img  src="https://uploads.hzshuangmei.com/180411/2-1P41111114I07.jpg"  alt="唐海桂"/>
                            <span>术前</span>

                            <p>[美丽蜕变] 唐海桂</p>
                        </a>
                        <a href="/cases/zhifang/225.html" class="qiehuan">
                            <img  src="https://uploads.hzshuangmei.com/180411/2-1P4111112211a.jpg"   alt="唐海桂"/>
                            <span>术后</span>

                            <p>[美丽蜕变] 唐海桂</p>
                        </a>
                    </div>
                    <div class="clients_b">
                        <p>塑美方案：<a href="https://www.hzshuangmei.com/projects/face/zitizhifang.html">自体脂肪面部填充</a></p>

                        <p>塑美专家：<a href="https://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;fi=68948">邓少波</a></p>
                        <a href="/cases/zhifang/225.html" class="xiangqing" target="_blank" rel="noopener">案例详情</a>
                    </div>
                </li>
<li>
                    <div class="clients_t">
                        <a href="/cases/zhifang/224.html" target="_blank" rel="noopener">
                            <img  src="https://uploads.hzshuangmei.com/180411/2-1P411110ZE53.jpg"  alt="岑娟芳"/>
                            <span>术前</span>

                            <p>[美丽蜕变] 岑娟芳</p>
                        </a>
                        <a href="/cases/zhifang/224.html" class="qiehuan">
                            <img  src="https://uploads.hzshuangmei.com/180411/2-1P411110926415.jpg"   alt="岑娟芳"/>
                            <span>术后</span>

                            <p>[美丽蜕变] 岑娟芳</p>
                        </a>
                    </div>
                    <div class="clients_b">
                        <p>塑美方案：<a href="https://www.hzshuangmei.com/projects/face/zitizhifang.html">自体脂肪面部填充</a></p>

                        <p>塑美专家：<a href="https://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;fi=68948">邓少波</a></p>
                        <a href="/cases/zhifang/224.html" class="xiangqing" target="_blank" rel="noopener">案例详情</a>
                    </div>
                </li>

            </ul>
            <ul class="clearFix">
                <li>
                    <div class="clients_t">
                        <a href="/cases/quban/96.html" target="_blank" rel="noopener">
                            <img  src="https://uploads.hzshuangmei.com/171207/2-1G20G15921209.jpg"  alt="欧长女"/>
                            <span>术前</span>

                            <p>[美丽蜕变] 欧长女</p>
                        </a>
                        <a href="/cases/quban/96.html" class="qiehuan" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/171207/2-1G20G1594EU.jpg"  alt="欧长女"/>
                            <span>术后</span>

                            <p>[美丽蜕变] 欧长女</p>
                        </a>
                    </div>
                    <div class="clients_b">
                        <p>塑美方案：<a href="https://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;fi=68948">激光祛斑</a></p>

                        <p>塑美专家：<a href="https://www.hzshuangmei.com/doctors/laser/lijie.html">李杰</a></p>
                        <a href="/cases/quban/96.html" class="xiangqing" target="_blank" rel="noopener">案例详情</a>
                    </div>
                </li>
<li>
                    <div class="clients_t">
                        <a href="/cases/skin/93.html" target="_blank" rel="noopener">
                            <img  src="https://uploads.hzshuangmei.com/171205/2-1G205152T3Q2.jpg"  alt="王慧慧"/>
                            <span>术前</span>

                            <p>[美丽蜕变] 王慧慧</p>
                        </a>
                        <a href="/cases/skin/93.html" class="qiehuan" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/171206/2-1G206104945A5.jpg"  alt="王慧慧"/>
                            <span>术后</span>

                            <p>[美丽蜕变] 王慧慧</p>
                        </a>
                    </div>
                    <div class="clients_b">
                        <p>塑美方案：<a href="https://www.hzshuangmei.com/projects/quban/pimiao.html">激光祛斑</a></p>

                        <p>塑美专家：<a href="https://www.hzshuangmei.com/doctors/laser/lijie.html">李杰</a> </p>
                        <a href="/cases/skin/93.html" class="xiangqing" target="_blank" rel="noopener">案例详情</a>
                    </div>
                </li>
<li>
                    <div class="clients_t">
                        <a href="/cases/quban/92.html" target="_blank" rel="noopener">
                            <img  src="https://uploads.hzshuangmei.com/180102/2-1P1021K301324.jpg"  alt="白琦琦"/>
                            <span>术前</span>

                            <p>[美丽蜕变] 白琦琦</p>
                        </a>
                        <a href="/cases/quban/92.html" class="qiehuan" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/171206/2-1G206154433359.jpg"  alt="白琦琦"/>
                            <span>术后</span>

                            <p>[美丽蜕变] 白琦琦</p>
                        </a>
                    </div>
                    <div class="clients_b">
                        <p>塑美方案：<a href="https://www.hzshuangmei.com/projects/quban/wuchuang.html">无创量子祛斑</a></p>

                        <p>塑美专家：<a href="https://www.hzshuangmei.com/doctors/laser/lijie.html">李杰</a></p>
                        <a href="/cases/quban/92.html" class="xiangqing" target="_blank" rel="noopener">案例详情</a>
                    </div>
                </li>

            </ul>
            <ul class="clearFix">
                <li>
                    <div class="clients_t">
                        <a href="/cases/ha/127.html" target="_blank" rel="noopener">
                            <img  src="https://uploads.hzshuangmei.com/180109/2-1P109155922414.JPG"   alt="薛恋婷"/>
                            <span>术前</span>

                            <p>[美丽蜕变] 薛恋婷</p>
                        </a>
                        <a href="/cases/ha/127.html" class="qiehuan" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180109/2-1P10915593V04.jpg"  alt="薛恋婷"/>
                            <span>术后</span>

                            <p>[美丽蜕变] 薛恋婷</p>
                        </a>
                    </div>
                    <div class="clients_b">
                        <p>塑美方案：<a href="http://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;fi=68948">芭比翘鼻</a> <a href="https://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;fi=68948">下巴吸脂</a> &nbsp;<a href="https://www.hzshuangmei.com/projects/ha/zhbns.html">玻尿酸塑形</a></p>

                        <p>塑美专家：<a href="https://www.hzshuangmei.com/doctors/surgery/guanhaitao.html">关海涛</a>&nbsp;<a href="http://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;fi=68948">罗勇</a></p>
                        <a href="/cases/ha/127.html" class="xiangqing">案例详情</a>
                    </div>
                </li>
<li>
                    <div class="clients_t">
                        <a href="/cases/botox/124.html" target="_blank" rel="noopener">
                            <img  src="https://uploads.hzshuangmei.com/180109/2-1P109153254632.JPG"   alt="王丹丹"/>
                            <span>术前</span>

                            <p>[美丽蜕变] 王丹丹</p>
                        </a>
                        <a href="/cases/botox/124.html" class="qiehuan" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180109/2-1P109153311443.jpg"  alt="王丹丹"/>
                            <span>术后</span>

                            <p>[美丽蜕变] 王丹丹</p>
                        </a>
                    </div>
                    <div class="clients_b">
                        <p>塑美方案：<a href="https://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;fi=68948">芭比大眼</a>、<a href="https://www.hzshuangmei.com/projects/botox/shoulianzhen2.html">BOTOX瘦脸</a></p>

                        <p>塑美专家：<a href="https://www.hzshuangmei.com/doctors/surgery/guanhaitao.html">关海涛</a>&nbsp;<a href="https://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;fi=68948">罗勇</a></p>
                        <a href="/cases/botox/124.html" class="xiangqing">案例详情</a>
                    </div>
                </li>
<li>
                    <div class="clients_t">
                        <a href="/cases/ha/121.html" target="_blank" rel="noopener">
                            <img  src="https://uploads.hzshuangmei.com/180109/2-1P10911413JS.JPG"   alt="黄海娜"/>
                            <span>术前</span>

                            <p>[美丽蜕变] 黄海娜</p>
                        </a>
                        <a href="/cases/ha/121.html" class="qiehuan" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180109/2-1P109114150947.jpg"  alt="黄海娜"/>
                            <span>术后</span>

                            <p>[美丽蜕变] 黄海娜</p>
                        </a>
                    </div>
                    <div class="clients_b">
                        <p>塑美方案：<a href="https://www.hzshuangmei.com/projects/ha/zhbns.html">玻尿酸塑形</a><br />
</p>

                        <p>塑美专家：<a href="https://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;amp;fi=68948">刘志坤</a></p>
                        <a href="/cases/ha/121.html" class="xiangqing">案例详情</a>
                    </div>
                </li>
<li>
                    <div class="clients_t">
                        <a href="/cases/mini/94.html" target="_blank" rel="noopener">
                            <img  src="https://uploads.hzshuangmei.com/171205/2-1G205161Q4448.jpg"   alt="韩一曼"/>
                            <span>术前</span>

                            <p>[美丽蜕变] 韩一曼</p>
                        </a>
                        <a href="/cases/mini/94.html" class="qiehuan" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/171205/2-1G205161S4393.jpg"  alt="韩一曼"/>
                            <span>术后</span>

                            <p>[美丽蜕变] 韩一曼</p>
                        </a>
                    </div>
                    <div class="clients_b">
                        <p>塑美方案：<a href="https://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;amp;amp;fi=68948">无创水光</a></p>

                        <p>塑美专家：<a href="https://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;amp;amp;fi=68948">刘志坤</a></p>
                        <a href="/cases/mini/94.html" class="xiangqing">案例详情</a>
                    </div>
                </li>

            </ul>
            <ul class="clearFix">
                <li>
                    <div class="clients_t">
                        <a href="/cases/tattoo/230.html" target="_blank" rel="noopener">
                            <img  src="https://uploads.hzshuangmei.com/180416/2-1P416111305c1.JPG"  alt="张扬"/>
                            <span>术前</span>

                            <p>[美丽蜕变] 张扬</p>
                        </a>
                        <a href="/cases/tattoo/230.html" class="qiehuan" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180416/2-1P4161113303E.JPG"  alt="张扬"/>
                            <span>术后</span>

                            <p>[美丽蜕变] 张扬</p>
                        </a>
                    </div>
                    <div class="clients_b">
                        <p>塑美方案：<a href="https://www.hzshuangmei.com/projects/tattoo/yzwc.html">半永久纹唇</a></p>

                        <p>塑美专家：<a href="https://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;fi=68948">卓宾娇</a></p>
                        <a href="/cases/tattoo/230.html" class="xiangqing">案例详情</a>
                    </div>
                </li>
<li>
                    <div class="clients_t">
                        <a href="/cases/tattoo/229.html" target="_blank" rel="noopener">
                            <img  src="https://uploads.hzshuangmei.com/180416/2-1P416104031c9.JPG"  alt="王慧根"/>
                            <span>术前</span>

                            <p>[美丽蜕变] 王慧根</p>
                        </a>
                        <a href="/cases/tattoo/229.html" class="qiehuan" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180416/2-1P416104106149.JPG"  alt="王慧根"/>
                            <span>术后</span>

                            <p>[美丽蜕变] 王慧根</p>
                        </a>
                    </div>
                    <div class="clients_b">
                        <p>塑美方案：<a href="https://www.hzshuangmei.com/projects/tattoo/yzwc.html">半永久纹唇</a></p>

                        <p>塑美专家：<a href="https://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;fi=68948">陈丹虹</a></p>
                        <a href="/cases/tattoo/229.html" class="xiangqing">案例详情</a>
                    </div>
                </li>
<li>
                    <div class="clients_t">
                        <a href="/cases/tattoo/228.html" target="_blank" rel="noopener">
                            <img  src="https://uploads.hzshuangmei.com/180416/2-1P416093513305.JPG"  alt="黎翠燕"/>
                            <span>术前</span>

                            <p>[美丽蜕变] 黎翠燕</p>
                        </a>
                        <a href="/cases/tattoo/228.html" class="qiehuan" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180416/2-1P41609355I03.JPG"  alt="黎翠燕"/>
                            <span>术后</span>

                            <p>[美丽蜕变] 黎翠燕</p>
                        </a>
                    </div>
                    <div class="clients_b">
                        <p>塑美方案：<a href="https://www.hzshuangmei.com/projects/tattoo/yzwc.html">半永久纹唇</a></p>

                        <p>塑美专家：<a href="https://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;fi=68948">青玉</a></p>
                        <a href="/cases/tattoo/228.html" class="xiangqing">案例详情</a>
                    </div>
                </li>
<li>
                    <div class="clients_t">
                        <a href="/cases/tattoo/183.html" target="_blank" rel="noopener">
                            <img  src="https://uploads.hzshuangmei.com/180206/2-1P20613435I60.JPG"  alt="高会兰"/>
                            <span>术前</span>

                            <p>[美丽蜕变] 高会兰</p>
                        </a>
                        <a href="/cases/tattoo/183.html" class="qiehuan" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180206/2-1P206134445V5.jpg"  alt="高会兰"/>
                            <span>术后</span>

                            <p>[美丽蜕变] 高会兰</p>
                        </a>
                    </div>
                    <div class="clients_b">
                        <p>塑美方案：<a href="https://www.hzshuangmei.com/projects/tattoo/hzyswx.html">粉雾眉</a></p>

                        <p>塑美专家：<a href="https://ryak66.kuaishang.cn/bs/leavemsg.htm?cas=58194___765150&amp;fi=68948&amp;ri=1034899920&amp;_d=15179689940613504">杨小丽</a></p>
                        <a href="/cases/tattoo/183.html" class="xiangqing">案例详情</a>
                    </div>
                </li>

            </ul>
        </div>
        <a href="/cases" class="ask" target="_blank" rel="noopener" rel="nofollow">MORE+</a>
    </div>
</div>
<!--红妆历程-->
<div class="lic"><div class="fzlc m_b60">
    <div class="fzlc_content wow fadeIn">
        <div class="lc_con_t">
            <div class="lc_list_box clearfix">
                <div class="lc_list_n1 lc_list_con">
                    <div class="sl1">
                        <img src="//img.hzshuangmei.com/pc/fzlc/lc1.png" alt="匠心传承">
                    </div>
                </div>
                <div class="lc_list_n2 lc_list_con clearfix">
                    <div class="sl2">
                        <img src="//img.hzshuangmei.com/pc/fzlc/lc2.png" alt="荣膺桂冠">
                    </div>
                </div>
                <div class="lc_list_n3 lc_list_con">
                    <div class="sl3">
                        <img src="//img.hzshuangmei.com/pc/fzlc/lc3.png" alt="慈善公益">
                    </div>
                </div>
                <div class="lc_list_n4 lc_list_con clearfix">
                    <div class="sl4">
                        <img src="//img.hzshuangmei.com/pc/fzlc/lc4.png" alt="安全材料">
                    </div>
                </div>
                <div class="lc_list_n5 lc_list_con clearfix">
                    <div class="sl5">
                        <img src="//img.hzshuangmei.com/pc/fzlc/lc5.png" alt="专业认证">
                    </div>
                </div>
            </div>
        </div>
        <div class="lc_con_b clearfix warp">
            <div class="lc_con_btn now">
                <span class="yk">&nbsp</span>
                <p class="p1">匠心传承</p>
                <p class="p2"> 美业沉淀  匠心传承</p>
            </div>
            <div class="lc_con_btn">
                <span class="yk">&nbsp</span>
                <p class="p1">荣膺桂冠</p>
                <p class="p2">独占鳌头  戴誉前行</p>
            </div>
            <div class="lc_con_btn">
                <span class="yk">&nbsp</span>
                <p class="p1">慈善公益</p>
                <p class="p2">广施善行  传递爱心</p>
            </div>
            <div class="lc_con_btn m0">
                <span class="yk">&nbsp</span>
                <p class="p1">安全材料</p>
                <p class="p2">国际授权 品质保障</p>
            </div>
            <div class="lc_con_btn m0">
                <span class="yk">&nbsp</span>
                <p class="p1">专业认证</p>
                <p class="p2">医学资质 安全塑美</p>
            </div>
        </div>
    </div>
</div></div>
<!--红妆历程-->
<div class="index_environment">
    <div class="m1">
        <ul class="clearFix">
            <li>
                <h2><a href="/honors/" target="_blank" rel="noopener">红妆荣誉<span>Red makeup honor</span></a></h2>

                <div class="swiper-button-next swiper-button-next5 swiper-button-next5_1"></div>
                <div class="swiper-button-prev swiper-button-prev5 swiper-button-prev5_1"></div>
                <div class="swiper-container swiper-container5 swiper-container5_1">
                    <div class="swiper-wrapper">
                        <a href="/honors/88.html" class="swiper-slide" target="_blank" rel="noopener">
                            <img  src="https://uploads.hzshuangmei.com/171225/2-1G225152543Q0.jpg"  alt="中国健康美容行业信誉联盟"/>

                            <p>中国健康美容行业信誉联盟</p>
                        </a>
<a href="/honors/87.html" class="swiper-slide" target="_blank" rel="noopener">
                            <img  src="https://uploads.hzshuangmei.com/171225/2-1G225152613S1.jpg"  alt="医疗信用单位"/>

                            <p>医疗信用单位</p>
                        </a>
<a href="/honors/86.html" class="swiper-slide" target="_blank" rel="noopener">
                            <img  src="https://uploads.hzshuangmei.com/171225/2-1G22515263b14.jpg"  alt="十佳诚信健康管理机构"/>

                            <p>十佳诚信健康管理机构</p>
                        </a>
<a href="/honors/83.html" class="swiper-slide" target="_blank" rel="noopener">
                            <img  src="https://uploads.hzshuangmei.com/171225/2-1G225152J0409.jpg"  alt="全国人民满意示范专科医院"/>

                            <p>全国人民满意示范专科医院</p>
                        </a>
<a href="/honors/82.html" class="swiper-slide" target="_blank" rel="noopener">
                            <img  src="https://uploads.hzshuangmei.com/171225/2-1G225152T2500.jpg"  alt="美国雅光指定教学示范基地"/>

                            <p>美国雅光指定教学示范基地</p>
                        </a>
<a href="/honors/81.html" class="swiper-slide" target="_blank" rel="noopener">
                            <img  src="https://uploads.hzshuangmei.com/171225/2-1G225152Z61H.jpg"  alt="美国雅光授权临床基地"/>

                            <p>美国雅光授权临床基地</p>
                        </a>
<a href="/honors/80.html" class="swiper-slide" target="_blank" rel="noopener">
                            <img  src="https://uploads.hzshuangmei.com/171205/2-1G2050UTA92.jpg"  alt="2011-2012年度中国绿色养生标杆会所"/>

                            <p>2011-2012年度中国绿色养生标杆会所</p>
                        </a>
<a href="/honors/79.html" class="swiper-slide" target="_blank" rel="noopener">
                            <img  src="https://uploads.hzshuangmei.com/171204/2-1G204104030192.jpg"  alt="纹眉组冠军"/>

                            <p>纹眉组冠军</p>
                        </a>
<a href="/honors/78.html" class="swiper-slide" target="_blank" rel="noopener">
                            <img  src="https://uploads.hzshuangmei.com/171204/2-1G204103449624.jpg"  alt="特别贡献奖"/>

                            <p>特别贡献奖</p>
                        </a>
<a href="/honors/77.html" class="swiper-slide" target="_blank" rel="noopener">
                            <img  src="https://uploads.hzshuangmei.com/171204/2-1G204103249606.jpg"  alt="全国五一巾帼标兵岗"/>

                            <p>全国五一巾帼标兵岗</p>
                        </a>

                    </div>
                </div>
            </li>
            <li>
                <h2><a href="/environment/" target="_blank" rel="noopener">红妆环境<span>Red makeup environment</span></a></h2>

                <div class="swiper-button-next swiper-button-next5 swiper-button-next5_2"></div>
                <div class="swiper-button-prev swiper-button-prev5 swiper-button-prev5_2"></div>
                <div class="swiper-container swiper-container5 swiper-container5_2">
                    <div class="swiper-wrapper">
                        <a href="/environment/48.html" class="swiper-slide" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/171129/2-1G1291AJ2505.jpg"   alt="幽美清静的水疗间"/>

                            <p>幽美清静的水疗间</p>
                        </a>
<a href="/environment/47.html" class="swiper-slide" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/171129/2-1G1291A531301.jpg"   alt="奢华优雅的理疗VIP房-1"/>

                            <p>奢华优雅的理疗VIP房-1</p>
                        </a>
<a href="/environment/46.html" class="swiper-slide" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/171129/2-1G1291A41U27.jpg"   alt="高端品质VIP房-2"/>

                            <p>高端品质VIP房-2</p>
                        </a>

                    </div>
                </div>
            </li>
            <li>
                <h2><a href="/equipment/" target="_blank" rel="noopener">尖端设备<span>sophisticated equipment</span></a></h2>

                <div class="swiper-button-next swiper-button-next5 swiper-button-next5_3"></div>
                <div class="swiper-button-prev swiper-button-prev5 swiper-button-prev5_3"></div>
                <div class="swiper-container swiper-container5 swiper-container5_3">
                    <div class="swiper-wrapper">
                        <a href="/equipment/184.html" class="swiper-slide" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180207/2-1P20G04432940.jpg"  alt="韩国小气泡"/>

                            <p>韩国小气泡</p>
                        </a>
<a href="/equipment/60.html" class="swiper-slide" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/171205/2-1G205144G2L3.jpg"  alt="无创激光"/>

                            <p>无创激光</p>
                        </a>
<a href="/equipment/59.html" class="swiper-slide" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/171205/2-1G205145F2562.jpg"  alt="无创点阵飞梭系统"/>

                            <p>无创点阵飞梭系统</p>
                        </a>
<a href="/equipment/58.html" class="swiper-slide" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/171205/2-1G205144323549.jpg"  alt="水光注射仪"/>

                            <p>水光注射仪</p>
                        </a>
<a href="/equipment/57.html" class="swiper-slide" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/171205/2-1G20510291DJ.jpg"  alt="深蓝射频王RF"/>

                            <p>深蓝射频王RF</p>
                        </a>
<a href="/equipment/56.html" class="swiper-slide" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/171205/2-1G20514053N35.jpg"  alt="皮秒激光"/>

                            <p>皮秒激光</p>
                        </a>
<a href="/equipment/55.html" class="swiper-slide" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/171208/2-1G20Q356122c.jpg"  alt="二氧化碳激光"/>

                            <p>二氧化碳激光</p>
                        </a>
<a href="/equipment/54.html" class="swiper-slide" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/171208/2-1G20Q35919208.jpg"  alt="超声刀"/>

                            <p>超声刀</p>
                        </a>
<a href="/equipment/53.html" class="swiper-slide" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/171208/2-1G20Q40140255.jpg"  alt="冰点脱毛仪"/>

                            <p>冰点脱毛仪</p>
                        </a>
<a href="/equipment/52.html" class="swiper-slide" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/171208/2-1G20Q40345A2.jpg"  alt="Q开关激光"/>

                            <p>Q开关激光</p>
                        </a>

                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>
<div class="index_items" id="index_items">
    <div class="shuang_m1">
        <div class="clearFix border-r">
            <div class="icon">
                <span>双美概况</span>
                <i></i>
            </div>
            <ul class="mar_t">
                <li><a href="/">>返回首页</a></li>
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>来院路线</a></li>
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>联系我们</a></li>
                <li><a href="/brand/" target="_blank" rel="noopener">>品牌起源</a></li>
                <!--<li><a href="">>企业文化</a></li>-->
            </ul>
        </div>
        <div class="clearFix border-l border-r">
            <div class="icon">
                <span>整形美容</span>
                <i></i>
            </div>
            <ul class="mar_t">
                <li><a href="/projects/chest/#project_nav" target="_blank" rel="noopener">>胸部整形</a></li>
                <li><a href="/projects/eye/#project_nav" target="_blank" rel="noopener">>眼部整形</a></li>
                <li><a href="/projects/nose/#project_nav" target="_blank" rel="noopener">>鼻部整形</a></li>
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>唇部整形</a></li>
                <li><a href="/projects/body/#project_nav" target="_blank" rel="noopener">>塑形体雕</a></li>
                <li><a href="/projects/zhifang/ztzfmd.html" target="_blank" rel="noopener">>自体脂肪填充</a></li>
                <li><a href="/projects/#project_nav" target="_blank" rel="noopener">>其他系列</a></li>
                <li><a href="/projects/ha/bnsxb.html" target="_blank" rel="noopener">>下巴整形</a></li>
                <li><a href="/projects/private/#project_nav" target="_blank" rel="noopener">>私密整形</a></li>
            </ul>
        </div>
        <div class="clearFix border-l border-r">
            <div class="icon">
                <span>光学美肤</span>
                <i></i>
            </div>
            <ul class="mar_t">
                <li><a href="/projects/quban/quban.html" target="_blank" rel="noopener">>美白祛斑</a></li>
                <li><a href="/projects/tuomao/tuomao2.html" target="_blank" rel="noopener">>专业脱毛</a></li>
                <li><a href="/projects/qudou/hzqdk.html" target="_blank" rel="noopener">>祛痘祛疤印</a></li>
                <li><a href="/projects/chuzhou/quzhou.html" target="_blank" rel="noopener">>紧肤抗衰</a></li>
            </ul>
        </div>
        <div class="clearFix border-l">
            <div class="icon">
                <span>微创美容</span>
                <i></i>
            </div>
            <ul class="mar_t">
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>玻尿酸塑形</a></li>
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>玻尿酸祛皱</a></li>
                <li><a href="/projects/botox/#project_nav" target="_blank" rel="noopener">>BOTOX注射</a></li>
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>疤痕针</a></li>
                <li><a href="/projects/tattoo/#project_nav" target="_blank" rel="noopener">>纹绣</a></li>
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>水光注射</a></li>
                <li><a href="/projects/#project_nav" target="_blank" rel="noopener">>其他</a></li>
            </ul>
        </div>
    </div>
</div>
<footer id="footer">
    <div class="shuang_m1 clearFix">
        <div class="left">
            <h2><a href=""><img src="https://img.hzshuangmei.com/pc/f_logo.png" alt="红妆双美"/></a></h2>
            <p class="addr"><i></i>红妆双美地址：海口市海府路4号海口宾馆附楼2层</p>
            <p>本站信息仅供参考建 版权所有:红妆双美 https://www.hzshuangmei.com<br/>
                <a href="http://www.miitbeian.gov.cn/" rel="nofollow" target="_blank">琼ICP备17004048号-1</a> (海)医广[2017]第085号 <a href="//www.hzshuangmei.com/humans.txt" rel="nofollow" target="_blank"><img src="//img.hzshuangmei.com/pc/humanstxt-transparent-color.png" class="humanstxt"></a><br/>
                网站部分图文来源于网络，如有侵权，请联系我们 联系电话：0898-36676570</p>
        </div>
        <div class="middle"></div>
        <div class="right">
            <div class="right_t clearFix">
                <div class="clearFix">
                    <div class="ewm"></div>
                    <div>
                        <p class="fon1">微信扫一扫</p>

                           <p>1）获得最新优惠</p>

                        <p>2）在线实时咨询</p>

                        <p>3）专属服务通道</p>
                    </div>
                </div>

                <div class="clearFix">
                    <div class="f_phone"></div>
                    <div>
                        <p class="fon1">全国免费咨询热线</p>

                        <p class="fon2">0898-36676570</p>

                        <p class="fon3">咨询时间：8:00—20:00</p>
                    </div>
                </div>
            </div>
            <div class="right_b">
                <i></i><span>友情链接:</span>
                
                <a href='https://www.honorreal.com/' target='_blank'>红瑞集团</a> /
                
                <a href='https://www.hoozonspa.com' rel='nofollow' target='_blank'>红妆美容</a> /
                
                <a href='http://www.yueyimei.com' target='_blank'>悦伊美</a> /
                
            </div>
            <p class="copyright">Copyright © 2017 红妆双美 版权所有 违者必究 | <a href="/statement/copyright.html" rel="nofollow" target="_blank">版权及隐私声明</a><br>
                    设计,文案,技术等求职请投递至网络部root#hzwlb.org(#t替换成@)
            </p>
        </div>
    </div>
</footer>
<!-- 右侧悬浮 开始 -->
<div class="yb_conct">
    <div class="yb_bar">
        <ul>
            <li class="yb_QQ"><a target="_blank" href="javascript:void(0)" class="j-consult" title="立即咨询" rel="nofollow">立即咨询</a></li>
            <li class="yb_phone"><a target="_blank" href="javascript:void(0)" class="j-consult" title="门店查询" rel="nofollow">门店查询</a></li>
            <li class="yb_top">返回顶部</li>
            <li class="yb_ercode" >微信扫一扫<br>
                <img class="hd_qr" src="https://img.hzshuangmei.com/pc/WeChatApplet.jpg" width="125" alt="关注微信小程序">
            </li>
        </ul>
    </div>
</div>
<!-- 结束 -->

</body>
<link rel="preload" href="https://js.hzshuangmei.com/pc/common.js" as="script" crossorigin>
<link rel="preload" href="https://js.hzshuangmei.com/pc/layer/layer.js" as="script" crossorigin>
<link rel="preload" href="https://js.hzshuangmei.com/pc/kst_popup.js" as="script" crossorigin>
<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/Swiper/3.4.2/js/swiper.min.js"></script>
<script src="https://js.hzshuangmei.com/pc/common.js" ></script>
<script src="https://js.hzshuangmei.com/pc/layer/layer.js"></script>
<script src="https://js.hzshuangmei.com/pc/kst_popup.js"></script>
 <!-- html5标签兼容ie低版本浏览器 -->
<!-- [if lt IE 9]>     -->
<script src="https://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<!-- <![endif] -->
<!-- 百度站内搜索 -->
<!-- <script type="text/javascript">(function(){document.write(unescape('%3Cdiv id="bdcs"%3E%3C/div%3E'));var bdcs = document.createElement('script');bdcs.type = 'text/javascript';bdcs.async = true;bdcs.src = '//znsv.baidu.com/customer_search/api/js?sid=5257607230163915007' + '&plate_url=' + encodeURIComponent(window.location.href) + '&t=' + Math.ceil(new Date()/3600000);var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(bdcs, s);})();</script> -->


<script src="https://js.hzshuangmei.com/pc/index.js"></script>
</html>
