<!DOCTYPE html>
<html lang="zh-cmn-Hans">
<head>
    <!-- Make 2018-04-19 16:50:04 -->
<!-- Make 1524127804 -->
<meta charset="UTF-8">
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
<meta name="renderer" content="webkit"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
<meta name=applicable-device content="pc">
<meta http-equiv="Cache-Control" content="no-transform"/>
<meta http-equiv="Cache-Control" content="no-siteapp"/>
<meta name="baidu-site-verification" content="99J7V1k1Vz" />
<meta name="google-site-verification" content="Odmo8X4zeUG1WPcCrCAueZz-dyBPFBs4Zqlb9FBT5z4" />
<meta http-equiv="Access-Control-Allow-Origin" content="*" />
<!-- Global site tag (gtag.js) - Google Analytics -->
<!-- <script async src="https://www.googletagmanager.com/gtag/js?id=UA-114904919-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-114904919-2');
</script> -->

    <title>激光洗纹绣_纹绣_海南红妆时尚双美整形美容连锁</title>
    <meta property="og:type" content="article"/>
    <meta property="article:author" content="红妆双美"/>
    <meta property="article:published_time" content="2018-02-22T11:19:28+08:00" />
    <meta name="keywords" content="激光,洗纹,绣,"/>
    <meta name="description" content="洗眉选错方法会留疤 工作室洗纹眉 技术不保证，可能会留下疤痕 高频电子表针洗纹眉 深层颜色难洗掉，往深处洗一定会留疤 中药洗纹眉 会产生凹陷疤痕，修复过分而产生增生留疤"/>
    <meta property="article:tag" content="激光,洗纹,绣,">
    <link rel="canonical" href="https://www.hzshuangmei.com/projects/tattoo/wash.html" />
    <link rel="alternate" media="only screen and(max-width: 640px)" href="https://m.hzshuangmei.com/projects/tattoo/wash.html" >
    <!-- Pre for optimization -->
<link rel="dns-prefetch" href="https://cdn.bootcss.com">
<link rel="dns-prefetch" href="https://uploads.hzshuangmei.com">
<link rel="dns-prefetch" href="https://img.hzshuangmei.com">
<link rel="dns-prefetch" href="https://css.hzshuangmei.com">
<link rel="dns-prefetch" href="https://js.hzshuangmei.com">
<link rel="dns-prefetch" href="https://pv.kuaishang.cn">
<link rel="dns-prefetch" href="https://z8.cnzz.com">
<link rel="dns-prefetch" href="https://s19.cnzz.com">
<link rel="dns-prefetch" href="https://tag.baidu.com">
<link rel="dns-prefetch" href="https://sp0.baidu.com">
<link rel="preload" href="https://css.hzshuangmei.com/pc/common.css" as="style" crossorigin />
<link rel="preload" href="https://img.hzshuangmei.com/pc/favicon.ico" as="image" type="image/x-icon" crossorigin />
<!-- Style for the page-->
<link rel="stylesheet" href="https://cdn.bootcss.com/Swiper/3.4.2/css/swiper.min.css"/>
<link rel="stylesheet" href="https://css.hzshuangmei.com/pc/common.css"/>
<link rel="stylesheet" href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" >
<!-- favicon.ico -->
<link rel="icon" href="https://img.hzshuangmei.com/pc/favicon.ico" type="image/x-icon"/>
<link rel="shortcut icon" href="https://img.hzshuangmei.com/pc/favicon.ico" type="image/x-icon"/>
<!-- humanstxt -->
<link rel="author" href="https://www.hzshuangmei.com/humans.txt" />
<link rel="preload" as=image  href="https://img.hzshuangmei.com/pc/kst/default.png">
<link rel="prefetch" src="https://img.hzshuangmei.com/pc/kst/default.png">
<link rel="prerender" src="https://img.hzshuangmei.com/pc/kst/default.png">
<link rel="prefetch" src="https://img.hzshuangmei.com/pc/kst/wash.png">
<link rel="prerender" src="https://img.hzshuangmei.com/pc/kst/wash.png">
<link rel="preload" as=image  href="https://img.hzshuangmei.com/pc/kst/wash.png">

     <link rel="preload" href="https://css.hzshuangmei.com/pc/tjb.css" as="style" crossorigin />
    <link rel="stylesheet" href="https://css.hzshuangmei.com/pc/tjb.css"/>
    <meta content="设计观彩恒，前端解象蜜/" name="author" />
<link href="http://css.hzshuangmei.com/pc/wash/css.css" rel="stylesheet" type="text/css" />

<body>
<header>
    <div class="top">
        <div class="shuang_m1 clearFix">
            <div class="top_l">
                <!--<span>香港红瑞集团 旗下品牌 海南红妆双美连锁</span>-->
                <img src="https://img.hzshuangmei.com/pc/tl_logo.png" alt="logo" />|<span>美丽时间：周一周日9点--21点</span>
            </div>
            <!-- 增加百度站内搜索 -->
            <div class="top_c">
                <div class="search_box">
                    <form action="https://www.hzshuangmei.com/search/" target="_blank" autocomplete="off" id="bdcs-search-form" class="site-search-form">
                        <input type="hidden" name="s" value="5257607230163915007">
                         <input type="hidden" name="entry" value="1">
                        <input type="text" placeholder="请输入您要搜索的内容..." id="bdcsMain" name="q">
                        <button type="submit" id="bdcs-search-form-submit"></button>
                    </form>
                </div>
            </div>
                        <!-- 增加百度站内搜索 -->
            <div class="top_r">
                <a href="" class="pad_r"><i class="tel"></i><span>0898-66156043</span></a>
                <span>关注我们：</span>
                <a href="" class="pad_l"><i class="wbo"></i></a>
                <a href=""><i class="wxin"></i></a>
                <a href=""><i class="qq"></i></a>
            </div>
        </div>
    </div>
    <div class="sm_logo">
        <a href="/"><img src="https://img.hzshuangmei.com/pc/h_logo.png" alt=""/></a>
    </div>
</header>
<nav id="nav">
    <ul class="shuang_m1 nav_ul">
        <li class="nav_list">
            <a href="/" class="nav_link" target="_blank" rel="noopener">
                <span>首 页</span><br/>
                <span>Home</span>
            </a>
        </li>
        <li class="nav_list">
            <a href="/brand" class="nav_link bor_r" target="_blank" rel="noopener">
                <span>品 牌</span><br/>
                <span>brands</span>
            </a>
        </li>
        <li class="nav_list">
            <a href="/projects" class="nav_link bor_l bor_r" target="_blank" rel="noopener">
                <span>项 目</span><br/>
                <span>projects</span>
            </a>
            <div class="clearFix" id="project">
                <ul>
                    <li>
                        <h5><a href="/projects/tattoo/" target="_blank" rel="noopener">医学纹绣</a></h5>
                    </li>
                    <!--              <li>
                        <a href="/projects/tattoo/yanxian.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P4041610355P.jpg" alt="红妆艺术美瞳线"/>
                            <p><i></i><span>红妆艺术美瞳线</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/tattoo/hsbyjwm.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404160923556.jpg" alt="韩式半永久纹眉"/>
                            <p><i></i><span>韩式半永久纹眉</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/tattoo/xwx.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/img/180331/1-1P3311106490-L.jpg" alt="洗纹绣"/>
                            <p><i></i><span>洗纹绣</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/tattoo/xwx.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/img/180331/1-1P3311106490-L.jpg" alt="洗纹绣"/>
                            <p><i></i><span>洗纹绣</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/tattoo/wash.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180222/1-1P222110205243.jpg" alt="激光洗纹绣"/>
                            <p><i></i><span>激光洗纹绣</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/tattoo/hsbyjwm.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404160923556.jpg" alt="韩式半永久纹眉"/>
                            <p><i></i><span>韩式半永久纹眉</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button">-->
                    <!--<a href="/projects" target="_blank" rel="noopener">查看更多</a>-->
                    <!--</li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/eye/" target="_blank" rel="noopener">眼部整形</a></h5>
                    </li>
                    <!--   <li>
                        <a href="/projects/eye/qmtm.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404161354458.jpg" alt=""/>
                            <p><i></i><span>切眉提眉术</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/eye/slxc.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180222/1-1P22216455E61.jpg" alt=""/>
                            <p><i></i><span>上睑下垂</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/eye/yandai.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404160Q03S.jpg" alt=""/>
                            <p><i></i><span>无痕祛眼袋</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/eye/yandai.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404160Q03S.jpg" alt="无痕祛眼袋"/>
                            <p><i></i><span>无痕祛眼袋</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/eye/slxc.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180222/1-1P22216455E61.jpg" alt="上睑下垂"/>
                            <p><i></i><span>上睑下垂</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/eye/hzyj.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180206/1-1P206100342338.jpg" alt="红妆孕睫术"/>
                            <p><i></i><span>红妆孕睫术</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/nose/" target="_blank" rel="noopener">鼻部整形</a></h5>
                    </li>
                    <!--              <li>
                        <a href="/projects/nose/lineeaglenose.html" target="_blank" rel="noopener">
                        <img src="https://uploads.hzshuangmei.com/180109/1-1P10916214I29.jpg" alt=""/>
                            <p><i></i><span>线雕隆鼻</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/nose/heben.html" target="_blank" rel="noopener">
                        <img src="https://uploads.hzshuangmei.com/180109/1-1P109162114246.jpg" alt=""/>
                            <p><i></i><span>红妆赫本软骨鼻</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/nose/longbijiage.html" target="_blank" rel="noopener">
                        <img src="https://uploads.hzshuangmei.com/180209/1-1P2091524433K.jpg" alt=""/>
                            <p><i></i><span>隆鼻价格</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/nose/longbijiage.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180209/1-1P2091524433K.jpg" alt="隆鼻价格"/>
                            <p><i></i><span>隆鼻价格</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/nose/hzbbqb.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180208/1-1P20QZ14O61.jpg" alt="红妆芭比翘鼻"/>
                            <p><i></i><span>红妆芭比翘鼻</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/nose/nose.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180109/1-1P109161Fc42.jpg" alt="全立体鼻缩窄术"/>
                            <p><i></i><span>全立体鼻缩窄术</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/face/" target="_blank" rel="noopener">面部整形</a></h5>
                    </li>
                    <!--                <li class="star">
                        <a href="/projects/zhifang/ztzfmd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180109/1-1P109162329454.jpg" alt=""/>
                            <p><i></i><span>自体脂肪面雕</span></p>
                        </a>
                    </li><li class="star">
                        <a href="/projects/xiaba/vlmxd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P40416062R04.jpg" alt=""/>
                            <p><i></i><span>v立美线雕</span></p>
                        </a>
                    </li><li class="star">
                        <a href="/projects/face/zitizhifang.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180208/1-1P20Q54P4G4.jpg" alt=""/>
                            <p><i></i><span>自体脂肪面部填充</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/face/zitizhifang.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180208/1-1P20Q54P4G4.jpg" alt="自体脂肪面部填充"/>
                            <p><i></i><span>自体脂肪面部填充</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/xiaba/vlmxd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P40416062R04.jpg" alt="v立美线雕"/>
                            <p><i></i><span>v立美线雕</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/zhifang/ztzfmd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180109/1-1P109162329454.jpg" alt="自体脂肪面雕"/>
                            <p><i></i><span>自体脂肪面雕</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/skin/" target="_blank" rel="noopener">皮肤美容</a></h5>
                    </li>
                    <!--                 <li>
                        <a href="/projects/qudou/duoweiqd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180222/1-1P222143953U0.jpg" alt=""/>
                            <p><i></i><span>红妆多维祛痘</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/quban/xpmqb.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180328/1-1P32Q356202V.jpg" alt=""/>
                            <p><i></i><span>红妆皮秒祛斑</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/skin/sgz.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180406/1-1P4061A303F6.jpg" alt=""/>
                            <p><i></i><span>水光针</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/quban/xpmqb.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180328/1-1P32Q356202V.jpg" alt="红妆皮秒祛斑"/>
                            <p><i></i><span>红妆皮秒祛斑</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/chuzhou/quzhou.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180212/1-1P212102446403.jpg" alt="除皱抗衰"/>
                            <p><i></i><span>除皱抗衰</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/quban/quban.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180312/1-1P3121601494G.jpg" alt="红妆祛斑"/>
                            <p><i></i><span>红妆祛斑</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/ha/" target="_blank" rel="noopener">玻尿酸</a></h5>
                    </li>
                    <!--                     <li>
                        <a href="/projects/ha/qydbns.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180208/1-1P20Q0501X26.jpg" alt=""/>
                            <p><i></i><span>乔雅登玻尿酸</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/ha/zhbns.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180109/1-1P109161SV57.jpg" alt=""/>
                            <p><i></i><span>综合玻尿酸</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/ha/restylane.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180413/1-1P413100FcV.jpg" alt=""/>
                            <p><i></i><span>瑞蓝玻尿酸</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/ha/restylane.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180413/1-1P413100FcV.jpg" alt="瑞蓝玻尿酸"/>
                            <p><i></i><span>瑞蓝玻尿酸</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/ha/bnsqflw.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180411/1-1P411140P9134.jpg" alt="玻尿酸祛除法令纹"/>
                            <p><i></i><span>玻尿酸祛除法令纹</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/ha/xbnsfet.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180322/1-1P322092GMV.jpg" alt="玻尿酸丰额头"/>
                            <p><i></i><span>玻尿酸丰额头</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/body/" target="_blank" rel="noopener">形体雕塑</a></h5>
                    </li>
                    <!-- <li>
                        <a href="/projects/body/sdlxz.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404161320X4.jpg" alt=""/>
                            <p><i></i><span>水动力吸脂</span></p>
                       </a>
                    </li> -->
                    <li>
                        <a href="/projects/body/sdlxz.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404161320X4.jpg" alt="水动力吸脂"/>
                            <p><i></i><span>水动力吸脂</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
            </div>
        </li>
        <li class="nav_list">
            <a href="/doctors" class="nav_link bor_l bor_r" target="_blank" rel="noopener">
                <span>专 家</span><br/>
                <span>experts</span>
            </a>
            <div id="expert">
                <ul>
                    <li>
                        <h5><a href="/doctors/surgery" target="_blank" rel="noopener">整形美容专家</a></h5>
                    </li>
                    <!--                     <li>
                        <a href="/plugin/view.php?aid=227" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180414/1-1P4140929454T.jpg" alt="薛开兴"/>
                            <p><span class="n_f">薛开兴</span><span class="n_b">整形外科院长</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=153" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180131/1-1P131093205432.jpg" alt="余志亮"/>
                            <p><span class="n_f">余志亮</span><span class="n_b">整形专家</span></p>
                            <i></i>
                        </a>
                    </li> -->
                    <li>
                        <a href="/doctors/surgery/guanhaitao.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180227/1-1P22G44625M2.jpg" alt="关海涛 "/>
                            <p><span class="n_f">关海涛 </span><span class="n_b">整形外科院长</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=176" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180131/1-1P1310U92D41.jpg" alt="朱红振"/>
                            <p><span class="n_f">朱红振</span><span class="n_b">整形外科院长</span></p>
                            <i></i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <h5><a href="/doctors/laser" target="_blank" rel="noopener">激光美容专家</a></h5>
                    </li>
                    <!--             <li>
                        <a href="/doctors/laser/lijie.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/171206/1-1G20611435D10.jpg" alt="李杰"/>
                            <p><span class="n_f">李杰</span><span class="n_b">光学美肤中心院长</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/doctors/laser/yzw.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180131/1-1P131104604521.jpg" alt="姚志文"/>
                            <p><span class="n_f">姚志文</span><span class="n_b">非手术面部年轻化专家</span></p>
                            <i></i>
                        </a>
                    </li> -->
                    <li>
                        <a href="/doctors/laser/lijie.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/171206/1-1G20611435D10.jpg" alt="李杰"/>
                            <p><span class="n_f">李杰</span><span class="n_b">光学美肤中心院长</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/doctors/laser/yzw.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180131/1-1P131104604521.jpg" alt="姚志文"/>
                            <p><span class="n_f">姚志文</span><span class="n_b">非手术面部年轻化专家</span></p>
                            <i></i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <h5><a href="/doctors/tattoo" target="_blank" rel="noopener">医学纹绣</a></h5>
                    </li>
                    <!--                    <li>
                        <a href="/plugin/view.php?aid=139" target="_blank" rel="noopener">
                    <img src="https://uploads.hzshuangmei.com/180117/1-1P11GF5391A.jpg" alt="杨小丽"/>
                            <p><span class="n_f">杨小丽</span><span class="n_b">纹饰指导师</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=136" target="_blank" rel="noopener">
                    <img src="https://uploads.hzshuangmei.com/180125/1-1P125154A1105.jpg" alt="高方云"/>
                            <p><span class="n_f">高方云</span><span class="n_b">纹饰指导师</span></p>
                            <i></i>
                        </a>
                    </li> -->
                    <li>
                        <a href="/plugin/view.php?aid=164" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180125/1-1P12515435J45.jpg" alt="冯晓琳"/>
                            <p><span class="n_f">冯晓琳</span><span class="n_b">纹饰技术总指导师</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=137" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180117/1-1P11GA95JV.jpg" alt="孟超"/>
                            <p><span class="n_f">孟超</span><span class="n_b">纹饰指导师</span></p>
                            <i></i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <h5><a href="/doctors" target="_blank" rel="noopener">特邀专家</a></h5>
                    </li>
                    <li>
                        <a href="/doctors/surgery/ljb.html" target="_blank" rel="noopener">
                             <img src="https://uploads.hzshuangmei.com/180131/1-1P131092S24W.jpg" alt="雷建波(客座)"/>
                            <p><span class="n_f">雷建波(客座)</span><span class="n_b">整形美容专家</span></p>
                            <i></i>
                        </a>
                    </li>
<li>
                        <a href="/doctors/surgery/liudalie.html" target="_blank" rel="noopener">
                             <img src="https://uploads.hzshuangmei.com/171223/1-1G223091J5950.jpg" alt="柳大烈(客座)"/>
                            <p><span class="n_f">柳大烈(客座)</span><span class="n_b">教授</span></p>
                            <i></i>
                        </a>
                    </li>

                </ul>
                <ul>
                    <li>
                        <h5 class="moon"><a href="/doctors" target="_blank" rel="noopener">每月专家</a></h5>
                    </li>
                    <li class="last-one">
                        <!--<a class="last-one" href="https://www.hzshuangmei.com/doctors/surgery/liudalie.html " target="_blank" rel="noopener">-->
                            <!--<img src="https://img.hzshuangmei.com/pc/nav_zhuanjial.jpg" alt=""/>-->
                        <!--</a>-->
                        <a class="last-one j-consult" href="javascript:void(0)"  target="_blank" rel="noopener nofollow">
                            <img src="https://img.hzshuangmei.com/pc/myzzj.jpg" alt=""/>
                        </a>
                    </li>
                </ul>
            </div>
        </li>
        <li class="nav_list">
            <a href="/cases" class="nav_link bor_l bor_r" target="_blank" rel="noopener">
                <span>真人秀</span><br/>
                <span>Show</span>
            </a>
        </li>
        <li class="nav_list">
            <a href="/news" class="nav_link bor_l" target="_blank" rel="noopener">
            <span>活 动</span><br/>
                <span>News</span>
            </a>
        </li>
    </ul>
</nav>


    <a class="j-consult" href="javascript:void(0);" rel="nofollow" title="整形洗眉banner">

        <div class="banner"></div>

    </a>

    <div class="main-one">

        <div class="title title1">

            <h3><strong>洗眉选错方法会留疤</strong></h3><img src="https://img.hzshuangmei.com/pc/wash/careful.png" alt="要慎重！" /> <span class="xian1"></span> <span class="xian2"></span> <em class="circle1"></em> <em class="circle2"></em></div>

        <div class="main1-center"><img src="https://img.hzshuangmei.com/pc/wash/lt.jpg" alt="" class="lt"> <img src="https://img.hzshuangmei.com/pc/wash/br.jpg" alt="" class="br">

            <div class="mian1Cin">

                <div class="ximei ximei1"><img src="https://img.hzshuangmei.com/pc/wash/ximei1.png" alt="" />

                    <div class="triangle"></div>

                    <h3><strong>工作室洗纹眉</strong></h3>

                    <p>技术不保证，可能会留下疤痕</p>

                </div>

                <div class="ximei ximei2">

                    <h3><strong>高频电子表针洗纹眉</strong></h3>

                    <p>深层颜色难洗掉，往深处洗一定会留疤</p>

                    <div class="triangle"></div><img src="https://img.hzshuangmei.com/pc/wash/ximei2.png" alt="" /></div>

                <div class="ximei ximei3"><img src="https://img.hzshuangmei.com/pc/wash/ximei3.png" alt="" />

                    <div class="triangle"></div>

                    <h3><strong>中药洗纹眉</strong></h3>

                    <p>会产生凹陷疤痕，修复过分而产生增生留疤</p>

                </div>

                <div class="ximei ximei4">

                    <h3><strong>神针移热法</strong></h3>

                    <p>伤到真皮会留疤，也容易感染</p>

                    <div class="triangle"></div><img src="https://img.hzshuangmei.com/pc/wash/ximei4.png" alt="" /></div>

            </div>

        </div>

    </div>

    <div class="main-two">

        <div class="main2-in">

            <div class="title title2">

                <h3><strong>选择红妆全新洗纹绣技术</strong></h3><img src="https://img.hzshuangmei.com/pc/wash/bahen.png" alt="高效不留疤恢复快"> <span class="xian1"></span> <span class="xian2"></span> <em class="circle1"></em> <em class="circle2"></em></div>

            <ul>

                <li><img src="https://img.hzshuangmei.com/pc/wash/qq.jpg" alt="" /><span></span>

                    <p><strong>洗纹眉</strong></p>

                </li>

                <li><img src="https://img.hzshuangmei.com/pc/wash/qq2.jpg" alt="" /><span></span>

                    <p><strong>洗眼线</strong></p>

                </li>

                <li class="nomargin"><img src="https://img.hzshuangmei.com/pc/wash/qq3.jpg" alt="" /><span></span>

                    <p><strong>洗纹唇</strong></p>

                </li>

            </ul>

            <p class="main2-arc">激光洗纹绣(洗眉、洗眼线、洗纹唇)是利用<strong>高科技专业激光照射，</strong>其特定的波长多脉冲光作用纹刺部位，使在皮肤内的颜料色素瞬间气化或爆破粉碎，分解成细小的颗粒，经体内吞噬细胞吞噬排出体外，而对周围正常的皮肤和毛发不造成损伤。</p>



            <div class="zxww tdh"><span class="sjtl"></span> <span class="sjbr"></span>

                <a class="j-consult" href="javascript:void(0);" rel="nofollow" title="整形洗眉立即咨询">

                    <p>立即咨询</p>

                </a>

            </div>



        </div>

    </div>

    <div class="main-three">

        <div class="title title3">

            <h3><strong>22年全新科技洗纹绣</strong></h3><img src="https://img.hzshuangmei.com/pc/wash/aqbz.png" alt="安全保障" /> <span class="xian1"></span> <span class="xian2"></span> <em class="circle1"></em> <em class="circle2"></em></div>

        <div class="liti">

            <div class="liti1"><em class="main3Sj1"></em> <em class="main3Sj2"></em></div>

            <div class="liti2"><img src="https://img.hzshuangmei.com/pc/wash/01.png" alt="" class="litinum">

                <h3><strong>激光洗纹眉</strong></h3><img src="https://img.hzshuangmei.com/pc/wash/youshi.png" alt="优势" class="youshi">

                <div class="zxww zx2 tdh"><span class="sjtl"></span> <span class="sjbr"></span>

                    <a class="j-consult" href="javascript:void(0);" rel="nofollow" title="整形洗眉立即咨询2">

                        <p>立即咨询</p>

                    </a>

                </div>

            </div>

            <div class="yinying"></div>

        </div>

        <div class="main3-center">

            <div class="main3arc">

                <div><em>1.</em>

                    <p><strong>激光洗眉不损伤皮肤</strong>，毛囊，不产生疤痕，只去除色素。</p>

                </div>

                <div class="distance1"><em>2.</em>

                    <p><strong>激光洗眉</strong>可以清除药物或其他方法未能去除的色素。</p>

                </div>

                <div class="distance2"><em>3.</em>

                    <p><strong>痛苦小</strong>，绝大多数人无需麻醉。</p>

                </div>

                <div class="distance3"><em>4.</em>

                    <p><strong>恢复快</strong>，对正常工作影响小。</p>

                </div>

                <div class="distance4"><em>5.</em>

                    <p><strong>激光洗眉后反应小</strong>，轻微的肿胀消退快。</p>

                </div>

                <div class="distance5"><em>6.</em>

                    <p><strong>激光杀菌</strong>，无交叉感染，不需特殊治疗环境。</p>

                </div>

                <div class="distance6"><em>7.</em>

                    <p><strong>方便快捷</strong>,每次仅需15-20分钟,无痛无创。</p>

                </div>

                <p class="main3eng tdh">

                    <a class="j-consult" href="javascript:void(0);" rel="nofollow" title="整形洗眉立即咨询3">
                        <img src="https://img.hzshuangmei.com/pc/wash/main3eng.png" alt="" /></a>

                </p>

            </div>

        </div>

        <div class="liti lititwo">

            <div class="liti1"><em class="main3Sj1"></em> <em class="main3Sj2"></em></div>

            <div class="liti2"><img src="https://img.hzshuangmei.com/pc/wash/02.png" alt="" class="litinum">

                <h3><strong>激光洗纹唇</strong></h3><img src="https://img.hzshuangmei.com/pc/wash/youshi.png" alt="优势" class="youshi">

                <div class="zxww zx2 tdh"><span class="sjtl"></span> <span class="sjbr"></span>

                    <a class="j-consult" href="javascript:void(0);" rel="nofollow" title="整形洗眉立即咨询4">

                        <p>立即咨询</p>

                    </a>

                </div>

            </div>

            <div class="yinying"></div>

        </div>

    </div>

    <div class="mian-four">

        <div class="main4-in">

            <div class="mian4img"><img src="https://img.hzshuangmei.com/pc/wash/main4tu1.jpg" alt="" /> <img src="https://img.hzshuangmei.com/pc/wash/main4tu2.jpg" alt="" /> <img src="https://img.hzshuangmei.com/pc/wash/main4tu3.jpg" alt="" /> <img src="https://img.hzshuangmei.com/pc/wash/main4tu4.jpg" alt="" /></div>

            <ul>

                <li>

                    <h3>不伤肌肤</h3>国际先进设备，与传统的激光洗纹绣不同，它利用不同波长的激光就能有选择地进行手术，使皮肤不受损伤。</li>

                <li>

                    <h3>效果显著</h3>激光洗纹唇可以去掉面积比较大，颜色重的图案。</li>

                <li>

                    <h3>不留疤痕</h3>显著的优点在于激光洗纹唇无需使用刀切或磨蚀，高效不留疤痕。</li>

                <li class="nomargin">

                    <h3>恢复快</h3>恢复时间无需住院，即做即走。</li>

            </ul>

            <div class="liti litithree">

                <div class="liti1"><em class="main3Sj1"></em> <em class="main3Sj2"></em></div>

                <div class="liti2"><img src="https://img.hzshuangmei.com/pc/wash/03.png" alt="" class="litinum">

                    <h3><strong>激光洗眼线</strong></h3><img src="https://img.hzshuangmei.com/pc/wash/youshi.png" alt="优势" class="youshi">

                    <div class="zxww zx2 tdh"><span class="sjtl"></span> <span class="sjbr"></span>

                        <a class="j-consult" href="javascript:void(0);" rel="nofollow" title="整形洗眉立即咨询5">

                            <p>立即咨询</p>

                        </a>

                    </div>

                </div>

                <div class="yinying"></div>

            </div>

        </div>

    </div>

    <div class="main-five">

        <ul>

            <li><img src="https://img.hzshuangmei.com/pc/wash/1.png" alt="" class="main4num">

                <h3>可人工调控</h3>

                <div class="main4eng"><em>+</em><span>artificial regulation</span><em>+</em></div><img src="https://img.hzshuangmei.com/pc/wash/mianfivetu1.jpg" alt="" />

                <p>先进的激光技术可以控制激光所到达的皮肤深度，可调节的脉冲能够使皮肤的损伤减低到小程度。</p>

            </li>

            <li><img src="https://img.hzshuangmei.com/pc/wash/2.png" alt="" class="main4num">

                <h3>术后恢复快</h3>

                <div class="main4eng"><em>+</em><span>fast recovered</span><em>+</em></div><img src="https://img.hzshuangmei.com/pc/wash/mianfivetu2.jpg" alt="" />

                <p>激光洗眼线利用高科技激光设备，在一至两分钟内消除眼线，效果明显，无疤痕无痛苦，不留疤痕。</p>

            </li>

            <li><img src="https://img.hzshuangmei.com/pc/wash/3.png" alt="" class="main4num">

                <h3>安全无疤痕</h3>

                <div class="main4eng"><em>+</em><span>Safety without scar</span><em>+</em></div><img src="https://img.hzshuangmei.com/pc/wash/mianfivetu3.jpg" alt="" />

                <p>由于使用的是物理的激光照射，不会对周边的皮肤组织造成伤害，所以激光洗眼线术比其他传统的方法安全有效。</p>

            </li>

        </ul>

        <div class="main4e tdh">

            <a class="j-consult" href="javascript:void(0);" rel="nofollow" title="整形洗眉立即咨询6"><img src="https://img.hzshuangmei.com/pc/wash/eng2.png" alt="" /></a>

        </div>

    </div>

    <div class="main-six">

        <div class="main6-in">

            <div class="title title4">

                <h3><strong>红妆洗眉、洗眼线、洗纹唇</strong></h3><img src="https://img.hzshuangmei.com/pc/wash/kexue.png" alt="科学诊断 层层清除"> <span class="xian1"></span> <span class="xian2"></span> <em class="circle1"></em> <em class="circle2"></em></div>

            <div class="mian6-in">

                <div class="main6Q1"><img src="https://img.hzshuangmei.com/pc/wash/main5tu1.png" alt="" />

                    <p>1.纹绣检测</p>

                </div>

                <div class="main6Q2"><img src="https://img.hzshuangmei.com/pc/wash/main5tu2.png" alt="" />

                    <p>2.纹身诊断</p>

                </div>

                <div class="main6Q3"><img src="https://img.hzshuangmei.com/pc/wash/main5tu3.png" alt="" />

                    <p>3.方案设计</p>

                </div>

                <div class="main6Q4"><img src="https://img.hzshuangmei.com/pc/wash/main5tu4.png" alt="" />

                    <p>4.专业治疗</p>

                </div>

                <div class="main6Q5"><img src="https://img.hzshuangmei.com/pc/wash/main5tu5.png" alt="" />

                    <p>5.保养护理</p>

                </div>

            </div>

            <div class="main4e tdh">

                <a class="j-consult" href="javascript:void(0);" rel="nofollow" title="整形洗眉立即咨询7"><img src="https://img.hzshuangmei.com/pc/wash/eng2.png" alt="立即咨询"></a>

            </div>

        </div>

    </div>

    <div class="main-seven">

        <div class="title title5">

            <h3><strong>红妆洗眉、洗眼线、洗纹唇</strong></h3><img src="https://img.hzshuangmei.com/pc/wash/zsan.png" alt="真实案例"> <span class="xian1"></span> <span class="xian2"></span> <em class="circle1"></em> <em class="circle2"></em></div>

        <ul>

            <li><img src="https://img.hzshuangmei.com/pc/wash/main6tu1.jpg" alt="" />

                <p>术前</p>

            </li>

            <li><img src="https://img.hzshuangmei.com/pc/wash/main6tu2.jpg" alt="" />

                <p>术后</p>

            </li>

            <li class="leftmargin"><img src="https://img.hzshuangmei.com/pc/wash/main6tu3.jpg" alt="" />

                <p>术前</p>

            </li>

            <li class="nomargin"><img src="https://img.hzshuangmei.com/pc/wash/main6tu4.jpg" alt="" />

                <p>术后</p>

            </li>

            <li><img src="https://img.hzshuangmei.com/pc/wash/main6tu5.jpg" alt="" />

                <p>术前</p>

            </li>

            <li><img src="https://img.hzshuangmei.com/pc/wash/main6tu6.jpg" alt="" />

                <p>术后</p>

            </li>

            <li class="leftmargin"><img src="https://img.hzshuangmei.com/pc/wash/main6tu7.jpg" alt="" />

                <p>术前</p>

            </li>

            <li class="nomargin"><img src="https://img.hzshuangmei.com/pc/wash/main6tu8.jpg" alt="" />

                <p>术后</p>

            </li>

        </ul>

        <div class="main4e tdh">

            <a class="j-consult" href="javascript:void(0);" rel="nofollow" title="整形洗眉立即咨询8"><img src="https://img.hzshuangmei.com/pc/wash/eng2.png" alt="立即咨询"></a>

        </div>

    </div>


<div  class="tjb">
    <div class="m_rj">
        <!--<div class="tjb_title1">-->
            <!--<img src="https://img.hzshuangmei.com/pc/tjb_title1.png" alt=""/>-->
        <!--</div>-->
               <div class="tjb_title1">
            <img src="https://img.hzshuangmei.com/pc/tjb_title1.png" alt="相关日记"/>
        </div><ul class="tjb_rj clearFix"> <li>
              <a href="/cases/tattoo/230.html" class="tbj_t" target="_blank">
                  <img src="https://uploads.hzshuangmei.com/180416/2-1P4161113303E.JPG" alt="术后"/>
              </a>
              <div class="tbj_b">
                  <a href="/cases/tattoo/230.html" class="tbj_b_img" target="_blank"><img src="https://uploads.hzshuangmei.com/180416/2-1P416111305c1.JPG" alt="术前"/></a>
                     <p class="p1 tbj_b_p1">【 速美项目 】</p>
                  <p class="p2"><a href="https://www.hzshuangmei.com/projects/tattoo/yzwc.html">半永久纹唇</a></p>
                  <a href="/cases/tattoo/230.html" class="tjb_video" target="_blank"><img src="//img.hzshuangmei.com/pc/tjb_video.png" alt="整形案例视频"/></a>
              </div>
              </li><li>
              <a href="/cases/tattoo/228.html" class="tbj_t" target="_blank">
                  <img src="https://uploads.hzshuangmei.com/180416/2-1P41609355I03.JPG" alt="术后"/>
              </a>
              <div class="tbj_b">
                  <a href="/cases/tattoo/228.html" class="tbj_b_img" target="_blank"><img src="https://uploads.hzshuangmei.com/180416/2-1P416093513305.JPG" alt="术前"/></a>
                     <p class="p1 tbj_b_p1">【 速美项目 】</p>
                  <p class="p2"><a href="https://www.hzshuangmei.com/projects/tattoo/yzwc.html">半永久纹唇</a></p>
                  <a href="/cases/tattoo/228.html" class="tjb_video" target="_blank"><img src="//img.hzshuangmei.com/pc/tjb_video.png" alt="整形案例视频"/></a>
              </div>
              </li><li>
              <a href="/cases/tattoo/183.html" class="tbj_t" target="_blank">
                  <img src="https://uploads.hzshuangmei.com/180206/2-1P206134445V5.jpg" alt="术后"/>
              </a>
              <div class="tbj_b">
                  <a href="/cases/tattoo/183.html" class="tbj_b_img" target="_blank"><img src="https://uploads.hzshuangmei.com/180206/2-1P20613435I60.JPG" alt="术前"/></a>
                     <p class="p1 tbj_b_p1">【 速美项目 】</p>
                  <p class="p2"><a href="https://www.hzshuangmei.com/projects/tattoo/hzyswx.html">粉雾眉</a></p>
                  <a href="/cases/tattoo/183.html" class="tjb_video" target="_blank"><img src="//img.hzshuangmei.com/pc/tjb_video.png" alt="整形案例视频"/></a>
              </div>
              </li></ul>
    </div>
    <div class="m_zj">
        <!--<div class="tjb_title2">-->
            <!--<img src="https://img.hzshuangmei.com/pc/tjb_title2.png" alt=""/>-->
        <!--</div>-->
             <div class="tjb_title2">
            <img src="https://img.hzshuangmei.com/pc/tjb_title2.png" alt="推荐专家"/>
        </div><ul class="tjb_zj clearFix"> <li class="clearFix">
                <a href="/plugin/view.php?aid=136" class="tjb_l" target="_blank"><img src="https://uploads.hzshuangmei.com/180125/1-1P125154A1105.jpg" alt="高方云"/></a>
                <div class="tjb_r">
                    <p class="p3"><a href="/plugin/view.php?aid=136" class="tjb_name" target="_blank">高方云</a></p>
                    <p class="p4"><a href="/plugin/view.php?aid=136" target="_blank">纹饰指导师</a></p>
                    <div class="tjb_sc clearFix">
                        <p>擅长项目：</p>
                        <p><a href="https://www.hzshuangmei.com/projects/tattoo/byjwm.html">粉雾眉</a>&nbsp;<a href="https://www.hzshuangmei.com/projects/tattoo/yanxian.html">美瞳线</a>&nbsp;<a href="https://www.hzshuangmei.com/projects/tattoo/yzwc.html">半永久纹唇</a><br />
<br />
<br />
 </p>
                    </div>
                    <div class="tjb_button">
                        <a class="j-consult" href="javascript:void(0);" rel="nofollow" target="_blank"><img src="//img.hzshuangmei.com/pc/tjb_button.png" alt="点击咨询"/></a>
                    </div>
                </div></li><li class="clearFix">
                <a href="/plugin/view.php?aid=137" class="tjb_l" target="_blank"><img src="https://uploads.hzshuangmei.com/180117/1-1P11GA95JV.jpg" alt="孟超"/></a>
                <div class="tjb_r">
                    <p class="p3"><a href="/plugin/view.php?aid=137" class="tjb_name" target="_blank">孟超</a></p>
                    <p class="p4"><a href="/plugin/view.php?aid=137" target="_blank">纹饰指导师</a></p>
                    <div class="tjb_sc clearFix">
                        <p>擅长项目：</p>
                        <p><a href="https://www.hzshuangmei.com/projects/tattoo/byjwm.html">半永久纹眉</a>&nbsp;<a href="https://www.hzshuangmei.com/projects/tattoo/yzwc.html">纹唇</a><br />
 </p>
                    </div>
                    <div class="tjb_button">
                        <a class="j-consult" href="javascript:void(0);" rel="nofollow" target="_blank"><img src="//img.hzshuangmei.com/pc/tjb_button.png" alt="点击咨询"/></a>
                    </div>
                </div></li></ul>
    </div>
    <div class="m_xm">
        <!--<div class="tjb_title3">-->
            <!--<img src="https://img.hzshuangmei.com/pc/tjb_title3.png" alt=""/>-->
        <!--</div>-->
        <!--<div class="tjb_xm">-->
               <div class="tjb_title3">
            <img src="https://img.hzshuangmei.com/pc/tjb_title3.png" alt="相关项目"/>
        </div><div class="tjb_xm"><div class="tjb_img clearFix">
  <a href="/projects/tattoo/mycwx.html" target="_blank"><img src="https://uploads.hzshuangmei.com/180109/1-1P109162435A1.jpg" alt="眉眼唇纹绣"></a><a href="/projects/tattoo/xwx.html" target="_blank"><img src="https://uploads.hzshuangmei.com/img/180331/1-1P3311106490-L.jpg" alt="洗纹绣"></a><a href="/projects/tattoo/yzwc.html" target="_blank"><img src="https://uploads.hzshuangmei.com/180109/1-1P109162533I9.jpg" alt="雅致纹唇"></a>
</div>         </div>

        <!--</div>-->
    </div>
</div>
<div class="index_items" id="index_items">
    <div class="shuang_m1">
        <div class="clearFix border-r">
            <div class="icon">
                <span>双美概况</span>
                <i></i>
            </div>
            <ul class="mar_t">
                <li><a href="/" target="_blank" rel="noopener" >>返回首页</a></li>
                <li><a class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener">>来院路线</a></li>
                <li><a class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener">>联系我们</a></li>
                <li><a href="/brand" target="_blank" rel="noopener">>品牌起源</a></li>
                <!--<li><a href="">>企业文化</a></li>-->
            </ul>
        </div>
        <div class="clearFix border-l border-r">
            <div class="icon">
                <span>整形美容</span>
                <i></i>
            </div>
            <ul class="mar_t">
                <li><a href="/projects/chest/#project_nav" target="_blank" rel="noopener">>胸部整形</a></li>
                <li><a href="/projects/eye/#project_nav" target="_blank" rel="noopener">>眼部整形</a></li>
                <li><a href="/projects/nose/#project_nav" target="_blank" rel="noopener">>鼻部整形</a></li>
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>唇部整形</a></li>
                <li><a href="/projects/body/#project_nav" target="_blank" rel="noopener">>塑形体雕</a></li>
                <li><a href="/projects/zhifang/ztzfmd.html" target="_blank" rel="noopener">>自体脂肪填充</a></li>
                <li><a href="/projects/#project_nav" target="_blank" rel="noopener">>其他系列</a></li>
                <li><a href="/projects/ha/bnsxb.html" target="_blank" rel="noopener">>下巴整形</a></li>
                <li><a href="/projects/private/#project_nav" target="_blank" rel="noopener">>私密整形</a></li>
            </ul>
        </div>
        <div class="clearFix border-l border-r">
            <div class="icon">
                <span>光学美肤</span>
                <i></i>
            </div>
            <ul class="mar_t">
                <li><a href="/projects/quban/quban.html" target="_blank" rel="noopener">>美白祛斑</a></li>
                <li><a href="/projects/tuomao/tuomao2.html" target="_blank" rel="noopener">>专业脱毛</a></li>
                <li><a href="/projects/qudou/hzqdk.html" target="_blank" rel="noopener">>祛痘祛疤印</a></li>
                <li><a href="/projects/chuzhou/quzhou.html" target="_blank" rel="noopener">>紧肤抗衰</a></li>
            </ul>
        </div>
        <div class="clearFix border-l">
            <div class="icon">
                <span>微创美容</span>
                <i></i>
            </div>
            <ul class="mar_t">
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>玻尿酸塑形</a></li>
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>玻尿酸祛皱</a></li>
                <li><a href="/projects/botox/#project_nav" target="_blank" rel="noopener">>BOTOX注射</a></li>
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>疤痕针</a></li>
                <li><a href="/projects/tattoo/#project_nav" target="_blank" rel="noopener">>纹绣</a></li>
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>水光注射</a></li>
                <li><a href="/projects/#project_nav" target="_blank" rel="noopener">>其他</a></li>
            </ul>
        </div>
    </div>
</div>
<footer id="footer">
    <div class="shuang_m1 clearFix">
        <div class="left">
            <h2><a href=""><img src="https://img.hzshuangmei.com/pc/f_logo.png" alt="红妆双美"/></a></h2>
            <p class="addr"><i></i>红妆双美地址：海口市海府路4号海口宾馆附楼2层</p>
            <p>本站信息仅供参考建 版权所有:红妆双美 https://www.hzshuangmei.com<br/>
                <a href="http://www.miitbeian.gov.cn/" rel="nofollow" target="_blank">琼ICP备17004048号-1</a> (海)医广[2017]第085号 <a href="//www.hzshuangmei.com/humans.txt" rel="nofollow" target="_blank"><img src="//img.hzshuangmei.com/pc/humanstxt-transparent-color.png" class="humanstxt"></a><br/>
                网站部分图文来源于网络，如有侵权，请联系我们 联系电话：0898-66156043</p>
        </div>
        <div class="middle"></div>
        <div class="right right1">
            <div class="right_t clearFix">
                <div class="clearFix">
                    <div class="ewm"></div>
                    <div>
                        <p class="fon1">微信扫一扫</p>

                        <p>1）获得最新优惠</p>

                        <p>2）在线实时咨询</p>

                        <p>3）专属服务通道</p>
                    </div>
                </div>

                <div class="clearFix">
                    <div class="f_phone"></div>
                    <div>
                        <p class="fon1">全国免费咨询热线</p>

                        <p class="fon2">0898-66156043</p>

                        <p class="fon3">咨询时间：8:00—20:00</p>
                    </div>
                </div>
            </div>
             <!--<div class="right_b">-->
                <!--<i></i><span>友情链接:</span>-->
                <!---->
                <!--<a href='https://www.honorreal.com/' target='_blank'>红瑞集团</a> /-->
                <!---->
                <!--<a href='https://www.hoozonspa.com' rel='nofollow' target='_blank'>红妆美容</a> /-->
                <!---->
                <!--<a href='http://www.yueyimei.com' target='_blank'>悦伊美</a> /-->
                <!---->
            <!--</div>-->
            <p class="copyright">Copyright © 2017 红妆双美 版权所有 违者必究 | <a href="/statement/copyright.html" rel="nofollow" target="_blank" rel="noopener">版权及隐私声明</a><br>
              设计,文案,技术等求职请投递至网络部root#hzwlb.org(#替换成@)</p>
        </div>
    </div>
</footer>
<!-- 右侧悬浮 开始 -->
<div class="yb_conct">
    <div class="yb_bar">
        <ul>
            <li class="yb_QQ"><a target="_blank" rel="noopener" href="javascript:void(0)" class="j-site-consult" title="立即咨询" rel="nofollow">立即咨询</a></li>
            <li class="yb_phone"><a target="_blank" rel="noopener" href="javascript:void(0)" class="j-site-consult" title="门店查询" rel="nofollow">门店查询</a></li>
            <li class="yb_top">返回顶部</li>
            <li class="yb_ercode" >微信扫一扫<br>
                <img class="hd_qr" src="https://img.hzshuangmei.com/pc/WeChatApplet.jpg" width="125" alt="关注微信小程序">
            </li>
        </ul>
    </div>
</div>
<!-- 结束 -->

</body>
<link rel="preload" href="https://js.hzshuangmei.com/pc/common.js" as="script" crossorigin>
<link rel="preload" href="https://js.hzshuangmei.com/pc/layer/layer.js" as="script" crossorigin>
<link rel="preload" href="https://js.hzshuangmei.com/pc/kst_popup.js" as="script" crossorigin>
<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/Swiper/3.4.2/js/swiper.min.js"></script>
<script src="https://js.hzshuangmei.com/pc/common.js" ></script>
<script src="https://js.hzshuangmei.com/pc/layer/layer.js"></script>
<script src="https://js.hzshuangmei.com/pc/kst_popup.js"></script>
 <!-- html5标签兼容ie低版本浏览器 -->
<!-- [if lt IE 9]>     -->
<script src="https://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<!-- <![endif] -->
<!-- 百度站内搜索 -->
<!-- <script type="text/javascript">(function(){document.write(unescape('%3Cdiv id="bdcs"%3E%3C/div%3E'));var bdcs = document.createElement('script');bdcs.type = 'text/javascript';bdcs.async = true;bdcs.src = '//znsv.baidu.com/customer_search/api/js?sid=5257607230163915007' + '&plate_url=' + encodeURIComponent(window.location.href) + '&t=' + Math.ceil(new Date()/3600000);var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(bdcs, s);})();</script> -->



</html>
