<?php  exit();
/*
Page: /houtai/sys_sql_query.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order by rand() limit 4' at line 1 <br />Error sql: <font color='red'>SELECT * FROM sm_archives,sm_addoncase where sm_archives.typeid =sm_addoncase.typeid and  order by rand() limit 4</font>
Time2017-11-11 17:08:09
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?typeid=43&maxpagesize=50&upnext=1
Error: Unknown column '$DedeMeValue' in 'where clause' <br />Error sql: <font color='red'>SELECT qiba.imgafter from `sm_addoncase` as qiba where qiba.typeid= $DedeMeValue LIMIT 0,1;</font>
Time2017-11-13 17:43:22
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?typeid=43&maxpagesize=50&upnext=1
Error: Unknown column 'a.id' in 'where clause' <br />Error sql: <font color='red'>SELECT a.imgafter FROM sm_addoncase AS a  
                              where a.id='' LIMIT 0,1;</font>
Time2017-11-13 17:52:58
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?typeid=43&maxpagesize=50&upnext=1
Error: Unknown column 'a.id' in 'where clause' <br />Error sql: <font color='red'>SELECT a.imgbefore FROM sm_addoncase AS a  
                              where a.id='43' LIMIT 0,1;</font>
Time2017-11-13 17:52:58
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?typeid=43&maxpagesize=50&upnext=1
Error: Unknown column 'a.id' in 'where clause' <br />Error sql: <font color='red'>SELECT a.imgafter FROM sm_addoncase AS a  
                              where a.id='' LIMIT 0,1;</font>
Time2017-11-13 17:52:58
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?typeid=43&maxpagesize=50&upnext=1
Error: Unknown column 'a.id' in 'where clause' <br />Error sql: <font color='red'>SELECT a.imgafter FROM sm_addoncase AS a  
                              where a.id='' LIMIT 0,1;</font>
Time2017-11-13 17:53:41
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?typeid=43&maxpagesize=50&upnext=1
Error: Unknown column 'a.id' in 'where clause' <br />Error sql: <font color='red'>SELECT a.imgbefore FROM sm_addoncase AS a  
                              where a.id='43' LIMIT 0,1;</font>
Time2017-11-13 17:53:41
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?typeid=43&maxpagesize=50&upnext=1
Error: Unknown column 'a.id' in 'where clause' <br />Error sql: <font color='red'>SELECT a.imgafter FROM sm_addoncase AS a  
                              where a.id='' LIMIT 0,1;</font>
Time2017-11-13 17:53:41
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?typeid=43&maxpagesize=50&upnext=1
Error: Unknown column 'a.id' in 'where clause' <br />Error sql: <font color='red'>SELECT a.imgafter FROM sm_addoncase AS a  
                              where a.id='1' LIMIT 0,1;</font>
Time2017-11-13 17:54:45
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?typeid=43&maxpagesize=50&upnext=1
Error: Unknown column 'a.id' in 'where clause' <br />Error sql: <font color='red'>SELECT a.imgbefore FROM sm_addoncase AS a  
                              where a.id='1' LIMIT 0,1;</font>
Time2017-11-13 17:54:45
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?typeid=43&maxpagesize=50&upnext=1
Error: Unknown column 'a.id' in 'where clause' <br />Error sql: <font color='red'>SELECT a.imgafter FROM sm_addoncase AS a  
                              where a.id='1' LIMIT 0,1;</font>
Time2017-11-13 17:54:45
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?typeid=43&maxpagesize=50&upnext=1
Error: Unknown column 'a.id' in 'where clause' <br />Error sql: <font color='red'>SELECT a.imgafter FROM sm_addoncase AS a  
                              where a.id='1' LIMIT 0,1;</font>
Time2017-11-13 17:55:10
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?typeid=43&maxpagesize=50&upnext=1
Error: Unknown column 'a.id' in 'where clause' <br />Error sql: <font color='red'>SELECT a.imgbefore FROM sm_addoncase AS a  
                              where a.id='1' LIMIT 0,1;</font>
Time2017-11-13 17:55:10
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?typeid=43&maxpagesize=50&upnext=1
Error: Unknown column 'a.id' in 'where clause' <br />Error sql: <font color='red'>SELECT a.imgafter FROM sm_addoncase AS a  
                              where a.id='1' LIMIT 0,1;</font>
Time2017-11-13 17:55:10
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?typeid=22&maxpagesize=50&upnext=1
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where a.typeid =b.typeid and a.typeid='43' order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT  * FROM sm_archives AS a,sm_addoncase AS b group by typeid
             where a.typeid =b.typeid and a.typeid='43' order by rand() limit 4 </font>
Time2017-11-14 15:52:20
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?typeid=22&maxpagesize=50&upnext=1
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where a.typeid =b.typeid and a.typeid='43' order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT  * FROM sm_archives AS a,sm_addoncase AS b group by typeid
             where a.typeid =b.typeid and a.typeid='43' order by rand() limit 4 </font>
Time2017-11-14 15:53:03
*/
?>
<?php  exit();
/*
Page: /houtai/sys_sql_query.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where a.typeid =b.typeid and a.typeid=43 order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT  * FROM sm_archives AS a,sm_addoncase AS b group by a.typeid
             where a.typeid =b.typeid and a.typeid=43 order by rand() limit 4</font>
Time2017-11-14 15:53:41
*/
?>
<?php  exit();
/*
Page: /houtai/sys_sql_query.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where a.typeid =b.typeid and a.typeid=43 order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT  * FROM sm_archives AS a,sm_addoncase AS b group by a.id
             where a.typeid =b.typeid and a.typeid=43 order by rand() limit 4</font>
Time2017-11-14 15:58:55
*/
?>
<?php  exit();
/*
Page: /houtai/sys_sql_query.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where a.typeid =b.typeid and a.typeid=43 order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT  * FROM sm_archives AS a,sm_addoncase AS b group by a.id
             where a.typeid =b.typeid and a.typeid=43 order by rand() limit 4</font>
Time2017-11-14 15:58:56
*/
?>
<?php  exit();
/*
Page: /houtai/sys_sql_query.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where a.typeid =b.typeid and a.typeid=43 order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT  * FROM sm_archives AS a,sm_addoncase AS b group by a.id
             where a.typeid =b.typeid and a.typeid=43 order by rand() limit 4</font>
Time2017-11-14 15:58:57
*/
?>
<?php  exit();
/*
Page: /houtai/sys_sql_query.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where a.typeid =b.typeid and a.typeid=43 order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT  * FROM sm_archives AS a,sm_addoncase AS b group by a.id
             where a.typeid =b.typeid and a.typeid=43 order by rand() limit 4</font>
Time2017-11-14 15:58:57
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?typeid=22&maxpagesize=50&upnext=1
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where a.typeid =b.typeid and a.typeid='43' order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT  * FROM sm_archives AS a,sm_addoncase AS b group by a.typeid
             where a.typeid =b.typeid and a.typeid='43' order by rand() limit 4 </font>
Time2017-11-14 16:03:53
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?gotype=mkallct&uppage=0&maxpagesize=50&typeid=0&pageno=24&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT * FROM sm_archives AS a,sm_addoncase AS b  
             where a.id =b.aid and a.typeid in ( 46,47,48, ) order by rand() limit 4 </font>
Time2017-12-02 16:13:24
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?gotype=mkallct&uppage=0&maxpagesize=50&typeid=0&pageno=25&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT * FROM sm_archives AS a,sm_addoncase AS b  
             where a.id =b.aid and a.typeid in ( 46,47,48, ) order by rand() limit 4 </font>
Time2017-12-02 16:13:24
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?gotype=mkallct&uppage=0&maxpagesize=50&typeid=0&pageno=24&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT * FROM sm_archives AS a,sm_addoncase AS b  
             where a.id =b.aid and a.typeid in ( 46,47,48, ) order by rand() limit 4 </font>
Time2017-12-02 16:18:18
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?gotype=mkallct&uppage=0&maxpagesize=50&typeid=0&pageno=25&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT * FROM sm_archives AS a,sm_addoncase AS b  
             where a.id =b.aid and a.typeid in ( 46,47,48, ) order by rand() limit 4 </font>
Time2017-12-02 16:18:18
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=45&startdd=20&pagesize=20&seltime=0&sstime=1512204063&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where c.id='41' LIMIT 0,1' at line 2 <br />Error sql: <font color='red'>SELECT * FROM #__archives AS c  
                              where c.id='41' LIMIT 0,1;</font>
Time2017-12-02 16:41:03
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=45&startdd=20&pagesize=20&seltime=0&sstime=1512204063&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where c.id='42' LIMIT 0,1' at line 2 <br />Error sql: <font color='red'>SELECT * FROM #__archives AS c  
                              where c.id='42' LIMIT 0,1;</font>
Time2017-12-02 16:41:03
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=45&startdd=20&pagesize=20&seltime=0&sstime=1512205674&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where c.id='41' LIMIT 0,1' at line 2 <br />Error sql: <font color='red'>SELECT * FROM #__archives AS c  
                              where c.id='41' LIMIT 0,1;</font>
Time2017-12-02 17:07:54
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=45&startdd=20&pagesize=20&seltime=0&sstime=1512205674&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where c.id='42' LIMIT 0,1' at line 2 <br />Error sql: <font color='red'>SELECT * FROM #__archives AS c  
                              where c.id='42' LIMIT 0,1;</font>
Time2017-12-02 17:07:54
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=45&startdd=20&pagesize=20&seltime=0&sstime=1512205727&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where c.id='41' LIMIT 0,1' at line 2 <br />Error sql: <font color='red'>SELECT * FROM #__archives AS c  
                              where c.id='41' LIMIT 0,1;</font>
Time2017-12-02 17:08:47
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=45&startdd=20&pagesize=20&seltime=0&sstime=1512205727&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where c.id='42' LIMIT 0,1' at line 2 <br />Error sql: <font color='red'>SELECT * FROM #__archives AS c  
                              where c.id='42' LIMIT 0,1;</font>
Time2017-12-02 17:08:47
*/
?>
<?php  exit();
/*
Page: /houtai/archives_edit.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where c.id='42' LIMIT 0,1' at line 2 <br />Error sql: <font color='red'>SELECT * FROM #__archives AS c  
                              where c.id='42' LIMIT 0,1;</font>
Time2017-12-02 17:13:59
*/
?>
<?php  exit();
/*
Page: /houtai/task_do.php?typeid=36&aid=&dopost=makeprenext&nextdo=makeindex,makeparenttype
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where c.id='41' LIMIT 0,1' at line 2 <br />Error sql: <font color='red'>SELECT * FROM #__archives AS c  
                              where c.id='41' LIMIT 0,1;</font>
Time2017-12-02 17:13:59
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=45&startdd=20&pagesize=20&seltime=0&sstime=1512206044&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where c.id='41' LIMIT 0,1' at line 2 <br />Error sql: <font color='red'>SELECT * FROM #__archives AS c  
                              where c.id='41' LIMIT 0,1;</font>
Time2017-12-02 17:14:05
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=45&startdd=20&pagesize=20&seltime=0&sstime=1512206044&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where c.id='42' LIMIT 0,1' at line 2 <br />Error sql: <font color='red'>SELECT * FROM #__archives AS c  
                              where c.id='42' LIMIT 0,1;</font>
Time2017-12-02 17:14:05
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=45&startdd=20&pagesize=20&seltime=0&sstime=1512206199&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where c.id='41' LIMIT 0,1' at line 2 <br />Error sql: <font color='red'>SELECT * FROM #__archives AS c  
                              where c.id='41' LIMIT 0,1;</font>
Time2017-12-02 17:16:40
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=45&startdd=20&pagesize=20&seltime=0&sstime=1512206199&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where c.id='42' LIMIT 0,1' at line 2 <br />Error sql: <font color='red'>SELECT * FROM #__archives AS c  
                              where c.id='42' LIMIT 0,1;</font>
Time2017-12-02 17:16:40
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=45&startdd=20&pagesize=20&seltime=0&sstime=1512206304&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where c.id='41' LIMIT 0,1' at line 2 <br />Error sql: <font color='red'>SELECT * FROM #__archives AS c  
                              where c.id='41' LIMIT 0,1;</font>
Time2017-12-02 17:18:24
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=45&startdd=20&pagesize=20&seltime=0&sstime=1512206304&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where c.id='42' LIMIT 0,1' at line 2 <br />Error sql: <font color='red'>SELECT * FROM #__archives AS c  
                              where c.id='42' LIMIT 0,1;</font>
Time2017-12-02 17:18:24
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=45&startdd=20&pagesize=20&seltime=0&sstime=1512206441&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where c.id='41' LIMIT 0,1' at line 2 <br />Error sql: <font color='red'>SELECT * FROM #__archives AS c  
                              where c.id='41' LIMIT 0,1;</font>
Time2017-12-02 17:20:41
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=45&startdd=20&pagesize=20&seltime=0&sstime=1512206441&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where c.id='42' LIMIT 0,1' at line 2 <br />Error sql: <font color='red'>SELECT * FROM #__archives AS c  
                              where c.id='42' LIMIT 0,1;</font>
Time2017-12-02 17:20:41
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=45&startdd=20&pagesize=20&seltime=0&sstime=1512206553&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where c.id='41' LIMIT 0,1' at line 2 <br />Error sql: <font color='red'>SELECT * FROM #__archives AS c  
                              where c.id='41' LIMIT 0,1;</font>
Time2017-12-02 17:22:34
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=45&startdd=20&pagesize=20&seltime=0&sstime=1512206553&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where c.id='42' LIMIT 0,1' at line 2 <br />Error sql: <font color='red'>SELECT * FROM #__archives AS c  
                              where c.id='42' LIMIT 0,1;</font>
Time2017-12-02 17:22:34
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=45&startdd=20&pagesize=20&seltime=0&sstime=1512206815&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where c.id='41' LIMIT 0,1' at line 2 <br />Error sql: <font color='red'>SELECT * FROM #__archives AS c  
                              where c.id='41' LIMIT 0,1;</font>
Time2017-12-02 17:26:55
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=45&startdd=20&pagesize=20&seltime=0&sstime=1512206815&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where c.id='42' LIMIT 0,1' at line 2 <br />Error sql: <font color='red'>SELECT * FROM #__archives AS c  
                              where c.id='42' LIMIT 0,1;</font>
Time2017-12-02 17:26:55
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=45&startdd=20&pagesize=20&seltime=0&sstime=1512206844&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where c.id='41' LIMIT 0,1' at line 2 <br />Error sql: <font color='red'>SELECT * FROM #__archives AS c  
                              where c.id='41' LIMIT 0,1;</font>
Time2017-12-02 17:27:24
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=45&startdd=20&pagesize=20&seltime=0&sstime=1512206844&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where c.id='42' LIMIT 0,1' at line 2 <br />Error sql: <font color='red'>SELECT * FROM #__archives AS c  
                              where c.id='42' LIMIT 0,1;</font>
Time2017-12-02 17:27:24
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=45&startdd=20&pagesize=20&seltime=0&sstime=1512207000&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where c.id='41' LIMIT 0,1' at line 2 <br />Error sql: <font color='red'>SELECT * FROM #__archives AS c  
                              where c.id='41' LIMIT 0,1;</font>
Time2017-12-02 17:30:00
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=45&startdd=20&pagesize=20&seltime=0&sstime=1512207000&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where c.id='42' LIMIT 0,1' at line 2 <br />Error sql: <font color='red'>SELECT * FROM #__archives AS c  
                              where c.id='42' LIMIT 0,1;</font>
Time2017-12-02 17:30:00
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=45&startdd=20&pagesize=20&seltime=0&sstime=1512207147&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where c.id='41' LIMIT 0,1' at line 2 <br />Error sql: <font color='red'>SELECT * FROM #__archives AS c  
                              where c.id='41' LIMIT 0,1;</font>
Time2017-12-02 17:32:28
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=45&startdd=20&pagesize=20&seltime=0&sstime=1512207147&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where c.id='42' LIMIT 0,1' at line 2 <br />Error sql: <font color='red'>SELECT * FROM #__archives AS c  
                              where c.id='42' LIMIT 0,1;</font>
Time2017-12-02 17:32:28
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=45&startdd=20&pagesize=20&seltime=0&sstime=1512207216&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where id='41' LIMIT 0,1' at line 2 <br />Error sql: <font color='red'>SELECT * FROM #__archives   
                              where id='41' LIMIT 0,1;</font>
Time2017-12-02 17:33:36
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=45&startdd=20&pagesize=20&seltime=0&sstime=1512207216&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where id='42' LIMIT 0,1' at line 2 <br />Error sql: <font color='red'>SELECT * FROM #__archives   
                              where id='42' LIMIT 0,1;</font>
Time2017-12-02 17:33:36
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=45&startdd=20&pagesize=20&seltime=0&sstime=1512207282&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where id='41' LIMIT 0,1' at line 2 <br />Error sql: <font color='red'>SELECT * FROM #__archives   
                              where id='41' LIMIT 0,1;</font>
Time2017-12-02 17:34:43
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?endid=0&startid=-1&typeid=0&totalnum=45&startdd=20&pagesize=20&seltime=0&sstime=1512207282&stime=&etime=&uptype=&mkvalue=0&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where id='42' LIMIT 0,1' at line 2 <br />Error sql: <font color='red'>SELECT * FROM #__archives   
                              where id='42' LIMIT 0,1;</font>
Time2017-12-02 17:34:43
*/
?>
<?php  exit();
/*
Page: /houtai/sys_sql_query.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where id=41' at line 2 <br />Error sql: <font color='red'>SELECT * FROM #__archives   
                              where id=41</font>
Time2017-12-02 17:35:16
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?typeid=0&startid=&endid=&pagesize=20
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')  order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT * FROM sm_archives AS a,sm_addoncase AS b  
           where a.id =b.aid and a.typeid in ( 46,47,48, )  order by rand() limit 4 </font>
Time2017-12-02 18:04:21
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?gotype=&uppage=0&maxpagesize=50&typeid=0&pageno=24&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT * FROM sm_archives AS a,sm_addoncase AS b  
             where a.id =b.aid and a.typeid in ( 46,47,48, ) order by rand() limit 4 </font>
Time2017-12-04 10:08:47
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?gotype=&uppage=0&maxpagesize=50&typeid=0&pageno=25&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT * FROM sm_archives AS a,sm_addoncase AS b  
             where a.id =b.aid and a.typeid in ( 46,47,48, ) order by rand() limit 4 </font>
Time2017-12-04 10:08:47
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?typeid=0&startid=&endid=&pagesize=20
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')  order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT * FROM sm_archives AS a,sm_addoncase AS b  
           where a.id =b.aid and a.typeid in ( 46,47,48, )  order by rand() limit 4 </font>
Time2017-12-04 10:10:28
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?gotype=&uppage=0&maxpagesize=50&typeid=0&pageno=24&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT * FROM sm_archives AS a,sm_addoncase AS b  
             where a.id =b.aid and a.typeid in ( 46,47,48, ) order by rand() limit 4 </font>
Time2017-12-04 11:22:18
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?gotype=&uppage=0&maxpagesize=50&typeid=0&pageno=25&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT * FROM sm_archives AS a,sm_addoncase AS b  
             where a.id =b.aid and a.typeid in ( 46,47,48, ) order by rand() limit 4 </font>
Time2017-12-04 11:22:18
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?gotype=&uppage=0&maxpagesize=50&typeid=0&pageno=24&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT * FROM sm_archives AS a,sm_addoncase AS b  
             where a.id =b.aid and a.typeid in ( 46,47,48, ) order by rand() limit 4 </font>
Time2017-12-04 13:41:58
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?gotype=&uppage=0&maxpagesize=50&typeid=0&pageno=25&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT * FROM sm_archives AS a,sm_addoncase AS b  
             where a.id =b.aid and a.typeid in ( 46,47,48, ) order by rand() limit 4 </font>
Time2017-12-04 13:41:58
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?gotype=&uppage=0&maxpagesize=50&typeid=0&pageno=24&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT * FROM sm_archives AS a,sm_addoncase AS b  
             where a.id =b.aid and a.typeid in ( 46,47,48, ) order by rand() limit 4 </font>
Time2017-12-04 13:42:57
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?gotype=&uppage=0&maxpagesize=50&typeid=0&pageno=25&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT * FROM sm_archives AS a,sm_addoncase AS b  
             where a.id =b.aid and a.typeid in ( 46,47,48, ) order by rand() limit 4 </font>
Time2017-12-04 13:42:57
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?gotype=&uppage=0&maxpagesize=50&typeid=0&pageno=24&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT * FROM sm_archives AS a,sm_addoncase AS b  
             where a.id =b.aid and a.typeid in ( 46,47,48, ) order by rand() limit 4 </font>
Time2017-12-04 13:46:41
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?gotype=&uppage=0&maxpagesize=50&typeid=0&pageno=25&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT * FROM sm_archives AS a,sm_addoncase AS b  
             where a.id =b.aid and a.typeid in ( 46,47,48, ) order by rand() limit 4 </font>
Time2017-12-04 13:46:41
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?typeid=0&startid=&endid=&pagesize=20
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')  order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT * FROM sm_archives AS a,sm_addoncase AS b  
           where a.id =b.aid and a.typeid in ( 46,47,48, )  order by rand() limit 4 </font>
Time2017-12-04 13:50:39
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?typeid=0&startid=&endid=&pagesize=20
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')  order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT * FROM sm_archives AS a,sm_addoncase AS b  
           where a.id =b.aid and a.typeid in ( 46,47,48, )  order by rand() limit 4 </font>
Time2017-12-04 13:56:44
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?gotype=&uppage=0&maxpagesize=50&typeid=0&pageno=24&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT * FROM sm_archives AS a,sm_addoncase AS b  
             where a.id =b.aid and a.typeid in ( 46,47,48, ) order by rand() limit 4 </font>
Time2017-12-04 15:47:12
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?gotype=&uppage=0&maxpagesize=50&typeid=0&pageno=25&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT * FROM sm_archives AS a,sm_addoncase AS b  
             where a.id =b.aid and a.typeid in ( 46,47,48, ) order by rand() limit 4 </font>
Time2017-12-04 15:47:13
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?gotype=&uppage=0&maxpagesize=50&typeid=0&pageno=24&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT * FROM sm_archives AS a,sm_addoncase AS b  
             where a.id =b.aid and a.typeid in ( 46,47,48, ) order by rand() limit 4 </font>
Time2017-12-04 15:51:32
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?gotype=&uppage=0&maxpagesize=50&typeid=0&pageno=25&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT * FROM sm_archives AS a,sm_addoncase AS b  
             where a.id =b.aid and a.typeid in ( 46,47,48, ) order by rand() limit 4 </font>
Time2017-12-04 15:51:32
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?gotype=&uppage=0&maxpagesize=50&typeid=0&pageno=24&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT * FROM sm_archives AS a,sm_addoncase AS b  
             where a.id =b.aid and a.typeid in ( 46,47,48, ) order by rand() limit 4 </font>
Time2017-12-04 15:54:47
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?gotype=&uppage=0&maxpagesize=50&typeid=0&pageno=25&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT * FROM sm_archives AS a,sm_addoncase AS b  
             where a.id =b.aid and a.typeid in ( 46,47,48, ) order by rand() limit 4 </font>
Time2017-12-04 15:54:47
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?typeid=0&startid=&endid=&pagesize=20
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')  order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT * FROM sm_archives AS a,sm_addoncase AS b  
           where a.id =b.aid and a.typeid in ( 46,47,48, )  order by rand() limit 4 </font>
Time2017-12-04 16:36:37
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_archives_action.php?typeid=0&startid=&endid=&pagesize=20
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')  order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT * FROM sm_archives AS a,sm_addoncase AS b  
           where a.id =b.aid and a.typeid in ( 46,47,48, )  order by rand() limit 4 </font>
Time2017-12-04 16:38:53
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?gotype=&uppage=0&maxpagesize=50&typeid=0&pageno=24&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT * FROM sm_archives AS a,sm_addoncase AS b  
             where a.id =b.aid and a.typeid in ( 46,47,48, ) order by rand() limit 4 </font>
Time2017-12-05 09:28:37
*/
?>
<?php  exit();
/*
Page: /houtai/makehtml_list_action.php?gotype=&uppage=0&maxpagesize=50&typeid=0&pageno=25&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') order by rand() limit 4' at line 2 <br />Error sql: <font color='red'>SELECT * FROM sm_archives AS a,sm_addoncase AS b  
             where a.id =b.aid and a.typeid in ( 46,47,48, ) order by rand() limit 4 </font>
Time2017-12-05 09:28:38
*/
?>
