<!DOCTYPE html>
<html lang="zh-cmn-Hans">
<head>
    <!-- Make 2018-04-19 16:50:03 -->
<!-- Make 1524127803 -->
<meta charset="UTF-8">
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
<meta name="renderer" content="webkit"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
<meta name=applicable-device content="pc">
<meta http-equiv="Cache-Control" content="no-transform"/>
<meta http-equiv="Cache-Control" content="no-siteapp"/>
<meta name="baidu-site-verification" content="99J7V1k1Vz" />
<meta name="google-site-verification" content="Odmo8X4zeUG1WPcCrCAueZz-dyBPFBs4Zqlb9FBT5z4" />
<meta http-equiv="Access-Control-Allow-Origin" content="*" />
<!-- Global site tag (gtag.js) - Google Analytics -->
<!-- <script async src="https://www.googletagmanager.com/gtag/js?id=UA-114904919-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-114904919-2');
</script> -->

    <title>乔雅登玻尿酸_玻尿酸_海南红妆时尚双美整形美容连锁</title>
    <meta property="og:type" content="article"/>
    <meta property="article:author" content="红妆双美"/>
    <meta property="article:published_time" content="2018-04-14T17:46:42+08:00" />
    <meta name="keywords" content="海口红妆,乔雅登玻尿酸，抚平皱纹，无痕微创，"/>
    <meta name="description" content="乔雅登玻尿酸，悄然心动 永葆青春的秘密。乔雅登玻尿酸抚平皱纹，无痕微创，减龄秘籍，安全塑美。采用独有的“HYLACROSS”技术， 区别于其他玻尿酸 “颗粒状”形态，生 产出高浓度"/>
    <meta property="article:tag" content="海口红妆,乔雅登玻尿酸，抚平皱纹，无痕微创，">
    <link rel="canonical" href="https://www.hzshuangmei.com/projects/ha/qydbns.html" />
    <link rel="alternate" media="only screen and(max-width: 640px)" href="https://m.hzshuangmei.com/projects/ha/qydbns.html" >
    <!-- Pre for optimization -->
<link rel="dns-prefetch" href="https://cdn.bootcss.com">
<link rel="dns-prefetch" href="https://uploads.hzshuangmei.com">
<link rel="dns-prefetch" href="https://img.hzshuangmei.com">
<link rel="dns-prefetch" href="https://css.hzshuangmei.com">
<link rel="dns-prefetch" href="https://js.hzshuangmei.com">
<link rel="dns-prefetch" href="https://pv.kuaishang.cn">
<link rel="dns-prefetch" href="https://z8.cnzz.com">
<link rel="dns-prefetch" href="https://s19.cnzz.com">
<link rel="dns-prefetch" href="https://tag.baidu.com">
<link rel="dns-prefetch" href="https://sp0.baidu.com">
<link rel="preload" href="https://css.hzshuangmei.com/pc/common.css" as="style" crossorigin />
<link rel="preload" href="https://img.hzshuangmei.com/pc/favicon.ico" as="image" type="image/x-icon" crossorigin />
<!-- Style for the page-->
<link rel="stylesheet" href="https://cdn.bootcss.com/Swiper/3.4.2/css/swiper.min.css"/>
<link rel="stylesheet" href="https://css.hzshuangmei.com/pc/common.css"/>
<link rel="stylesheet" href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" >
<!-- favicon.ico -->
<link rel="icon" href="https://img.hzshuangmei.com/pc/favicon.ico" type="image/x-icon"/>
<link rel="shortcut icon" href="https://img.hzshuangmei.com/pc/favicon.ico" type="image/x-icon"/>
<!-- humanstxt -->
<link rel="author" href="https://www.hzshuangmei.com/humans.txt" />
<link rel="preload" as=image  href="https://img.hzshuangmei.com/pc/kst/default.png">
<link rel="prefetch" src="https://img.hzshuangmei.com/pc/kst/default.png">
<link rel="prerender" src="https://img.hzshuangmei.com/pc/kst/default.png">
<link rel="prefetch" src="https://img.hzshuangmei.com/pc/kst/qydbns.png">
<link rel="prerender" src="https://img.hzshuangmei.com/pc/kst/qydbns.png">
<link rel="preload" as=image  href="https://img.hzshuangmei.com/pc/kst/qydbns.png">

     <link rel="preload" href="https://css.hzshuangmei.com/pc/tjb.css" as="style" crossorigin />
    <link rel="stylesheet" href="https://css.hzshuangmei.com/pc/tjb.css"/>
    <meta content="设计王璠,前端陈晓珍,文案黄晓慧/" name="author" />
<link href="https://css.hzshuangmei.com/pc/qydbns/theme.css" rel="stylesheet" />
<link href="https://cdn.bootcss.com/animate.css/3.5.2/animate.min.css" rel="stylesheet" />

<body>
<header>
    <div class="top">
        <div class="shuang_m1 clearFix">
            <div class="top_l">
                <!--<span>香港红瑞集团 旗下品牌 海南红妆双美连锁</span>-->
                <img src="https://img.hzshuangmei.com/pc/tl_logo.png" alt="logo" />|<span>美丽时间：周一周日9点--21点</span>
            </div>
            <!-- 增加百度站内搜索 -->
            <div class="top_c">
                <div class="search_box">
                    <form action="https://www.hzshuangmei.com/search/" target="_blank" autocomplete="off" id="bdcs-search-form" class="site-search-form">
                        <input type="hidden" name="s" value="5257607230163915007">
                         <input type="hidden" name="entry" value="1">
                        <input type="text" placeholder="请输入您要搜索的内容..." id="bdcsMain" name="q">
                        <button type="submit" id="bdcs-search-form-submit"></button>
                    </form>
                </div>
            </div>
                        <!-- 增加百度站内搜索 -->
            <div class="top_r">
                <a href="" class="pad_r"><i class="tel"></i><span>0898-66156043</span></a>
                <span>关注我们：</span>
                <a href="" class="pad_l"><i class="wbo"></i></a>
                <a href=""><i class="wxin"></i></a>
                <a href=""><i class="qq"></i></a>
            </div>
        </div>
    </div>
    <div class="sm_logo">
        <a href="/"><img src="https://img.hzshuangmei.com/pc/h_logo.png" alt=""/></a>
    </div>
</header>
<nav id="nav">
    <ul class="shuang_m1 nav_ul">
        <li class="nav_list">
            <a href="/" class="nav_link" target="_blank" rel="noopener">
                <span>首 页</span><br/>
                <span>Home</span>
            </a>
        </li>
        <li class="nav_list">
            <a href="/brand" class="nav_link bor_r" target="_blank" rel="noopener">
                <span>品 牌</span><br/>
                <span>brands</span>
            </a>
        </li>
        <li class="nav_list">
            <a href="/projects" class="nav_link bor_l bor_r" target="_blank" rel="noopener">
                <span>项 目</span><br/>
                <span>projects</span>
            </a>
            <div class="clearFix" id="project">
                <ul>
                    <li>
                        <h5><a href="/projects/tattoo/" target="_blank" rel="noopener">医学纹绣</a></h5>
                    </li>
                    <!--              <li>
                        <a href="/projects/tattoo/yanxian.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P4041610355P.jpg" alt="红妆艺术美瞳线"/>
                            <p><i></i><span>红妆艺术美瞳线</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/tattoo/hsbyjwm.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404160923556.jpg" alt="韩式半永久纹眉"/>
                            <p><i></i><span>韩式半永久纹眉</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/tattoo/xwx.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/img/180331/1-1P3311106490-L.jpg" alt="洗纹绣"/>
                            <p><i></i><span>洗纹绣</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/tattoo/xwx.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/img/180331/1-1P3311106490-L.jpg" alt="洗纹绣"/>
                            <p><i></i><span>洗纹绣</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/tattoo/wash.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180222/1-1P222110205243.jpg" alt="激光洗纹绣"/>
                            <p><i></i><span>激光洗纹绣</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/tattoo/hsbyjwm.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404160923556.jpg" alt="韩式半永久纹眉"/>
                            <p><i></i><span>韩式半永久纹眉</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button">-->
                    <!--<a href="/projects" target="_blank" rel="noopener">查看更多</a>-->
                    <!--</li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/eye/" target="_blank" rel="noopener">眼部整形</a></h5>
                    </li>
                    <!--   <li>
                        <a href="/projects/eye/qmtm.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404161354458.jpg" alt=""/>
                            <p><i></i><span>切眉提眉术</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/eye/slxc.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180222/1-1P22216455E61.jpg" alt=""/>
                            <p><i></i><span>上睑下垂</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/eye/yandai.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404160Q03S.jpg" alt=""/>
                            <p><i></i><span>无痕祛眼袋</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/eye/yandai.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404160Q03S.jpg" alt="无痕祛眼袋"/>
                            <p><i></i><span>无痕祛眼袋</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/eye/slxc.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180222/1-1P22216455E61.jpg" alt="上睑下垂"/>
                            <p><i></i><span>上睑下垂</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/eye/hzyj.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180206/1-1P206100342338.jpg" alt="红妆孕睫术"/>
                            <p><i></i><span>红妆孕睫术</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/nose/" target="_blank" rel="noopener">鼻部整形</a></h5>
                    </li>
                    <!--              <li>
                        <a href="/projects/nose/lineeaglenose.html" target="_blank" rel="noopener">
                        <img src="https://uploads.hzshuangmei.com/180109/1-1P10916214I29.jpg" alt=""/>
                            <p><i></i><span>线雕隆鼻</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/nose/heben.html" target="_blank" rel="noopener">
                        <img src="https://uploads.hzshuangmei.com/180109/1-1P109162114246.jpg" alt=""/>
                            <p><i></i><span>红妆赫本软骨鼻</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/nose/longbijiage.html" target="_blank" rel="noopener">
                        <img src="https://uploads.hzshuangmei.com/180209/1-1P2091524433K.jpg" alt=""/>
                            <p><i></i><span>隆鼻价格</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/nose/longbijiage.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180209/1-1P2091524433K.jpg" alt="隆鼻价格"/>
                            <p><i></i><span>隆鼻价格</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/nose/hzbbqb.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180208/1-1P20QZ14O61.jpg" alt="红妆芭比翘鼻"/>
                            <p><i></i><span>红妆芭比翘鼻</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/nose/nose.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180109/1-1P109161Fc42.jpg" alt="全立体鼻缩窄术"/>
                            <p><i></i><span>全立体鼻缩窄术</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/face/" target="_blank" rel="noopener">面部整形</a></h5>
                    </li>
                    <!--                <li class="star">
                        <a href="/projects/zhifang/ztzfmd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180109/1-1P109162329454.jpg" alt=""/>
                            <p><i></i><span>自体脂肪面雕</span></p>
                        </a>
                    </li><li class="star">
                        <a href="/projects/xiaba/vlmxd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P40416062R04.jpg" alt=""/>
                            <p><i></i><span>v立美线雕</span></p>
                        </a>
                    </li><li class="star">
                        <a href="/projects/face/zitizhifang.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180208/1-1P20Q54P4G4.jpg" alt=""/>
                            <p><i></i><span>自体脂肪面部填充</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/face/zitizhifang.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180208/1-1P20Q54P4G4.jpg" alt="自体脂肪面部填充"/>
                            <p><i></i><span>自体脂肪面部填充</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/xiaba/vlmxd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P40416062R04.jpg" alt="v立美线雕"/>
                            <p><i></i><span>v立美线雕</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/zhifang/ztzfmd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180109/1-1P109162329454.jpg" alt="自体脂肪面雕"/>
                            <p><i></i><span>自体脂肪面雕</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/skin/" target="_blank" rel="noopener">皮肤美容</a></h5>
                    </li>
                    <!--                 <li>
                        <a href="/projects/qudou/duoweiqd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180222/1-1P222143953U0.jpg" alt=""/>
                            <p><i></i><span>红妆多维祛痘</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/quban/xpmqb.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180328/1-1P32Q356202V.jpg" alt=""/>
                            <p><i></i><span>红妆皮秒祛斑</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/skin/sgz.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180406/1-1P4061A303F6.jpg" alt=""/>
                            <p><i></i><span>水光针</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/quban/xpmqb.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180328/1-1P32Q356202V.jpg" alt="红妆皮秒祛斑"/>
                            <p><i></i><span>红妆皮秒祛斑</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/chuzhou/quzhou.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180212/1-1P212102446403.jpg" alt="除皱抗衰"/>
                            <p><i></i><span>除皱抗衰</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/quban/quban.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180312/1-1P3121601494G.jpg" alt="红妆祛斑"/>
                            <p><i></i><span>红妆祛斑</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/ha/" target="_blank" rel="noopener">玻尿酸</a></h5>
                    </li>
                    <!--                     <li>
                        <a href="/projects/ha/qydbns.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180208/1-1P20Q0501X26.jpg" alt=""/>
                            <p><i></i><span>乔雅登玻尿酸</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/ha/zhbns.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180109/1-1P109161SV57.jpg" alt=""/>
                            <p><i></i><span>综合玻尿酸</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/ha/restylane.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180413/1-1P413100FcV.jpg" alt=""/>
                            <p><i></i><span>瑞蓝玻尿酸</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/ha/restylane.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180413/1-1P413100FcV.jpg" alt="瑞蓝玻尿酸"/>
                            <p><i></i><span>瑞蓝玻尿酸</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/ha/bnsqflw.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180411/1-1P411140P9134.jpg" alt="玻尿酸祛除法令纹"/>
                            <p><i></i><span>玻尿酸祛除法令纹</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/ha/xbnsfet.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180322/1-1P322092GMV.jpg" alt="玻尿酸丰额头"/>
                            <p><i></i><span>玻尿酸丰额头</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/body/" target="_blank" rel="noopener">形体雕塑</a></h5>
                    </li>
                    <!-- <li>
                        <a href="/projects/body/sdlxz.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404161320X4.jpg" alt=""/>
                            <p><i></i><span>水动力吸脂</span></p>
                       </a>
                    </li> -->
                    <li>
                        <a href="/projects/body/sdlxz.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404161320X4.jpg" alt="水动力吸脂"/>
                            <p><i></i><span>水动力吸脂</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
            </div>
        </li>
        <li class="nav_list">
            <a href="/doctors" class="nav_link bor_l bor_r" target="_blank" rel="noopener">
                <span>专 家</span><br/>
                <span>experts</span>
            </a>
            <div id="expert">
                <ul>
                    <li>
                        <h5><a href="/doctors/surgery" target="_blank" rel="noopener">整形美容专家</a></h5>
                    </li>
                    <!--                     <li>
                        <a href="/plugin/view.php?aid=227" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180414/1-1P4140929454T.jpg" alt="薛开兴"/>
                            <p><span class="n_f">薛开兴</span><span class="n_b">整形外科院长</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=153" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180131/1-1P131093205432.jpg" alt="余志亮"/>
                            <p><span class="n_f">余志亮</span><span class="n_b">整形专家</span></p>
                            <i></i>
                        </a>
                    </li> -->
                    <li>
                        <a href="/doctors/surgery/guanhaitao.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180227/1-1P22G44625M2.jpg" alt="关海涛 "/>
                            <p><span class="n_f">关海涛 </span><span class="n_b">整形外科院长</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=176" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180131/1-1P1310U92D41.jpg" alt="朱红振"/>
                            <p><span class="n_f">朱红振</span><span class="n_b">整形外科院长</span></p>
                            <i></i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <h5><a href="/doctors/laser" target="_blank" rel="noopener">激光美容专家</a></h5>
                    </li>
                    <!--             <li>
                        <a href="/doctors/laser/lijie.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/171206/1-1G20611435D10.jpg" alt="李杰"/>
                            <p><span class="n_f">李杰</span><span class="n_b">光学美肤中心院长</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/doctors/laser/yzw.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180131/1-1P131104604521.jpg" alt="姚志文"/>
                            <p><span class="n_f">姚志文</span><span class="n_b">非手术面部年轻化专家</span></p>
                            <i></i>
                        </a>
                    </li> -->
                    <li>
                        <a href="/doctors/laser/lijie.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/171206/1-1G20611435D10.jpg" alt="李杰"/>
                            <p><span class="n_f">李杰</span><span class="n_b">光学美肤中心院长</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/doctors/laser/yzw.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180131/1-1P131104604521.jpg" alt="姚志文"/>
                            <p><span class="n_f">姚志文</span><span class="n_b">非手术面部年轻化专家</span></p>
                            <i></i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <h5><a href="/doctors/tattoo" target="_blank" rel="noopener">医学纹绣</a></h5>
                    </li>
                    <!--                    <li>
                        <a href="/plugin/view.php?aid=139" target="_blank" rel="noopener">
                    <img src="https://uploads.hzshuangmei.com/180117/1-1P11GF5391A.jpg" alt="杨小丽"/>
                            <p><span class="n_f">杨小丽</span><span class="n_b">纹饰指导师</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=136" target="_blank" rel="noopener">
                    <img src="https://uploads.hzshuangmei.com/180125/1-1P125154A1105.jpg" alt="高方云"/>
                            <p><span class="n_f">高方云</span><span class="n_b">纹饰指导师</span></p>
                            <i></i>
                        </a>
                    </li> -->
                    <li>
                        <a href="/plugin/view.php?aid=164" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180125/1-1P12515435J45.jpg" alt="冯晓琳"/>
                            <p><span class="n_f">冯晓琳</span><span class="n_b">纹饰技术总指导师</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=137" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180117/1-1P11GA95JV.jpg" alt="孟超"/>
                            <p><span class="n_f">孟超</span><span class="n_b">纹饰指导师</span></p>
                            <i></i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <h5><a href="/doctors" target="_blank" rel="noopener">特邀专家</a></h5>
                    </li>
                    <li>
                        <a href="/doctors/surgery/ljb.html" target="_blank" rel="noopener">
                             <img src="https://uploads.hzshuangmei.com/180131/1-1P131092S24W.jpg" alt="雷建波(客座)"/>
                            <p><span class="n_f">雷建波(客座)</span><span class="n_b">整形美容专家</span></p>
                            <i></i>
                        </a>
                    </li>
<li>
                        <a href="/doctors/surgery/liudalie.html" target="_blank" rel="noopener">
                             <img src="https://uploads.hzshuangmei.com/171223/1-1G223091J5950.jpg" alt="柳大烈(客座)"/>
                            <p><span class="n_f">柳大烈(客座)</span><span class="n_b">教授</span></p>
                            <i></i>
                        </a>
                    </li>

                </ul>
                <ul>
                    <li>
                        <h5 class="moon"><a href="/doctors" target="_blank" rel="noopener">每月专家</a></h5>
                    </li>
                    <li class="last-one">
                        <!--<a class="last-one" href="https://www.hzshuangmei.com/doctors/surgery/liudalie.html " target="_blank" rel="noopener">-->
                            <!--<img src="https://img.hzshuangmei.com/pc/nav_zhuanjial.jpg" alt=""/>-->
                        <!--</a>-->
                        <a class="last-one j-consult" href="javascript:void(0)"  target="_blank" rel="noopener nofollow">
                            <img src="https://img.hzshuangmei.com/pc/myzzj.jpg" alt=""/>
                        </a>
                    </li>
                </ul>
            </div>
        </li>
        <li class="nav_list">
            <a href="/cases" class="nav_link bor_l bor_r" target="_blank" rel="noopener">
                <span>真人秀</span><br/>
                <span>Show</span>
            </a>
        </li>
        <li class="nav_list">
            <a href="/news" class="nav_link bor_l" target="_blank" rel="noopener">
            <span>活 动</span><br/>
                <span>News</span>
            </a>
        </li>
    </ul>
</nav>

<div class="container banner">
	<div class="g-doc">
		<div class="content">
			<h1>
				<span class="sr-only">乔雅登玻尿酸</span></h1>
			<p class="sr-only">
				悄然心动 永葆青春的秘密</p>
			<p class="sr-only">
				<span>抚平皱纹</span> <span>无痕微创</span> <span>减龄秘籍</span> <span>安全塑美</span></p>
			<a class="j-consult consult" href="javascript:void(0);" rel="nofollow">点击咨询</a></div>
	</div>
</div>
<div class="conatiner m1">
	<div class="g-doc">
		<h2 class="wow fadeInUp">
			<span class="sr-only">什么是乔雅登玻尿酸?</span></h2>
		<div class="content wow fadeInUp">
			<div class="des">
				<p>
					<strong>美国FDA批准</strong><br />
					疗效可以维持一年以上的玻尿酸</p>
			</div>
			<div class="row f-cb">
				<div class="left wow fadeInLeft">
					<img alt="模特图" src="https://img.hzshuangmei.com/pc/qydbns/img1_1.jpg" /></div>
				<img alt="乔雅登玻尿酸" class="mid wow rollIn " src="https://img.hzshuangmei.com/pc/qydbns/img1_2.png" />
				<div class="right wow fadeInRight">
					<h3>
						乔雅登玻尿酸</h3>
					<p>
						采用独有的&ldquo;HYLACROSS&rdquo;技术， 区别于其他玻尿酸 &ldquo;颗粒状&rdquo;形态，生 产出高浓度、柔顺平滑的&ldquo;果冻状&rdquo;玻尿酸，具有不易被降解的特性。乔雅登比同体积的其它注射型玻尿酸多出35%的交联键，因此乔雅登玻尿酸注射效果可以在人体内保持12-18个月。</p>
				</div>
			</div>
			<a class="j-consult consult" href="javascript:void(0);" rel="nofollow">点击咨询</a></div>
	</div>
</div>
<div class="conatiner m2">
	<div class="g-doc">
		<h2 class="wow fadeInUp">
			<span class="sr-only">乔雅登玻尿酸的特点</span></h2>
		<div class="content wow fadeInUp">
			<p class="des">
				乔雅登玻尿酸被称为玻尿酸中的&ldquo;王者&rdquo;，为什么它被如此赞誉?</p>
			<div class="row">
				<div class="item ">
					<img alt="浓度高" src="https://img.hzshuangmei.com/pc/qydbns/img2_1.jpg" />
					<p class="num">
						1</p>
					<div>
						<h3>
							浓度高</h3>
						<div class="line">
							&nbsp;</div>
						<p>
							乔雅登不同在于普通玻尿酸构造，普通的玻尿酸是颗粒状，并在制造时筛出不同的分子大小，而乔雅登玻尿酸则是粘稠的流体，浓度较高。</p>
					</div>
				</div>
				<div class="item">
					<img alt="不含颗粒" src="https://img.hzshuangmei.com/pc/qydbns/img2_2.jpg" />
					<p class="num">
						2</p>
					<div>
						<h3>
							不含颗粒</h3>
						<div class="line">
							&nbsp;</div>
						<p>
							乔雅登在高科技工艺下生产出均质的不含颗粒的凝胶，并使其具有高度凝聚性的三维立体结构，凝胶柔顺平滑且不易被降解</p>
					</div>
				</div>
				<div class="item">
					<img alt="安全有效" src="https://img.hzshuangmei.com/pc/qydbns/img2_3.jpg" />
					<p class="num">
						3</p>
					<div>
						<h3>
							安全有效</h3>
						<div class="line">
							&nbsp;</div>
						<p>
							乔雅登注射凝胶所采用的玻尿酸 原材料是微生物发酵法制的，并非来源于动物体内，安全有效。</p>
					</div>
				</div>
				<div class="item">
					<img alt="容易注射" src="https://img.hzshuangmei.com/pc/qydbns/img2_4.jpg" />
					<p class="num">
						4</p>
					<div>
						<h3>
							容易注射</h3>
						<div class="line">
							&nbsp;</div>
						<p>
							注射乔雅登玻尿酸更加好推、而且疼痛感更低，乔雅登注射进皮肤后触感比较柔软，与皮肤组织更容易融合。</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="conatiner m3">
	<div class="g-doc">
		<h2 class="wow fadeInUp">
			<span class="sr-only">红妆乔雅登玻尿酸5大优势</span></h2>
		<div class="content">
			<div class="row wow fadeInLeft">
				<img alt="红妆代言人" src="https://img.hzshuangmei.com/pc/qydbns/bg3_1.jpg" />
				<div>
					<h3>
						<span class="sr-only">1</span>简单安全，快速有效</h3>
					<p>
						采用局部注射法，避免了手术风险，同时效果显现快速。</p>
				</div>
			</div>
			<div class="row even wow fadeInRight">
				<div>
					<h3>
						<span class="sr-only">2</span>填充均匀，效果自然</h3>
					<p>
						填充均匀，不会有棱状或颗粒状物质残留；注射后无 明显痕迹，效果自然。</p>
				</div>
				<img alt="红妆代言人" src="https://img.hzshuangmei.com/pc/qydbns/bg3_2.jpg" /></div>
			<div class="row wow fadeInLeft">
				<img alt="红妆代言人" src="https://img.hzshuangmei.com/pc/qydbns/bg3_3.jpg" />
				<div>
					<h3>
						<span class="sr-only">3</span>痛楚低</h3>
					<p>
						如打针一样，局部仅有微胀微痛感。</p>
				</div>
			</div>
			<div class="row even wow fadeInRight">
				<div class="four">
					<h3>
						<span class="sr-only">4</span>安全舒适</h3>
					<p>
						高度的生物相容性、小的组织排斥性，在注射过程 中，引发炎症反应的可能性非常低。</p>
				</div>
				<img alt="红妆代言人" src="https://img.hzshuangmei.com/pc/qydbns/bg3_4.jpg" /></div>
			<div class="row wow fadeInLeft">
				<img alt="红妆代言人" src="https://img.hzshuangmei.com/pc/qydbns/bg3_5.jpg" />
				<div>
					<h3>
						<span class="sr-only">5</span>无需恢复期</h3>
					<p>
						做完即走，不影响工作和生活。</p>
				</div>
			</div>
			<a class="j-consult consult" href="javascript:void(0);" rel="nofollow">点击咨询</a></div>
	</div>
</div>
<div class="conatiner m4">
	<div class="g-doc">
		<h2 class="wow fadeInUp">
			<span class="sr-only">选择红妆让颜值改变人生</span></h2>
		<div class="content f-cb wow fadeInUp">
			<div class="left">
				<p class="info">
					抚平皱纹</p>
				<img alt="抚平皱纹" src="https://img.hzshuangmei.com/pc/qydbns/img4_1.jpg" />
				<h3>
					乔雅登&reg;雅致</h3>
				<img alt="乔雅登®雅致" src="https://img.hzshuangmei.com/pc/qydbns/img4_3.jpg" />
				<p class="des">
					【适应症】抚平皱纹，再现年轻肌肤，比如面部除皱，祛鱼 尾纹、祛鼻唇沟等中度和重度皱纹。</p>
			</div>
			<div class="right">
				<p class="info">
					轮廓塑性</p>
				<img alt="轮廓塑性" src="https://img.hzshuangmei.com/pc/qydbns/img4_2.jpg" />
				<h3>
					乔雅登&reg;极致</h3>
				<img alt="乔雅登®极致" src="https://img.hzshuangmei.com/pc/qydbns/img4_4.jpg" />
				<p class="des">
					【适应症】轮廓塑型，凝聚力更强更多的是用来丰盈面庞， 重塑轮廓来进行塑性，比如丰唇、丰苹果肌、丰下巴、 隆鼻等。</p>
			</div>
		</div>
		<a class="j-consult consult" href="javascript:void(0);" rel="nofollow">点击咨询</a></div>
</div>
<div class="conatiner m5">
	<div class="g-doc">
		<h2 class="wow fadeInUp">
			<span class="sr-only">塑美案例</span></h2>
		<div class="content wow fadeInUp">
			<div class="row f-cb">
				<div class="pic f-fl">
					<img alt="婷子术后" src="https://img.hzshuangmei.com/pc/qydbns/img5_1.jpg" /><img alt="婷子术前" class="before" src="https://img.hzshuangmei.com/pc/qydbns/img5_2.jpg" /></div>
				<div class="des f-fr">
					<h3>
						Ms. Xue<br />
						婷子</h3>
					<p>
						我泪沟很深，即使每天睡的早，还是出现了泪 沟，真的非常的难看！可能是之前疏于对皮肤的保 养，所以出现明显眼部细纹，而且我化妆也是用遮 瑕效果很好的粉底，就是遮不住。想来想去，还是 去红妆注射【乔雅登雅致】玻尿酸。</p>
					<p class="mark">
						此案例为我院真实案例，禁止转载，违者必究！</p>
					<a class="j-consult consult" href="javascript:void(0);" rel="nofollow">查看更多案例</a></div>
			</div>
			<div class="row row2 f-cb">
				<div class="des f-fl">
					<h3>
						Ms. hong<br />
						绣林</h3>
					<p>
						我是属于鼻子基础特别不好的那种，鼻梁很塌，感 觉整个人五官不立体平平的，所以经过我慎重考虑 后，选择到红妆注射乔雅登极致玻尿酸！</p>
					<p class="mark">
						此案例为我院真实案例，禁止转载，违者必究！</p>
					<a class="j-consult consult" href="javascript:void(0);" rel="nofollow">查看更多案例</a></div>
				<div class="pic f-fr">
					<img alt="绣林术后" src="https://img.hzshuangmei.com/pc/qydbns/img5_3.jpg" /><img alt="绣林术前" class="before" src="https://img.hzshuangmei.com/pc/qydbns/img5_4.jpg" /></div>
			</div>
		</div>
	</div>
</div>
<div class="conatiner m6">
	<div class="g-doc">
		<h2 class="wow fadeInUp">
			<span class="sr-only">不将就 就要美</span></h2>
		<div class="content wow fadeInUp">
			<p class="des">
				红妆尚医学美容专家团队致力于为每位求美者提供全面的美肤解决<br />
				方案，帮数名女性解决各类皮肤问题，让每一位女性<br />
				在这里收获的不只是美丽还有快乐。</p>
			<div class="slideW">
				<ul class="slideC">
					<li class="item">
						<div class="left">
							<img alt="刘志坤" src="https://img.hzshuangmei.com/pc/qydbns/img6_5.jpg" />
							<h3>
								刘志坤</h3>
							<p>
								红妆整形外科院长</p>
						</div>
						<div class="right">
							<ul>
								<li>
									精微眼鼻综合整形专家</li>
								<li>
									中国整形美容协会海峡两岸分会委员</li>
								<li>
									中国中西医结合学会医学美容专业委员会<br />
									脂肪整形分会委员</li>
								<li>
									中国整形美容协会眼整形美容理事会理事</li>
								<li>
									湖南省医疗美容协会鼻整形专业委员会委员</li>
							</ul>
							<h3>
								擅长项目:</h3>
							<!-- <img src="https://img.hzshuangmei.com/pc/qydbns/img6_6.jpg" alt="擅长项目"> -->
							<p>
								<span>眼部综合整形</span> <span>鼻部综合整形</span> <span>微创面部年轻化</span> <span>乳房综合整形</span></p>
						</div>
					</li>
					<li class="item">
						<div class="left">
							<img alt="朱红振" src="https://img.hzshuangmei.com/pc/qydbns/img6_1.jpg" />
							<h3>
								朱红振</h3>
							<p>
								红妆整形外科海府院长</p>
						</div>
						<div class="right">
							<ul>
								<li>
									赫本软骨鼻创领者</li>
								<li>
									全鼻整形技术集大成者</li>
								<li>
									中韩整形技术交流峰会中方代表</li>
								<li>
									大型整形真人秀《美丽新约》评审委员</li>
								<li>
									韩国心美眼鼻医院客座专家</li>
								<li>
									大韩整形美容外科协会会员</li>
								<li>
									国际医疗整形美容协会会员</li>
							</ul>
							<!--  <h3>擅长项目</h3>
                                <img src="https://img.hzshuangmei.com/pc/qydbns/img6_2.jpg" alt="擅长项目">
                                <p>
                                    <span>面部年轻化</span>
                                    <span>眼部美容</span>
                                    <span>鼻部整形</span>
                                    <span>胶原蛋白美容</span>
                                </p> --></div>
					</li>
					<li class="item">
						<div class="left">
							<img alt="关海涛" src="https://img.hzshuangmei.com/pc/qydbns/img6_3.jpg" />
							<h3>
								关海涛</h3>
							<p>
								红妆医学美容外科院长</p>
						</div>
						<div class="right">
							<ul>
								<li>
									中国医师协会整形与美容分会会员</li>
								<li>
									国际医疗美容协会会员</li>
								<li>
									大韩整形美容外科协会荣誉会员</li>
								<li>
									韩国心美眼整形医院特邀专家</li>
								<li>
									五官整形权威专家</li>
								<li>
									丰胸、吸脂、形体整形专家</li>
								<li>
									面部年轻化，青春气质技术专家</li>
							</ul>
							<h3>
								擅长项目:</h3>
							<!-- <img src="https://img.hzshuangmei.com/pc/qydbns/img6_4.jpg" alt="擅长项目"> -->
							<p>
								<span>玻尿酸注射</span> <span>鼻部美容</span> <span>眼部美容</span> <span>形体塑造</span> <span>丰胸</span></p>
						</div>
					</li>
				</ul>
				<a class="btn prev" href="javascript:void(0);">&nbsp;</a> <a class="btn next" href="javascript:void(0);">&nbsp;</a></div>
			<a class="j-consult consult" href="javascript:void(0);" rel="nofollow">咨询专家医师</a></div>
	</div>
</div>


<div  class="tjb">
    <div class="m_rj">
        <!--<div class="tjb_title1">-->
            <!--<img src="https://img.hzshuangmei.com/pc/tjb_title1.png" alt=""/>-->
        <!--</div>-->
               <div class="tjb_title1">
            <img src="https://img.hzshuangmei.com/pc/tjb_title1.png" alt="相关日记"/>
        </div><ul class="tjb_rj clearFix"> <li>
              <a href="/cases/ha/121.html" class="tbj_t" target="_blank">
                  <img src="https://uploads.hzshuangmei.com/180109/2-1P109114150947.jpg" alt="术后"/>
              </a>
              <div class="tbj_b">
                  <a href="/cases/ha/121.html" class="tbj_b_img" target="_blank"><img src="https://uploads.hzshuangmei.com/180109/2-1P10911413JS.JPG" alt="术前"/></a>
                     <p class="p1 tbj_b_p1">【 速美项目 】</p>
                  <p class="p2"><a href="https://www.hzshuangmei.com/projects/ha/zhbns.html">玻尿酸塑形</a><br />
</p>
                  <a href="/cases/ha/121.html" class="tjb_video" target="_blank"><img src="//img.hzshuangmei.com/pc/tjb_video.png" alt="整形案例视频"/></a>
              </div>
              </li><li>
              <a href="/cases/ha/127.html" class="tbj_t" target="_blank">
                  <img src="https://uploads.hzshuangmei.com/180109/2-1P10915593V04.jpg" alt="术后"/>
              </a>
              <div class="tbj_b">
                  <a href="/cases/ha/127.html" class="tbj_b_img" target="_blank"><img src="https://uploads.hzshuangmei.com/180109/2-1P109155922414.JPG" alt="术前"/></a>
                     <p class="p1 tbj_b_p1">【 速美项目 】</p>
                  <p class="p2"><a href="http://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;fi=68948">芭比翘鼻</a> <a href="https://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;fi=68948">下巴吸脂</a> &nbsp;<a href="https://www.hzshuangmei.com/projects/ha/zhbns.html">玻尿酸塑形</a></p>
                  <a href="/cases/ha/127.html" class="tjb_video" target="_blank"><img src="//img.hzshuangmei.com/pc/tjb_video.png" alt="整形案例视频"/></a>
              </div>
              </li></ul>
    </div>
    <div class="m_zj">
        <!--<div class="tjb_title2">-->
            <!--<img src="https://img.hzshuangmei.com/pc/tjb_title2.png" alt=""/>-->
        <!--</div>-->
             <div class="tjb_title2">
            <img src="https://img.hzshuangmei.com/pc/tjb_title2.png" alt="推荐专家"/>
        </div><ul class="tjb_zj clearFix"> <li class="clearFix">
                <a href="/doctors/surgery/liudalie.html" class="tjb_l" target="_blank"><img src="https://uploads.hzshuangmei.com/171223/1-1G223091J5950.jpg" alt="柳大烈(客座)"/></a>
                <div class="tjb_r">
                    <p class="p3"><a href="/doctors/surgery/liudalie.html" class="tjb_name" target="_blank">柳大烈(客座)</a></p>
                    <p class="p4"><a href="/doctors/surgery/liudalie.html" target="_blank">教授</a></p>
                    <div class="tjb_sc clearFix">
                        <p>擅长项目：</p>
                        <p><a href="http://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;fi=68948">韩式改脸型</a> &nbsp;<a href="http://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;fi=68948"> 面部除皱</a> </p>
                    </div>
                    <div class="tjb_button">
                        <a class="j-consult" href="javascript:void(0);" rel="nofollow" target="_blank"><img src="//img.hzshuangmei.com/pc/tjb_button.png" alt="点击咨询"/></a>
                    </div>
                </div></li><li class="clearFix">
                <a href="/doctors/surgery/guozongke.html" class="tjb_l" target="_blank"><img src="https://uploads.hzshuangmei.com/img/180112/1-1P112160H50-L.jpg" alt="郭宗科(客座)"/></a>
                <div class="tjb_r">
                    <p class="p3"><a href="/doctors/surgery/guozongke.html" class="tjb_name" target="_blank">郭宗科(客座)</a></p>
                    <p class="p4"><a href="/doctors/surgery/guozongke.html" target="_blank">教授</a></p>
                    <div class="tjb_sc clearFix">
                        <p>擅长项目：</p>
                        <p><a href="https://www.hzshuangmei.com/projects/nose/nose.html">全立体鼻缩窄术</a> &nbsp; <a href="https://www.hzshuangmei.com/projects/nose/dlslb.html">达拉斯隆鼻</a> </p>
                    </div>
                    <div class="tjb_button">
                        <a class="j-consult" href="javascript:void(0);" rel="nofollow" target="_blank"><img src="//img.hzshuangmei.com/pc/tjb_button.png" alt="点击咨询"/></a>
                    </div>
                </div></li></ul>
    </div>
    <div class="m_xm">
        <!--<div class="tjb_title3">-->
            <!--<img src="https://img.hzshuangmei.com/pc/tjb_title3.png" alt=""/>-->
        <!--</div>-->
        <!--<div class="tjb_xm">-->
               <div class="tjb_title3">
            <img src="https://img.hzshuangmei.com/pc/tjb_title3.png" alt="相关项目"/>
        </div><div class="tjb_xm"><div class="tjb_img clearFix">
  <a href="/projects/ha/bnsqflw.html" target="_blank"><img src="https://uploads.hzshuangmei.com/180411/1-1P411140P9134.jpg" alt="玻尿酸祛除法令纹"></a><a href="/projects/ha/xbnsfet.html" target="_blank"><img src="https://uploads.hzshuangmei.com/180322/1-1P322092GMV.jpg" alt="玻尿酸丰额头"></a><a href="/projects/ha/ymbns.html" target="_blank"><img src="https://uploads.hzshuangmei.com/180301/1-1P30110012Ja.jpg" alt="逸美玻尿酸"></a>
</div>         </div>

        <!--</div>-->
    </div>
</div>
<div class="index_items" id="index_items">
    <div class="shuang_m1">
        <div class="clearFix border-r">
            <div class="icon">
                <span>双美概况</span>
                <i></i>
            </div>
            <ul class="mar_t">
                <li><a href="/" target="_blank" rel="noopener" >>返回首页</a></li>
                <li><a class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener">>来院路线</a></li>
                <li><a class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener">>联系我们</a></li>
                <li><a href="/brand" target="_blank" rel="noopener">>品牌起源</a></li>
                <!--<li><a href="">>企业文化</a></li>-->
            </ul>
        </div>
        <div class="clearFix border-l border-r">
            <div class="icon">
                <span>整形美容</span>
                <i></i>
            </div>
            <ul class="mar_t">
                <li><a href="/projects/chest/#project_nav" target="_blank" rel="noopener">>胸部整形</a></li>
                <li><a href="/projects/eye/#project_nav" target="_blank" rel="noopener">>眼部整形</a></li>
                <li><a href="/projects/nose/#project_nav" target="_blank" rel="noopener">>鼻部整形</a></li>
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>唇部整形</a></li>
                <li><a href="/projects/body/#project_nav" target="_blank" rel="noopener">>塑形体雕</a></li>
                <li><a href="/projects/zhifang/ztzfmd.html" target="_blank" rel="noopener">>自体脂肪填充</a></li>
                <li><a href="/projects/#project_nav" target="_blank" rel="noopener">>其他系列</a></li>
                <li><a href="/projects/ha/bnsxb.html" target="_blank" rel="noopener">>下巴整形</a></li>
                <li><a href="/projects/private/#project_nav" target="_blank" rel="noopener">>私密整形</a></li>
            </ul>
        </div>
        <div class="clearFix border-l border-r">
            <div class="icon">
                <span>光学美肤</span>
                <i></i>
            </div>
            <ul class="mar_t">
                <li><a href="/projects/quban/quban.html" target="_blank" rel="noopener">>美白祛斑</a></li>
                <li><a href="/projects/tuomao/tuomao2.html" target="_blank" rel="noopener">>专业脱毛</a></li>
                <li><a href="/projects/qudou/hzqdk.html" target="_blank" rel="noopener">>祛痘祛疤印</a></li>
                <li><a href="/projects/chuzhou/quzhou.html" target="_blank" rel="noopener">>紧肤抗衰</a></li>
            </ul>
        </div>
        <div class="clearFix border-l">
            <div class="icon">
                <span>微创美容</span>
                <i></i>
            </div>
            <ul class="mar_t">
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>玻尿酸塑形</a></li>
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>玻尿酸祛皱</a></li>
                <li><a href="/projects/botox/#project_nav" target="_blank" rel="noopener">>BOTOX注射</a></li>
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>疤痕针</a></li>
                <li><a href="/projects/tattoo/#project_nav" target="_blank" rel="noopener">>纹绣</a></li>
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>水光注射</a></li>
                <li><a href="/projects/#project_nav" target="_blank" rel="noopener">>其他</a></li>
            </ul>
        </div>
    </div>
</div>
<footer id="footer">
    <div class="shuang_m1 clearFix">
        <div class="left">
            <h2><a href=""><img src="https://img.hzshuangmei.com/pc/f_logo.png" alt="红妆双美"/></a></h2>
            <p class="addr"><i></i>红妆双美地址：海口市海府路4号海口宾馆附楼2层</p>
            <p>本站信息仅供参考建 版权所有:红妆双美 https://www.hzshuangmei.com<br/>
                <a href="http://www.miitbeian.gov.cn/" rel="nofollow" target="_blank">琼ICP备17004048号-1</a> (海)医广[2017]第085号 <a href="//www.hzshuangmei.com/humans.txt" rel="nofollow" target="_blank"><img src="//img.hzshuangmei.com/pc/humanstxt-transparent-color.png" class="humanstxt"></a><br/>
                网站部分图文来源于网络，如有侵权，请联系我们 联系电话：0898-66156043</p>
        </div>
        <div class="middle"></div>
        <div class="right right1">
            <div class="right_t clearFix">
                <div class="clearFix">
                    <div class="ewm"></div>
                    <div>
                        <p class="fon1">微信扫一扫</p>

                        <p>1）获得最新优惠</p>

                        <p>2）在线实时咨询</p>

                        <p>3）专属服务通道</p>
                    </div>
                </div>

                <div class="clearFix">
                    <div class="f_phone"></div>
                    <div>
                        <p class="fon1">全国免费咨询热线</p>

                        <p class="fon2">0898-66156043</p>

                        <p class="fon3">咨询时间：8:00—20:00</p>
                    </div>
                </div>
            </div>
             <!--<div class="right_b">-->
                <!--<i></i><span>友情链接:</span>-->
                <!---->
                <!--<a href='https://www.honorreal.com/' target='_blank'>红瑞集团</a> /-->
                <!---->
                <!--<a href='https://www.hoozonspa.com' rel='nofollow' target='_blank'>红妆美容</a> /-->
                <!---->
                <!--<a href='http://www.yueyimei.com' target='_blank'>悦伊美</a> /-->
                <!---->
            <!--</div>-->
            <p class="copyright">Copyright © 2017 红妆双美 版权所有 违者必究 | <a href="/statement/copyright.html" rel="nofollow" target="_blank" rel="noopener">版权及隐私声明</a><br>
              设计,文案,技术等求职请投递至网络部root#hzwlb.org(#替换成@)</p>
        </div>
    </div>
</footer>
<!-- 右侧悬浮 开始 -->
<div class="yb_conct">
    <div class="yb_bar">
        <ul>
            <li class="yb_QQ"><a target="_blank" rel="noopener" href="javascript:void(0)" class="j-site-consult" title="立即咨询" rel="nofollow">立即咨询</a></li>
            <li class="yb_phone"><a target="_blank" rel="noopener" href="javascript:void(0)" class="j-site-consult" title="门店查询" rel="nofollow">门店查询</a></li>
            <li class="yb_top">返回顶部</li>
            <li class="yb_ercode" >微信扫一扫<br>
                <img class="hd_qr" src="https://img.hzshuangmei.com/pc/WeChatApplet.jpg" width="125" alt="关注微信小程序">
            </li>
        </ul>
    </div>
</div>
<!-- 结束 -->

</body>
<link rel="preload" href="https://js.hzshuangmei.com/pc/common.js" as="script" crossorigin>
<link rel="preload" href="https://js.hzshuangmei.com/pc/layer/layer.js" as="script" crossorigin>
<link rel="preload" href="https://js.hzshuangmei.com/pc/kst_popup.js" as="script" crossorigin>
<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/Swiper/3.4.2/js/swiper.min.js"></script>
<script src="https://js.hzshuangmei.com/pc/common.js" ></script>
<script src="https://js.hzshuangmei.com/pc/layer/layer.js"></script>
<script src="https://js.hzshuangmei.com/pc/kst_popup.js"></script>
 <!-- html5标签兼容ie低版本浏览器 -->
<!-- [if lt IE 9]>     -->
<script src="https://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<!-- <![endif] -->
<!-- 百度站内搜索 -->
<!-- <script type="text/javascript">(function(){document.write(unescape('%3Cdiv id="bdcs"%3E%3C/div%3E'));var bdcs = document.createElement('script');bdcs.type = 'text/javascript';bdcs.async = true;bdcs.src = '//znsv.baidu.com/customer_search/api/js?sid=5257607230163915007' + '&plate_url=' + encodeURIComponent(window.location.href) + '&t=' + Math.ceil(new Date()/3600000);var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(bdcs, s);})();</script> -->


<script src="https://js.hzshuangmei.com/pc/qydbns/theme.js" type="text/javascript" charset="utf-8"></script><script src="https://cdn.bootcss.com/wow/1.1.2/wow.min.js "></script><script>
        var wow = new WOW({
            boxClass: 'wow',
            animateClass: 'animated',
            offset: 0,
            mobile: true,
            live: true,
            callback: function(box) {

            },
            scrollContainer: null
        });
        wow.init();
    </script>
</html>
