<!DOCTYPE html>
<html lang="zh-cmn-Hans">
<head>
    <!-- Make 2018-04-19 16:50:00 -->
<!-- Make 1524127800 -->
<meta charset="UTF-8">
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
<meta name="renderer" content="webkit"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
<meta name=applicable-device content="pc">
<meta http-equiv="Cache-Control" content="no-transform"/>
<meta http-equiv="Cache-Control" content="no-siteapp"/>
<meta name="baidu-site-verification" content="99J7V1k1Vz" />
<meta name="google-site-verification" content="Odmo8X4zeUG1WPcCrCAueZz-dyBPFBs4Zqlb9FBT5z4" />
<meta http-equiv="Access-Control-Allow-Origin" content="*" />
<!-- Global site tag (gtag.js) - Google Analytics -->
<!-- <script async src="https://www.googletagmanager.com/gtag/js?id=UA-114904919-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-114904919-2');
</script> -->

    <title>红妆双眼皮修复_眼部_海南红妆时尚双美整形美容连锁</title>
    <meta property="og:type" content="article"/>
    <meta property="article:author" content="红妆双美"/>
    <meta property="article:published_time" content="2018-01-15T14:21:23+08:00" />
    <meta name="keywords" content="红妆双眼皮修复,"/>
    <meta name="description" content="在红妆，我们倡导健康美眼理念 红妆双眼皮修复已经不是单纯的缝合切口，而是要松解粘连，耗时一个小时的3-4层缝合， 分为：加强力量的缝合、双眼皮固定缝合、全层间断"/>
    <meta property="article:tag" content="红妆双眼皮修复,">
    <link rel="canonical" href="https://www.hzshuangmei.com/projects/eye/hzsypxf.html" />
    <link rel="alternate" media="only screen and(max-width: 640px)" href="https://m.hzshuangmei.com/projects/eye/hzsypxf.html" >
    <!-- Pre for optimization -->
<link rel="dns-prefetch" href="https://cdn.bootcss.com">
<link rel="dns-prefetch" href="https://uploads.hzshuangmei.com">
<link rel="dns-prefetch" href="https://img.hzshuangmei.com">
<link rel="dns-prefetch" href="https://css.hzshuangmei.com">
<link rel="dns-prefetch" href="https://js.hzshuangmei.com">
<link rel="dns-prefetch" href="https://pv.kuaishang.cn">
<link rel="dns-prefetch" href="https://z8.cnzz.com">
<link rel="dns-prefetch" href="https://s19.cnzz.com">
<link rel="dns-prefetch" href="https://tag.baidu.com">
<link rel="dns-prefetch" href="https://sp0.baidu.com">
<link rel="preload" href="https://css.hzshuangmei.com/pc/common.css" as="style" crossorigin />
<link rel="preload" href="https://img.hzshuangmei.com/pc/favicon.ico" as="image" type="image/x-icon" crossorigin />
<!-- Style for the page-->
<link rel="stylesheet" href="https://cdn.bootcss.com/Swiper/3.4.2/css/swiper.min.css"/>
<link rel="stylesheet" href="https://css.hzshuangmei.com/pc/common.css"/>
<link rel="stylesheet" href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" >
<!-- favicon.ico -->
<link rel="icon" href="https://img.hzshuangmei.com/pc/favicon.ico" type="image/x-icon"/>
<link rel="shortcut icon" href="https://img.hzshuangmei.com/pc/favicon.ico" type="image/x-icon"/>
<!-- humanstxt -->
<link rel="author" href="https://www.hzshuangmei.com/humans.txt" />
<link rel="preload" as=image  href="https://img.hzshuangmei.com/pc/kst/default.png">
<link rel="prefetch" src="https://img.hzshuangmei.com/pc/kst/default.png">
<link rel="prerender" src="https://img.hzshuangmei.com/pc/kst/default.png">
<link rel="prefetch" src="https://img.hzshuangmei.com/pc/kst/hzsypxf.png">
<link rel="prerender" src="https://img.hzshuangmei.com/pc/kst/hzsypxf.png">
<link rel="preload" as=image  href="https://img.hzshuangmei.com/pc/kst/hzsypxf.png">

     <link rel="preload" href="https://css.hzshuangmei.com/pc/tjb.css" as="style" crossorigin />
    <link rel="stylesheet" href="https://css.hzshuangmei.com/pc/tjb.css"/>
    <meta content="设计观彩恒，王广成/" name="author" />
<link href="//css.hzshuangmei.com/pc/hzsypxf/css/sypxf.css" rel="stylesheet" />

<body>
<header>
    <div class="top">
        <div class="shuang_m1 clearFix">
            <div class="top_l">
                <!--<span>香港红瑞集团 旗下品牌 海南红妆双美连锁</span>-->
                <img src="https://img.hzshuangmei.com/pc/tl_logo.png" alt="logo" />|<span>美丽时间：周一周日9点--21点</span>
            </div>
            <!-- 增加百度站内搜索 -->
            <div class="top_c">
                <div class="search_box">
                    <form action="https://www.hzshuangmei.com/search/" target="_blank" autocomplete="off" id="bdcs-search-form" class="site-search-form">
                        <input type="hidden" name="s" value="5257607230163915007">
                         <input type="hidden" name="entry" value="1">
                        <input type="text" placeholder="请输入您要搜索的内容..." id="bdcsMain" name="q">
                        <button type="submit" id="bdcs-search-form-submit"></button>
                    </form>
                </div>
            </div>
                        <!-- 增加百度站内搜索 -->
            <div class="top_r">
                <a href="" class="pad_r"><i class="tel"></i><span>0898-66156043</span></a>
                <span>关注我们：</span>
                <a href="" class="pad_l"><i class="wbo"></i></a>
                <a href=""><i class="wxin"></i></a>
                <a href=""><i class="qq"></i></a>
            </div>
        </div>
    </div>
    <div class="sm_logo">
        <a href="/"><img src="https://img.hzshuangmei.com/pc/h_logo.png" alt=""/></a>
    </div>
</header>
<nav id="nav">
    <ul class="shuang_m1 nav_ul">
        <li class="nav_list">
            <a href="/" class="nav_link" target="_blank" rel="noopener">
                <span>首 页</span><br/>
                <span>Home</span>
            </a>
        </li>
        <li class="nav_list">
            <a href="/brand" class="nav_link bor_r" target="_blank" rel="noopener">
                <span>品 牌</span><br/>
                <span>brands</span>
            </a>
        </li>
        <li class="nav_list">
            <a href="/projects" class="nav_link bor_l bor_r" target="_blank" rel="noopener">
                <span>项 目</span><br/>
                <span>projects</span>
            </a>
            <div class="clearFix" id="project">
                <ul>
                    <li>
                        <h5><a href="/projects/tattoo/" target="_blank" rel="noopener">医学纹绣</a></h5>
                    </li>
                    <!--              <li>
                        <a href="/projects/tattoo/yanxian.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P4041610355P.jpg" alt="红妆艺术美瞳线"/>
                            <p><i></i><span>红妆艺术美瞳线</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/tattoo/hsbyjwm.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404160923556.jpg" alt="韩式半永久纹眉"/>
                            <p><i></i><span>韩式半永久纹眉</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/tattoo/xwx.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/img/180331/1-1P3311106490-L.jpg" alt="洗纹绣"/>
                            <p><i></i><span>洗纹绣</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/tattoo/xwx.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/img/180331/1-1P3311106490-L.jpg" alt="洗纹绣"/>
                            <p><i></i><span>洗纹绣</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/tattoo/wash.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180222/1-1P222110205243.jpg" alt="激光洗纹绣"/>
                            <p><i></i><span>激光洗纹绣</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/tattoo/hsbyjwm.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404160923556.jpg" alt="韩式半永久纹眉"/>
                            <p><i></i><span>韩式半永久纹眉</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button">-->
                    <!--<a href="/projects" target="_blank" rel="noopener">查看更多</a>-->
                    <!--</li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/eye/" target="_blank" rel="noopener">眼部整形</a></h5>
                    </li>
                    <!--   <li>
                        <a href="/projects/eye/qmtm.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404161354458.jpg" alt=""/>
                            <p><i></i><span>切眉提眉术</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/eye/slxc.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180222/1-1P22216455E61.jpg" alt=""/>
                            <p><i></i><span>上睑下垂</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/eye/yandai.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404160Q03S.jpg" alt=""/>
                            <p><i></i><span>无痕祛眼袋</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/eye/yandai.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404160Q03S.jpg" alt="无痕祛眼袋"/>
                            <p><i></i><span>无痕祛眼袋</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/eye/slxc.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180222/1-1P22216455E61.jpg" alt="上睑下垂"/>
                            <p><i></i><span>上睑下垂</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/eye/hzyj.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180206/1-1P206100342338.jpg" alt="红妆孕睫术"/>
                            <p><i></i><span>红妆孕睫术</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/nose/" target="_blank" rel="noopener">鼻部整形</a></h5>
                    </li>
                    <!--              <li>
                        <a href="/projects/nose/lineeaglenose.html" target="_blank" rel="noopener">
                        <img src="https://uploads.hzshuangmei.com/180109/1-1P10916214I29.jpg" alt=""/>
                            <p><i></i><span>线雕隆鼻</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/nose/heben.html" target="_blank" rel="noopener">
                        <img src="https://uploads.hzshuangmei.com/180109/1-1P109162114246.jpg" alt=""/>
                            <p><i></i><span>红妆赫本软骨鼻</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/nose/longbijiage.html" target="_blank" rel="noopener">
                        <img src="https://uploads.hzshuangmei.com/180209/1-1P2091524433K.jpg" alt=""/>
                            <p><i></i><span>隆鼻价格</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/nose/longbijiage.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180209/1-1P2091524433K.jpg" alt="隆鼻价格"/>
                            <p><i></i><span>隆鼻价格</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/nose/hzbbqb.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180208/1-1P20QZ14O61.jpg" alt="红妆芭比翘鼻"/>
                            <p><i></i><span>红妆芭比翘鼻</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/nose/nose.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180109/1-1P109161Fc42.jpg" alt="全立体鼻缩窄术"/>
                            <p><i></i><span>全立体鼻缩窄术</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/face/" target="_blank" rel="noopener">面部整形</a></h5>
                    </li>
                    <!--                <li class="star">
                        <a href="/projects/zhifang/ztzfmd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180109/1-1P109162329454.jpg" alt=""/>
                            <p><i></i><span>自体脂肪面雕</span></p>
                        </a>
                    </li><li class="star">
                        <a href="/projects/xiaba/vlmxd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P40416062R04.jpg" alt=""/>
                            <p><i></i><span>v立美线雕</span></p>
                        </a>
                    </li><li class="star">
                        <a href="/projects/face/zitizhifang.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180208/1-1P20Q54P4G4.jpg" alt=""/>
                            <p><i></i><span>自体脂肪面部填充</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/face/zitizhifang.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180208/1-1P20Q54P4G4.jpg" alt="自体脂肪面部填充"/>
                            <p><i></i><span>自体脂肪面部填充</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/xiaba/vlmxd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P40416062R04.jpg" alt="v立美线雕"/>
                            <p><i></i><span>v立美线雕</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/zhifang/ztzfmd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180109/1-1P109162329454.jpg" alt="自体脂肪面雕"/>
                            <p><i></i><span>自体脂肪面雕</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/skin/" target="_blank" rel="noopener">皮肤美容</a></h5>
                    </li>
                    <!--                 <li>
                        <a href="/projects/qudou/duoweiqd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180222/1-1P222143953U0.jpg" alt=""/>
                            <p><i></i><span>红妆多维祛痘</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/quban/xpmqb.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180328/1-1P32Q356202V.jpg" alt=""/>
                            <p><i></i><span>红妆皮秒祛斑</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/skin/sgz.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180406/1-1P4061A303F6.jpg" alt=""/>
                            <p><i></i><span>水光针</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/quban/xpmqb.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180328/1-1P32Q356202V.jpg" alt="红妆皮秒祛斑"/>
                            <p><i></i><span>红妆皮秒祛斑</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/chuzhou/quzhou.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180212/1-1P212102446403.jpg" alt="除皱抗衰"/>
                            <p><i></i><span>除皱抗衰</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/quban/quban.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180312/1-1P3121601494G.jpg" alt="红妆祛斑"/>
                            <p><i></i><span>红妆祛斑</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/ha/" target="_blank" rel="noopener">玻尿酸</a></h5>
                    </li>
                    <!--                     <li>
                        <a href="/projects/ha/qydbns.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180208/1-1P20Q0501X26.jpg" alt=""/>
                            <p><i></i><span>乔雅登玻尿酸</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/ha/zhbns.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180109/1-1P109161SV57.jpg" alt=""/>
                            <p><i></i><span>综合玻尿酸</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/ha/restylane.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180413/1-1P413100FcV.jpg" alt=""/>
                            <p><i></i><span>瑞蓝玻尿酸</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/ha/restylane.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180413/1-1P413100FcV.jpg" alt="瑞蓝玻尿酸"/>
                            <p><i></i><span>瑞蓝玻尿酸</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/ha/bnsqflw.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180411/1-1P411140P9134.jpg" alt="玻尿酸祛除法令纹"/>
                            <p><i></i><span>玻尿酸祛除法令纹</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/ha/xbnsfet.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180322/1-1P322092GMV.jpg" alt="玻尿酸丰额头"/>
                            <p><i></i><span>玻尿酸丰额头</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/body/" target="_blank" rel="noopener">形体雕塑</a></h5>
                    </li>
                    <!-- <li>
                        <a href="/projects/body/sdlxz.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404161320X4.jpg" alt=""/>
                            <p><i></i><span>水动力吸脂</span></p>
                       </a>
                    </li> -->
                    <li>
                        <a href="/projects/body/sdlxz.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404161320X4.jpg" alt="水动力吸脂"/>
                            <p><i></i><span>水动力吸脂</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
            </div>
        </li>
        <li class="nav_list">
            <a href="/doctors" class="nav_link bor_l bor_r" target="_blank" rel="noopener">
                <span>专 家</span><br/>
                <span>experts</span>
            </a>
            <div id="expert">
                <ul>
                    <li>
                        <h5><a href="/doctors/surgery" target="_blank" rel="noopener">整形美容专家</a></h5>
                    </li>
                    <!--                     <li>
                        <a href="/plugin/view.php?aid=227" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180414/1-1P4140929454T.jpg" alt="薛开兴"/>
                            <p><span class="n_f">薛开兴</span><span class="n_b">整形外科院长</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=153" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180131/1-1P131093205432.jpg" alt="余志亮"/>
                            <p><span class="n_f">余志亮</span><span class="n_b">整形专家</span></p>
                            <i></i>
                        </a>
                    </li> -->
                    <li>
                        <a href="/doctors/surgery/guanhaitao.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180227/1-1P22G44625M2.jpg" alt="关海涛 "/>
                            <p><span class="n_f">关海涛 </span><span class="n_b">整形外科院长</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=176" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180131/1-1P1310U92D41.jpg" alt="朱红振"/>
                            <p><span class="n_f">朱红振</span><span class="n_b">整形外科院长</span></p>
                            <i></i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <h5><a href="/doctors/laser" target="_blank" rel="noopener">激光美容专家</a></h5>
                    </li>
                    <!--             <li>
                        <a href="/doctors/laser/lijie.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/171206/1-1G20611435D10.jpg" alt="李杰"/>
                            <p><span class="n_f">李杰</span><span class="n_b">光学美肤中心院长</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/doctors/laser/yzw.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180131/1-1P131104604521.jpg" alt="姚志文"/>
                            <p><span class="n_f">姚志文</span><span class="n_b">非手术面部年轻化专家</span></p>
                            <i></i>
                        </a>
                    </li> -->
                    <li>
                        <a href="/doctors/laser/lijie.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/171206/1-1G20611435D10.jpg" alt="李杰"/>
                            <p><span class="n_f">李杰</span><span class="n_b">光学美肤中心院长</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/doctors/laser/yzw.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180131/1-1P131104604521.jpg" alt="姚志文"/>
                            <p><span class="n_f">姚志文</span><span class="n_b">非手术面部年轻化专家</span></p>
                            <i></i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <h5><a href="/doctors/tattoo" target="_blank" rel="noopener">医学纹绣</a></h5>
                    </li>
                    <!--                    <li>
                        <a href="/plugin/view.php?aid=139" target="_blank" rel="noopener">
                    <img src="https://uploads.hzshuangmei.com/180117/1-1P11GF5391A.jpg" alt="杨小丽"/>
                            <p><span class="n_f">杨小丽</span><span class="n_b">纹饰指导师</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=136" target="_blank" rel="noopener">
                    <img src="https://uploads.hzshuangmei.com/180125/1-1P125154A1105.jpg" alt="高方云"/>
                            <p><span class="n_f">高方云</span><span class="n_b">纹饰指导师</span></p>
                            <i></i>
                        </a>
                    </li> -->
                    <li>
                        <a href="/plugin/view.php?aid=164" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180125/1-1P12515435J45.jpg" alt="冯晓琳"/>
                            <p><span class="n_f">冯晓琳</span><span class="n_b">纹饰技术总指导师</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=137" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180117/1-1P11GA95JV.jpg" alt="孟超"/>
                            <p><span class="n_f">孟超</span><span class="n_b">纹饰指导师</span></p>
                            <i></i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <h5><a href="/doctors" target="_blank" rel="noopener">特邀专家</a></h5>
                    </li>
                    <li>
                        <a href="/doctors/surgery/ljb.html" target="_blank" rel="noopener">
                             <img src="https://uploads.hzshuangmei.com/180131/1-1P131092S24W.jpg" alt="雷建波(客座)"/>
                            <p><span class="n_f">雷建波(客座)</span><span class="n_b">整形美容专家</span></p>
                            <i></i>
                        </a>
                    </li>
<li>
                        <a href="/doctors/surgery/liudalie.html" target="_blank" rel="noopener">
                             <img src="https://uploads.hzshuangmei.com/171223/1-1G223091J5950.jpg" alt="柳大烈(客座)"/>
                            <p><span class="n_f">柳大烈(客座)</span><span class="n_b">教授</span></p>
                            <i></i>
                        </a>
                    </li>

                </ul>
                <ul>
                    <li>
                        <h5 class="moon"><a href="/doctors" target="_blank" rel="noopener">每月专家</a></h5>
                    </li>
                    <li class="last-one">
                        <!--<a class="last-one" href="https://www.hzshuangmei.com/doctors/surgery/liudalie.html " target="_blank" rel="noopener">-->
                            <!--<img src="https://img.hzshuangmei.com/pc/nav_zhuanjial.jpg" alt=""/>-->
                        <!--</a>-->
                        <a class="last-one j-consult" href="javascript:void(0)"  target="_blank" rel="noopener nofollow">
                            <img src="https://img.hzshuangmei.com/pc/myzzj.jpg" alt=""/>
                        </a>
                    </li>
                </ul>
            </div>
        </li>
        <li class="nav_list">
            <a href="/cases" class="nav_link bor_l bor_r" target="_blank" rel="noopener">
                <span>真人秀</span><br/>
                <span>Show</span>
            </a>
        </li>
        <li class="nav_list">
            <a href="/news" class="nav_link bor_l" target="_blank" rel="noopener">
            <span>活 动</span><br/>
                <span>News</span>
            </a>
        </li>
    </ul>
</nav>

<div class="banner j-consult">
    <p class="onlitext">
        点击咨询</p>
</div>
<div class="m1">
    <div class="m1_con1">
        <h4>
            在红妆，我们倡导健康美眼理念</h4>
        <div class="hx">
            &nbsp;</div>
        <p>
            红妆双眼皮修复已经不是单纯的缝合切口，而是要松解粘连，耗时一个小时的3-4层缝合，<br />
            分为：加强力量的缝合、双眼皮固定缝合、全层间断缝合、表皮连续缝合。让各层组织之间进行复位固定，<br />
            进行功能的重建，弥补因去除组织过多造成的多种问题，同时尽量减少人工痕迹，<br />
            重塑眼部美感，重现灵动双眼。</p>
    </div>
    <div class="m1_con2">
        <img alt="" class="m1img1" src="//img.hzshuangmei.com/pc/hzsypxf/images/m1img1.png" />
        <div>
            <a class="j-consult djzx" href="javascript:void(0)" rel="nofollow">双眼修复会比割的贵吗 <span>GO</span></a></div>
    </div>
</div>
<div class="m2">
    <h3 class="onlitext">
        精湛技术</h3>
    <img alt="" class="m2h" src="//img.hzshuangmei.com/pc/hzsypxf/images/m2h.png" />
    <div class="hen1">
        &nbsp;</div>
    <p>
        exquisite technique Guarantee effect</p>
    <div class="m2_con1">
        <div class="page">
            <img alt="" src="//img.hzshuangmei.com/pc/hzsypxf/images/m2img1.jpg" />
            <h4>
                亚洲修复眼刘志坤</h4>
            <div class="hen2">
                &nbsp;</div>
            <p>
                PROFESSIONAL TECHNOLOGY</p>
            <div>
                红妆时尚双美连锁机构成立高难度眼部修复基地，让更多求美者找回美丽，找回自信，做更美的自己</div>
        </div>
        <div class="page">
            <img alt="" src="//img.hzshuangmei.com/pc/hzsypxf/images/m2img2.jpg" />
            <h4>
                精密检测针对修复</h4>
            <div class="hen2">
                &nbsp;</div>
            <p>
                PRECISION INSPECTION</p>
            <div>
                通过科学的术前检查和细心问诊，了解导致双眼皮失败的原因，个性定制针对性的修复方案</div>
        </div>
        <div class="page">
            <img alt="" src="//img.hzshuangmei.com/pc/hzsypxf/images/m2img3.jpg" />
            <h4>
                6D系统重塑魅惑大眼</h4>
            <div class="hen2">
                &nbsp;</div>
            <p>
                PERFECT TECHNOLOGY</p>
            <div>
                6D技术逐层分离眼睑组织，综合协调眼部形态。避免因手术剥离组织的破坏眼睑层次出现不良状态</div>
        </div>
        <div class="page">
            <img alt="" src="//img.hzshuangmei.com/pc/hzsypxf/images/m2img4.jpg" />
            <h4>
                0.1毫米精细缝合技术</h4>
            <div class="hen2">
                &nbsp;</div>
            <p>
                FINE SUTURE</p>
            <div>
                根据切口肌肉，肌腱膜，皮肤的眼睑分层做精细缝合，保证修复后伤口平整不留疤</div>
        </div>
        <div>
            <a class="j-consult djzx" href="javascript:void(0)" rel="nofollow">双眼修复会比割的贵吗 <span>GO</span></a></div>
    </div>
</div>
<div class="m3">
    <div class="m3cont">
        <h3 class="onlitext">
            这些失败的双眼皮案例</h3>
        <p class="onlitext">
            你属于哪一种？</p>
        <img alt="" class="m3img1" src="//img.hzshuangmei.com/pc/hzsypxf/images/m3img1.jpg" />
        <ul>
            <li>
                <img alt="" src="//img.hzshuangmei.com/pc/hzsypxf/images/m3img2.jpg" />
                <p>
                    双眼皮多层</p>
            </li>
            <li>
                <img alt="" src="//img.hzshuangmei.com/pc/hzsypxf/images/m3img3.jpg" />
                <p>
                    双眼皮过宽</p>
            </li>
            <li>
                <img alt="" src="//img.hzshuangmei.com/pc/hzsypxf/images/m3img4.jpg" />
                <p>
                    双眼皮过窄</p>
            </li>
            <li>
                <img alt="" src="//img.hzshuangmei.com/pc/hzsypxf/images/m3img5.jpg" />
                <p>
                    双眼皮过深</p>
            </li>
            <li>
                <img alt="" src="//img.hzshuangmei.com/pc/hzsypxf/images/m3img6.jpg" />
                <p>
                    双眼线疤痕明显</p>
            </li>
            <li>
                <img alt="" src="//img.hzshuangmei.com/pc/hzsypxf/images/m3img7.jpg" />
                <p>
                    双眼皮不对称</p>
            </li>
        </ul>
        <div>
            <a class="j-consult djzx" href="javascript:void(0)" rel="nofollow">4年的双眼皮消失可以修复吗 <span>GO</span></a></div>
    </div>
</div>
<div class="m4">
    <div class="m4cont">
        <h3 class="onlitext">
            你失败的原因？</h3>
        <p class="onlitext">
            Why did you fail?</p>
        <img alt="" class="m4img1" src="//img.hzshuangmei.com/pc/hzsypxf/images/m4img1.png" /> <img alt="" class="m4img2" src="//img.hzshuangmei.com/pc/hzsypxf/images/m4img2.png" />
        <div class="m4text">
            <div>
                <p>
                    不专业的整形机构</p>
                <p>
                    易出现事故</p>
            </div>
            <div>
                <p>
                    审美设计不专业</p>
                <p>
                    缺乏美感</p>
            </div>
            <div>
                <p>
                    术前沟通不充分</p>
                <p>
                    效果误差</p>
            </div>
            <div>
                <p>
                    医生技术不过关</p>
                <p>
                    眼部手术失败</p>
            </div>
        </div>
        <div>
            <a class="j-consult djzx" href="javascript:void(0)" rel="nofollow">双眼皮割坏了怎么修复 <span>GO</span></a></div>
    </div>
</div>
<div class="m5">
    <div class="m5cont">
        <h3 class="onlitext">
            红妆双眼皮修复术</h3>
        <p class="onlitext">
            分型精修 重塑美眸</p>
        <img alt="" class="m5img1" src="//img.hzshuangmei.com/pc/hzsypxf/images/m5img1.png" />
        <div class="ulbox">
            <ul>
                <li class="jiantou jiantou1">
                    <span>双眼皮过窄/过低</span></li>
                <li class="jiantou">
                    <span>双眼皮不对称</span></li>
                <li class="jiantou">
                    <span>双眼线疤痕明显</span></li>
                <li class="jiantou">
                    <span>双眼皮多层</span></li>
                <li class="jiantou">
                    <span>双眼皮过宽</span></li>
                <li class="jiantou jiantou5">
                    <span>双眼皮过深</span></li>
            </ul>
        </div>
        <div class="jiantoucont">
            <div class="pagecont" style="display: block">
                <div class="left">
                    <h5>
                        双眼皮过窄/过低</h5>
                    <p>
                        1.重睑线设计过窄</p>
                    <p>
                        2.眼皮出现松弛下垂</p>
                    <img alt="" class="page1" src="//img.hzshuangmei.com/pc/hzsypxf/images/imgpage1.jpg" /> <span>方 案</span>
                    <p>
                        对于皮肤宽度尚可，缝合过低，或者皮肤组织下滑造成的双眼皮过窄，需重新提高缝合固定；对于切口线过低的，要在原切口瘢痕上方作新切口，下方重新分离，再做重睑缝合。</p>
                </div>
                <div class="right">
                    <img alt="" src="//img.hzshuangmei.com/pc/hzsypxf/images/img11.jpg" /></div>
            </div>
            <div class="pagecont">
                <div class="left">
                    <h5>
                        双眼皮不对称</h5>
                    <p>
                        1.重睑线不明显或部分完全消失</p>
                    <p>
                        2.双侧高度不一样</p>
                    <p>
                        3.眼睁幅度不一样</p>
                    <img alt="" src="//img.hzshuangmei.com/pc/hzsypxf/images/imgpage2.jpg" /> <span>方案</span>
                    <p>
                        针对情况进行调整，可以两侧都做，也可以一侧为模板进行手术，达到双眼对称的目的。</p>
                </div>
                <div class="right">
                    <img alt="" src="//img.hzshuangmei.com/pc/hzsypxf/images/img22.jpg" /></div>
            </div>
            <div class="pagecont">
                <div class="left">
                    <h5>
                        双眼线疤痕明显</h5>
                    <p>
                        1.设计不合理</p>
                    <p>
                        2.手术中去掉组织过多</p>
                    <p>
                        3.缝合粗糙</p>
                    <img alt="" src="//img.hzshuangmei.com/pc/hzsypxf/images/imgpage3.jpg" /> <span>方案</span>
                    <p>
                        当切开法导致过宽时，可将已经成型的组织分解并去除原有双眼皮后，再重新做新的一条双眼皮线。</p>
                </div>
                <div class="right">
                    <img alt="" src="//img.hzshuangmei.com/pc/hzsypxf/images/img33.jpg" /></div>
            </div>
            <div class="pagecont">
                <div class="left">
                    <h5>
                        双眼皮多层</h5>
                    <p>
                        1..固定不够牢固</p>
                    <p>
                        2.未去除多余皮肤和脂肪</p>
                    <p>
                        3.未矫正上睑下垂</p>
                    <img alt="" src="//img.hzshuangmei.com/pc/hzsypxf/images/imgpage4.jpg" /> <span>方案</span>
                    <p>
                        消肿后经原切口切开，将过多的皮肤切除，并根据缺少的组织量填充适量的脂肪，上方的皱襞消失或减轻。</p>
                </div>
                <div class="right">
                    <img alt="" src="//img.hzshuangmei.com/pc/hzsypxf/images/img44.jpg" /></div>
            </div>
            <div class="pagecont">
                <div class="left">
                    <h5>
                        双眼皮过宽</h5>
                    <p>
                        1过度切除皮肤</p>
                    <p>
                        2.上眼睑脂肪组织过多</p>
                    <p>
                        3.上睑下垂未得到矫正</p>
                    <img alt="" src="//img.hzshuangmei.com/pc/hzsypxf/images/imgpage5.jpg" /> <span>方案</span>
                    <p>
                        术后3-6个月以后重新设计重睑矫正方案，切除多余皮肤和组织，去除前一次手术形成的粘连，然后缝合，同时矫正上睑下垂，形成优美的重睑弧线。</p>
                </div>
                <div class="right">
                    <img alt="" src="//img.hzshuangmei.com/pc/hzsypxf/images/img55.jpg" /></div>
            </div>
            <div class="pagecont">
                <div class="left">
                    <h5>
                        双眼皮过深</h5>
                    <p>
                        1.过高固定双眼皮</p>
                    <img alt="" src="//img.hzshuangmei.com/pc/hzsypxf/images/imgpage6.jpg" /> <span>方案</span>
                    <p>
                        松解原过高的粘连在原有重睑线下浅一些的进行固定，同时防止在原有粘连部位再次粘连。</p>
                </div>
                <div class="right">
                    <img alt="" src="//img.hzshuangmei.com/pc/hzsypxf/images/img66.jpg" /></div>
            </div>
        </div>
        <div>
            <a class="j-consult djzx" href="javascript:void(0)" rel="nofollow">我要咨询双眼皮修复方案 <span>GO</span></a></div>
    </div>
</div>
<div class="m6">
    <div class="m6cont">
        <h3 class="onlitext">
            红妆双眼皮修复案例</h3>
        <p class="onlitext">
            分型精修 重塑美眸</p>
        <img alt="" class="m6img1" src="//img.hzshuangmei.com/pc/hzsypxf/images/m6img1.png" />
        <div class="m6imgcont">
            <img alt="" class="imgm6left" src="//img.hzshuangmei.com/pc/hzsypxf/images/m6img2.jpg" /><img alt="" src="//img.hzshuangmei.com/pc/hzsypxf/images/m6img3.jpg" /> <img alt="" class="imgm6left" src="//img.hzshuangmei.com/pc/hzsypxf/images/m6img4.jpg" /><img alt="" src="//img.hzshuangmei.com/pc/hzsypxf/images/m6img5.jpg" /></div>
        <div>
            <a class="j-consult djzx" href="javascript:void(0)" rel="nofollow">了解更多案例 <span>GO</span></a></div>
    </div>
</div>
<div class="m7">
    <div class="m7cont">
        <img alt="" class="m7img1" src="//img.hzshuangmei.com/pc/hzsypxf/images/m7img1.png" />
        <div class="m7byuan1">
            <span>资质荣誉</span></div>
        <img alt="" class="m7img2" src="//img.hzshuangmei.com/pc/hzsypxf/images/m7img2.png" /> <img alt="" class="m7img3" src="//img.hzshuangmei.com/pc/hzsypxf/images/m7img3.png" />
        <div class="m7byuan2">
			<span>擅<br />
			长<br />
			项<br />
			目</span></div>
        <ul>
            <li>
                眼综合整形</li>
            <li>
                韩式切开重睑术</li>
            <li>
                鼻综合整形</li>
            <li>
                自体脂肪面雕</li>
            <li class="smli">
                微整形及注射美容</li>
            <li class="smli">
                抽脂塑身及脂肪移植</li>
            <li class="smli">
                体表肿瘤的科学手术及创面修复等</li>
        </ul>
        <div class="djzxm7 j-consult">
            如何预约刘院长进行面诊
            <div>
                点击咨询<span>&gt;&gt;</span></div>
        </div>
        <div class="djzxm7 j-consult">
            我要咨询双眼皮修复方案
            <div>
                点击咨询<span>&gt;&gt;</span></div>
        </div>
    </div>
</div>


<div  class="tjb">
    <div class="m_rj">
        <!--<div class="tjb_title1">-->
            <!--<img src="https://img.hzshuangmei.com/pc/tjb_title1.png" alt=""/>-->
        <!--</div>-->
               <div class="tjb_title1">
            <img src="https://img.hzshuangmei.com/pc/tjb_title1.png" alt="相关日记"/>
        </div><ul class="tjb_rj clearFix"> <li>
              <a href="/cases/eye/95.html" class="tbj_t" target="_blank">
                  <img src="https://uploads.hzshuangmei.com/180102/1-1P1020952123b.jpg" alt="术后"/>
              </a>
              <div class="tbj_b">
                  <a href="/cases/eye/95.html" class="tbj_b_img" target="_blank"><img src="https://uploads.hzshuangmei.com/171206/2-1G206105G3E6.jpg" alt="术前"/></a>
                     <p class="p1 tbj_b_p1">【 速美项目 】</p>
                  <p class="p2"><a href="https://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;amp;fi=68948">全切双眼皮+开眼角+祛眼袋</a></p>
                  <a href="/cases/eye/95.html" class="tjb_video" target="_blank"><img src="//img.hzshuangmei.com/pc/tjb_video.png" alt="整形案例视频"/></a>
              </div>
              </li><li>
              <a href="/cases/eye/89.html" class="tbj_t" target="_blank">
                  <img src="https://uploads.hzshuangmei.com/171205/2-1G205114S5945.jpg" alt="术后"/>
              </a>
              <div class="tbj_b">
                  <a href="/cases/eye/89.html" class="tbj_b_img" target="_blank"><img src="https://uploads.hzshuangmei.com/171205/2-1G205114KV25.jpg" alt="术前"/></a>
                     <p class="p1 tbj_b_p1">【 速美项目 】</p>
                  <p class="p2"><a href="https://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;fi=68948">红妆大眼综合术</a></p>
                  <a href="/cases/eye/89.html" class="tjb_video" target="_blank"><img src="//img.hzshuangmei.com/pc/tjb_video.png" alt="整形案例视频"/></a>
              </div>
              </li><li>
              <a href="/cases/eye/116.html" class="tbj_t" target="_blank">
                  <img src="https://uploads.hzshuangmei.com/180110/2-1P1101624453U.jpg" alt="术后"/>
              </a>
              <div class="tbj_b">
                  <a href="/cases/eye/116.html" class="tbj_b_img" target="_blank"><img src="https://uploads.hzshuangmei.com/180108/2-1P10Q6323E06.jpg" alt="术前"/></a>
                     <p class="p1 tbj_b_p1">【 速美项目 】</p>
                  <p class="p2"><a href="https://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;fi=68948">芭比大眼术</a>、<a href="https://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;fi=68948">芭比翘鼻</a></p>
                  <a href="/cases/eye/116.html" class="tjb_video" target="_blank"><img src="//img.hzshuangmei.com/pc/tjb_video.png" alt="整形案例视频"/></a>
              </div>
              </li></ul>
    </div>
    <div class="m_zj">
        <!--<div class="tjb_title2">-->
            <!--<img src="https://img.hzshuangmei.com/pc/tjb_title2.png" alt=""/>-->
        <!--</div>-->
             <div class="tjb_title2">
            <img src="https://img.hzshuangmei.com/pc/tjb_title2.png" alt="推荐专家"/>
        </div><ul class="tjb_zj clearFix"> <li class="clearFix">
                <a href="/plugin/view.php?aid=176" class="tjb_l" target="_blank"><img src="https://uploads.hzshuangmei.com/180131/1-1P1310U92D41.jpg" alt="朱红振"/></a>
                <div class="tjb_r">
                    <p class="p3"><a href="/plugin/view.php?aid=176" class="tjb_name" target="_blank">朱红振</a></p>
                    <p class="p4"><a href="/plugin/view.php?aid=176" target="_blank">整形外科院长</a></p>
                    <div class="tjb_sc clearFix">
                        <p>擅长项目：</p>
                        <p><a href="https://www.hzshuangmei.com/projects/nose/heben.html">赫本软骨鼻</a>&nbsp;<a href="https://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;amp;fi=68948">无创抗衰</a> </p>
                    </div>
                    <div class="tjb_button">
                        <a class="j-consult" href="javascript:void(0);" rel="nofollow" target="_blank"><img src="//img.hzshuangmei.com/pc/tjb_button.png" alt="点击咨询"/></a>
                    </div>
                </div></li><li class="clearFix">
                <a href="/doctors/surgery/liudalie.html" class="tjb_l" target="_blank"><img src="https://uploads.hzshuangmei.com/171223/1-1G223091J5950.jpg" alt="柳大烈(客座)"/></a>
                <div class="tjb_r">
                    <p class="p3"><a href="/doctors/surgery/liudalie.html" class="tjb_name" target="_blank">柳大烈(客座)</a></p>
                    <p class="p4"><a href="/doctors/surgery/liudalie.html" target="_blank">教授</a></p>
                    <div class="tjb_sc clearFix">
                        <p>擅长项目：</p>
                        <p><a href="http://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;fi=68948">韩式改脸型</a> &nbsp;<a href="http://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;fi=68948"> 面部除皱</a> </p>
                    </div>
                    <div class="tjb_button">
                        <a class="j-consult" href="javascript:void(0);" rel="nofollow" target="_blank"><img src="//img.hzshuangmei.com/pc/tjb_button.png" alt="点击咨询"/></a>
                    </div>
                </div></li></ul>
    </div>
    <div class="m_xm">
        <!--<div class="tjb_title3">-->
            <!--<img src="https://img.hzshuangmei.com/pc/tjb_title3.png" alt=""/>-->
        <!--</div>-->
        <!--<div class="tjb_xm">-->
               <div class="tjb_title3">
            <img src="https://img.hzshuangmei.com/pc/tjb_title3.png" alt="相关项目"/>
        </div><div class="tjb_xm"><div class="tjb_img clearFix">
  <a href="/projects/eye/kyj.html" target="_blank"><img src="https://uploads.hzshuangmei.com/180109/1-1P109161Z13c.jpg" alt="红妆无痕开眼角"></a><a href="/projects/eye/slxc.html" target="_blank"><img src="https://uploads.hzshuangmei.com/180222/1-1P22216455E61.jpg" alt="上睑下垂"></a><a href="/projects/eye/qmtm.html" target="_blank"><img src="https://uploads.hzshuangmei.com/180404/1-1P404161354458.jpg" alt="切眉提眉术"></a>
</div>         </div>

        <!--</div>-->
    </div>
</div>
<div class="index_items" id="index_items">
    <div class="shuang_m1">
        <div class="clearFix border-r">
            <div class="icon">
                <span>双美概况</span>
                <i></i>
            </div>
            <ul class="mar_t">
                <li><a href="/" target="_blank" rel="noopener" >>返回首页</a></li>
                <li><a class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener">>来院路线</a></li>
                <li><a class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener">>联系我们</a></li>
                <li><a href="/brand" target="_blank" rel="noopener">>品牌起源</a></li>
                <!--<li><a href="">>企业文化</a></li>-->
            </ul>
        </div>
        <div class="clearFix border-l border-r">
            <div class="icon">
                <span>整形美容</span>
                <i></i>
            </div>
            <ul class="mar_t">
                <li><a href="/projects/chest/#project_nav" target="_blank" rel="noopener">>胸部整形</a></li>
                <li><a href="/projects/eye/#project_nav" target="_blank" rel="noopener">>眼部整形</a></li>
                <li><a href="/projects/nose/#project_nav" target="_blank" rel="noopener">>鼻部整形</a></li>
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>唇部整形</a></li>
                <li><a href="/projects/body/#project_nav" target="_blank" rel="noopener">>塑形体雕</a></li>
                <li><a href="/projects/zhifang/ztzfmd.html" target="_blank" rel="noopener">>自体脂肪填充</a></li>
                <li><a href="/projects/#project_nav" target="_blank" rel="noopener">>其他系列</a></li>
                <li><a href="/projects/ha/bnsxb.html" target="_blank" rel="noopener">>下巴整形</a></li>
                <li><a href="/projects/private/#project_nav" target="_blank" rel="noopener">>私密整形</a></li>
            </ul>
        </div>
        <div class="clearFix border-l border-r">
            <div class="icon">
                <span>光学美肤</span>
                <i></i>
            </div>
            <ul class="mar_t">
                <li><a href="/projects/quban/quban.html" target="_blank" rel="noopener">>美白祛斑</a></li>
                <li><a href="/projects/tuomao/tuomao2.html" target="_blank" rel="noopener">>专业脱毛</a></li>
                <li><a href="/projects/qudou/hzqdk.html" target="_blank" rel="noopener">>祛痘祛疤印</a></li>
                <li><a href="/projects/chuzhou/quzhou.html" target="_blank" rel="noopener">>紧肤抗衰</a></li>
            </ul>
        </div>
        <div class="clearFix border-l">
            <div class="icon">
                <span>微创美容</span>
                <i></i>
            </div>
            <ul class="mar_t">
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>玻尿酸塑形</a></li>
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>玻尿酸祛皱</a></li>
                <li><a href="/projects/botox/#project_nav" target="_blank" rel="noopener">>BOTOX注射</a></li>
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>疤痕针</a></li>
                <li><a href="/projects/tattoo/#project_nav" target="_blank" rel="noopener">>纹绣</a></li>
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>水光注射</a></li>
                <li><a href="/projects/#project_nav" target="_blank" rel="noopener">>其他</a></li>
            </ul>
        </div>
    </div>
</div>
<footer id="footer">
    <div class="shuang_m1 clearFix">
        <div class="left">
            <h2><a href=""><img src="https://img.hzshuangmei.com/pc/f_logo.png" alt="红妆双美"/></a></h2>
            <p class="addr"><i></i>红妆双美地址：海口市海府路4号海口宾馆附楼2层</p>
            <p>本站信息仅供参考建 版权所有:红妆双美 https://www.hzshuangmei.com<br/>
                <a href="http://www.miitbeian.gov.cn/" rel="nofollow" target="_blank">琼ICP备17004048号-1</a> (海)医广[2017]第085号 <a href="//www.hzshuangmei.com/humans.txt" rel="nofollow" target="_blank"><img src="//img.hzshuangmei.com/pc/humanstxt-transparent-color.png" class="humanstxt"></a><br/>
                网站部分图文来源于网络，如有侵权，请联系我们 联系电话：0898-66156043</p>
        </div>
        <div class="middle"></div>
        <div class="right right1">
            <div class="right_t clearFix">
                <div class="clearFix">
                    <div class="ewm"></div>
                    <div>
                        <p class="fon1">微信扫一扫</p>

                        <p>1）获得最新优惠</p>

                        <p>2）在线实时咨询</p>

                        <p>3）专属服务通道</p>
                    </div>
                </div>

                <div class="clearFix">
                    <div class="f_phone"></div>
                    <div>
                        <p class="fon1">全国免费咨询热线</p>

                        <p class="fon2">0898-66156043</p>

                        <p class="fon3">咨询时间：8:00—20:00</p>
                    </div>
                </div>
            </div>
             <!--<div class="right_b">-->
                <!--<i></i><span>友情链接:</span>-->
                <!---->
                <!--<a href='https://www.honorreal.com/' target='_blank'>红瑞集团</a> /-->
                <!---->
                <!--<a href='https://www.hoozonspa.com' rel='nofollow' target='_blank'>红妆美容</a> /-->
                <!---->
                <!--<a href='http://www.yueyimei.com' target='_blank'>悦伊美</a> /-->
                <!---->
            <!--</div>-->
            <p class="copyright">Copyright © 2017 红妆双美 版权所有 违者必究 | <a href="/statement/copyright.html" rel="nofollow" target="_blank" rel="noopener">版权及隐私声明</a><br>
              设计,文案,技术等求职请投递至网络部root#hzwlb.org(#替换成@)</p>
        </div>
    </div>
</footer>
<!-- 右侧悬浮 开始 -->
<div class="yb_conct">
    <div class="yb_bar">
        <ul>
            <li class="yb_QQ"><a target="_blank" rel="noopener" href="javascript:void(0)" class="j-site-consult" title="立即咨询" rel="nofollow">立即咨询</a></li>
            <li class="yb_phone"><a target="_blank" rel="noopener" href="javascript:void(0)" class="j-site-consult" title="门店查询" rel="nofollow">门店查询</a></li>
            <li class="yb_top">返回顶部</li>
            <li class="yb_ercode" >微信扫一扫<br>
                <img class="hd_qr" src="https://img.hzshuangmei.com/pc/WeChatApplet.jpg" width="125" alt="关注微信小程序">
            </li>
        </ul>
    </div>
</div>
<!-- 结束 -->

</body>
<link rel="preload" href="https://js.hzshuangmei.com/pc/common.js" as="script" crossorigin>
<link rel="preload" href="https://js.hzshuangmei.com/pc/layer/layer.js" as="script" crossorigin>
<link rel="preload" href="https://js.hzshuangmei.com/pc/kst_popup.js" as="script" crossorigin>
<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/Swiper/3.4.2/js/swiper.min.js"></script>
<script src="https://js.hzshuangmei.com/pc/common.js" ></script>
<script src="https://js.hzshuangmei.com/pc/layer/layer.js"></script>
<script src="https://js.hzshuangmei.com/pc/kst_popup.js"></script>
 <!-- html5标签兼容ie低版本浏览器 -->
<!-- [if lt IE 9]>     -->
<script src="https://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<!-- <![endif] -->
<!-- 百度站内搜索 -->
<!-- <script type="text/javascript">(function(){document.write(unescape('%3Cdiv id="bdcs"%3E%3C/div%3E'));var bdcs = document.createElement('script');bdcs.type = 'text/javascript';bdcs.async = true;bdcs.src = '//znsv.baidu.com/customer_search/api/js?sid=5257607230163915007' + '&plate_url=' + encodeURIComponent(window.location.href) + '&t=' + Math.ceil(new Date()/3600000);var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(bdcs, s);})();</script> -->


<script>
    $(".jiantou").hover(function () {
        $(this).css({
                'background-color':'#89363d',
            'color':'white',
            'width;':'176px',
            'height':'67px'
        }
           ).siblings().css({
                'background-color':'transparent',
            'color':'#6a5e5e'
        }
           );
        var i=$(this).index();
        $(".pagecont").eq(i).css('display','block').siblings().css('display',"none")
    })
</script>
</html>
