<!DOCTYPE html>
<html lang="zh-cmn-Hans">
<head>
    <!-- Make 2018-04-19 16:50:02 -->
<!-- Make 1524127802 -->
<meta charset="UTF-8">
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
<meta name="renderer" content="webkit"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
<meta name=applicable-device content="pc">
<meta http-equiv="Cache-Control" content="no-transform"/>
<meta http-equiv="Cache-Control" content="no-siteapp"/>
<meta name="baidu-site-verification" content="99J7V1k1Vz" />
<meta name="google-site-verification" content="Odmo8X4zeUG1WPcCrCAueZz-dyBPFBs4Zqlb9FBT5z4" />
<meta http-equiv="Access-Control-Allow-Origin" content="*" />
<!-- Global site tag (gtag.js) - Google Analytics -->
<!-- <script async src="https://www.googletagmanager.com/gtag/js?id=UA-114904919-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-114904919-2');
</script> -->

    <title>双眼皮价格解密_眼部_海南红妆时尚双美整形美容连锁</title>
    <meta property="og:type" content="article"/>
    <meta property="article:author" content="红妆双美"/>
    <meta property="article:published_time" content="2018-03-14T19:04:44+08:00" />
    <meta name="keywords" content="双眼皮,价格解密,双眼皮价格解密"/>
    <meta name="description" content="双眼皮属于有风险的细致手术，一定要选择专业整形医院！海口红妆双眼皮-海口红妆双眼皮哪家好-海南红妆医学美容医院"/>
    <meta property="article:tag" content="双眼皮,价格解密,双眼皮价格解密">
    <link rel="canonical" href="https://www.hzshuangmei.com/projects/eye/sypjgjm.html" />
    <link rel="alternate" media="only screen and(max-width: 640px)" href="https://m.hzshuangmei.com/projects/eye/sypjgjm.html" >
    <!-- Pre for optimization -->
<link rel="dns-prefetch" href="https://cdn.bootcss.com">
<link rel="dns-prefetch" href="https://uploads.hzshuangmei.com">
<link rel="dns-prefetch" href="https://img.hzshuangmei.com">
<link rel="dns-prefetch" href="https://css.hzshuangmei.com">
<link rel="dns-prefetch" href="https://js.hzshuangmei.com">
<link rel="dns-prefetch" href="https://pv.kuaishang.cn">
<link rel="dns-prefetch" href="https://z8.cnzz.com">
<link rel="dns-prefetch" href="https://s19.cnzz.com">
<link rel="dns-prefetch" href="https://tag.baidu.com">
<link rel="dns-prefetch" href="https://sp0.baidu.com">
<link rel="preload" href="https://css.hzshuangmei.com/pc/common.css" as="style" crossorigin />
<link rel="preload" href="https://img.hzshuangmei.com/pc/favicon.ico" as="image" type="image/x-icon" crossorigin />
<!-- Style for the page-->
<link rel="stylesheet" href="https://cdn.bootcss.com/Swiper/3.4.2/css/swiper.min.css"/>
<link rel="stylesheet" href="https://css.hzshuangmei.com/pc/common.css"/>
<link rel="stylesheet" href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" >
<!-- favicon.ico -->
<link rel="icon" href="https://img.hzshuangmei.com/pc/favicon.ico" type="image/x-icon"/>
<link rel="shortcut icon" href="https://img.hzshuangmei.com/pc/favicon.ico" type="image/x-icon"/>
<!-- humanstxt -->
<link rel="author" href="https://www.hzshuangmei.com/humans.txt" />
<link rel="preload" as=image  href="https://img.hzshuangmei.com/pc/kst/default.png">
<link rel="prefetch" src="https://img.hzshuangmei.com/pc/kst/default.png">
<link rel="prerender" src="https://img.hzshuangmei.com/pc/kst/default.png">
<link rel="prefetch" src="https://img.hzshuangmei.com/pc/kst/sypjgjm.png">
<link rel="prerender" src="https://img.hzshuangmei.com/pc/kst/sypjgjm.png">
<link rel="preload" as=image  href="https://img.hzshuangmei.com/pc/kst/sypjgjm.png">

     <link rel="preload" href="https://css.hzshuangmei.com/pc/tjb.css" as="style" crossorigin />
    <link rel="stylesheet" href="https://css.hzshuangmei.com/pc/tjb.css"/>
    <meta content="设计王璠，前端羊夏文/" name="author" />
<link href="//css.hzshuangmei.com/pc/sypjgjm/css/css.css" rel="stylesheet" />
<link href="//css.hzshuangmei.com/pc/sypjgjm/css/bootstrap.min.css" rel="stylesheet" />

<body>
<header>
    <div class="top">
        <div class="shuang_m1 clearFix">
            <div class="top_l">
                <!--<span>香港红瑞集团 旗下品牌 海南红妆双美连锁</span>-->
                <img src="https://img.hzshuangmei.com/pc/tl_logo.png" alt="logo" />|<span>美丽时间：周一周日9点--21点</span>
            </div>
            <!-- 增加百度站内搜索 -->
            <div class="top_c">
                <div class="search_box">
                    <form action="https://www.hzshuangmei.com/search/" target="_blank" autocomplete="off" id="bdcs-search-form" class="site-search-form">
                        <input type="hidden" name="s" value="5257607230163915007">
                         <input type="hidden" name="entry" value="1">
                        <input type="text" placeholder="请输入您要搜索的内容..." id="bdcsMain" name="q">
                        <button type="submit" id="bdcs-search-form-submit"></button>
                    </form>
                </div>
            </div>
                        <!-- 增加百度站内搜索 -->
            <div class="top_r">
                <a href="" class="pad_r"><i class="tel"></i><span>0898-66156043</span></a>
                <span>关注我们：</span>
                <a href="" class="pad_l"><i class="wbo"></i></a>
                <a href=""><i class="wxin"></i></a>
                <a href=""><i class="qq"></i></a>
            </div>
        </div>
    </div>
    <div class="sm_logo">
        <a href="/"><img src="https://img.hzshuangmei.com/pc/h_logo.png" alt=""/></a>
    </div>
</header>
<nav id="nav">
    <ul class="shuang_m1 nav_ul">
        <li class="nav_list">
            <a href="/" class="nav_link" target="_blank" rel="noopener">
                <span>首 页</span><br/>
                <span>Home</span>
            </a>
        </li>
        <li class="nav_list">
            <a href="/brand" class="nav_link bor_r" target="_blank" rel="noopener">
                <span>品 牌</span><br/>
                <span>brands</span>
            </a>
        </li>
        <li class="nav_list">
            <a href="/projects" class="nav_link bor_l bor_r" target="_blank" rel="noopener">
                <span>项 目</span><br/>
                <span>projects</span>
            </a>
            <div class="clearFix" id="project">
                <ul>
                    <li>
                        <h5><a href="/projects/tattoo/" target="_blank" rel="noopener">医学纹绣</a></h5>
                    </li>
                    <!--              <li>
                        <a href="/projects/tattoo/yanxian.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P4041610355P.jpg" alt="红妆艺术美瞳线"/>
                            <p><i></i><span>红妆艺术美瞳线</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/tattoo/hsbyjwm.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404160923556.jpg" alt="韩式半永久纹眉"/>
                            <p><i></i><span>韩式半永久纹眉</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/tattoo/xwx.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/img/180331/1-1P3311106490-L.jpg" alt="洗纹绣"/>
                            <p><i></i><span>洗纹绣</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/tattoo/xwx.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/img/180331/1-1P3311106490-L.jpg" alt="洗纹绣"/>
                            <p><i></i><span>洗纹绣</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/tattoo/wash.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180222/1-1P222110205243.jpg" alt="激光洗纹绣"/>
                            <p><i></i><span>激光洗纹绣</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/tattoo/hsbyjwm.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404160923556.jpg" alt="韩式半永久纹眉"/>
                            <p><i></i><span>韩式半永久纹眉</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button">-->
                    <!--<a href="/projects" target="_blank" rel="noopener">查看更多</a>-->
                    <!--</li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/eye/" target="_blank" rel="noopener">眼部整形</a></h5>
                    </li>
                    <!--   <li>
                        <a href="/projects/eye/qmtm.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404161354458.jpg" alt=""/>
                            <p><i></i><span>切眉提眉术</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/eye/slxc.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180222/1-1P22216455E61.jpg" alt=""/>
                            <p><i></i><span>上睑下垂</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/eye/yandai.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404160Q03S.jpg" alt=""/>
                            <p><i></i><span>无痕祛眼袋</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/eye/yandai.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404160Q03S.jpg" alt="无痕祛眼袋"/>
                            <p><i></i><span>无痕祛眼袋</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/eye/slxc.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180222/1-1P22216455E61.jpg" alt="上睑下垂"/>
                            <p><i></i><span>上睑下垂</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/eye/hzyj.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180206/1-1P206100342338.jpg" alt="红妆孕睫术"/>
                            <p><i></i><span>红妆孕睫术</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/nose/" target="_blank" rel="noopener">鼻部整形</a></h5>
                    </li>
                    <!--              <li>
                        <a href="/projects/nose/lineeaglenose.html" target="_blank" rel="noopener">
                        <img src="https://uploads.hzshuangmei.com/180109/1-1P10916214I29.jpg" alt=""/>
                            <p><i></i><span>线雕隆鼻</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/nose/heben.html" target="_blank" rel="noopener">
                        <img src="https://uploads.hzshuangmei.com/180109/1-1P109162114246.jpg" alt=""/>
                            <p><i></i><span>红妆赫本软骨鼻</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/nose/longbijiage.html" target="_blank" rel="noopener">
                        <img src="https://uploads.hzshuangmei.com/180209/1-1P2091524433K.jpg" alt=""/>
                            <p><i></i><span>隆鼻价格</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/nose/longbijiage.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180209/1-1P2091524433K.jpg" alt="隆鼻价格"/>
                            <p><i></i><span>隆鼻价格</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/nose/hzbbqb.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180208/1-1P20QZ14O61.jpg" alt="红妆芭比翘鼻"/>
                            <p><i></i><span>红妆芭比翘鼻</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/nose/nose.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180109/1-1P109161Fc42.jpg" alt="全立体鼻缩窄术"/>
                            <p><i></i><span>全立体鼻缩窄术</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/face/" target="_blank" rel="noopener">面部整形</a></h5>
                    </li>
                    <!--                <li class="star">
                        <a href="/projects/zhifang/ztzfmd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180109/1-1P109162329454.jpg" alt=""/>
                            <p><i></i><span>自体脂肪面雕</span></p>
                        </a>
                    </li><li class="star">
                        <a href="/projects/xiaba/vlmxd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P40416062R04.jpg" alt=""/>
                            <p><i></i><span>v立美线雕</span></p>
                        </a>
                    </li><li class="star">
                        <a href="/projects/face/zitizhifang.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180208/1-1P20Q54P4G4.jpg" alt=""/>
                            <p><i></i><span>自体脂肪面部填充</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/face/zitizhifang.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180208/1-1P20Q54P4G4.jpg" alt="自体脂肪面部填充"/>
                            <p><i></i><span>自体脂肪面部填充</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/xiaba/vlmxd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P40416062R04.jpg" alt="v立美线雕"/>
                            <p><i></i><span>v立美线雕</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/zhifang/ztzfmd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180109/1-1P109162329454.jpg" alt="自体脂肪面雕"/>
                            <p><i></i><span>自体脂肪面雕</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/skin/" target="_blank" rel="noopener">皮肤美容</a></h5>
                    </li>
                    <!--                 <li>
                        <a href="/projects/qudou/duoweiqd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180222/1-1P222143953U0.jpg" alt=""/>
                            <p><i></i><span>红妆多维祛痘</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/quban/xpmqb.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180328/1-1P32Q356202V.jpg" alt=""/>
                            <p><i></i><span>红妆皮秒祛斑</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/skin/sgz.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180406/1-1P4061A303F6.jpg" alt=""/>
                            <p><i></i><span>水光针</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/quban/xpmqb.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180328/1-1P32Q356202V.jpg" alt="红妆皮秒祛斑"/>
                            <p><i></i><span>红妆皮秒祛斑</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/chuzhou/quzhou.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180212/1-1P212102446403.jpg" alt="除皱抗衰"/>
                            <p><i></i><span>除皱抗衰</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/quban/quban.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180312/1-1P3121601494G.jpg" alt="红妆祛斑"/>
                            <p><i></i><span>红妆祛斑</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/ha/" target="_blank" rel="noopener">玻尿酸</a></h5>
                    </li>
                    <!--                     <li>
                        <a href="/projects/ha/qydbns.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180208/1-1P20Q0501X26.jpg" alt=""/>
                            <p><i></i><span>乔雅登玻尿酸</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/ha/zhbns.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180109/1-1P109161SV57.jpg" alt=""/>
                            <p><i></i><span>综合玻尿酸</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/ha/restylane.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180413/1-1P413100FcV.jpg" alt=""/>
                            <p><i></i><span>瑞蓝玻尿酸</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/ha/restylane.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180413/1-1P413100FcV.jpg" alt="瑞蓝玻尿酸"/>
                            <p><i></i><span>瑞蓝玻尿酸</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/ha/bnsqflw.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180411/1-1P411140P9134.jpg" alt="玻尿酸祛除法令纹"/>
                            <p><i></i><span>玻尿酸祛除法令纹</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/ha/xbnsfet.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180322/1-1P322092GMV.jpg" alt="玻尿酸丰额头"/>
                            <p><i></i><span>玻尿酸丰额头</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/body/" target="_blank" rel="noopener">形体雕塑</a></h5>
                    </li>
                    <!-- <li>
                        <a href="/projects/body/sdlxz.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404161320X4.jpg" alt=""/>
                            <p><i></i><span>水动力吸脂</span></p>
                       </a>
                    </li> -->
                    <li>
                        <a href="/projects/body/sdlxz.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404161320X4.jpg" alt="水动力吸脂"/>
                            <p><i></i><span>水动力吸脂</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
            </div>
        </li>
        <li class="nav_list">
            <a href="/doctors" class="nav_link bor_l bor_r" target="_blank" rel="noopener">
                <span>专 家</span><br/>
                <span>experts</span>
            </a>
            <div id="expert">
                <ul>
                    <li>
                        <h5><a href="/doctors/surgery" target="_blank" rel="noopener">整形美容专家</a></h5>
                    </li>
                    <!--                     <li>
                        <a href="/plugin/view.php?aid=227" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180414/1-1P4140929454T.jpg" alt="薛开兴"/>
                            <p><span class="n_f">薛开兴</span><span class="n_b">整形外科院长</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=153" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180131/1-1P131093205432.jpg" alt="余志亮"/>
                            <p><span class="n_f">余志亮</span><span class="n_b">整形专家</span></p>
                            <i></i>
                        </a>
                    </li> -->
                    <li>
                        <a href="/doctors/surgery/guanhaitao.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180227/1-1P22G44625M2.jpg" alt="关海涛 "/>
                            <p><span class="n_f">关海涛 </span><span class="n_b">整形外科院长</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=176" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180131/1-1P1310U92D41.jpg" alt="朱红振"/>
                            <p><span class="n_f">朱红振</span><span class="n_b">整形外科院长</span></p>
                            <i></i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <h5><a href="/doctors/laser" target="_blank" rel="noopener">激光美容专家</a></h5>
                    </li>
                    <!--             <li>
                        <a href="/doctors/laser/lijie.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/171206/1-1G20611435D10.jpg" alt="李杰"/>
                            <p><span class="n_f">李杰</span><span class="n_b">光学美肤中心院长</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/doctors/laser/yzw.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180131/1-1P131104604521.jpg" alt="姚志文"/>
                            <p><span class="n_f">姚志文</span><span class="n_b">非手术面部年轻化专家</span></p>
                            <i></i>
                        </a>
                    </li> -->
                    <li>
                        <a href="/doctors/laser/lijie.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/171206/1-1G20611435D10.jpg" alt="李杰"/>
                            <p><span class="n_f">李杰</span><span class="n_b">光学美肤中心院长</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/doctors/laser/yzw.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180131/1-1P131104604521.jpg" alt="姚志文"/>
                            <p><span class="n_f">姚志文</span><span class="n_b">非手术面部年轻化专家</span></p>
                            <i></i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <h5><a href="/doctors/tattoo" target="_blank" rel="noopener">医学纹绣</a></h5>
                    </li>
                    <!--                    <li>
                        <a href="/plugin/view.php?aid=139" target="_blank" rel="noopener">
                    <img src="https://uploads.hzshuangmei.com/180117/1-1P11GF5391A.jpg" alt="杨小丽"/>
                            <p><span class="n_f">杨小丽</span><span class="n_b">纹饰指导师</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=136" target="_blank" rel="noopener">
                    <img src="https://uploads.hzshuangmei.com/180125/1-1P125154A1105.jpg" alt="高方云"/>
                            <p><span class="n_f">高方云</span><span class="n_b">纹饰指导师</span></p>
                            <i></i>
                        </a>
                    </li> -->
                    <li>
                        <a href="/plugin/view.php?aid=164" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180125/1-1P12515435J45.jpg" alt="冯晓琳"/>
                            <p><span class="n_f">冯晓琳</span><span class="n_b">纹饰技术总指导师</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=137" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180117/1-1P11GA95JV.jpg" alt="孟超"/>
                            <p><span class="n_f">孟超</span><span class="n_b">纹饰指导师</span></p>
                            <i></i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <h5><a href="/doctors" target="_blank" rel="noopener">特邀专家</a></h5>
                    </li>
                    <li>
                        <a href="/doctors/surgery/ljb.html" target="_blank" rel="noopener">
                             <img src="https://uploads.hzshuangmei.com/180131/1-1P131092S24W.jpg" alt="雷建波(客座)"/>
                            <p><span class="n_f">雷建波(客座)</span><span class="n_b">整形美容专家</span></p>
                            <i></i>
                        </a>
                    </li>
<li>
                        <a href="/doctors/surgery/liudalie.html" target="_blank" rel="noopener">
                             <img src="https://uploads.hzshuangmei.com/171223/1-1G223091J5950.jpg" alt="柳大烈(客座)"/>
                            <p><span class="n_f">柳大烈(客座)</span><span class="n_b">教授</span></p>
                            <i></i>
                        </a>
                    </li>

                </ul>
                <ul>
                    <li>
                        <h5 class="moon"><a href="/doctors" target="_blank" rel="noopener">每月专家</a></h5>
                    </li>
                    <li class="last-one">
                        <!--<a class="last-one" href="https://www.hzshuangmei.com/doctors/surgery/liudalie.html " target="_blank" rel="noopener">-->
                            <!--<img src="https://img.hzshuangmei.com/pc/nav_zhuanjial.jpg" alt=""/>-->
                        <!--</a>-->
                        <a class="last-one j-consult" href="javascript:void(0)"  target="_blank" rel="noopener nofollow">
                            <img src="https://img.hzshuangmei.com/pc/myzzj.jpg" alt=""/>
                        </a>
                    </li>
                </ul>
            </div>
        </li>
        <li class="nav_list">
            <a href="/cases" class="nav_link bor_l bor_r" target="_blank" rel="noopener">
                <span>真人秀</span><br/>
                <span>Show</span>
            </a>
        </li>
        <li class="nav_list">
            <a href="/news" class="nav_link bor_l" target="_blank" rel="noopener">
            <span>活 动</span><br/>
                <span>News</span>
            </a>
        </li>
    </ul>
</nav>

<div class="banner">
	<img alt="海口红妆" src="//img.hzshuangmei.com/pc/sypjgjm/images/banner.jpg" />
	<div class="sr-only">
		<h1>
			双眼皮价格解密</h1>
		<p>
			灵韵自然，专业塑美</p>
		<ul>
			<li>
				美学设计</li>
			<li>
				专属定制</li>
			<li>
				宛若天生</li>
			<li>
				安全无痛</li>
		</ul>
	</div>
</div>
<div class="part1 row clearfix">
	<div class="title">
		<h2>
			这些的确<span>很便宜</span>，但是你真的<span>敢吗？</span></h2>
	</div>
	<div class="main clearfix">
		<div class="first">
			<h3>
				工作室</h3>
			<p>
				既没有医疗执照也没有医生资质</p>
			<span>有些美容院为了盈利，超出审批范围经营，<br />
			结果让人触目惊心</span></div>
		<div class="second">
			<h3>
				实习医生</h3>
			<p>
				年轻无经验医生用来实验</p>
			<span>综合医院的整形科在医生技术上都<br />
			相对薄弱，往往沦为年轻实习医生<br />
			的实验品。</span></div>
		<div class="third">
			<h3>
				私人门诊</h3>
			<p>
				手术没有保障</p>
			<span>职业资格证存疑，手术器械落后，卫生环境<br />
			差、手术过程不规范都存在很大的术后<br />
			隐患。</span></div>
		<img alt="海口红妆" src="//img.hzshuangmei.com/pc/sypjgjm/images/img_part1-1.png" /> <img alt="海口红妆" class="img_2" src="//img.hzshuangmei.com/pc/sypjgjm/images/img_part1-2.png" /> <img alt="海口红妆" class="img_3" src="//img.hzshuangmei.com/pc/sypjgjm/images/img_part1-3.png" /></div>
	<div class="bottom">
		<div class="left">
			<p class="tip">
				Tips</p>
			<p>
				EXPERTS</p>
			<h2>
				专家提醒</h2>
		</div>
		<div class="right">
			<p>
				双眼皮属于有风险的细致手术，一定要选择<br />
				<span>专业整形医院！</span></p>
		</div>
	</div>
</div>
<div class="part2 row">
	<div class="title">
		<h2>
			<span>改变</span>&middot;遇见<span>最美</span>的自己</h2>
	</div>
	<div class="main">
		<div class="wrap">
			<div class="next">
				<img alt="海南红妆" src="//img.hzshuangmei.com/pc/sypjgjm/images/igm_next.jpg" /></div>
			<div class="prev">
				<img alt="海南红妆" src="//img.hzshuangmei.com/pc/sypjgjm/images/img_prev.jpg" /></div>
			<div class="imgwrap">
				<div class="slider">
					<img alt="海南红妆" src="//img.hzshuangmei.com/pc/sypjgjm/images/img_part2-1.jpg" /> <img alt="海南红妆" src="//img.hzshuangmei.com/pc/sypjgjm/images/img_part2-2.jpg" /></div>
			</div>
		</div>
	</div>
</div>
<div class="part3 row">
	<div class="title">
		<h2>
			一样的钱，不一样的<span>超值尊贵享受</span></h2>
	</div>
	<div class="main">
		<ul class="clearfix">
			<li>
				<h3>
					专业定制</h3>
				<p>
					专业医生免费设计综合<br />
					美眼方案</p>
				<img alt="海南红妆" src="//img.hzshuangmei.com/pc/sypjgjm/images/img_part3-1.jpg" /></li>
			<li>
				<h3>
					隐私保密</h3>
				<p>
					严格保证客户隐私<br />
					签订协议安心求美</p>
				<img alt="海南红妆" src="//img.hzshuangmei.com/pc/sypjgjm/images/img_part3-3.jpg" /></li>
			<li>
				<h3>
					严格检查</h3>
				<p>
					手术前严格检查身体情况</p>
				<img alt="海南红妆" src="//img.hzshuangmei.com/pc/sypjgjm/images/img_part3-2.jpg" /></li>
			<li class="no-right">
				<h3>
					专业医生</h3>
				<p>
					由专业医生团队<br />
					亲自打造</p>
				<img alt="海南红妆" src="//img.hzshuangmei.com/pc/sypjgjm/images/img_part3-4.jpg" /></li>
		</ul>
		<ul class="Ul2">
			<li>
				<h3>
					严格标准</h3>
				<p>
					手术操作规范严格执行<br />
					世界卫生组织标准</p>
				<img alt="海南红妆" src="//img.hzshuangmei.com/pc/sypjgjm/images/img_part3-5.jpg" /></li>
			<li>
				<h3>
					灵韵自然</h3>
				<p>
					细腻的手术技巧<br />
					令术后双眼放大，灵韵有神</p>
				<img alt="海南红妆" src="//img.hzshuangmei.com/pc/sypjgjm/images/img_part3-6.jpg" /></li>
			<li class="no-right">
				<h3>
					贴心护理</h3>
				<p>
					术后专业护理，恢复时间短<br />
					医嘱到家</p>
				<img alt="海南红妆" src="//img.hzshuangmei.com/pc/sypjgjm/images/img_part3-7.jpg" /></li>
		</ul>
	</div>
</div>
<div class="part4 row">
	<div class="title">
		<h2>
			红妆双眼皮<span>项目解密</span></h2>
	</div>
	<div class="main">
		<div class="contain clearfix">
			<h2>
				1、埋线法</h2>
			<h3>
				拥有明媚、清晰双眼的秘诀</h3>
			<p class="p_3">
				<span>适合人群：</span>&nbsp;&nbsp;眼睑较薄或者眼睑下垂较轻者</p>
			<p>
				<span>手术时间：</span>&nbsp;&nbsp;20-30分钟&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span>麻醉方式：</span>&nbsp;&nbsp;局部麻醉</p>
			<p>
				<span>拆线时间：</span>&nbsp;&nbsp;无需拆线</p>
			<img alt="海南红妆" class="img_6" src="//img.hzshuangmei.com/pc/sypjgjm/images/img_part4_mai-1.jpg" /> <img alt="海南红妆" class="img_7" src="//img.hzshuangmei.com/pc/sypjgjm/images/img_part4_mai-2.jpg" />
			<div class="contact">
				<a class="j-consult prise" href="javascript:void(0)" rel="nofollow"><span>咨询价格&gt;</span> </a> <a class="j-consult appointement" href="javascript:void(0)" rel="nofollow"> <span>预约医生&gt;</span> </a></div>
		</div>
		<div class="contain clearfix contain_2">
			<img alt="海南红妆" src="//img.hzshuangmei.com/pc/sypjgjm/images/img_part4_weichuang-1.jpg" />
			<h2>
				2、微创三点定位法</h2>
			<h3>
				眼睛变大，变精神的秘诀</h3>
			<p class="p_4">
				<span>适合人群：</span>&nbsp;&nbsp;眼睑皮肤薄、眼裂长、鼻梁高的求美者</p>
			<p>
				<span>手术时间：</span>&nbsp;&nbsp;30-40分钟 <span>麻醉方式：</span>&nbsp;&nbsp;局部麻醉</p>
			<p>
				<span>拆线时间：</span>&nbsp;&nbsp;7天拆线</p>
			<img alt="海南红妆" class="img_7" src="//img.hzshuangmei.com/pc/sypjgjm/images/img_part4_weichuang-2.jpg" />
			<div class="contact">
				<a class="j-consult prise" href="javascript:void(0)" rel="nofollow"><span>咨询价格&gt;</span> </a> <a class="j-consult appointement" href="javascript:void(0)" rel="nofollow"> <span>预约医生&gt;</span> </a></div>
		</div>
		<div class="contain clearfix contain_3">
			<h2>
				3、隐形全切法</h2>
			<h3>
				精微细雕，毫厘细节，小整形，大改变</h3>
			<p class="p_3">
				<span>适合人群：</span>&nbsp;&nbsp;各种类型、任何年龄的单眼皮，对上眼睑皮肤松弛和<br />
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;上脸臃肿者尤为适宜</p>
			<p class="p_4">
				<span>手术时间：</span>&nbsp;&nbsp;30-40分钟&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span>麻醉方式：</span>&nbsp;&nbsp;局部麻醉</p>
			<p>
				<span>拆线时间：</span>&nbsp;&nbsp;7天左右拆线</p>
			<img alt="海南红妆" class="img_6" src="//img.hzshuangmei.com/pc/sypjgjm/images/img_part4_yinxing-1.jpg" /> <img alt="海南红妆" class="img_7" src="//img.hzshuangmei.com/pc/sypjgjm/images/img_part4_yinxing-2.jpg" />
			<div class="contact">
				<a class="j-consult prise" href="javascript:void(0)" rel="nofollow"><span>咨询价格&gt;</span> </a> <a class="j-consult appointement" href="javascript:void(0)" rel="nofollow"> <span>预约医生&gt;</span> </a></div>
		</div>
	</div>
</div>
<div class="part5 row">
	<div class="title">
		<h2>
			<span>实力</span>成就技术，<span>案例</span>为美记录</h2>
	</div>
	<div class="main">
		<div class="left">
			<img alt="海口红妆" class="change1" src="//img.hzshuangmei.com/pc/sypjgjm/images/bg_part5_1-1.jpg" /> <img alt="" class="change" src="//img.hzshuangmei.com/pc/sypjgjm/images/igm_next.jpg" /> <img alt="海口红妆" class="change2" src="//img.hzshuangmei.com/pc/sypjgjm/images/bg_part5_1-2.jpg" /></div>
		<div class="right">
			<img alt="海口红妆" class="change1" src="//img.hzshuangmei.com/pc/sypjgjm/images/bg_part5_2-1.jpg" /> <img alt="海口红妆" class="change" src="//img.hzshuangmei.com/pc/sypjgjm/images/igm_next.jpg" /> <img alt="海口红妆" class="change2" src="//img.hzshuangmei.com/pc/sypjgjm/images/bg_part5_2-2.jpg" /></div>
	</div>
</div>
<div class="title last">
	<h2>
		<span>红妆美眼</span>专家</h2>
</div>
<div class="part6 row">
	<div class="main">
		<div class="name">
			<h2>
				关海涛</h2>
			<p>
				DOCTOR</p>
			<p class="last">
				整形专家</p>
		</div>
		<div class="summary">
			<p class="p_1">
				达拉斯隆鼻海南技术带头人</p>
			<p>
				国际医疗美容整形协会会员</p>
			<p>
				大韩整形美容外科协会荣誉会员</p>
			<p>
				中国医师协会整形与美容分会会会员</p>
			<p>
				第31、39届中韩国际整形美容交流会专家组核心成员</p>
		</div>
		<h3>
			擅长</h3>
		<p>
			眼部综合整形、达拉斯鼻部整形、鼻部综合整形、大韩加减鼻雕</p>
		<div class="contact">
			<a class="j-consult prise" href="javascript:void(0)" rel="nofollow"><span>咨询价格&gt;</span> </a> <a class="j-consult appointement" href="javascript:void(0)" rel="nofollow"> <span>预约医生&gt;</span> </a></div>
	</div>
</div>


<div  class="tjb">
    <div class="m_rj">
        <!--<div class="tjb_title1">-->
            <!--<img src="https://img.hzshuangmei.com/pc/tjb_title1.png" alt=""/>-->
        <!--</div>-->
               <div class="tjb_title1">
            <img src="https://img.hzshuangmei.com/pc/tjb_title1.png" alt="相关日记"/>
        </div><ul class="tjb_rj clearFix"> <li>
              <a href="/cases/eye/117.html" class="tbj_t" target="_blank">
                  <img src="https://uploads.hzshuangmei.com/180108/2-1P10QFG55P.jpg" alt="术后"/>
              </a>
              <div class="tbj_b">
                  <a href="/cases/eye/117.html" class="tbj_b_img" target="_blank"><img src="https://uploads.hzshuangmei.com/180108/2-1P10QFF0540.jpg" alt="术前"/></a>
                     <p class="p1 tbj_b_p1">【 速美项目 】</p>
                  <p class="p2"><a href="https://www.hzshuangmei.com/projects/eye/qjsyp.html">双眼皮手术</a>、<a href="https://www.hzshuangmei.com/projects/eye/kyj.html">开内眼角手术</a></p>
                  <a href="/cases/eye/117.html" class="tjb_video" target="_blank"><img src="//img.hzshuangmei.com/pc/tjb_video.png" alt="整形案例视频"/></a>
              </div>
              </li><li>
              <a href="/cases/eye/91.html" class="tbj_t" target="_blank">
                  <img src="https://uploads.hzshuangmei.com/171206/2-1G206153935255.jpg" alt="术后"/>
              </a>
              <div class="tbj_b">
                  <a href="/cases/eye/91.html" class="tbj_b_img" target="_blank"><img src="https://uploads.hzshuangmei.com/171206/2-1G206153Z9547.jpg" alt="术前"/></a>
                     <p class="p1 tbj_b_p1">【 速美项目 】</p>
                  <p class="p2"><a href="https://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;fi=68948">灵动翘睫双眼皮</a></p>
                  <a href="/cases/eye/91.html" class="tjb_video" target="_blank"><img src="//img.hzshuangmei.com/pc/tjb_video.png" alt="整形案例视频"/></a>
              </div>
              </li><li>
              <a href="/cases/eye/116.html" class="tbj_t" target="_blank">
                  <img src="https://uploads.hzshuangmei.com/180110/2-1P1101624453U.jpg" alt="术后"/>
              </a>
              <div class="tbj_b">
                  <a href="/cases/eye/116.html" class="tbj_b_img" target="_blank"><img src="https://uploads.hzshuangmei.com/180108/2-1P10Q6323E06.jpg" alt="术前"/></a>
                     <p class="p1 tbj_b_p1">【 速美项目 】</p>
                  <p class="p2"><a href="https://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;fi=68948">芭比大眼术</a>、<a href="https://ryak66.kuaishang.cn/bs/im.htm?cas=58194___765150&amp;fi=68948">芭比翘鼻</a></p>
                  <a href="/cases/eye/116.html" class="tjb_video" target="_blank"><img src="//img.hzshuangmei.com/pc/tjb_video.png" alt="整形案例视频"/></a>
              </div>
              </li></ul>
    </div>
    <div class="m_zj">
        <!--<div class="tjb_title2">-->
            <!--<img src="https://img.hzshuangmei.com/pc/tjb_title2.png" alt=""/>-->
        <!--</div>-->
             <div class="tjb_title2">
            <img src="https://img.hzshuangmei.com/pc/tjb_title2.png" alt="推荐专家"/>
        </div><ul class="tjb_zj clearFix"> <li class="clearFix">
                <a href="/plugin/view.php?aid=211" class="tjb_l" target="_blank"><img src="https://uploads.hzshuangmei.com/180321/2-1P3211409122a.jpg" alt="张子杰（客座）"/></a>
                <div class="tjb_r">
                    <p class="p3"><a href="/plugin/view.php?aid=211" class="tjb_name" target="_blank">张子杰（客座）</a></p>
                    <p class="p4"><a href="/plugin/view.php?aid=211" target="_blank">教授</a></p>
                    <div class="tjb_sc clearFix">
                        <p>擅长项目：</p>
                        <p>无创美容注射 自体脂肪移植 韩式MISKO韩式隆鼻&nbsp; </p>
                    </div>
                    <div class="tjb_button">
                        <a class="j-consult" href="javascript:void(0);" rel="nofollow" target="_blank"><img src="//img.hzshuangmei.com/pc/tjb_button.png" alt="点击咨询"/></a>
                    </div>
                </div></li><li class="clearFix">
                <a href="/doctors/surgery/ljb.html" class="tjb_l" target="_blank"><img src="https://uploads.hzshuangmei.com/180131/1-1P131092S24W.jpg" alt="雷建波(客座)"/></a>
                <div class="tjb_r">
                    <p class="p3"><a href="/doctors/surgery/ljb.html" class="tjb_name" target="_blank">雷建波(客座)</a></p>
                    <p class="p4"><a href="/doctors/surgery/ljb.html" target="_blank">整形美容专家</a></p>
                    <div class="tjb_sc clearFix">
                        <p>擅长项目：</p>
                        <p><a href="https://www.hzshuangmei.com/projects/nose/dlslb.html">达拉斯隆鼻</a> &nbsp; <a href="https://www.hzshuangmei.com/projects/nose/nose.html">全立体鼻缩窄术</a> &nbsp; <a href="https://www.hzshuangmei.com/projects/eye/qjsyp.html">双眼皮</a> </p>
                    </div>
                    <div class="tjb_button">
                        <a class="j-consult" href="javascript:void(0);" rel="nofollow" target="_blank"><img src="//img.hzshuangmei.com/pc/tjb_button.png" alt="点击咨询"/></a>
                    </div>
                </div></li></ul>
    </div>
    <div class="m_xm">
        <!--<div class="tjb_title3">-->
            <!--<img src="https://img.hzshuangmei.com/pc/tjb_title3.png" alt=""/>-->
        <!--</div>-->
        <!--<div class="tjb_xm">-->
               <div class="tjb_title3">
            <img src="https://img.hzshuangmei.com/pc/tjb_title3.png" alt="相关项目"/>
        </div><div class="tjb_xm"><div class="tjb_img clearFix">
  <a href="/projects/eye/qjsyp.html" target="_blank"><img src="https://uploads.hzshuangmei.com/180109/1-1P109162050I6.jpg" alt="红妆翘睫双眼皮"></a><a href="/projects/eye/hzsypxf.html" target="_blank"><img src="https://uploads.hzshuangmei.com/180110/1-1P1101GK5964.jpg" alt="红妆双眼皮修复"></a><a href="/projects/eye/kyj.html" target="_blank"><img src="https://uploads.hzshuangmei.com/180109/1-1P109161Z13c.jpg" alt="红妆无痕开眼角"></a>
</div>         </div>

        <!--</div>-->
    </div>
</div>
<div class="index_items" id="index_items">
    <div class="shuang_m1">
        <div class="clearFix border-r">
            <div class="icon">
                <span>双美概况</span>
                <i></i>
            </div>
            <ul class="mar_t">
                <li><a href="/" target="_blank" rel="noopener" >>返回首页</a></li>
                <li><a class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener">>来院路线</a></li>
                <li><a class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener">>联系我们</a></li>
                <li><a href="/brand" target="_blank" rel="noopener">>品牌起源</a></li>
                <!--<li><a href="">>企业文化</a></li>-->
            </ul>
        </div>
        <div class="clearFix border-l border-r">
            <div class="icon">
                <span>整形美容</span>
                <i></i>
            </div>
            <ul class="mar_t">
                <li><a href="/projects/chest/#project_nav" target="_blank" rel="noopener">>胸部整形</a></li>
                <li><a href="/projects/eye/#project_nav" target="_blank" rel="noopener">>眼部整形</a></li>
                <li><a href="/projects/nose/#project_nav" target="_blank" rel="noopener">>鼻部整形</a></li>
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>唇部整形</a></li>
                <li><a href="/projects/body/#project_nav" target="_blank" rel="noopener">>塑形体雕</a></li>
                <li><a href="/projects/zhifang/ztzfmd.html" target="_blank" rel="noopener">>自体脂肪填充</a></li>
                <li><a href="/projects/#project_nav" target="_blank" rel="noopener">>其他系列</a></li>
                <li><a href="/projects/ha/bnsxb.html" target="_blank" rel="noopener">>下巴整形</a></li>
                <li><a href="/projects/private/#project_nav" target="_blank" rel="noopener">>私密整形</a></li>
            </ul>
        </div>
        <div class="clearFix border-l border-r">
            <div class="icon">
                <span>光学美肤</span>
                <i></i>
            </div>
            <ul class="mar_t">
                <li><a href="/projects/quban/quban.html" target="_blank" rel="noopener">>美白祛斑</a></li>
                <li><a href="/projects/tuomao/tuomao2.html" target="_blank" rel="noopener">>专业脱毛</a></li>
                <li><a href="/projects/qudou/hzqdk.html" target="_blank" rel="noopener">>祛痘祛疤印</a></li>
                <li><a href="/projects/chuzhou/quzhou.html" target="_blank" rel="noopener">>紧肤抗衰</a></li>
            </ul>
        </div>
        <div class="clearFix border-l">
            <div class="icon">
                <span>微创美容</span>
                <i></i>
            </div>
            <ul class="mar_t">
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>玻尿酸塑形</a></li>
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>玻尿酸祛皱</a></li>
                <li><a href="/projects/botox/#project_nav" target="_blank" rel="noopener">>BOTOX注射</a></li>
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>疤痕针</a></li>
                <li><a href="/projects/tattoo/#project_nav" target="_blank" rel="noopener">>纹绣</a></li>
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>水光注射</a></li>
                <li><a href="/projects/#project_nav" target="_blank" rel="noopener">>其他</a></li>
            </ul>
        </div>
    </div>
</div>
<footer id="footer">
    <div class="shuang_m1 clearFix">
        <div class="left">
            <h2><a href=""><img src="https://img.hzshuangmei.com/pc/f_logo.png" alt="红妆双美"/></a></h2>
            <p class="addr"><i></i>红妆双美地址：海口市海府路4号海口宾馆附楼2层</p>
            <p>本站信息仅供参考建 版权所有:红妆双美 https://www.hzshuangmei.com<br/>
                <a href="http://www.miitbeian.gov.cn/" rel="nofollow" target="_blank">琼ICP备17004048号-1</a> (海)医广[2017]第085号 <a href="//www.hzshuangmei.com/humans.txt" rel="nofollow" target="_blank"><img src="//img.hzshuangmei.com/pc/humanstxt-transparent-color.png" class="humanstxt"></a><br/>
                网站部分图文来源于网络，如有侵权，请联系我们 联系电话：0898-66156043</p>
        </div>
        <div class="middle"></div>
        <div class="right right1">
            <div class="right_t clearFix">
                <div class="clearFix">
                    <div class="ewm"></div>
                    <div>
                        <p class="fon1">微信扫一扫</p>

                        <p>1）获得最新优惠</p>

                        <p>2）在线实时咨询</p>

                        <p>3）专属服务通道</p>
                    </div>
                </div>

                <div class="clearFix">
                    <div class="f_phone"></div>
                    <div>
                        <p class="fon1">全国免费咨询热线</p>

                        <p class="fon2">0898-66156043</p>

                        <p class="fon3">咨询时间：8:00—20:00</p>
                    </div>
                </div>
            </div>
             <!--<div class="right_b">-->
                <!--<i></i><span>友情链接:</span>-->
                <!---->
                <!--<a href='https://www.honorreal.com/' target='_blank'>红瑞集团</a> /-->
                <!---->
                <!--<a href='https://www.hoozonspa.com' rel='nofollow' target='_blank'>红妆美容</a> /-->
                <!---->
                <!--<a href='http://www.yueyimei.com' target='_blank'>悦伊美</a> /-->
                <!---->
            <!--</div>-->
            <p class="copyright">Copyright © 2017 红妆双美 版权所有 违者必究 | <a href="/statement/copyright.html" rel="nofollow" target="_blank" rel="noopener">版权及隐私声明</a><br>
              设计,文案,技术等求职请投递至网络部root#hzwlb.org(#替换成@)</p>
        </div>
    </div>
</footer>
<!-- 右侧悬浮 开始 -->
<div class="yb_conct">
    <div class="yb_bar">
        <ul>
            <li class="yb_QQ"><a target="_blank" rel="noopener" href="javascript:void(0)" class="j-site-consult" title="立即咨询" rel="nofollow">立即咨询</a></li>
            <li class="yb_phone"><a target="_blank" rel="noopener" href="javascript:void(0)" class="j-site-consult" title="门店查询" rel="nofollow">门店查询</a></li>
            <li class="yb_top">返回顶部</li>
            <li class="yb_ercode" >微信扫一扫<br>
                <img class="hd_qr" src="https://img.hzshuangmei.com/pc/WeChatApplet.jpg" width="125" alt="关注微信小程序">
            </li>
        </ul>
    </div>
</div>
<!-- 结束 -->

</body>
<link rel="preload" href="https://js.hzshuangmei.com/pc/common.js" as="script" crossorigin>
<link rel="preload" href="https://js.hzshuangmei.com/pc/layer/layer.js" as="script" crossorigin>
<link rel="preload" href="https://js.hzshuangmei.com/pc/kst_popup.js" as="script" crossorigin>
<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/Swiper/3.4.2/js/swiper.min.js"></script>
<script src="https://js.hzshuangmei.com/pc/common.js" ></script>
<script src="https://js.hzshuangmei.com/pc/layer/layer.js"></script>
<script src="https://js.hzshuangmei.com/pc/kst_popup.js"></script>
 <!-- html5标签兼容ie低版本浏览器 -->
<!-- [if lt IE 9]>     -->
<script src="https://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<!-- <![endif] -->
<!-- 百度站内搜索 -->
<!-- <script type="text/javascript">(function(){document.write(unescape('%3Cdiv id="bdcs"%3E%3C/div%3E'));var bdcs = document.createElement('script');bdcs.type = 'text/javascript';bdcs.async = true;bdcs.src = '//znsv.baidu.com/customer_search/api/js?sid=5257607230163915007' + '&plate_url=' + encodeURIComponent(window.location.href) + '&t=' + Math.ceil(new Date()/3600000);var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(bdcs, s);})();</script> -->


<script charset="utf-8" src="//js.hzshuangmei.com/pc/sypjgjm/js/js.js" type="text/javascript">
</script>
</html>
