<!DOCTYPE html>
<html lang="zh-cmn-Hans">
<head>
    <!-- Make 2018-04-21 10:00:08 -->
<!-- Make 1524276008 -->
<meta charset="UTF-8">
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
<meta name="renderer" content="webkit"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
<meta name=applicable-device content="pc">
<meta http-equiv="Cache-Control" content="no-transform"/>
<meta http-equiv="Cache-Control" content="no-siteapp"/>
<meta name="baidu-site-verification" content="99J7V1k1Vz" />
<meta name="google-site-verification" content="Odmo8X4zeUG1WPcCrCAueZz-dyBPFBs4Zqlb9FBT5z4" />
<meta http-equiv="Access-Control-Allow-Origin" content="*" />
<!-- Global site tag (gtag.js) - Google Analytics -->
<!-- <script async src="https://www.googletagmanager.com/gtag/js?id=UA-114904919-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-114904919-2');
</script> -->

    <title>红妆双美整形美容项目介绍_海南红妆时尚双美整形美容连锁</title>
      <meta name="keywords" content="红妆时尚双美连锁机构,红妆双美整形项目,红妆双美美容项目"/>
    <meta name="description" content="红妆双美整形美容项目,包含了红妆双美整形美容项目以及生活美容项目"/>
    <!-- Pre for optimization -->
<link rel="dns-prefetch" href="https://cdn.bootcss.com">
<link rel="dns-prefetch" href="https://uploads.hzshuangmei.com">
<link rel="dns-prefetch" href="https://img.hzshuangmei.com">
<link rel="dns-prefetch" href="https://css.hzshuangmei.com">
<link rel="dns-prefetch" href="https://js.hzshuangmei.com">
<link rel="dns-prefetch" href="https://pv.kuaishang.cn">
<link rel="dns-prefetch" href="https://z8.cnzz.com">
<link rel="dns-prefetch" href="https://s19.cnzz.com">
<link rel="dns-prefetch" href="https://tag.baidu.com">
<link rel="dns-prefetch" href="https://sp0.baidu.com">
<link rel="preload" href="https://css.hzshuangmei.com/pc/common.css" as="style" crossorigin />
<link rel="preload" href="https://img.hzshuangmei.com/pc/favicon.ico" as="image" type="image/x-icon" crossorigin />
<!-- Style for the page-->
<link rel="stylesheet" href="https://cdn.bootcss.com/Swiper/3.4.2/css/swiper.min.css"/>
<link rel="stylesheet" href="https://css.hzshuangmei.com/pc/common.css"/>
<link rel="stylesheet" href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" >
<!-- favicon.ico -->
<link rel="icon" href="https://img.hzshuangmei.com/pc/favicon.ico" type="image/x-icon"/>
<link rel="shortcut icon" href="https://img.hzshuangmei.com/pc/favicon.ico" type="image/x-icon"/>
<!-- humanstxt -->
<link rel="author" href="https://www.hzshuangmei.com/humans.txt" />
<link rel="preload" as=image  href="https://img.hzshuangmei.com/pc/kst/default.png">
<link rel="prefetch" src="https://img.hzshuangmei.com/pc/kst/default.png">
<link rel="prerender" src="https://img.hzshuangmei.com/pc/kst/default.png">
<link rel="prefetch" src="https://img.hzshuangmei.com/pc/kst/.png">
<link rel="prerender" src="https://img.hzshuangmei.com/pc/kst/.png">
<link rel="preload" as=image  href="https://img.hzshuangmei.com/pc/kst/.png">

    <link rel="preload" href="https://css.hzshuangmei.com/pc/list_project.css" as="style"  crossorigin />
    <link rel="preload" href="https://js.hzshuangmei.com/pc/list_project.js" as="script" crossorigin>
    <link rel="stylesheet" href="https://css.hzshuangmei.com/pc/list_project.css"/>
    <link rel="canonical" href="https://www.hzshuangmei.com/projects/">
    <link rel="alternate" media="only screen and(max-width: 640px)"     href="https://m.hzshuangmei.com/projects/" >
</head>
<body>
<header>
    <div class="top">
        <div class="shuang_m1 clearFix">
            <div class="top_l">
                <!--<span>香港红瑞集团 旗下品牌 海南红妆双美连锁</span>-->
                <img src="https://img.hzshuangmei.com/pc/tl_logo.png" alt="logo" />|<span>美丽时间：周一周日9点--21点</span>
            </div>
            <!-- 增加百度站内搜索 -->
            <div class="top_c">
                <div class="search_box">
                    <form action="https://www.hzshuangmei.com/search/" target="_blank" autocomplete="off" id="bdcs-search-form" class="site-search-form">
                        <input type="hidden" name="s" value="5257607230163915007">
                         <input type="hidden" name="entry" value="1">
                        <input type="text" placeholder="请输入您要搜索的内容..." id="bdcsMain" name="q">
                        <button type="submit" id="bdcs-search-form-submit"></button>
                    </form>
                </div>
            </div>
                        <!-- 增加百度站内搜索 -->
            <div class="top_r">
                <a href="" class="pad_r"><i class="tel"></i><span>0898-66156043</span></a>
                <span>关注我们：</span>
                <a href="" class="pad_l"><i class="wbo"></i></a>
                <a href=""><i class="wxin"></i></a>
                <a href=""><i class="qq"></i></a>
            </div>
        </div>
    </div>
    <div class="sm_logo">
        <a href="/"><img src="https://img.hzshuangmei.com/pc/h_logo.png" alt=""/></a>
    </div>
</header>
<nav id="nav">
    <ul class="shuang_m1 nav_ul">
        <li class="nav_list">
            <a href="/" class="nav_link" target="_blank" rel="noopener">
                <span>首 页</span><br/>
                <span>Home</span>
            </a>
        </li>
        <li class="nav_list">
            <a href="/brand" class="nav_link bor_r" target="_blank" rel="noopener">
                <span>品 牌</span><br/>
                <span>brands</span>
            </a>
        </li>
        <li class="nav_list">
            <a href="/projects" class="nav_link bor_l bor_r" target="_blank" rel="noopener">
                <span>项 目</span><br/>
                <span>projects</span>
            </a>
            <div class="clearFix" id="project">
                <ul>
                    <li>
                        <h5><a href="/projects/tattoo/" target="_blank" rel="noopener">医学纹绣</a></h5>
                    </li>
                    <!--              <li>
                        <a href="/projects/tattoo/yanxian.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P4041610355P.jpg" alt="红妆艺术美瞳线"/>
                            <p><i></i><span>红妆艺术美瞳线</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/tattoo/hsbyjwm.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404160923556.jpg" alt="韩式半永久纹眉"/>
                            <p><i></i><span>韩式半永久纹眉</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/tattoo/xwx.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/img/180331/1-1P3311106490-L.jpg" alt="洗纹绣"/>
                            <p><i></i><span>洗纹绣</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/tattoo/xwx.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/img/180331/1-1P3311106490-L.jpg" alt="洗纹绣"/>
                            <p><i></i><span>洗纹绣</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/tattoo/wash.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180222/1-1P222110205243.jpg" alt="激光洗纹绣"/>
                            <p><i></i><span>激光洗纹绣</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/tattoo/hsbyjwm.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404160923556.jpg" alt="韩式半永久纹眉"/>
                            <p><i></i><span>韩式半永久纹眉</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button">-->
                    <!--<a href="/projects" target="_blank" rel="noopener">查看更多</a>-->
                    <!--</li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/eye/" target="_blank" rel="noopener">眼部整形</a></h5>
                    </li>
                    <!--   <li>
                        <a href="/projects/eye/qmtm.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404161354458.jpg" alt=""/>
                            <p><i></i><span>切眉提眉术</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/eye/slxc.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180222/1-1P22216455E61.jpg" alt=""/>
                            <p><i></i><span>上睑下垂</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/eye/yandai.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404160Q03S.jpg" alt=""/>
                            <p><i></i><span>无痕祛眼袋</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/eye/yandai.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404160Q03S.jpg" alt="无痕祛眼袋"/>
                            <p><i></i><span>无痕祛眼袋</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/eye/slxc.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180222/1-1P22216455E61.jpg" alt="上睑下垂"/>
                            <p><i></i><span>上睑下垂</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/eye/hzyj.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180206/1-1P206100342338.jpg" alt="红妆孕睫术"/>
                            <p><i></i><span>红妆孕睫术</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/nose/" target="_blank" rel="noopener">鼻部整形</a></h5>
                    </li>
                    <!--              <li>
                        <a href="/projects/nose/lineeaglenose.html" target="_blank" rel="noopener">
                        <img src="https://uploads.hzshuangmei.com/180109/1-1P10916214I29.jpg" alt=""/>
                            <p><i></i><span>线雕隆鼻</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/nose/heben.html" target="_blank" rel="noopener">
                        <img src="https://uploads.hzshuangmei.com/180109/1-1P109162114246.jpg" alt=""/>
                            <p><i></i><span>红妆赫本软骨鼻</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/nose/longbijiage.html" target="_blank" rel="noopener">
                        <img src="https://uploads.hzshuangmei.com/180209/1-1P2091524433K.jpg" alt=""/>
                            <p><i></i><span>隆鼻价格</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/nose/longbijiage.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180209/1-1P2091524433K.jpg" alt="隆鼻价格"/>
                            <p><i></i><span>隆鼻价格</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/nose/hzbbqb.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180208/1-1P20QZ14O61.jpg" alt="红妆芭比翘鼻"/>
                            <p><i></i><span>红妆芭比翘鼻</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/nose/nose.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180109/1-1P109161Fc42.jpg" alt="全立体鼻缩窄术"/>
                            <p><i></i><span>全立体鼻缩窄术</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/face/" target="_blank" rel="noopener">面部整形</a></h5>
                    </li>
                    <!--                <li class="star">
                        <a href="/projects/zhifang/ztzfmd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180109/1-1P109162329454.jpg" alt=""/>
                            <p><i></i><span>自体脂肪面雕</span></p>
                        </a>
                    </li><li class="star">
                        <a href="/projects/xiaba/vlmxd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P40416062R04.jpg" alt=""/>
                            <p><i></i><span>v立美线雕</span></p>
                        </a>
                    </li><li class="star">
                        <a href="/projects/face/zitizhifang.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180208/1-1P20Q54P4G4.jpg" alt=""/>
                            <p><i></i><span>自体脂肪面部填充</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/face/zitizhifang.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180208/1-1P20Q54P4G4.jpg" alt="自体脂肪面部填充"/>
                            <p><i></i><span>自体脂肪面部填充</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/xiaba/vlmxd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P40416062R04.jpg" alt="v立美线雕"/>
                            <p><i></i><span>v立美线雕</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/zhifang/ztzfmd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180109/1-1P109162329454.jpg" alt="自体脂肪面雕"/>
                            <p><i></i><span>自体脂肪面雕</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/skin/" target="_blank" rel="noopener">皮肤美容</a></h5>
                    </li>
                    <!--                 <li>
                        <a href="/projects/qudou/duoweiqd.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180222/1-1P222143953U0.jpg" alt=""/>
                            <p><i></i><span>红妆多维祛痘</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/quban/xpmqb.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180328/1-1P32Q356202V.jpg" alt=""/>
                            <p><i></i><span>红妆皮秒祛斑</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/skin/sgz.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180406/1-1P4061A303F6.jpg" alt=""/>
                            <p><i></i><span>水光针</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/quban/xpmqb.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180328/1-1P32Q356202V.jpg" alt="红妆皮秒祛斑"/>
                            <p><i></i><span>红妆皮秒祛斑</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/chuzhou/quzhou.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180212/1-1P212102446403.jpg" alt="除皱抗衰"/>
                            <p><i></i><span>除皱抗衰</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/quban/quban.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180312/1-1P3121601494G.jpg" alt="红妆祛斑"/>
                            <p><i></i><span>红妆祛斑</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/ha/" target="_blank" rel="noopener">玻尿酸</a></h5>
                    </li>
                    <!--                     <li>
                        <a href="/projects/ha/qydbns.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180208/1-1P20Q0501X26.jpg" alt=""/>
                            <p><i></i><span>乔雅登玻尿酸</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/ha/zhbns.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180109/1-1P109161SV57.jpg" alt=""/>
                            <p><i></i><span>综合玻尿酸</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/ha/restylane.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180413/1-1P413100FcV.jpg" alt=""/>
                            <p><i></i><span>瑞蓝玻尿酸</span></p>
                        </a>
                    </li> -->
                    <li>
                        <a href="/projects/ha/restylane.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180413/1-1P413100FcV.jpg" alt="瑞蓝玻尿酸"/>
                            <p><i></i><span>瑞蓝玻尿酸</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/ha/bnsqflw.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180411/1-1P411140P9134.jpg" alt="玻尿酸祛除法令纹"/>
                            <p><i></i><span>玻尿酸祛除法令纹</span></p>
                        </a>
                    </li><li>
                        <a href="/projects/ha/xbnsfet.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180322/1-1P322092GMV.jpg" alt="玻尿酸丰额头"/>
                            <p><i></i><span>玻尿酸丰额头</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/body/" target="_blank" rel="noopener">形体雕塑</a></h5>
                    </li>
                    <!-- <li>
                        <a href="/projects/body/sdlxz.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404161320X4.jpg" alt=""/>
                            <p><i></i><span>水动力吸脂</span></p>
                       </a>
                    </li> -->
                    <li>
                        <a href="/projects/body/sdlxz.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180404/1-1P404161320X4.jpg" alt="水动力吸脂"/>
                            <p><i></i><span>水动力吸脂</span></p>
                        </a>
                    </li>
                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
            </div>
        </li>
        <li class="nav_list">
            <a href="/doctors" class="nav_link bor_l bor_r" target="_blank" rel="noopener">
                <span>专 家</span><br/>
                <span>experts</span>
            </a>
            <div id="expert">
                <ul>
                    <li>
                        <h5><a href="/doctors/surgery" target="_blank" rel="noopener">整形美容专家</a></h5>
                    </li>
                    <!--                     <li>
                        <a href="/plugin/view.php?aid=227" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180414/1-1P4140929454T.jpg" alt="薛开兴"/>
                            <p><span class="n_f">薛开兴</span><span class="n_b">整形外科院长</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=153" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180131/1-1P131093205432.jpg" alt="余志亮"/>
                            <p><span class="n_f">余志亮</span><span class="n_b">整形专家</span></p>
                            <i></i>
                        </a>
                    </li> -->
                    <li>
                        <a href="/doctors/surgery/guanhaitao.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180227/1-1P22G44625M2.jpg" alt="关海涛 "/>
                            <p><span class="n_f">关海涛 </span><span class="n_b">整形外科院长</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=176" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180131/1-1P1310U92D41.jpg" alt="朱红振"/>
                            <p><span class="n_f">朱红振</span><span class="n_b">整形外科院长</span></p>
                            <i></i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <h5><a href="/doctors/laser" target="_blank" rel="noopener">激光美容专家</a></h5>
                    </li>
                    <!--             <li>
                        <a href="/doctors/laser/lijie.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/171206/1-1G20611435D10.jpg" alt="李杰"/>
                            <p><span class="n_f">李杰</span><span class="n_b">光学美肤中心院长</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/doctors/laser/yzw.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180131/1-1P131104604521.jpg" alt="姚志文"/>
                            <p><span class="n_f">姚志文</span><span class="n_b">非手术面部年轻化专家</span></p>
                            <i></i>
                        </a>
                    </li> -->
                    <li>
                        <a href="/doctors/laser/lijie.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/171206/1-1G20611435D10.jpg" alt="李杰"/>
                            <p><span class="n_f">李杰</span><span class="n_b">光学美肤中心院长</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/doctors/laser/yzw.html" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180131/1-1P131104604521.jpg" alt="姚志文"/>
                            <p><span class="n_f">姚志文</span><span class="n_b">非手术面部年轻化专家</span></p>
                            <i></i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <h5><a href="/doctors/tattoo" target="_blank" rel="noopener">医学纹绣</a></h5>
                    </li>
                    <!--                    <li>
                        <a href="/plugin/view.php?aid=139" target="_blank" rel="noopener">
                    <img src="https://uploads.hzshuangmei.com/180117/1-1P11GF5391A.jpg" alt="杨小丽"/>
                            <p><span class="n_f">杨小丽</span><span class="n_b">纹饰指导师</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=136" target="_blank" rel="noopener">
                    <img src="https://uploads.hzshuangmei.com/180125/1-1P125154A1105.jpg" alt="高方云"/>
                            <p><span class="n_f">高方云</span><span class="n_b">纹饰指导师</span></p>
                            <i></i>
                        </a>
                    </li> -->
                    <li>
                        <a href="/plugin/view.php?aid=164" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180125/1-1P12515435J45.jpg" alt="冯晓琳"/>
                            <p><span class="n_f">冯晓琳</span><span class="n_b">纹饰技术总指导师</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=137" target="_blank" rel="noopener">
                            <img src="https://uploads.hzshuangmei.com/180117/1-1P11GA95JV.jpg" alt="孟超"/>
                            <p><span class="n_f">孟超</span><span class="n_b">纹饰指导师</span></p>
                            <i></i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <h5><a href="/doctors" target="_blank" rel="noopener">特邀专家</a></h5>
                    </li>
                    <li>
                        <a href="/doctors/surgery/ljb.html" target="_blank" rel="noopener">
                             <img src="https://uploads.hzshuangmei.com/180131/1-1P131092S24W.jpg" alt="雷建波(客座)"/>
                            <p><span class="n_f">雷建波(客座)</span><span class="n_b">整形美容专家</span></p>
                            <i></i>
                        </a>
                    </li>
<li>
                        <a href="/doctors/surgery/liudalie.html" target="_blank" rel="noopener">
                             <img src="https://uploads.hzshuangmei.com/171223/1-1G223091J5950.jpg" alt="柳大烈(客座)"/>
                            <p><span class="n_f">柳大烈(客座)</span><span class="n_b">教授</span></p>
                            <i></i>
                        </a>
                    </li>

                </ul>
                <ul>
                    <li>
                        <h5 class="moon"><a href="/doctors" target="_blank" rel="noopener">每月专家</a></h5>
                    </li>
                    <li class="last-one">
                        <!--<a class="last-one" href="https://www.hzshuangmei.com/doctors/surgery/liudalie.html " target="_blank" rel="noopener">-->
                            <!--<img src="https://img.hzshuangmei.com/pc/nav_zhuanjial.jpg" alt=""/>-->
                        <!--</a>-->
                        <a class="last-one j-consult" href="javascript:void(0)"  target="_blank" rel="noopener nofollow">
                            <img src="https://img.hzshuangmei.com/pc/myzzj.jpg" alt=""/>
                        </a>
                    </li>
                </ul>
            </div>
        </li>
        <li class="nav_list">
            <a href="/cases" class="nav_link bor_l bor_r" target="_blank" rel="noopener">
                <span>真人秀</span><br/>
                <span>Show</span>
            </a>
        </li>
        <li class="nav_list">
            <a href="/news" class="nav_link bor_l" target="_blank" rel="noopener">
            <span>活 动</span><br/>
                <span>News</span>
            </a>
        </li>
    </ul>
</nav>

<div class="swiper-container banner_swiper">
    <div class="swiper-wrapper">
        <!--<a href="javascript:void(0)" target="_blank" class="swiper-slide j-site-consult">-->
        <!--<img src="//img.hzshuangmei.com/pc/banner/xnxymm.jpg" alt="新年新颜"/>-->
        <!--</a>-->
        <!--<a href="javascript:void(0)" target="_blank" class="swiper-slide j-site-consult">-->
        <!--<img src="//img.hzshuangmei.com/pc/banner/banner0.jpg" alt="新年耀美"/>-->
        <!--</a>-->
        <!--<a class="j-consult swiper-slide" href="javascript:void(0)"  rel="nofollow">-->
        <!--<img src="//img.hzshuangmei.com/pc/banner/pczzj.jpg" alt="张子杰专家"/>-->
        <!--</a>-->
        <a class="j-consult swiper-slide" href="javascript:void(0)"  rel="nofollow">
            <img src="//img.hzshuangmei.com/pc/banner/wxsg.jpg" alt="纹绣水光"/>
        </a>
        <a class="j-consult swiper-slide" href="javascript:void(0)"  rel="nofollow">
            <img src="//img.hzshuangmei.com/pc/banner/banner6.jpg" alt="樱花唇"/>
        </a>
        <!--<a href="//www.hzshuangmei.com/brand/"  class="swiper-slide">-->
            <!--<img src="//img.hzshuangmei.com/pc/banner/banner1.jpg" alt="红妆22年"/>-->
        <!--</a>-->
        <!--<a href="//www.hzshuangmei.com/projects/tattoo/byjwm.html" class="swiper-slide">-->
        <!--<img src="//img.hzshuangmei.com/pc/banner/banner2.jpg " alt="半永久纹眉"/>-->
        <!--</a>-->
        <a href="//www.hzshuangmei.com/projects/eye/qjsyp.html " class="swiper-slide">
            <img src="//img.hzshuangmei.com/pc/banner/banner3.jpg" alt="翘睫双眼皮"/>
        </a>
        <a href="//www.hzshuangmei.com/projects/nose/dlslb.html" class="swiper-slide">
            <img src="//img.hzshuangmei.com/pc/banner/banner5.jpg" alt="达拉斯隆鼻"/>
        </a>
        <a class="j-consult swiper-slide" href="javascript:void(0)"  rel="nofollow">
            <img src="//img.hzshuangmei.com/pc/banner/hzjm.jpg" alt="红妆脊美"/>
        </a>
    </div>
    <div class="swiper-pagination banner-pagination"></div>
</div>
<div class="m1">
    <div class="location">
        <i></i><span>当前位置：</span><a href='https://www.hzshuangmei.com/'>首页</a> > <a href='/projects/'>项目</a>
    </div>
    <div class="line"></div>
    <h2 class="tit_h2"><img src="https://img.hzshuangmei.com/pc/project_title.png" alt="红妆双美整形美容推荐项目"/></h2>
    <div class="project_banner clearFix">
           <div id="ptabCon">
            <div class="pdiv"><a href="https://www.hzshuangmei.com/projects/nose/dlslb.html"><img src="//img.hzshuangmei.com/pc/banner/project/dlslb.jpg" alt="达拉斯隆鼻"></a></div>
            <div><a href="https://www.hzshuangmei.com/projects/eye/qjsyp.html"><img src="//img.hzshuangmei.com/pc/banner/project/qjsyp.jpg" alt="翘睫双眼皮"></a></div>
            <div><a href="https://www.hzshuangmei.com/projects/tattoo/byjwm.html"><img src="//img.hzshuangmei.com/pc/banner/project/byjwm.jpg" alt="半永久纹眉"></a></div>
        </div>
        <div id="ptab">
            <ul>
                <li class="pli"><img src="//img.hzshuangmei.com/pc/banner/project/dlslb.jpg" alt="达拉斯隆鼻"></li>
                <li><img src="//img.hzshuangmei.com/pc/banner/project/qjsyp.jpg" alt="翘捷双眼皮"></li>
                <li><img src="//img.hzshuangmei.com/pc/banner/project/byjwm.jpg" alt="半永久纹眉"></li>
            </ul>
        </div>
    </div>
    <div class="project_content" id="pro_01">
        <div id="ptab2">
            <ul id="project_nav" class="btn1 clearFix">
                <li class="nav_list"><a href="/projects" class="nav_link"><img src="https://img.hzshuangmei.com/pc/project_hi0.jpg" alt="全部项目"/></a></li>
                <li class="nav_list"><a href="/projects/eye" class="nav_link"><img src="https://img.hzshuangmei.com/pc/project_hi1.jpg" alt="眼部项目"/></a></li>
                <li class="nav_list"><a href="/projects/nose" class="nav_link"><img src="https://img.hzshuangmei.com/pc/project_hi2.jpg" alt="鼻部项目"/></a></li>
                <li class="nav_list"> <a href="/projects/face" class="nav_link"><img src="https://img.hzshuangmei.com/pc/project_hi3.jpg" alt="面部五官项目"/></a></li>
                <li class="nav_list"><a href="/projects/tattoo" class="nav_link"><img src="https://img.hzshuangmei.com/pc/project_hi4.jpg" alt="纹绣项目"/></a></li>
                <li class="nav_list"><a href="/projects/skin" class="nav_link"><img src="https://img.hzshuangmei.com/pc/project_hi5.jpg" alt="皮肤美容"/></a></li>
                <li class="nav_list"><a href="/projects/chest" class="nav_link"><img src="https://img.hzshuangmei.com/pc/project_hi6.jpg" alt="胸部整形"/></a></li>
                <li class="nav_list"><a href="/projects/private" class="nav_link"><img src="https://img.hzshuangmei.com/pc/project_hi7.jpg" alt="私密整形"/></a></li>
                <li class="nav_list"><a href="/projects/body" class="nav_link"><img src="https://img.hzshuangmei.com/pc/project_hi8.jpg" alt="形体雕塑"/></a></li>
                <li class="nav_list"> <a href="/projects/ha" class="nav_link"><img src="https://img.hzshuangmei.com/pc/project_hi9.jpg" alt="玻尿酸"/></a></li>
                <li class="nav_list"><a href="/projects/botox" class="nav_link"><img src="https://img.hzshuangmei.com/pc/project_hi10.jpg" alt="botox"/></a></li>
                <li class="nav_list"><a href="/projects/hengli" class="nav_link"><img src="https://img.hzshuangmei.com/pc/project_hi11.jpg" alt="衡力"/></a></li>
            </ul>
        </div>
		
        <div id="ptabCon2" class="project_con">
            <div class="clearFix">
                <a href="/projects/bahen/dianzhen.html" title="无创点阵激光">
                    <img src="https://uploads.hzshuangmei.com/180404/1-1P404160T4516.jpg" alt="无创点阵激光"/>
                    <div>
                        <p>
                            <span>无创点阵激光</span><br/>
                            <span>RED MAKEUP</span>
                        </p>
                        <div class="click">
                            <i></i>
                            <span>点击</span>
                        </div>
                        <div class="line1"></div>
                    </div>
                </a><a href="/projects/nose/longbijiage.html" title="隆鼻价格">
                    <img src="https://uploads.hzshuangmei.com/180209/1-1P2091524433K.jpg" alt="隆鼻价格"/>
                    <div>
                        <p>
                            <span>隆鼻价格</span><br/>
                            <span>RED MAKEUP</span>
                        </p>
                        <div class="click">
                            <i></i>
                            <span>点击</span>
                        </div>
                        <div class="line1"></div>
                    </div>
                </a><a href="/projects/face/zitizhifang.html" title="自体脂肪面部填充">
                    <img src="https://uploads.hzshuangmei.com/180208/1-1P20Q54P4G4.jpg" alt="自体脂肪面部填充"/>
                    <div>
                        <p>
                            <span>自体脂肪面部填充</span><br/>
                            <span>RED MAKEUP</span>
                        </p>
                        <div class="click">
                            <i></i>
                            <span>点击</span>
                        </div>
                        <div class="line1"></div>
                    </div>
                </a><a href="/projects/nose/hzbbqb.html" title="红妆芭比翘鼻">
                    <img src="https://uploads.hzshuangmei.com/180208/1-1P20QZ14O61.jpg" alt="红妆芭比翘鼻"/>
                    <div>
                        <p>
                            <span>红妆芭比翘鼻</span><br/>
                            <span>RED MAKEUP</span>
                        </p>
                        <div class="click">
                            <i></i>
                            <span>点击</span>
                        </div>
                        <div class="line1"></div>
                    </div>
                </a><a href="/projects/tattoo/hsbyjwm.html" title="韩式半永久纹眉">
                    <img src="https://uploads.hzshuangmei.com/180404/1-1P404160923556.jpg" alt="韩式半永久纹眉"/>
                    <div>
                        <p>
                            <span>韩式半永久纹眉</span><br/>
                            <span>RED MAKEUP</span>
                        </p>
                        <div class="click">
                            <i></i>
                            <span>点击</span>
                        </div>
                        <div class="line1"></div>
                    </div>
                </a><a href="/projects/eye/slxc.html" title="上睑下垂">
                    <img src="https://uploads.hzshuangmei.com/180222/1-1P22216455E61.jpg" alt="上睑下垂"/>
                    <div>
                        <p>
                            <span>上睑下垂</span><br/>
                            <span>RED MAKEUP</span>
                        </p>
                        <div class="click">
                            <i></i>
                            <span>点击</span>
                        </div>
                        <div class="line1"></div>
                    </div>
                </a><a href="/projects/eye/hzyj.html" title="红妆孕睫术">
                    <img src="https://uploads.hzshuangmei.com/180206/1-1P206100342338.jpg" alt="红妆孕睫术"/>
                    <div>
                        <p>
                            <span>红妆孕睫术</span><br/>
                            <span>RED MAKEUP</span>
                        </p>
                        <div class="click">
                            <i></i>
                            <span>点击</span>
                        </div>
                        <div class="line1"></div>
                    </div>
                </a><a href="/projects/tattoo/hzyswx.html" title="红妆艺术纹绣">
                    <img src="https://uploads.hzshuangmei.com/180129/1-1P129101FQQ.jpg" alt="红妆艺术纹绣"/>
                    <div>
                        <p>
                            <span>红妆艺术纹绣</span><br/>
                            <span>RED MAKEUP</span>
                        </p>
                        <div class="click">
                            <i></i>
                            <span>点击</span>
                        </div>
                        <div class="line1"></div>
                    </div>
                </a><a href="/projects/qudou/hzqdk.html" title="红妆祛痘坑">
                    <img src="https://uploads.hzshuangmei.com/180127/1-1P12G2231bE.jpg" alt="红妆祛痘坑"/>
                    <div>
                        <p>
                            <span>红妆祛痘坑</span><br/>
                            <span>RED MAKEUP</span>
                        </p>
                        <div class="click">
                            <i></i>
                            <span>点击</span>
                        </div>
                        <div class="line1"></div>
                    </div>
                </a><a href="/projects/chest/hzwhfx.html" title="红妆无痕丰胸">
                    <img src="https://uploads.hzshuangmei.com/180127/1-1P12F95154601.jpg" alt="红妆无痕丰胸"/>
                    <div>
                        <p>
                            <span>红妆无痕丰胸</span><br/>
                            <span>RED MAKEUP</span>
                        </p>
                        <div class="click">
                            <i></i>
                            <span>点击</span>
                        </div>
                        <div class="line1"></div>
                    </div>
                </a><a href="/projects/eye/qmtm.html" title="切眉提眉术">
                    <img src="https://uploads.hzshuangmei.com/180404/1-1P404161354458.jpg" alt="切眉提眉术"/>
                    <div>
                        <p>
                            <span>切眉提眉术</span><br/>
                            <span>RED MAKEUP</span>
                        </p>
                        <div class="click">
                            <i></i>
                            <span>点击</span>
                        </div>
                        <div class="line1"></div>
                    </div>
                </a><a href="/projects/xiaba/vlmxd.html" title="v立美线雕">
                    <img src="https://uploads.hzshuangmei.com/180404/1-1P40416062R04.jpg" alt="v立美线雕"/>
                    <div>
                        <p>
                            <span>v立美线雕</span><br/>
                            <span>RED MAKEUP</span>
                        </p>
                        <div class="click">
                            <i></i>
                            <span>点击</span>
                        </div>
                        <div class="line1"></div>
                    </div>
                </a>
            </div>
        </div>
    </div>
    <ul class="pagination clearFix">
        <li><a href="/projects/">首页</a></li>
<li><a href="/projects/">前一页</a></li>
<li><a href="/projects/">1</a></li>
<li class="thisclass">2</li>
<li><a href="/projects/list_3.html">3</a></li>
<li><a href="/projects/list_4.html">4</a></li>
<li><a href="/projects/list_5.html">5</a></li>
<li><a href='/projects/list_3.html'>下一页</a></li>
<li><a href='/projects/list_5.html'>末页</a></li>

    </ul>
    <!--<a href="" class="ask">更多项目<i></i></a>-->
</div>
<div class="index_items" id="index_items">
    <div class="shuang_m1">
        <div class="clearFix border-r">
            <div class="icon">
                <span>双美概况</span>
                <i></i>
            </div>
            <ul class="mar_t">
                <li><a href="/" target="_blank" rel="noopener" >>返回首页</a></li>
                <li><a class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener">>来院路线</a></li>
                <li><a class="j-site-consult" href="javascript:void(0)" target="_blank" rel="noopener">>联系我们</a></li>
                <li><a href="/brand" target="_blank" rel="noopener">>品牌起源</a></li>
                <!--<li><a href="">>企业文化</a></li>-->
            </ul>
        </div>
        <div class="clearFix border-l border-r">
            <div class="icon">
                <span>整形美容</span>
                <i></i>
            </div>
            <ul class="mar_t">
                <li><a href="/projects/chest/#project_nav" target="_blank" rel="noopener">>胸部整形</a></li>
                <li><a href="/projects/eye/#project_nav" target="_blank" rel="noopener">>眼部整形</a></li>
                <li><a href="/projects/nose/#project_nav" target="_blank" rel="noopener">>鼻部整形</a></li>
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>唇部整形</a></li>
                <li><a href="/projects/body/#project_nav" target="_blank" rel="noopener">>塑形体雕</a></li>
                <li><a href="/projects/zhifang/ztzfmd.html" target="_blank" rel="noopener">>自体脂肪填充</a></li>
                <li><a href="/projects/#project_nav" target="_blank" rel="noopener">>其他系列</a></li>
                <li><a href="/projects/ha/bnsxb.html" target="_blank" rel="noopener">>下巴整形</a></li>
                <li><a href="/projects/private/#project_nav" target="_blank" rel="noopener">>私密整形</a></li>
            </ul>
        </div>
        <div class="clearFix border-l border-r">
            <div class="icon">
                <span>光学美肤</span>
                <i></i>
            </div>
            <ul class="mar_t">
                <li><a href="/projects/quban/quban.html" target="_blank" rel="noopener">>美白祛斑</a></li>
                <li><a href="/projects/tuomao/tuomao2.html" target="_blank" rel="noopener">>专业脱毛</a></li>
                <li><a href="/projects/qudou/hzqdk.html" target="_blank" rel="noopener">>祛痘祛疤印</a></li>
                <li><a href="/projects/chuzhou/quzhou.html" target="_blank" rel="noopener">>紧肤抗衰</a></li>
            </ul>
        </div>
        <div class="clearFix border-l">
            <div class="icon">
                <span>微创美容</span>
                <i></i>
            </div>
            <ul class="mar_t">
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>玻尿酸塑形</a></li>
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>玻尿酸祛皱</a></li>
                <li><a href="/projects/botox/#project_nav" target="_blank" rel="noopener">>BOTOX注射</a></li>
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>疤痕针</a></li>
                <li><a href="/projects/tattoo/#project_nav" target="_blank" rel="noopener">>纹绣</a></li>
                <li><a href="javascript:void(0)" class="j-site-consult" target="_blank" rel="noopener">>水光注射</a></li>
                <li><a href="/projects/#project_nav" target="_blank" rel="noopener">>其他</a></li>
            </ul>
        </div>
    </div>
</div>
<footer id="footer">
    <div class="shuang_m1 clearFix">
        <div class="left">
            <h2><a href=""><img src="https://img.hzshuangmei.com/pc/f_logo.png" alt="红妆双美"/></a></h2>
            <p class="addr"><i></i>红妆双美地址：海口市海府路4号海口宾馆附楼2层</p>
            <p>本站信息仅供参考建 版权所有:红妆双美 https://www.hzshuangmei.com<br/>
                <a href="http://www.miitbeian.gov.cn/" rel="nofollow" target="_blank">琼ICP备17004048号-1</a> (海)医广[2017]第085号 <a href="//www.hzshuangmei.com/humans.txt" rel="nofollow" target="_blank"><img src="//img.hzshuangmei.com/pc/humanstxt-transparent-color.png" class="humanstxt"></a><br/>
                网站部分图文来源于网络，如有侵权，请联系我们 联系电话：0898-66156043</p>
        </div>
        <div class="middle"></div>
        <div class="right right1">
            <div class="right_t clearFix">
                <div class="clearFix">
                    <div class="ewm"></div>
                    <div>
                        <p class="fon1">微信扫一扫</p>

                        <p>1）获得最新优惠</p>

                        <p>2）在线实时咨询</p>

                        <p>3）专属服务通道</p>
                    </div>
                </div>

                <div class="clearFix">
                    <div class="f_phone"></div>
                    <div>
                        <p class="fon1">全国免费咨询热线</p>

                        <p class="fon2">0898-66156043</p>

                        <p class="fon3">咨询时间：8:00—20:00</p>
                    </div>
                </div>
            </div>
             <!--<div class="right_b">-->
                <!--<i></i><span>友情链接:</span>-->
                <!---->
                <!--<a href='https://www.honorreal.com/' target='_blank'>红瑞集团</a> /-->
                <!---->
                <!--<a href='https://www.hoozonspa.com' rel='nofollow' target='_blank'>红妆美容</a> /-->
                <!---->
                <!--<a href='http://www.yueyimei.com' target='_blank'>悦伊美</a> /-->
                <!---->
            <!--</div>-->
            <p class="copyright">Copyright © 2017 红妆双美 版权所有 违者必究 | <a href="/statement/copyright.html" rel="nofollow" target="_blank" rel="noopener">版权及隐私声明</a><br>
              设计,文案,技术等求职请投递至网络部root#hzwlb.org(#替换成@)</p>
        </div>
    </div>
</footer>
<!-- 右侧悬浮 开始 -->
<div class="yb_conct">
    <div class="yb_bar">
        <ul>
            <li class="yb_QQ"><a target="_blank" rel="noopener" href="javascript:void(0)" class="j-site-consult" title="立即咨询" rel="nofollow">立即咨询</a></li>
            <li class="yb_phone"><a target="_blank" rel="noopener" href="javascript:void(0)" class="j-site-consult" title="门店查询" rel="nofollow">门店查询</a></li>
            <li class="yb_top">返回顶部</li>
            <li class="yb_ercode" >微信扫一扫<br>
                <img class="hd_qr" src="https://img.hzshuangmei.com/pc/WeChatApplet.jpg" width="125" alt="关注微信小程序">
            </li>
        </ul>
    </div>
</div>
<!-- 结束 -->

</body>
<link rel="preload" href="https://js.hzshuangmei.com/pc/common.js" as="script" crossorigin>
<link rel="preload" href="https://js.hzshuangmei.com/pc/layer/layer.js" as="script" crossorigin>
<link rel="preload" href="https://js.hzshuangmei.com/pc/kst_popup.js" as="script" crossorigin>
<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/Swiper/3.4.2/js/swiper.min.js"></script>
<script src="https://js.hzshuangmei.com/pc/common.js" ></script>
<script src="https://js.hzshuangmei.com/pc/layer/layer.js"></script>
<script src="https://js.hzshuangmei.com/pc/kst_popup.js"></script>
 <!-- html5标签兼容ie低版本浏览器 -->
<!-- [if lt IE 9]>     -->
<script src="https://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<!-- <![endif] -->
<!-- 百度站内搜索 -->
<!-- <script type="text/javascript">(function(){document.write(unescape('%3Cdiv id="bdcs"%3E%3C/div%3E'));var bdcs = document.createElement('script');bdcs.type = 'text/javascript';bdcs.async = true;bdcs.src = '//znsv.baidu.com/customer_search/api/js?sid=5257607230163915007' + '&plate_url=' + encodeURIComponent(window.location.href) + '&t=' + Math.ceil(new Date()/3600000);var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(bdcs, s);})();</script> -->


<script src="https://js.hzshuangmei.com/pc/list_project.js"></script>
</html>
