_header.htm,公用头部模板   位于head标签
_footer.htm,公用底部模板   位于body底部
_meta.htm,公用meta模板     位于head标签
_link.htm,公用样式资源模板 位于head标签
_script.htm,公脚本资源模板 位于body底部

404.htm, 404页面
index.htm,主页模板
index_jc_beian.htm,备案审核首页模板
index_default.htm,默认自定义频道封面
index_brand.htm,品牌页模板
index_article.htm,品牌频道封面模板
list_default.htm,默认自定义模型列表模板
list_article.htm,默认文章列表模板
list_news.htm,活动新闻列表模板
list_doctors.htm,专家医生列表模板
list_project.htm,项目列表模板
list_case.htm,案例日记列表模板

article_default.htm,默认自定义文档内容模板
article_article.htm,文章内容页模板
article_news.htm,活动新闻内容页模板
article_doctors.htm,专家医生内容页模板
article_designers.htm,美学设计内容页模板
article_project.htm,项目内容页模板
article_case.htm,案例日记内容页模板
article_activity.htm,活动项目内容页模板

_sj_copyright.htm,手机站底部版权申明
_sj_index_nav.htm,手机站首页导航模块
_sj_index_doctor.htm,手机站首页医生模块
_sj_zt_meta.htm,手机站项目页公用meta
_sj_zt_link.htm,手机站项目页公用link
_sj_zt_header.htm,手机站项目页公用头部
_sj_zt_footer.htm,手机站项目页公用底部

