<!DOCTYPE html>
<html lang="zh-cmn-Hans">

<head> <!-- Make 2018-02-06 19:41:00 -->
<!-- Make 1517917260 -->
<meta charset="UTF-8">
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
<meta name="renderer" content="webkit"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
<meta name=applicable-device content="pc">
<meta http-equiv="Cache-Control" content="no-transform"/>
<meta http-equiv="Cache-Control" content="no-siteapp"/>
<meta name="baidu-site-verification" content="99J7V1k1Vz" />
<meta name="google-site-verification" content="Odmo8X4zeUG1WPcCrCAueZz-dyBPFBs4Zqlb9FBT5z4" />

    <title>红妆时尚双美连锁机构整形专家_海南红妆时尚双美整形美容连锁</title>
    <meta name="keywords" content="海南整形医院专家,激光美肤科主任李杰、美容整形外科主任刘志坤，精细化整形专家" />
    <meta name="description" content="海南整形医院-红妆时尚双美连锁机构作为精细化整形倡领者，汇集了以激光美肤主任李杰，美容整形外科主任刘志坤为核心的多位有名整形美容、皮肤美容专家，率先倡导“精细化整形”理念，即精细化设计、精细化操作，精细化服务。" /> <!-- Pre for optimization -->
<link rel="dns-prefetch" href="https://cdn.bootcss.com/">
<link rel="dns-prefetch" href="https://uploads.hzshuangmei.com">
<link rel="dns-prefetch" href="https://img.hzshuangmei.com">
<link rel="dns-prefetch" href="https://css.hzshuangmei.com">
<link rel="dns-prefetch" href="https://js.hzshuangmei.com">
<link rel="preconnect" href="https://cdn.bootcss.com/">
<link rel="preconnect" href="https://uploads.hzshuangmei.com">
<link rel="preconnect" href="https://img.hzshuangmei.com">
<link rel="preconnect" href="https://css.hzshuangmei.com">
<link rel="preconnect" href="https://js.hzshuangmei.com">
<!-- Style for the page-->
<link rel="stylesheet" href="https://cdn.bootcss.com/Swiper/3.4.2/css/swiper.min.css"/>
<link rel="stylesheet" href="https://css.hzshuangmei.com/pc/common.css"/>
<!-- favicon.ico -->
<link rel="icon" href="https://img.hzshuangmei.com/pc/favicon.ico" type="image/x-icon"/>
<link rel="shortcut icon" href="https://img.hzshuangmei.com/pc/favicon.ico" type="image/x-icon"/>
<!-- humanstxt -->
<link rel="author" href="https://www.hzshuangmei.com/humans.txt" />
<link rel="preload" as=image  href="https://img.hzshuangmei.com/pc/kst/default.png">
<link rel="prefetch" src="https://img.hzshuangmei.com/pc/kst/default.png">
<link rel="prerender" src="https://img.hzshuangmei.com/pc/kst/default.png">
<link rel="prefetch" src="https://img.hzshuangmei.com/pc/kst/.png">
<link rel="prerender" src="https://img.hzshuangmei.com/pc/kst/.png">
<link rel="preload" as=image  href="https://img.hzshuangmei.com/pc/kst/.png">

    <link rel="stylesheet" href="https://css.hzshuangmei.com/pc/list_doctors.css" />
    <link rel="canonical" href="https://www.hzshuangmei.com/doctors/">
    <link rel="alternate" media="only screen and(max-width: 640px)" href="https://m.hzshuangmei.com/doctors/">
</head>

<body><header>
    <div class="top">
        <div class="shuang_m1 clearFix">
            <div class="top_l">
                <span>香港红瑞集团 旗下品牌 海南红妆双美连锁</span> | <span>美丽时间：周一周日9点--21点</span>
            </div>
            <div class="top_r">
                <a href="" class="pad_r"><i class="tel"></i><span>0898-66156043</span></a>
                <span>关注我们：</span>
                <a href="" class="pad_l"><i class="wbo"></i></a>
                <a href=""><i class="wxin"></i></a>
                <a href=""><i class="qq"></i></a>
            </div>
        </div>
    </div>
    <div class="sm_logo">
        <a href="/"><img src="https://img.hzshuangmei.com/pc/h_logo.png" alt=""/></a>
    </div>
</header>
<nav id="nav">
    <ul class="shuang_m1 nav_ul">
        <li class="nav_list">
            <a href="/" class="nav_link" target="_blank">
                <span>首 页</span><br/>
                <span>Home</span>
            </a>
        </li>
        <li class="nav_list">
            <a href="/brand" class="nav_link bor_r" target="_blank">
                <span>品 牌</span><br/>
                <span>brands</span>
            </a>
        </li>
        <li class="nav_list">
            <a href="/projects" class="nav_link bor_l bor_r" target="_blank">
                <span>项 目</span><br/>
                <span>projects</span>
            </a>
            <div class="clearFix" id="project">
                <ul>
                    <li>
                        <h5><a href="/projects/tattoo/" target="_blank">医学纹绣</a></h5>
                    </li>
                    <li>
                        <a href="/projects/tattoo/hsbyjwm.html" target="_blank">
                            <img src="https://uploads.hzshuangmei.com/img/180205/1-1P205103S10-L.jpg" alt=""/>
                            <p><i></i><span>韩式半永久纹眉</span></p>
                        </a>
                    </li>
<li>
                        <a href="/projects/tattoo/hzyswx.html" target="_blank">
                            <img src="https://uploads.hzshuangmei.com/180129/1-1P129101FQQ.jpg" alt=""/>
                            <p><i></i><span>红妆艺术纹绣</span></p>
                        </a>
                    </li>
<li>
                        <a href="/projects/tattoo/yanxian.html" target="_blank">
                            <img src="https://uploads.hzshuangmei.com/img/180125/1-1P1251I1140-L.jpg" alt=""/>
                            <p><i></i><span>红妆艺术美瞳线</span></p>
                        </a>
                    </li>

                    <!--<li class="n_button">-->
                        <!--<a href="/projects" target="_blank">查看更多</a>-->
                    <!--</li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/eye/" target="_blank">眼部整形</a></h5>
                    </li>
                    <li>
                        <a href="/projects/eye/slxc.html" target="_blank">
                            <img src="https://uploads.hzshuangmei.com/180205/1-1P2051554094J.jpg" alt=""/>
                            <p><i></i><span>上睑下垂</span></p>
                        </a>
                    </li>
<li>
                        <a href="/projects/eye/hzyj.html" target="_blank">
                            <img src="https://uploads.hzshuangmei.com/180206/1-1P206100342338.jpg" alt=""/>
                            <p><i></i><span>红妆孕睫术</span></p>
                        </a>
                    </li>
<li>
                        <a href="/projects/eye/qmtm.html" target="_blank">
                            <img src="https://uploads.hzshuangmei.com/img/180126/1-1P1261456320-L.jpg" alt=""/>
                            <p><i></i><span>切眉提眉术</span></p>
                        </a>
                    </li>

                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/nose/" target="_blank">鼻部整形</a></h5>
                    </li>
                    <li>
                        <a href="/projects/nose/hzbbqb.html" target="_blank">
                        <img src="/images/defaultpic.gif" alt=""/>
                            <p><i></i><span>红妆芭比翘鼻</span></p>
                        </a>
                    </li>
<li>
                        <a href="/projects/nose/nose.html" target="_blank">
                        <img src="https://uploads.hzshuangmei.com/180109/1-1P109161Fc42.jpg" alt=""/>
                            <p><i></i><span>全立体鼻缩窄术</span></p>
                        </a>
                    </li>
<li>
                        <a href="/projects/nose/dlslb.html" target="_blank">
                        <img src="https://uploads.hzshuangmei.com/180109/1-1P10916201a20.jpg" alt=""/>
                            <p><i></i><span>达拉斯隆鼻</span></p>
                        </a>
                    </li>

                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/face/" target="_blank">面部整形</a></h5>
                    </li>
                    <li class="star">
                        <a href="/projects/xiaba/vlmxd.html" target="_blank">
                            <img src="https://uploads.hzshuangmei.com/img/180126/1-1P1261446360-L.jpg" alt=""/>
                            <p><i></i><span>v立美线雕</span></p>
                        </a>
                    </li>
<li class="star">
                        <a href="/projects/zhifang/ztzfmd.html" target="_blank">
                            <img src="https://uploads.hzshuangmei.com/180109/1-1P109162329454.jpg" alt=""/>
                            <p><i></i><span>自体脂肪面雕</span></p>
                        </a>
                    </li>

                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/skin/" target="_blank">皮肤美容</a></h5>
                    </li>
                    <li>
                        <a href="/projects/qudou/hzqdk.html" target="_blank">
                            <img src="https://uploads.hzshuangmei.com/180127/1-1P12G2231bE.jpg" alt=""/>
                            <p><i></i><span>红妆祛痘坑</span></p>
                        </a>
                    </li>
<li>
                        <a href="/projects/quban/wuchuang.html" target="_blank">
                            <img src="https://uploads.hzshuangmei.com/180127/1-1P12GG42M10.jpg" alt=""/>
                            <p><i></i><span>红妆无创量子祛斑</span></p>
                        </a>
                    </li>
<li>
                        <a href="/projects/quban/queban.html" target="_blank">
                            <img src="https://uploads.hzshuangmei.com/img/180125/1-1P125162U30-L.jpg" alt=""/>
                            <p><i></i><span>红妆祛雀斑</span></p>
                        </a>
                    </li>

                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/ha/" target="_blank">玻尿酸</a></h5>
                    </li>
                    <li>
                        <a href="/projects/ha/bnsxb.html" target="_blank">
                            <img src="https://uploads.hzshuangmei.com/180126/1-1P1261F10CK.jpg" alt=""/>
                            <p><i></i><span>红妆玻尿酸下巴专题</span></p>
                        </a>
                    </li>
<li>
                        <a href="/projects/ha/bnsbcg.html" target="_blank">
                            <img src="https://uploads.hzshuangmei.com/180125/1-1P1251026402Y.jpg" alt=""/>
                            <p><i></i><span>红妆玻尿酸鼻唇沟专题</span></p>
                        </a>
                    </li>
<li>
                        <a href="/projects/ha/bnset.html" target="_blank">
                            <img src="https://uploads.hzshuangmei.com/180124/1-1P1241R14B49.jpg" alt=""/>
                            <p><i></i><span>红妆玻尿酸额头专题</span></p>
                        </a>
                    </li>

                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
                <ul>
                    <li>
                        <h5><a href="/projects/body/" target="_blank">形体雕塑</a></h5> </li> <li>
                        <a href="/projects/body/sdlxz.html" target="_blank">
                            <img src="https://uploads.hzshuangmei.com/img/180125/1-1P125154K00-L.jpg" alt=""/>
                            <p><i></i><span>水动力吸脂</span></p>
                       </a>
                    </li>

                    <!--<li class="n_button"> <a href="/projects">查看更多</a> </li>-->
                </ul>
            </div>
        </li>
        <li class="nav_list">
            <a href="/doctors" class="nav_link bor_l bor_r" target="_blank">
                <span>专 家</span><br/>
                <span>experts</span>
            </a>
            <div id="expert">
                <ul>
                    <li>
                        <h5><a href="/doctors/surgery" target="_blank">整形美容专家</a></h5>
                    </li>
<!--                     <li>
                        <a href="/doctors/surgery/guanhaitao.html" target="_blank">
                            <img src="https://uploads.hzshuangmei.com/171206/1-1G206154431456.jpg" alt="关海涛 "/>
                            <p><span class="n_f">关海涛 </span><span class="n_b">整形外科院长</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=159" target="_blank">
                            <img src="https://uploads.hzshuangmei.com/180131/1-1P131093239440.jpg" alt="周春金"/>
                            <p><span class="n_f">周春金</span><span class="n_b">助理医生</span></p>
                            <i></i>
                        </a>
                    </li> -->
       <li>
                        <a href="/doctors/surgery/guanhaitao.html" target="_blank">
                            <img src="https://uploads.hzshuangmei.com/171206/1-1G206154431456.jpg" alt="关海涛 "/>
                            <p><span class="n_f">关海涛 </span><span class="n_b">整形外科院长</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=150" target="_blank">
                            <img src="https://uploads.hzshuangmei.com/180131/1-1P131092910358.jpg" alt="刘志坤"/>
                            <p><span class="n_f">刘志坤</span><span class="n_b">整形外科院长</span></p>
                            <i></i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <h5><a href="/doctors/laser" target="_blank">激光美容专家</a></h5>
                    </li>
        <!--             <li>
                        <a href="/doctors/laser/lijie.html" target="_blank">
                            <img src="https://uploads.hzshuangmei.com/171206/1-1G20611435D10.jpg" alt="李杰"/>
                            <p><span class="n_f">李杰</span><span class="n_b">光学美肤中心院长</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=145" target="_blank">
                            <img src="https://uploads.hzshuangmei.com/180131/1-1P131104G3264.jpg" alt="赵丽萍"/>
                            <p><span class="n_f">赵丽萍</span><span class="n_b">射频嫩肤美容专家</span></p>
                            <i></i>
                        </a>
                    </li> -->
                           <li>
                        <a href="/doctors/laser/lijie.html" target="_blank">
                            <img src="https://uploads.hzshuangmei.com/171206/1-1G20611435D10.jpg" alt="李杰"/>
                            <p><span class="n_f">李杰</span><span class="n_b">光学美肤中心院长</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=144" target="_blank">
                            <img src="https://uploads.hzshuangmei.com/180131/1-1P131104604521.jpg" alt="姚志文"/>
                            <p><span class="n_f">姚志文</span><span class="n_b">非手术面部年轻化专家</span></p>
                            <i></i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <h5><a href="/doctors/tattoo" target="_blank">医学纹绣</a></h5>
                    </li>
 <!--                    <li>
                        <a href="/plugin/view.php?aid=137" target="_blank">
                    <img src="https://uploads.hzshuangmei.com/180117/1-1P11GA95JV.jpg" alt="孟超"/>
                            <p><span class="n_f">孟超</span><span class="n_b">纹饰指导师</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=136" target="_blank">
                    <img src="https://uploads.hzshuangmei.com/180125/1-1P125154A1105.jpg" alt="高方云"/>
                            <p><span class="n_f">高方云</span><span class="n_b">纹饰指导师</span></p>
                            <i></i>
                        </a>
                    </li> -->
                           <li>
                        <a href="/plugin/view.php?aid=164" target="_blank">
                            <img src="https://uploads.hzshuangmei.com/180125/1-1P12515435J45.jpg" alt="冯晓琳"/>
                            <p><span class="n_f">冯晓琳</span><span class="n_b">纹饰技术总指导师</span></p>
                            <i></i>
                        </a>
                    </li><li>
                        <a href="/plugin/view.php?aid=137" target="_blank">
                            <img src="https://uploads.hzshuangmei.com/180117/1-1P11GA95JV.jpg" alt="孟超"/>
                            <p><span class="n_f">孟超</span><span class="n_b">纹饰指导师</span></p>
                            <i></i>
                        </a>
                    </li>
                </ul>
                <ul>
                    <li>
                        <h5><a href="/doctors" target="_blank">特邀专家</a></h5>
                    </li>
                    <li>
                        <a href="/doctors/surgery/ljb.html" target="_blank">
                             <img src="https://uploads.hzshuangmei.com/180131/1-1P131092S24W.jpg" alt="雷建波(客座)"/>
                            <p><span class="n_f">雷建波(客座)</span><span class="n_b">整形美容专家</span></p>
                            <i></i>
                        </a>
                    </li>
<li>
                        <a href="/doctors/surgery/liudalie.html" target="_blank">
                             <img src="https://uploads.hzshuangmei.com/171223/1-1G223091J5950.jpg" alt="柳大烈(客座)"/>
                            <p><span class="n_f">柳大烈(客座)</span><span class="n_b">教授</span></p>
                            <i></i>
                        </a>
                    </li>

                </ul>
                <ul>
                    <li>
                        <h5 class="moon"><a href="/doctors" target="_blank">每月专家</a></h5>
                    </li>
                    <li class="last-one">
                        <a class="last-one" href="https://www.hzshuangmei.com/doctors/surgery/liudalie.html " target="_blank">
                            <img src="https://img.hzshuangmei.com/pc/nav_zhuanjial.jpg" alt=""/>
                        </a>
                    </li>
                </ul>
            </div>
        </li>
        <li class="nav_list">
            <a href="/cases" class="nav_link bor_l bor_r" target="_blank">
                <span>真人秀</span><br/>
                <span>Show</span>
            </a>
        </li>
        <li class="nav_list">
            <a href="/news" class="nav_link bor_l" target="_blank">
            <span>活 动</span><br/>
                <span>News</span>
            </a>
        </li>
    </ul>
</nav>
<div class="swiper-container banner_swiper">
    <div class="swiper-wrapper">
        <a href="javascript:void(0)" target="_blank" class="swiper-slide j-site-consult">
            <img src="//img.hzshuangmei.com/pc/banner/xnxymm.jpg" alt="新年新颜"/>
        </a>
        <a href="javascript:void(0)" target="_blank" class="swiper-slide j-site-consult">
            <img src="//img.hzshuangmei.com/pc/banner/banner0.jpg" alt="新年耀美"/>
        </a>
        <a href="//www.hzshuangmei.com/brand/" class="swiper-slide">
            <img src="//img.hzshuangmei.com/pc/banner/banner1.jpg" alt="红妆22年"/>
        </a>
        <a href="//www.hzshuangmei.com/projects/tattoo/byjwm.html" class="swiper-slide">
            <img src="//img.hzshuangmei.com/pc/banner/banner2.jpg " alt="半永久纹眉"/>
        </a>
        <a href="//www.hzshuangmei.com/projects/eye/qjsyp.html " class="swiper-slide">
            <img src="//img.hzshuangmei.com/pc/banner/banner3.jpg" alt="翘睫双眼皮"/>
        </a>
        <a href="//www.hzshuangmei.com/projects/nose/dlslb.html" class="swiper-slide">
            <img src="//img.hzshuangmei.com/pc/banner/banner5.jpg" alt="达拉斯隆鼻"/>
        </a>
    </div>
    <div class="swiper-pagination banner-pagination"></div>
</div>
    <div class="m1">
        <div class="location"><i></i><span>当前位置：</span><a href='https://www.hzshuangmei.com/'>首页</a> > <a href='/doctors/'>专家医生</a></div>
        <div class="line"></div>
        <h2 class="h2_tit"><img src="https://img.hzshuangmei.com/pc/doctors_title.png" alt=""/></h2>
        <div id="doctors_banner">   <div class="swiper-container doctors_banner ">
            <div class="swiper-wrapper">
                <a href="/doctors/surgery/guanhaitao.html" class="swiper-slide"><img src="//img.hzshuangmei.com/pc/banner/doctors/guanhaitao.jpg" alt="关海涛"/></a>
                <a href="/doctors/laser/lijie.html" class="swiper-slide"><img src="//img.hzshuangmei.com/pc/banner/doctors/lijie.jpg" alt="李杰"/></a>
                <a href="javascript:void(0)" target="_blank" class="swiper-slide j-site-consult"><img src="//img.hzshuangmei.com/pc/banner/doctors/liuzhikun.jpg" alt="刘志坤"/></a>
            </div>
        </div>
        <div class="swiper-pagination doctors_pagination"></div></div>
        <div class="doctors_content">
            <div id="doctors_tab">
                <ul class="clearFix btn" id="doctor_nav">
                    <li class="nav_list"><a href="/doctors" class="nav_link">全部专家</a></li>
                    <li class="nav_list"><a href="/doctors/surgery" class="nav_link">整形美容专家</a></li>
                    <li class="nav_list"><a href="/doctors/laser" class="nav_link">皮肤美容专家</a></li>
                    <li class="nav_list"><a href="/doctors/tattoo" class="nav_link">医学纹绣师</a></li>
                </ul>
            </div>
            <div id="doctors_tabCon">
                <ul class="doc_fdiv doc_con clearFix">
                        <li>
                        <div class="doctor1">
                            <div><img src="https://uploads.hzshuangmei.com/180131/1-1P131104641351.jpg" alt="袁兆周"></div>
                            <div class="clearFix">
                                <a href="/plugin/view.php?aid=146" class="order" target="_blank"><span>详细<br/>了解</span></a>
                                <a class="consult j-site-consult" href="javascript:void(0)" target="_blank"><span>马上<br/> 预约</span></a>
                            </div>
                        </div>
                        <p class="doc_p1"><span>袁兆周</span>紧肤除皱抗衰专家</p>
                        <p class="doc_p2">擅长项目：<a href="https://www.hzshuangmei.com/projects/quban/queban.html">红妆激光祛雀斑</a></p><i></i>
                    </li><li>
                        <div class="doctor1">
                            <div><img src="https://uploads.hzshuangmei.com/180131/1-1P131104504O7.jpg" alt="林粤鑫"></div>
                            <div class="clearFix">
                                <a href="/plugin/view.php?aid=147" class="order" target="_blank"><span>详细<br/>了解</span></a>
                                <a class="consult j-site-consult" href="javascript:void(0)" target="_blank"><span>马上<br/> 预约</span></a>
                            </div>
                        </div>
                        <p class="doc_p1"><span>林粤鑫</span>色素祛除皮肤美容专家</p>
                        <p class="doc_p2">擅长项目：<a href="https://www.hzshuangmei.com/projects/qudou/hzqdk.html" style="font-size: 13.3333px;">红妆激光祛痘坑</a><br style="font-size: 13.3333px;" />
<a href="https://www.hzshuangmei.com/projects/quban/queban.html" style="font-size: 13.3333px;">红妆激光祛雀斑</a></p><i></i>
                    </li><li>
                        <div class="doctor1">
                            <div><img src="https://uploads.hzshuangmei.com/180131/1-1P131104355J3.jpg" alt="李华"></div>
                            <div class="clearFix">
                                <a href="/plugin/view.php?aid=148" class="order" target="_blank"><span>详细<br/>了解</span></a>
                                <a class="consult j-site-consult" href="javascript:void(0)" target="_blank"><span>马上<br/> 预约</span></a>
                            </div>
                        </div>
                        <p class="doc_p1"><span>李华</span>水光嫩肤祛斑专家</p>
                        <p class="doc_p2">擅长项目：<a href="https://ryak66.kuaishang.cn/bs/leavemsg.htm?cas=58194___765150&amp;fi=68948&amp;ri=1034468365&amp;_d=15172827787449990">无创水光</a></p><i></i>
                    </li><li>
                        <div class="doctor1">
                            <div><img src="https://uploads.hzshuangmei.com/180131/1-1P13110453C32.jpg" alt="王平藏"></div>
                            <div class="clearFix">
                                <a href="/plugin/view.php?aid=149" class="order" target="_blank"><span>详细<br/>了解</span></a>
                                <a class="consult j-site-consult" href="javascript:void(0)" target="_blank"><span>马上<br/> 预约</span></a>
                            </div>
                        </div>
                        <p class="doc_p1"><span>王平藏</span>祛斑美肤专家</p>
                        <p class="doc_p2">擅长项目：<a href="https://www.hzshuangmei.com/projects/quban/queban.html">激光祛斑</a></p><i></i>
                    </li>
                </ul>
            </div>
        </div>
        <ul class="pagination clearFix">
            <li><a href="/doctors/">首页</a></li>
<li><a href="/doctors/list_3.html">前一页</a></li>
<li><a href="/doctors/">1</a></li>
<li><a href="/doctors/list_2.html">2</a></li>
<li><a href="/doctors/list_3.html">3</a></li>
<li class="thisclass">4</li>
<li><a>末页</a></li>

        </ul>
    </div>
    <div class="index_items" id="index_items">
    <div class="shuang_m1">
        <div class="clearFix border-r">
            <div class="icon">
                <span>双美概况</span>
                <i></i>
            </div>
            <ul class="mar_t">
                <li><a href="/" target="_blank">>返回首页</a></li>
                <li><a class="j-site-consult" href="javascript:void(0)" target="_blank">>来院路线</a></li>
                <li><a class="j-site-consult" href="javascript:void(0)" target="_blank">>联系我们</a></li>
                <li><a href="/brand" target="_blank">>品牌起源</a></li>
                <!--<li><a href="">>企业文化</a></li>-->
            </ul>
        </div>
        <div class="clearFix border-l border-r">
            <div class="icon">
                <span>整形美容</span>
                <i></i>
            </div>
            <ul class="mar_t">
                <li><a href="/projects/chest/" target="_blank">>胸部整形</a></li>
                <li><a href="/projects/eye/">>眼部整形</a></li>
                <li><a href="/projects/nose/">>鼻部整形</a></li>
                <li><a href="">>唇部整形</a></li>
                <li><a href="/projects/body/">>塑形体雕</a></li>
                <li><a href="">>自体脂肪填充</a></li>
                <li><a href="">>其他系列</a></li>
                <li><a href="">>下巴整形</a></li>
                <li><a href="/projects/private/">>私密整形</a></li>
            </ul>
        </div>
        <div class="clearFix border-l border-r">
            <div class="icon">
                <span>光学美肤</span>
                <i></i>
            </div>
            <ul class="mar_t">
                <li><a href="">>美白祛斑</a></li>
                <li><a href="">>专业脱毛</a></li>
                <li><a href="">>祛痘祛疤印</a></li>
                <li><a href="">>紧肤抗衰</a></li>
            </ul>
        </div>
        <div class="clearFix border-l">
            <div class="icon">
                <span>微创美容</span>
                <i></i>
            </div>
            <ul class="mar_t">
                <li><a href="">>玻尿酸塑形</a></li>
                <li><a href="">>玻尿酸祛皱</a></li>
                <li><a href="">>BOTOX注射</a></li>
                <li><a href="">>疤痕针</a></li>
                <li><a href="">>纹绣</a></li>
                <li><a href="">>水光注射</a></li>
                <li><a href="">>其他</a></li>
            </ul>
        </div>
    </div>
</div>
<footer id="footer">
    <div class="shuang_m1 clearFix">
        <div class="left">
            <h2><a href=""><img src="https://img.hzshuangmei.com/pc/f_logo.png" alt="红妆双美"/></a></h2>
            <p class="addr"><i></i>红妆双美地址：海口市海府路4号海口宾馆附楼2层</p>
            <p>本站信息仅供参考建 版权所有:红妆双美 https://www.hzshuangmei.com<br/>
                <a href="http://www.miitbeian.gov.cn/" rel="nofollow" target="_blank">琼ICP备17004048号-1</a> (海)医广[2017]第085号 <a href="//www.hzshuangmei.com/humans.txt" rel="nofollow" target="_blank"><img src="//img.hzshuangmei.com/pc/humanstxt-transparent-color.png" class="humanstxt"></a><br/>
                网站部分图文来源于网络，如有侵权，请联系我们 联系电话：0898-66156043</p>
        </div>
        <div class="middle"></div>
        <div class="right right1">
            <div class="right_t clearFix">
                <div class="clearFix">
                    <div class="ewm"></div>
                    <div>
                        <p class="fon1">微信扫一扫</p>

                        <p>1）获得最新优惠</p>

                        <p>2）在线实时咨询</p>

                        <p>3）专属服务通道</p>
                    </div>
                </div>

                <div class="clearFix">
                    <div class="f_phone"></div>
                    <div>
                        <p class="fon1">全国免费咨询热线</p>

                        <p class="fon2">0898-66156043</p>

                        <p class="fon3">咨询时间：8:00—20:00</p>
                    </div>
                </div>
            </div>
             <!--<div class="right_b">-->
                <!--<i></i><span>友情链接:</span>-->
                <!---->
                <!--<a href='https://www.honorreal.com/' target='_blank'>红瑞集团</a> /-->
                <!---->
                <!--<a href='https://www.hoozonspa.com' rel='nofollow' target='_blank'>红妆美容</a> /-->
                <!---->
                <!--<a href='http://www.yueyimei.com' target='_blank'>悦伊美</a> /-->
                <!---->
            <!--</div>-->
            <p class="copyright">Copyright © 2017 红妆双美 版权所有 违者必究 | <a href="/statement/copyright.html" rel="nofollow" target="_blank">版权及隐私声明</a><br>
              设计,文案,技术等求职请投递至网络部root#hzwlb.org(#t替换成@)</p>
        </div>
    </div>
</footer>
<!-- 右侧悬浮 开始 -->
<div class="yb_conct">
    <div class="yb_bar">
        <ul>
            <li class="yb_QQ"><a target="_blank" href="javascript:void(0)" class="j-site-consult" title="立即咨询" rel="nofollow">立即咨询</a></li>
            <li class="yb_phone"><a target="_blank" href="javascript:void(0)" class="j-site-consult" title="门店查询" rel="nofollow">门店查询</a></li>
            <li class="yb_top">返回顶部</li>
            <li class="yb_ercode" >微信扫一扫<br>
                <img class="hd_qr" src="https://img.hzshuangmei.com/pc/WeChatApplet.jpg" width="125" alt="关注微信小程序">
            </li>
        </ul>
    </div>
</div>
<!-- 结束 -->

</body>
<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/Swiper/3.4.2/js/swiper.min.js"></script>
<script src="https://js.hzshuangmei.com/pc/common.js"></script>
<script src="https://js.hzshuangmei.com/pc/layer/layer.js"></script>
<script src="https://js.hzshuangmei.com/pc/kst_popup.js"></script>
 <!-- html5标签兼容ie低版本浏览器 -->
<!-- [if lt IE 9]>     -->
<script src="https://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<!-- <![endif] -->


<script src="https://js.hzshuangmei.com/pc/list_doctors.js"></script>

</html>
