_header.htm,公用头部模板
_footer.htm,公用底部模板 (除首页外)
_meta.htm,公用meta模板 位于head标签
_link.htm,公用样式资源模板 位于head标签
_script.htm,公脚本资源模板 位于body底部

index.htm,主页模板
index_footer.htm,主页底部模块

index_default.htm,默认自定义频道封面

list_default.htm,默认自定义模型列表模板
list_article.htm,默认文章列表模板
list_news.htm,活动新闻列表模板
list_doctors.htm,专家医生列表模板
list_project.htm,项目列表模板
list_case.htm,案例日记列表模板

article_default.htm,默认自定义文档内容模板
article_article.htm,文章内容页模板
article_news.htm,活动新闻内容页模板
article_doctors.htm,专家医生内容页模板
article_project.htm,项目内容页模板
article_case.htm,案例日记内容页模板
article_aside.htm,内容详情页侧边模块
article_bottom.htm,内容详情页非主体部分模块

indexgsb.htm,广告审查页面模板
404.htm,404页面模板